-- Simula o que o Supabase fornece de fabrica (auth, storage, papeis), para
-- rodar as migracoes e o teste de isolamento num Postgres descartavel.
-- NAO faz parte das migracoes: nunca e aplicado no Supabase.

CREATE ROLE anon;
CREATE ROLE authenticated;
CREATE ROLE service_role;

-- O Supabase da, por padrao, permissao em TUDO que for criado no schema public
-- para anon e authenticated. Imitamos isso aqui: sem esta linha, o teste nao
-- enxergaria uma funcao que ficou executavel por qualquer um.
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES    TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;

CREATE SCHEMA auth;
CREATE TABLE auth.users (
  id uuid PRIMARY KEY,
  email text,
  email_confirmed_at timestamptz
);

-- No Supabase real, auth.uid() le o token JWT. Aqui le uma variavel de sessao.
CREATE FUNCTION auth.uid() RETURNS uuid
LANGUAGE sql STABLE AS $$
  SELECT nullif(current_setting('teste.uid', true), '')::uuid
$$;

CREATE SCHEMA storage;
CREATE TABLE storage.buckets (id text PRIMARY KEY, name text, public boolean);
CREATE TABLE storage.objects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bucket_id text REFERENCES storage.buckets(id),
  name text
);
ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON storage.objects TO authenticated;
GRANT USAGE ON SCHEMA storage, auth, public TO authenticated, anon, service_role;
