-- =========================================================================
-- STGame — A trava do PIN do tablet passa a ser POR PESSOA.
--
-- Como usar: Supabase -> SQL Editor -> New query -> colar TUDO -> Run.
-- Se der erro, NADA é aplicado: me mande a mensagem.
-- Pode rodar duas vezes sem problema.
--
-- ATENÇÃO: aplique antes o aplicar-desempate-e-dias-sem-lancamento.sql (e os
-- anteriores). Aplique ESTE ARQUIVO ANTES de publicar a versão nova.
--
-- Este arquivo é UMA migração só:
--   20260929246000_trava_do_pin_por_pessoa.sql
--
-- O QUE MUDA: no tablet, a pessoa toca no próprio nome antes do PIN (na
-- tarefa com dono, não precisa). Quem erra fica bloqueado sozinho — 1, 3 e
-- no máximo 10 minutos —, não o tablet. PIN certo de quem está de folga não
-- conta como erro. O gestor libera em Pessoas → Equipe.
-- AO APLICAR: os bloqueios antigos do tablet em vigor são apagados.
-- =========================================================================


BEGIN;

-- A trava do PIN do tablet passa a ser POR PESSOA (29/09/2026, decisão do
-- Wisley). Em 29/09 uma pessoa ficou 112 minutos travada digitando o PIN
-- CERTO: ela estava de folga, o PIN certo de quem está de folga contava como
-- erro, e a trava era do TABLET (20 erros em 24 horas travavam a loja
-- inteira até o erro mais antigo completar 24 horas).
--
-- Agora:
--   * o tablet sabe QUEM está tentando antes do PIN: na tarefa com dono é o
--     dono; na entrega é quem pegou; na missão, na compartilhada e no menu a
--     pessoa toca no próprio nome (só quem trabalha hoje nesta loja aparece);
--   * a trava é da PESSOA: os dois primeiros erros seguidos são tolerados
--     (dedo que escorrega); a partir do terceiro, 1, depois 3, depois 10
--     minutos — nunca mais que 10;
--   * digitar durante o bloqueio NÃO aumenta o prazo: só diz quanto falta;
--   * um acerto zera; 24 horas sem errar também;
--   * PIN de quem está de folga não conta como erro, e a tela diz a verdade
--     ("<Nome> está de folga hoje nesta loja"): o nome já estava na tela;
--   * o gestor libera na hora (Pessoas → Equipe), e fica gravado quem e quando.
-- Os bloqueios em vigor (a trava antiga, do tablet) são limpos.

-- ---------------------------------------------------------------------------
-- 1. O estado da trava de cada pessoa, e o registro de quem liberou
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.travaspin (
  contaid       integer NOT NULL DEFAULT public.minha_conta() REFERENCES public.contas (contaid) ON DELETE RESTRICT,
  funcionarioid integer NOT NULL,
  erros         integer NOT NULL DEFAULT 0 CHECK (erros >= 0),
  nivel         integer NOT NULL DEFAULT 0 CHECK (nivel >= 0),
  bloqueadoate  timestamptz,
  ultimoerro    timestamptz,
  PRIMARY KEY (contaid, funcionarioid),
  CONSTRAINT travaspin_funcionario_fk FOREIGN KEY (contaid, funcionarioid)
    REFERENCES public.funcionarios (contaid, funcionarioid) ON DELETE CASCADE
);
ALTER TABLE public.travaspin ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.travaspin FROM anon, authenticated;
GRANT SELECT ON public.travaspin TO authenticated;
GRANT ALL ON public.travaspin TO service_role;
DROP POLICY IF EXISTS travaspin_sel ON public.travaspin;
CREATE POLICY travaspin_sel ON public.travaspin FOR SELECT TO authenticated
  USING (contaid = (select public.minha_conta()));
COMMENT ON TABLE public.travaspin IS
  'A trava do PIN do tablet, por pessoa: erros seguidos, o degrau (1, 3 ou 10 minutos) e até quando está bloqueada. Só as funções do tablet e liberar_pin escrevem.';

CREATE TABLE IF NOT EXISTS public.pinliberacoes (
  liberacaoid   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contaid       integer NOT NULL DEFAULT public.minha_conta() REFERENCES public.contas (contaid) ON DELETE RESTRICT,
  funcionarioid integer NOT NULL,
  liberadopor   uuid,
  liberadoem    timestamptz NOT NULL DEFAULT now(),
  estavaate     timestamptz,
  erros         integer,
  CONSTRAINT pinliberacoes_conta_unico UNIQUE (contaid, liberacaoid),
  CONSTRAINT pinliberacoes_funcionario_fk FOREIGN KEY (contaid, funcionarioid)
    REFERENCES public.funcionarios (contaid, funcionarioid) ON DELETE CASCADE
);
ALTER TABLE public.pinliberacoes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.pinliberacoes FROM anon, authenticated;
GRANT SELECT ON public.pinliberacoes TO authenticated;
GRANT ALL ON public.pinliberacoes TO service_role;
DROP POLICY IF EXISTS pinliberacoes_sel ON public.pinliberacoes;
CREATE POLICY pinliberacoes_sel ON public.pinliberacoes FOR SELECT TO authenticated
  USING (contaid = (select public.minha_conta()));
COMMENT ON TABLE public.pinliberacoes IS
  'Quem liberou o PIN de quem, e quando (Pessoas → Equipe → "liberar PIN agora"). Nunca muda.';

-- ---------------------------------------------------------------------------
-- 2. A escada: UM lugar só (o teto de 10 minutos mora aqui)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.pin_minutos_do_degrau(p_nivel integer)
RETURNS integer
LANGUAGE sql
IMMUTABLE
SET search_path = public, pg_temp
AS $$
  SELECT CASE WHEN p_nivel <= 1 THEN 1 WHEN p_nivel = 2 THEN 3 ELSE 10 END
$$;
REVOKE ALL ON FUNCTION public.pin_minutos_do_degrau(integer) FROM public, anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.pin_minutos_do_degrau(integer) TO service_role;

-- ---------------------------------------------------------------------------
-- 3. Conferir o PIN DE UMA PESSOA (a pessoa já é conhecida)
-- ---------------------------------------------------------------------------
-- Devolve {funcionarioid, nome} quando o PIN confere, ou o motivo:
--   {naoeloja}           a pessoa não é desta loja (ou foi desligada);
--   {folga, nome}        está de folga hoje (NÃO conta como erro);
--   {bloqueado, minutos, nome}   em bloqueio: digitar de novo NÃO aumenta;
--   {sempin, nome}       ainda não cadastrou o PIN;
--   {pinerrado, nome, bloqueado?, minutos?}  errou (e, se fechou, por quanto).
-- Interna: recebe a conta e a loja.
CREATE OR REPLACE FUNCTION public.pin_conferir_pessoa(p_contaid integer, p_lojaid integer,
                                                      p_funcionarioid integer, p_pinhash text)
RETURNS jsonb
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  f  record;
  t  public.travaspin%ROWTYPE;
  v_nome text;
BEGIN
  IF NOT public.bot_contexto_confiavel() THEN
    RAISE EXCEPTION 'Só o servidor confere o PIN.' USING ERRCODE = 'insufficient_privilege';
  END IF;

  SELECT fu.funcionarioid, fu.nomecompleto, fu.pinhash, fu.diadefolga, fu.domingofolgamensal,
         fu.datainicioafastamento, fu.datafimafastamento
    INTO f
    FROM public.funcionarios fu
    JOIN public.funcionarioslojas fl ON fl.funcionarioid = fu.funcionarioid AND fl.contaid = p_contaid
                                    AND fl.lojaid = p_lojaid AND fl.ativo
   WHERE fu.contaid = p_contaid AND fu.funcionarioid = p_funcionarioid AND fu.ativo;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('naoeloja', true);
  END IF;
  v_nome := public.nome_curto(f.nomecompleto);

  -- De folga: nem conta como tentativa. O nome já estava na tela.
  IF NOT public.dia_de_trabalho(f.diadefolga, f.domingofolgamensal, f.datainicioafastamento,
                                f.datafimafastamento, public.hoje_da_conta(p_contaid)) THEN
    RETURN jsonb_build_object('folga', true, 'nome', v_nome);
  END IF;

  INSERT INTO public.travaspin (contaid, funcionarioid) VALUES (p_contaid, p_funcionarioid)
  ON CONFLICT DO NOTHING;
  SELECT * INTO t FROM public.travaspin
   WHERE contaid = p_contaid AND funcionarioid = p_funcionarioid FOR UPDATE;

  -- Em bloqueio: diz quanto falta e NÃO mexe em nada (não estende).
  IF t.bloqueadoate IS NOT NULL AND t.bloqueadoate > now() THEN
    RETURN jsonb_build_object('bloqueado', true, 'nome', v_nome,
                              'minutos', greatest(1, ceil(extract(epoch FROM t.bloqueadoate - now()) / 60)::integer));
  END IF;

  IF f.pinhash IS NULL THEN
    RETURN jsonb_build_object('sempin', true, 'nome', v_nome);
  END IF;

  -- Acertou: zera.
  IF f.pinhash = p_pinhash::bpchar THEN
    UPDATE public.travaspin SET erros = 0, nivel = 0, bloqueadoate = NULL
     WHERE contaid = p_contaid AND funcionarioid = p_funcionarioid AND (erros > 0 OR nivel > 0 OR bloqueadoate IS NOT NULL);
    RETURN jsonb_build_object('funcionarioid', f.funcionarioid, 'nome', v_nome);
  END IF;

  -- Errou. 24 horas sem errar recomeçam a conta.
  IF t.ultimoerro IS NULL OR t.ultimoerro < now() - interval '24 hours' THEN
    t.erros := 0; t.nivel := 0;
  END IF;
  t.erros := t.erros + 1;
  -- Os dois primeiros erros seguidos são tolerados; do terceiro em diante,
  -- cada erro sobe um degrau: 1, 3, 10, 10... minutos.
  IF t.erros >= 3 THEN
    t.nivel := t.nivel + 1;
    t.bloqueadoate := now() + make_interval(mins => public.pin_minutos_do_degrau(t.nivel));
  ELSE
    t.bloqueadoate := NULL;
  END IF;
  UPDATE public.travaspin
     SET erros = t.erros, nivel = t.nivel, bloqueadoate = t.bloqueadoate, ultimoerro = now()
   WHERE contaid = p_contaid AND funcionarioid = p_funcionarioid;

  RETURN jsonb_build_object('pinerrado', true, 'nome', v_nome)
         || CASE WHEN t.bloqueadoate IS NOT NULL
                 THEN jsonb_build_object('bloqueado', true, 'minutos', public.pin_minutos_do_degrau(t.nivel))
                 ELSE '{}'::jsonb END;
END;
$$;
REVOKE ALL ON FUNCTION public.pin_conferir_pessoa(integer, integer, integer, text) FROM public, anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.pin_conferir_pessoa(integer, integer, integer, text) TO service_role;

-- ---------------------------------------------------------------------------
-- 4. Quem trabalha hoje nesta loja (a lista de "toque no seu nome")
-- ---------------------------------------------------------------------------
-- A mesma regra de quem pode pegar (quem_pode_pegar): ativo, ligado à loja,
-- fora de folga e de afastamento. Só primeiro nome e inicial.
CREATE OR REPLACE FUNCTION public.visao_equipe_de_hoje(p_contaid integer, p_lojaid integer)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT coalesce(jsonb_agg(jsonb_build_object('funcionarioid', f.funcionarioid,
                                               'nome', public.nome_curto(f.nomecompleto))
                            ORDER BY public.nome_curto(f.nomecompleto), f.funcionarioid), '[]'::jsonb)
    FROM public.funcionarios f
    JOIN public.funcionarioslojas fl ON fl.contaid = p_contaid AND fl.funcionarioid = f.funcionarioid
                                    AND fl.lojaid = p_lojaid AND fl.ativo
   WHERE public.bot_contexto_confiavel()
     AND f.contaid = p_contaid AND f.ativo
     AND public.dia_de_trabalho(f.diadefolga, f.domingofolgamensal, f.datainicioafastamento,
                                f.datafimafastamento, public.hoje_da_conta(p_contaid))
$$;
REVOKE ALL ON FUNCTION public.visao_equipe_de_hoje(integer, integer) FROM public, anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.visao_equipe_de_hoje(integer, integer) TO service_role;

-- ---------------------------------------------------------------------------
-- 5. Pegar e entregar pelo tablet, com a pessoa conhecida
-- ---------------------------------------------------------------------------
-- As versões antigas (visao_pegar_com_pin / visao_entregar_com_pin, com a
-- trava do tablet) continuam no banco até a versão nova ser publicada: o
-- servidor antigo ainda as chama nesse intervalo.
CREATE OR REPLACE FUNCTION public.visao_pegar_com_pin_de(p_contaid integer, p_lojaid integer,
                                                         p_pinhash text, p_funcionarioid integer,
                                                         p_atribuicaoid integer)
RETURNS jsonb
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  t0 timestamptz := clock_timestamp();
  t1 timestamptz;
  t2 timestamptz;
  v_quem  jsonb;
  v_fila  jsonb;
  v_dono  integer;
  v_pessoa integer;
BEGIN
  IF NOT public.bot_contexto_confiavel() THEN
    RAISE EXCEPTION 'Só o servidor abre a visão da loja.' USING ERRCODE = 'insufficient_privilege';
  END IF;

  -- Tarefa com dono: é o dono, seja qual for o nome tocado.
  SELECT ta.funcionarioid INTO v_dono FROM public.tarefasatribuidas ta
   WHERE ta.contaid = p_contaid AND ta.atribuicaoid = p_atribuicaoid AND ta.lojaid = p_lojaid;
  v_pessoa := coalesce(v_dono, p_funcionarioid);
  IF v_pessoa IS NULL THEN
    RETURN jsonb_build_object('erro', 'Toque no seu nome antes do PIN.');
  END IF;

  v_quem := public.pin_conferir_pessoa(p_contaid, p_lojaid, v_pessoa, p_pinhash);
  IF NOT (v_quem ? 'funcionarioid') THEN
    RETURN v_quem;
  END IF;
  t1 := clock_timestamp();

  BEGIN
    PERFORM public.visao_pegar(p_contaid, p_lojaid, v_pessoa, p_atribuicaoid);
  EXCEPTION WHEN OTHERS THEN
    RETURN jsonb_build_object('erro', SQLERRM);
  END;
  t2 := clock_timestamp();

  v_fila := public.visao_fila(p_contaid, p_lojaid);
  RETURN jsonb_build_object(
    'nome', v_quem->'nome',
    'fila', v_fila,
    'tempos', jsonb_build_object('pin',  public.ms_entre(t0, t1),
                                 'acao', public.ms_entre(t1, t2),
                                 'fila', public.ms_entre(t2, clock_timestamp())));
END;
$$;
REVOKE ALL ON FUNCTION public.visao_pegar_com_pin_de(integer, integer, text, integer, integer) FROM public, anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.visao_pegar_com_pin_de(integer, integer, text, integer, integer) TO service_role;

-- Entregar: a pessoa é QUEM ACEITOU hoje. O tablet mostra o nome.
CREATE OR REPLACE FUNCTION public.visao_entregar_com_pin_de(p_contaid integer, p_lojaid integer,
                                                            p_pinhash text, p_atribuicaoid integer,
                                                            p_caminho text, p_observacao text,
                                                            p_fotoidunico text, p_semhorafoto boolean)
RETURNS jsonb
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  t0 timestamptz := clock_timestamp();
  t1 timestamptz;
  t2 timestamptz;
  v_quem   jsonb;
  v_fila   jsonb;
  v_pessoa integer;
BEGIN
  IF NOT public.bot_contexto_confiavel() THEN
    RAISE EXCEPTION 'Só o servidor abre a visão da loja.' USING ERRCODE = 'insufficient_privilege';
  END IF;

  -- Só quem aceitou entrega (visao_entregar confere de novo): a pessoa é ela.
  SELECT a.funcionarioid INTO v_pessoa
    FROM public.missoesaceites a
    JOIN public.tarefasatribuidas ta ON ta.contaid = a.contaid AND ta.atribuicaoid = a.atribuicaoid
                                    AND ta.lojaid = p_lojaid
   WHERE a.contaid = p_contaid AND a.atribuicaoid = p_atribuicaoid
     AND a.dia = public.hoje_da_conta(p_contaid) AND a.revogadoem IS NULL;
  IF v_pessoa IS NULL THEN
    RETURN jsonb_build_object('erro', 'Aceite a tarefa antes de entregar.');
  END IF;

  v_quem := public.pin_conferir_pessoa(p_contaid, p_lojaid, v_pessoa, p_pinhash);
  IF NOT (v_quem ? 'funcionarioid') THEN
    RETURN v_quem;
  END IF;
  t1 := clock_timestamp();

  BEGIN
    PERFORM public.visao_entregar(p_contaid, p_lojaid, v_pessoa, p_atribuicaoid, p_caminho, p_observacao,
                                  p_fotoidunico, coalesce(p_semhorafoto, false));
  EXCEPTION WHEN OTHERS THEN
    RETURN jsonb_build_object('erro', SQLERRM);
  END;
  t2 := clock_timestamp();

  v_fila := public.visao_fila(p_contaid, p_lojaid);
  RETURN jsonb_build_object(
    'nome', v_quem->'nome',
    'fila', v_fila,
    'tempos', jsonb_build_object('pin',  public.ms_entre(t0, t1),
                                 'acao', public.ms_entre(t1, t2),
                                 'fila', public.ms_entre(t2, clock_timestamp())));
END;
$$;
REVOKE ALL ON FUNCTION public.visao_entregar_com_pin_de(integer, integer, text, integer, text, text, text, boolean)
  FROM public, anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.visao_entregar_com_pin_de(integer, integer, text, integer, text, text, text, boolean)
  TO service_role;

-- ---------------------------------------------------------------------------
-- 6. O gestor libera o PIN de uma pessoa, na hora
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.liberar_pin(p_funcionarioid integer)
RETURNS void
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_conta integer := public.minha_conta_editavel();
  t public.travaspin%ROWTYPE;
BEGIN
  IF v_conta IS NULL THEN
    RAISE EXCEPTION 'Sua conta não pode alterar dados no momento.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF NOT public.sou_master() THEN
    RAISE EXCEPTION 'Só o responsável pela conta libera o PIN.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.funcionarios WHERE contaid = v_conta AND funcionarioid = p_funcionarioid) THEN
    RAISE EXCEPTION 'Pessoa não encontrada.' USING ERRCODE = 'no_data_found';
  END IF;
  SELECT * INTO t FROM public.travaspin WHERE contaid = v_conta AND funcionarioid = p_funcionarioid FOR UPDATE;
  INSERT INTO public.pinliberacoes (contaid, funcionarioid, liberadopor, estavaate, erros)
  VALUES (v_conta, p_funcionarioid, auth.uid(), t.bloqueadoate, t.erros);
  UPDATE public.travaspin SET erros = 0, nivel = 0, bloqueadoate = NULL
   WHERE contaid = v_conta AND funcionarioid = p_funcionarioid;
END;
$$;
REVOKE ALL ON FUNCTION public.liberar_pin(integer) FROM public, anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.liberar_pin(integer) TO authenticated;

-- O que Pessoas → Equipe mostra: quem errou o PIN e quantos minutos faltam
-- (pela hora do SERVIDOR, não do computador do gestor). Lê com as regras de
-- acesso de quem pergunta: só a própria conta.
CREATE OR REPLACE FUNCTION public.travas_do_pin()
RETURNS TABLE (funcionarioid integer, erros integer, minutosfaltam integer)
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
  SELECT t.funcionarioid, t.erros,
         CASE WHEN t.bloqueadoate > now()
              THEN greatest(1, ceil(extract(epoch FROM t.bloqueadoate - now()) / 60)::integer) ELSE 0 END
    FROM public.travaspin t
   WHERE t.contaid = public.minha_conta()
     AND (t.bloqueadoate > now() OR (t.erros > 0 AND t.ultimoerro > now() - interval '24 hours'))
$$;
REVOKE ALL ON FUNCTION public.travas_do_pin() FROM public, anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.travas_do_pin() TO authenticated;

-- ---------------------------------------------------------------------------
-- 7. Ao aplicar: limpa os bloqueios em vigor (a trava antiga, do tablet)
-- ---------------------------------------------------------------------------
DELETE FROM public.tentativasacesso WHERE tipo = 'pintablet';

COMMIT;
