-- =========================================================================
-- STGame — Metas por mês: a meta de cada dia, seis permissões de meta e o
-- histórico de toda mudança de meta.
--
-- Como usar: Supabase -> SQL Editor -> New query -> colar TUDO -> Run.
-- Se der erro, NADA é aplicado: me mande a mensagem.
-- Pode rodar duas vezes sem problema.
--
-- ATENÇÃO: aplique antes o aplicar-jornada-por-loja.sql (e os anteriores).
-- Aplique ESTE ARQUIVO ANTES de publicar a versão nova.
--
-- Este arquivo tem UMA migração:
--   20260930100000_metas_por_mes.sql
--
-- CLASSIFICAÇÃO: ACRESCENTA (cria duas tabelas, seis permissões, uma leitura e uma gravação; as funções que o site no ar chama continuam com o mesmo nome e os mesmos parâmetros, e a resposta ao master não muda. O site no ar continua funcionando com o banco novo)
--
-- O QUE MUDA: a meta de um dia passa a vir da especial, depois da meta daquele dia no mês, depois do modelo da semana (mês que ninguém editou fica igual). Meta de mês que já passou vira somente leitura, também para o master. O gerente só vê e mexe na meta com as permissões novas, que nascem desmarcadas: até você marcá-las, quem hoje vê a meta do mês, o modelo e as especiais deixa de ver. Toda mudança de meta aparece na lista dos Estornos.
-- =========================================================================


BEGIN;

-- ======== 20260930100000_metas_por_mes.sql ========
-- CLASSIFICAÇÃO: ACRESCENTA
-- (cria duas tabelas, seis permissões novas, uma leitura e uma gravação novas;
-- as funções que o site no ar chama continuam com o mesmo nome, os mesmos
-- parâmetros e a mesma resposta para o master. O que muda para quem usa o site
-- no ar é regra decidida: mês passado vira somente leitura, e o gerente só vê
-- e mexe na meta com as permissões novas, que nascem desmarcadas.)
--
-- Metas por mês (30/09/2026, decisões do Wisley):
-- 1. A META DE UM DIA vem de UM lugar só, meta_do_dia, nesta ordem:
--      1º a meta especial daquela data;
--      2º a meta daquele dia naquele mês (a novidade, tabela metasdodia);
--      3º o modelo do dia da semana (o de sempre, que vira o padrão).
--    Toda leitura (painel, TV, Início, aviso da venda de ontem, lançamento)
--    já pergunta a meta_do_dia: mudando ela, muda tudo junto. Mês que ninguém
--    editou continua igual ao de hoje.
-- 2. A meta por dia do mês grava pela salvar_metas_do_mes_por_dia, tudo ou
--    nada: nunca em dia já lançado (a meta dele ficou guardada no lançamento),
--    nunca em dia com meta especial, nunca em mês que já passou.
-- 4. Editar meta (do mês, do dia, especial): do mês atual em diante. O mês
--    passado é somente leitura. Lançar e corrigir venda: como já era (mês
--    atual e anterior).
-- 6. Seis permissões novas, desmarcadas: ver/editar meta do mês, meta por dia
--    e metas especiais. Quem não pode ver não edita; quem não vê R$ não edita.
--    Toda mudança de meta (valor ou pontos, antes e depois, quem e quando) vai
--    para metasalteracoes, por gatilho — por qualquer caminho — e aparece para
--    o master na lista dos Estornos.

-- ---------------------------------------------------------------------------
-- 1. A meta de cada dia do mês, por loja
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.metasdodia (
  metadodiaid  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contaid      integer NOT NULL DEFAULT public.minha_conta() REFERENCES public.contas (contaid) ON DELETE RESTRICT,
  lojaid       integer NOT NULL,
  data         date NOT NULL,
  valormeta    numeric(18,2) NOT NULL,
  pontospremio integer NOT NULL DEFAULT 0,
  alteradopor  uuid REFERENCES auth.users (id) ON DELETE SET NULL,
  alteradoem   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT metasdodia_conta_unico UNIQUE (contaid, metadodiaid),
  CONSTRAINT metasdodia_uma_por_data UNIQUE (lojaid, data),
  CONSTRAINT metasdodia_loja_fk FOREIGN KEY (contaid, lojaid) REFERENCES public.lojas (contaid, lojaid) ON DELETE RESTRICT,
  CONSTRAINT metasdodia_valores_validos CHECK (valormeta >= 0 AND valormeta < 1000000000
                                               AND pontospremio >= 0 AND pontospremio <= 10000)
);
COMMENT ON TABLE public.metasdodia IS
  'A meta de um dia de um mês, por loja (30/09/2026). Vale entre a meta especial da data e o modelo do dia da semana (meta_do_dia). Grava só pela salvar_metas_do_mes_por_dia.';
ALTER TABLE public.metasdodia ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.metasdodia FROM anon, authenticated;
GRANT SELECT ON public.metasdodia TO authenticated;
GRANT ALL ON public.metasdodia TO service_role;
DROP POLICY IF EXISTS metasdodia_sel ON public.metasdodia;
CREATE POLICY metasdodia_sel ON public.metasdodia FOR SELECT TO authenticated
  USING (contaid = (SELECT public.minha_conta()));

-- ---------------------------------------------------------------------------
-- 2. O histórico de toda mudança de meta
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.metasalteracoes (
  alteracaoid  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contaid      integer NOT NULL DEFAULT public.minha_conta() REFERENCES public.contas (contaid) ON DELETE RESTRICT,
  lojaid       integer NOT NULL,
  tipo         text NOT NULL,
  referencia   text NOT NULL,
  valorantes   numeric(18,2),
  valordepois  numeric(18,2),
  pontosantes  integer,
  pontosdepois integer,
  alteradopor  uuid REFERENCES auth.users (id) ON DELETE SET NULL,
  alteradoem   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT metasalteracoes_conta_unico UNIQUE (contaid, alteracaoid),
  CONSTRAINT metasalteracoes_loja_fk FOREIGN KEY (contaid, lojaid) REFERENCES public.lojas (contaid, lojaid) ON DELETE RESTRICT,
  CONSTRAINT metasalteracoes_tipo_valido CHECK (tipo IN ('mes', 'dia', 'semana', 'especial'))
);
COMMENT ON TABLE public.metasalteracoes IS
  'Toda mudança de meta (30/09/2026): meta do mês, do dia, modelo da semana e especial; valor e pontos antes e depois, quem e quando. Grava só o gatilho; nunca muda nem se apaga. Só o master lê (lista dos Estornos).';
CREATE INDEX IF NOT EXISTS metasalteracoes_loja_idx ON public.metasalteracoes (contaid, lojaid, alteradoem DESC);
ALTER TABLE public.metasalteracoes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.metasalteracoes FROM anon, authenticated;
GRANT SELECT ON public.metasalteracoes TO authenticated;
GRANT ALL ON public.metasalteracoes TO service_role;
DROP POLICY IF EXISTS metasalteracoes_sel ON public.metasalteracoes;
CREATE POLICY metasalteracoes_sel ON public.metasalteracoes FOR SELECT TO authenticated
  USING (contaid = (SELECT public.minha_conta()));
DROP TRIGGER IF EXISTS metasalteracoes_imutavel ON public.metasalteracoes;
CREATE TRIGGER metasalteracoes_imutavel BEFORE UPDATE OR DELETE ON public.metasalteracoes
  FOR EACH ROW EXECUTE FUNCTION public.historico_imutavel();

-- O gatilho: registra só quando o VALOR ou os PONTOS mudam (salvar de novo o
-- mesmo valor, ou mudar só o nome, não entra).
CREATE OR REPLACE FUNCTION public.registrar_mudanca_de_meta()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_antes  jsonb := CASE WHEN TG_OP <> 'INSERT' THEN to_jsonb(OLD) END;
  v_depois jsonb := CASE WHEN TG_OP <> 'DELETE' THEN to_jsonb(NEW) END;
  r        jsonb := coalesce(CASE WHEN TG_OP <> 'DELETE' THEN to_jsonb(NEW) END, to_jsonb(OLD));
  v_tipo   text;
  v_ref    text;
  v_campo  text := 'valormeta';
BEGIN
  IF TG_TABLE_NAME = 'metasprincipais' THEN
    v_tipo := 'mes'; v_campo := 'valormetatotal';
    v_ref := 'Meta do mês ' || to_char((r->>'datainicio')::date, 'MM/YYYY');
  ELSIF TG_TABLE_NAME = 'metasdodia' THEN
    v_tipo := 'dia';
    v_ref := 'Meta do dia ' || to_char((r->>'data')::date, 'DD/MM/YYYY');
  ELSIF TG_TABLE_NAME = 'metasdiariasmodelos' THEN
    v_tipo := 'semana';
    v_ref := 'Modelo de ' || (ARRAY['domingo', 'segunda', 'terça', 'quarta', 'quinta', 'sexta', 'sábado'])[(r->>'diasemanaid')::integer];
  ELSE
    v_tipo := 'especial';
    v_ref := 'Meta especial ' || to_char((r->>'data')::date, 'DD/MM/YYYY') || ' (' || (r->>'descricao') || ')';
  END IF;
  IF (v_antes->>v_campo)::numeric IS NOT DISTINCT FROM (v_depois->>v_campo)::numeric
     AND (v_antes->>'pontospremio')::integer IS NOT DISTINCT FROM (v_depois->>'pontospremio')::integer THEN
    RETURN NULL;
  END IF;
  INSERT INTO public.metasalteracoes (contaid, lojaid, tipo, referencia, valorantes, valordepois,
                                      pontosantes, pontosdepois, alteradopor)
  VALUES ((r->>'contaid')::integer, (r->>'lojaid')::integer, v_tipo, v_ref,
          (v_antes->>v_campo)::numeric, (v_depois->>v_campo)::numeric,
          (v_antes->>'pontospremio')::integer, (v_depois->>'pontospremio')::integer, auth.uid());
  RETURN NULL;
END;
$$;
REVOKE ALL ON FUNCTION public.registrar_mudanca_de_meta() FROM public, anon, authenticated;
DROP TRIGGER IF EXISTS metasprincipais_historico ON public.metasprincipais;
CREATE TRIGGER metasprincipais_historico AFTER INSERT OR UPDATE OR DELETE ON public.metasprincipais
  FOR EACH ROW EXECUTE FUNCTION public.registrar_mudanca_de_meta();
DROP TRIGGER IF EXISTS metasdodia_historico ON public.metasdodia;
CREATE TRIGGER metasdodia_historico AFTER INSERT OR UPDATE OR DELETE ON public.metasdodia
  FOR EACH ROW EXECUTE FUNCTION public.registrar_mudanca_de_meta();
DROP TRIGGER IF EXISTS metasdiariasmodelos_historico ON public.metasdiariasmodelos;
CREATE TRIGGER metasdiariasmodelos_historico AFTER INSERT OR UPDATE OR DELETE ON public.metasdiariasmodelos
  FOR EACH ROW EXECUTE FUNCTION public.registrar_mudanca_de_meta();
DROP TRIGGER IF EXISTS metasespeciais_historico ON public.metasespeciais;
CREATE TRIGGER metasespeciais_historico AFTER INSERT OR UPDATE OR DELETE ON public.metasespeciais
  FOR EACH ROW EXECUTE FUNCTION public.registrar_mudanca_de_meta();

-- ---------------------------------------------------------------------------
-- 3. A meta de um dia: UMA ordem só, escrita UMA vez
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.meta_do_dia(p_lojaid integer, p_dia date)
RETURNS TABLE (valormeta numeric, pontospremio integer, origem text, descricao text)
LANGUAGE sql
STABLE
SET search_path = public, pg_temp
AS $$
  -- A ordem das três origens (30/09/2026): 1º a especial da data, 2º a meta
  -- daquele dia naquele mês, 3º o modelo do dia da semana. Toda tela e todo
  -- lançamento perguntam AQUI; não repita esta ordem em outro lugar.
  SELECT x.valormeta, x.pontospremio, x.origem, x.descricao
    FROM (
      SELECT me.valormeta, me.pontospremio, 'especial'::text AS origem, me.descricao::text AS descricao, 1 AS ordem
        FROM public.metasespeciais me
       WHERE me.lojaid = p_lojaid AND me.data = p_dia
      UNION ALL
      SELECT md.valormeta, md.pontospremio, 'mes', NULL::text, 2
        FROM public.metasdodia md
       WHERE md.lojaid = p_lojaid AND md.data = p_dia
      UNION ALL
      SELECT mm.valormeta, mm.pontospremio, 'semana', mm.nomedia::text, 3
        FROM public.metasdiariasmodelos mm
       WHERE mm.lojaid = p_lojaid AND mm.diasemanaid = extract(dow FROM p_dia)::integer + 1
    ) x
   ORDER BY x.ordem
   LIMIT 1
$$;

-- ---------------------------------------------------------------------------
-- 4. As seis permissões novas (nascem negadas para todo cargo)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.catalogo_de_permissoes()
 RETURNS TABLE(codigo text, tela text, nome text, ordem integer)
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'public', 'pg_temp'
AS $function$
  SELECT v.codigo, v.tela, v.nome, v.ordem FROM (VALUES
    ('inicio.ver',                'Início',          'Ver',                                   10),
    ('painel.ver',                'Painel da loja',  'Ver',                                   20),
    ('quadro.ver',                'Quadro',          'Ver',                                   30),
    ('quadro.registrar_entrega',  'Quadro',          'Registrar entrega',                     31),
    ('quadro.aprovar',            'Quadro',          'Aprovar',                               32),
    ('quadro.recusar',            'Quadro',          'Recusar',                               33),
    ('quadro.estornar',           'Quadro',          'Estornar entrega aprovada',             34),
    ('quadro.revogar_aceite',     'Quadro',          'Revogar aceite',                        35),
    ('quadro.passar_folga',       'Quadro',          'Passar tarefa de quem está de folga',   36),
    ('tarefas.ver',               'Tarefas',         'Ver',                                   40),
    ('tarefas.atribuir',          'Tarefas',         'Atribuir',                              41),
    ('tarefas.encerrar_atribuicao','Tarefas',        'Encerrar atribuição',                   42),
    ('tarefas.catalogo',          'Tarefas',         'Editar catálogo (criar, editar, desativar)', 43),
    ('solicitacoes.ver',          'Solicitações',    'Ver',                                   50),
    ('solicitacoes.abrir',        'Solicitações',    'Abrir',                                 51),
    ('solicitacoes.concluir',     'Solicitações',    'Concluir',                              52),
    ('solicitacoes.recusar',      'Solicitações',    'Recusar',                               53),
    ('relatorios.ver',            'Relatórios',      'Ver',                                   60),
    ('equipe.ver',                'Equipe',          'Ver',                                   70),
    ('equipe.criar',              'Equipe',          'Criar pessoa',                          71),
    ('equipe.editar',             'Equipe',          'Editar',                                72),
    ('equipe.desativar',          'Equipe',          'Desativar e reativar',                  73),
    ('equipe.criar_acesso',       'Equipe',          'Criar acesso',                          74),
    ('equipe.redefinir_acesso',   'Equipe',          'Redefinir acesso',                      75),
    ('equipe.liberar_pin',        'Equipe',          'Liberar PIN',                           76),
    ('jornada.ver',               'Jornada',         'Ver',                                   80),
    ('jornada.vincular',          'Jornada',         'Ligar pessoa a uma jornada',            81),
    ('jornada.mapa',              'Jornada',         'Mapa e exportar',                       82),
    ('jornada.editar',            'Jornada',         'Criar, editar e apagar jornada',        83),
    ('feedbacks.ver',             'Feedbacks',       'Ver',                                   90),
    ('feedbacks.registrar',       'Feedbacks',       'Registrar',                             91),
    ('feedbacks.anular',          'Feedbacks',       'Anular',                                92),
    ('justificativas.ver',        'Justificativas',  'Ver',                                  100),
    ('justificativas.registrar',  'Justificativas',  'Registrar',                            101),
    ('justificativas.decidir',    'Justificativas',  'Aceitar e recusar',                    102),
    ('ranking.ver',               'Ranking',         'Ver',                                  110),
    ('conquistas.ver',            'Conquistas',      'Ver',                                  111),
    ('extrato.ver',               'Extrato',         'Ver',                                  112),
    ('premios.ver',               'Prêmios',         'Ver',                                  120),
    ('premios.registrar',         'Prêmios',         'Registrar resgate',                    121),
    ('premios.entregar',          'Prêmios',         'Aprovar (entregar) resgate',           122),
    ('premios.cancelar',          'Prêmios',         'Cancelar resgate',                     123),
    ('premios.estornar',          'Prêmios',         'Estornar resgate',                     124),
    ('metas.ver',                 'Metas',           'Ver',                                  130),
    ('metas.lancar_venda',        'Metas',           'Lançar venda',                         131),
    ('metas.mes_ver',             'Metas',           'Ver meta do mês',                      132),
    ('metas.mes_editar',          'Metas',           'Editar meta do mês',                   133),
    ('metas.dia_ver',             'Metas',           'Ver meta por dia',                     134),
    ('metas.dia_editar',          'Metas',           'Editar meta por dia',                  135),
    ('metas.especiais_ver',       'Metas',           'Ver metas especiais',                  136),
    ('metas.especiais_editar',    'Metas',           'Editar metas especiais',               137),
    ('agenda.ver',                'Agenda',          'Ver',                                  140),
    ('agenda.editar',             'Agenda',          'Criar e editar',                       141),
    ('agenda.realizado',          'Agenda',          'Marcar realizado',                     142),
    ('agenda.pagamento',          'Agenda',          'Pagamento',                            143),
    ('comunicados.ver',           'Comunicados',     'Ver',                                  150),
    ('comunicados.publicar',      'Comunicados',     'Publicar',                             151),
    ('onboarding.ver',            'Onboarding',      'Ver',                                  160),
    ('onboarding.conduzir',       'Onboarding',      'Conduzir',                             161),
    ('lojas.ver',                 'Lojas',           'Ver',                                  170),
    ('lojas.editar',              'Lojas',           'Editar',                               171),
    ('lojas.tv',                  'Lojas',           'Configurar TV',                        172),
    ('lojas.tablet_som',          'Lojas',           'Som do tablet',                        173),
    ('lojas.tablet_acesso',       'Lojas',           'Senha do tablet',                      174),
    ('valores.ver_rs',            'Todas as telas',  'Ver valores em R$',                    180)
  ) AS v(codigo, tela, nome, ordem)
$function$;

-- ---------------------------------------------------------------------------
-- 5. O mês dia a dia: a leitura da tela nova
-- ---------------------------------------------------------------------------
-- Cada dia com a meta que vale e DE ONDE ela veio: 'lancado' (congelada no
-- lançamento), 'especial', 'mes' (deste mês) ou 'semana' (do modelo). Master:
-- tudo da loja dele. Gerente: com Metas, R$ e "Ver meta por dia" na loja; o
-- valor de dia com meta especial, só com "Ver metas especiais".
CREATE OR REPLACE FUNCTION public.metas_do_mes_por_dia(p_lojaid integer, p_mes date)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_conta    integer := coalesce(public.minha_conta(), public.conta_do_gerente());
  v_ini      date := date_trunc('month', p_mes)::date;
  v_fim      date := (date_trunc('month', p_mes) + interval '1 month - 1 day')::date;
  v_hoje     date;
  v_esp      boolean;
  v_editar   boolean;
  v_espedit  boolean;
BEGIN
  IF v_conta IS NULL OR p_mes IS NULL
     OR NOT EXISTS (SELECT 1 FROM public.lojas l WHERE l.contaid = v_conta AND l.lojaid = p_lojaid)
     OR NOT (public.pode('metas.ver', p_lojaid) AND public.pode('valores.ver_rs', p_lojaid)
             AND public.pode('metas.dia_ver', p_lojaid)) THEN
    RETURN NULL;
  END IF;
  v_hoje := public.hoje_da_conta(v_conta);
  v_esp := public.pode('metas.especiais_ver', p_lojaid);
  v_editar := v_ini >= date_trunc('month', v_hoje)::date AND public.pode('metas.dia_editar', p_lojaid);
  v_espedit := v_ini >= date_trunc('month', v_hoje)::date AND v_esp AND public.pode('metas.especiais_editar', p_lojaid);
  RETURN jsonb_build_object(
    'hoje', v_hoje,
    'mesatual', date_trunc('month', v_hoje)::date,
    'podeeditar', v_editar,
    'especiaisver', v_esp,
    'especiaiseditar', v_espedit,
    'modelo', (SELECT coalesce(jsonb_agg(jsonb_build_object('diasemanaid', m.diasemanaid, 'valormeta', m.valormeta,
                                                            'pontospremio', m.pontospremio) ORDER BY m.diasemanaid), '[]'::jsonb)
                 FROM public.metasdiariasmodelos m WHERE m.contaid = v_conta AND m.lojaid = p_lojaid),
    'dias', (
      SELECT coalesce(jsonb_agg(jsonb_build_object(
               'dia', x.dia, 'lancado', x.lancado, 'origem', x.origem,
               'meta', CASE WHEN x.especial AND NOT v_esp THEN NULL ELSE x.meta END,
               'pontos', CASE WHEN x.especial AND NOT v_esp THEN NULL ELSE x.pontos END,
               'descricao', CASE WHEN x.especial AND NOT v_esp THEN NULL ELSE x.descricao END,
               'modelo', x.modelo, 'modelopontos', x.modelopontos) ORDER BY x.dia), '[]'::jsonb)
        FROM (
          SELECT d::date AS dia,
                 a.apuracaoid IS NOT NULL AS lancado,
                 CASE WHEN a.apuracaoid IS NOT NULL THEN coalesce(a.origemmeta, 'semana') ELSE md.origem END AS origem,
                 coalesce(CASE WHEN a.apuracaoid IS NOT NULL THEN a.origemmeta ELSE md.origem END, '') = 'especial' AS especial,
                 CASE WHEN a.apuracaoid IS NOT NULL THEN a.valormetadia ELSE md.valormeta END AS meta,
                 CASE WHEN a.apuracaoid IS NOT NULL THEN a.pontosmetadia ELSE md.pontospremio END AS pontos,
                 CASE WHEN a.apuracaoid IS NOT NULL THEN a.descricaometa ELSE md.descricao END AS descricao,
                 mm.valormeta AS modelo, mm.pontospremio AS modelopontos
            FROM generate_series(v_ini, v_fim, interval '1 day') d
            LEFT JOIN public.metasdiariasapuracoes a ON a.contaid = v_conta AND a.lojaid = p_lojaid AND a.dataapuracao = d::date
            LEFT JOIN LATERAL public.meta_do_dia(p_lojaid, d::date) md ON true
            LEFT JOIN public.metasdiariasmodelos mm ON mm.contaid = v_conta AND mm.lojaid = p_lojaid
                                                   AND mm.diasemanaid = extract(dow FROM d)::integer + 1
        ) x)
  );
END;
$$;
REVOKE ALL ON FUNCTION public.metas_do_mes_por_dia(integer, date) FROM public, anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.metas_do_mes_por_dia(integer, date) TO authenticated;

-- ---------------------------------------------------------------------------
-- 6. O mês dia a dia: a gravação (um Salvar só, tudo ou nada)
-- ---------------------------------------------------------------------------
-- p_linhas: [{dia, valormeta, pontospremio}], só os dias que mudaram.
-- valormeta vazio = o dia volta a seguir o modelo.
CREATE OR REPLACE FUNCTION public.salvar_metas_do_mes_por_dia(p_lojaid integer, p_mes date, p_linhas jsonb)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_conta integer := public.conta_do_gestor_editavel();
  v_ini   date := date_trunc('month', p_mes)::date;
  v_fim   date := (date_trunc('month', p_mes) + interval '1 month - 1 day')::date;
  v_hoje  date;
  l       record;
  v_atual public.metasdodia%ROWTYPE;
  n       integer := 0;
BEGIN
  IF v_conta IS NULL THEN
    RAISE EXCEPTION '%', public.motivo_da_recusa() USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.lojas WHERE lojaid = p_lojaid AND contaid = v_conta AND ativa) THEN
    RAISE EXCEPTION 'Loja não encontrada.' USING ERRCODE = 'no_data_found';
  END IF;
  -- Permissão e loja, no banco (a régua do alcance: pode() na loja).
  IF NOT public.pode('metas.dia_editar', p_lojaid) THEN
    RAISE EXCEPTION 'Seu cargo não permite editar a meta por dia desta loja.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  -- Quem não pode ver um valor não pode gravá-lo.
  IF NOT public.pode('metas.dia_ver', p_lojaid) THEN
    RAISE EXCEPTION 'Seu cargo não mostra a meta por dia desta loja, então não a edita.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF NOT public.pode('valores.ver_rs', p_lojaid) THEN
    RAISE EXCEPTION 'Seu cargo não mostra valores em R$ nesta loja, então não edita meta.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  v_hoje := public.hoje_da_conta(v_conta);
  IF p_mes IS NULL OR v_ini < date_trunc('month', v_hoje)::date THEN
    RAISE EXCEPTION 'Este mês já passou: a meta dele fica como foi. Só dá para mexer na meta do mês atual e dos próximos.'
      USING ERRCODE = 'check_violation';
  END IF;
  IF p_linhas IS NULL OR jsonb_typeof(p_linhas) <> 'array' THEN
    RAISE EXCEPTION 'Nada para salvar.' USING ERRCODE = 'check_violation';
  END IF;
  IF (SELECT count(*) <> count(DISTINCT e->>'dia') FROM jsonb_array_elements(p_linhas) e) THEN
    RAISE EXCEPTION 'O mesmo dia veio duas vezes.' USING ERRCODE = 'check_violation';
  END IF;

  FOR l IN SELECT (e->>'dia')::date AS dia,
                  nullif(e->>'valormeta', '')::numeric AS valor,
                  nullif(e->>'pontospremio', '')::numeric AS pontos
             FROM jsonb_array_elements(p_linhas) e
            ORDER BY 1 LOOP
    IF l.dia IS NULL OR l.dia < v_ini OR l.dia > v_fim THEN
      RAISE EXCEPTION 'O dia % não é deste mês.', coalesce(to_char(l.dia, 'DD/MM/YYYY'), '(vazio)') USING ERRCODE = 'check_violation';
    END IF;
    -- O mesmo cadeado do lançamento daquele dia: ou a meta muda antes, ou o
    -- lançamento guarda a meta de antes e esta gravação é recusada.
    PERFORM pg_advisory_xact_lock(p_lojaid, l.dia - date '2000-01-01');
    IF EXISTS (SELECT 1 FROM public.metasdiariasapuracoes
                WHERE contaid = v_conta AND lojaid = p_lojaid AND dataapuracao = l.dia) THEN
      RAISE EXCEPTION 'O dia % já foi lançado: a meta dele ficou guardada no lançamento e não muda mais.', to_char(l.dia, 'DD/MM/YYYY')
        USING ERRCODE = 'check_violation';
    END IF;
    IF EXISTS (SELECT 1 FROM public.metasespeciais
                WHERE contaid = v_conta AND lojaid = p_lojaid AND data = l.dia) THEN
      RAISE EXCEPTION 'O dia % tem meta especial: mude na aba Metas especiais.', to_char(l.dia, 'DD/MM/YYYY')
        USING ERRCODE = 'check_violation';
    END IF;
    SELECT * INTO v_atual FROM public.metasdodia WHERE contaid = v_conta AND lojaid = p_lojaid AND data = l.dia;
    IF l.valor IS NULL THEN
      -- Volta para o modelo do dia da semana.
      IF v_atual.metadodiaid IS NOT NULL THEN
        DELETE FROM public.metasdodia WHERE metadodiaid = v_atual.metadodiaid;
        n := n + 1;
      END IF;
      CONTINUE;
    END IF;
    IF l.valor < 0 OR l.valor >= 1000000000 THEN
      RAISE EXCEPTION 'Meta inválida em %.', to_char(l.dia, 'DD/MM/YYYY') USING ERRCODE = 'check_violation';
    END IF;
    IF l.pontos IS NULL OR l.pontos < 0 OR l.pontos > 10000 OR l.pontos <> trunc(l.pontos) THEN
      RAISE EXCEPTION 'Pontos inválidos em % (um número inteiro de 0 a 10.000).', to_char(l.dia, 'DD/MM/YYYY') USING ERRCODE = 'check_violation';
    END IF;
    IF v_atual.metadodiaid IS NULL THEN
      INSERT INTO public.metasdodia (contaid, lojaid, data, valormeta, pontospremio, alteradopor)
      VALUES (v_conta, p_lojaid, l.dia, round(l.valor, 2), l.pontos::integer, auth.uid());
      n := n + 1;
    ELSIF v_atual.valormeta IS DISTINCT FROM round(l.valor, 2) OR v_atual.pontospremio IS DISTINCT FROM l.pontos::integer THEN
      UPDATE public.metasdodia
         SET valormeta = round(l.valor, 2), pontospremio = l.pontos::integer, alteradopor = auth.uid(), alteradoem = now()
       WHERE metadodiaid = v_atual.metadodiaid;
      n := n + 1;
    END IF;
  END LOOP;
  RETURN n;
END;
$$;
REVOKE ALL ON FUNCTION public.salvar_metas_do_mes_por_dia(integer, date, jsonb) FROM public, anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.salvar_metas_do_mes_por_dia(integer, date, jsonb) TO authenticated;

-- ---------------------------------------------------------------------------
-- 7. Meta do mês: o gerente com a permissão; mês passado, só leitura
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.salvar_meta_do_mes(p_lojaid integer, p_mes date, p_nome text, p_valor numeric, p_pontos integer, p_descricao text DEFAULT NULL::text)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_conta integer := public.conta_do_gestor_editavel();
  v_ini   date := date_trunc('month', p_mes)::date;
  v_id    integer;
BEGIN
  IF v_conta IS NULL THEN
    RAISE EXCEPTION '%', public.motivo_da_recusa() USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.lojas WHERE lojaid = p_lojaid AND contaid = v_conta AND ativa) THEN
    RAISE EXCEPTION 'Loja não encontrada.' USING ERRCODE = 'no_data_found';
  END IF;
  -- Permissão e loja, no banco (30/09/2026: o master pode delegar).
  IF NOT public.bot_contexto_confiavel() AND NOT public.pode('metas.mes_editar', p_lojaid) THEN
    RAISE EXCEPTION 'Seu cargo não permite editar a meta do mês desta loja.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  -- Quem não pode ver um valor não pode gravá-lo.
  IF NOT public.bot_contexto_confiavel() AND NOT public.pode('metas.mes_ver', p_lojaid) THEN
    RAISE EXCEPTION 'Seu cargo não mostra a meta do mês desta loja, então não a edita.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF NOT public.bot_contexto_confiavel() AND NOT public.pode('valores.ver_rs', p_lojaid) THEN
    RAISE EXCEPTION 'Seu cargo não mostra valores em R$ nesta loja, então não edita meta.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  -- O passado é o que foi (30/09/2026): do mês atual em diante.
  IF p_mes IS NULL OR v_ini < date_trunc('month', public.hoje_da_conta(v_conta))::date THEN
    RAISE EXCEPTION 'Este mês já passou: a meta dele fica como foi. Só dá para mexer na meta do mês atual e dos próximos.' USING ERRCODE = 'check_violation';
  END IF;
  IF p_valor IS NULL OR p_valor <= 0 THEN
    RAISE EXCEPTION 'A meta do mês precisa ser maior que zero.' USING ERRCODE = 'check_violation';
  END IF;
  IF p_pontos IS NULL OR p_pontos < 0 THEN
    RAISE EXCEPTION 'Os pontos do prêmio precisam ser zero ou mais.' USING ERRCODE = 'check_violation';
  END IF;

  PERFORM pg_advisory_xact_lock(p_lojaid, -(extract(year FROM v_ini)::integer * 12 + extract(month FROM v_ini)::integer));

  INSERT INTO public.metasprincipais (contaid, lojaid, nomemeta, descricao, valormetatotal, datainicio, datafim,
                                      pontospremio, criadopor)
  VALUES (v_conta, p_lojaid, coalesce(nullif(btrim(coalesce(p_nome, '')), ''), 'Meta de ' || to_char(v_ini, 'MM/YYYY')),
          nullif(btrim(coalesce(p_descricao, '')), ''), round(p_valor, 2), v_ini,
          (v_ini + interval '1 month - 1 day')::date, p_pontos, auth.uid())
  ON CONFLICT (lojaid, datainicio) DO UPDATE
     SET nomemeta = EXCLUDED.nomemeta, descricao = EXCLUDED.descricao,
         valormetatotal = EXCLUDED.valormetatotal, pontospremio = EXCLUDED.pontospremio, atualizadoem = now()
  RETURNING metaprincipalid INTO v_id;

  -- Lancamentos do mes que ainda nao estavam ligados a meta.
  UPDATE public.metasdiariasapuracoes SET metaprincipalid = v_id
   WHERE lojaid = p_lojaid AND dataapuracao BETWEEN v_ini AND (v_ini + interval '1 month - 1 day')::date
     AND metaprincipalid IS DISTINCT FROM v_id;

  PERFORM public.reavaliar_meta_do_mes(v_conta, p_lojaid, v_ini);
  RETURN v_id;
END;
$function$;

-- ---------------------------------------------------------------------------
-- 8. O modelo da semana: com "Editar meta por dia"
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.salvar_metas_da_semana(p_lojaid integer, p_linhas jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE v_conta integer := public.conta_do_gestor_editavel();
BEGIN
  IF v_conta IS NULL THEN
    RAISE EXCEPTION '%', public.motivo_da_recusa() USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.lojas WHERE lojaid = p_lojaid AND contaid = v_conta) THEN
    RAISE EXCEPTION 'Loja não encontrada.' USING ERRCODE = 'no_data_found';
  END IF;
  -- O modelo é a meta por dia de todo mês que ninguém editou (30/09/2026).
  IF NOT public.pode('metas.dia_editar', p_lojaid) THEN
    RAISE EXCEPTION 'Seu cargo não permite editar a meta por dia desta loja.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF NOT public.pode('metas.dia_ver', p_lojaid) THEN
    RAISE EXCEPTION 'Seu cargo não mostra a meta por dia desta loja, então não a edita.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF NOT public.pode('valores.ver_rs', p_lojaid) THEN
    RAISE EXCEPTION 'Seu cargo não mostra valores em R$ nesta loja, então não edita meta.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  INSERT INTO public.metasdiariasmodelos (contaid, lojaid, diasemanaid, nomedia, valormeta, pontospremio)
  SELECT v_conta, p_lojaid, (l->>'diasemanaid')::integer, l->>'nomedia', (l->>'valormeta')::numeric, (l->>'pontospremio')::integer
    FROM jsonb_array_elements(coalesce(p_linhas, '[]'::jsonb)) l
  ON CONFLICT (lojaid, diasemanaid) DO UPDATE
     SET nomedia = EXCLUDED.nomedia, valormeta = EXCLUDED.valormeta, pontospremio = EXCLUDED.pontospremio;
END;
$function$;

-- ---------------------------------------------------------------------------
-- 9. Metas especiais: com "Editar metas especiais"; data do mês atual em diante
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.criar_meta_especial(p_lojaid integer, p_data date, p_descricao text, p_valormeta numeric, p_pontospremio integer)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE v_conta integer := public.conta_do_gestor_editavel(); v_id integer;
BEGIN
  IF v_conta IS NULL THEN
    RAISE EXCEPTION '%', public.motivo_da_recusa() USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.lojas WHERE lojaid = p_lojaid AND contaid = v_conta) THEN
    RAISE EXCEPTION 'Loja não encontrada.' USING ERRCODE = 'no_data_found';
  END IF;
  IF NOT public.pode('metas.especiais_editar', p_lojaid) THEN
    RAISE EXCEPTION 'Seu cargo não permite editar metas especiais desta loja.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF NOT public.pode('metas.especiais_ver', p_lojaid) THEN
    RAISE EXCEPTION 'Seu cargo não mostra as metas especiais desta loja, então não as edita.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF NOT public.pode('valores.ver_rs', p_lojaid) THEN
    RAISE EXCEPTION 'Seu cargo não mostra valores em R$ nesta loja, então não edita meta.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF p_data IS NULL OR p_data < date_trunc('month', public.hoje_da_conta(v_conta))::date THEN
    RAISE EXCEPTION 'Esta data é de um mês que já passou: a meta dele fica como foi.' USING ERRCODE = 'check_violation';
  END IF;
  INSERT INTO public.metasespeciais (contaid, lojaid, data, descricao, valormeta, pontospremio)
  VALUES (v_conta, p_lojaid, p_data, p_descricao, p_valormeta, p_pontospremio)
  RETURNING metaespecialid INTO v_id;
  RETURN v_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.apagar_meta_especial(p_metaespecialid integer)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE v_conta integer := public.conta_do_gestor_editavel(); v_loja integer; v_data date;
BEGIN
  IF v_conta IS NULL THEN
    RAISE EXCEPTION '%', public.motivo_da_recusa() USING ERRCODE = 'insufficient_privilege';
  END IF;
  SELECT lojaid, data INTO v_loja, v_data FROM public.metasespeciais WHERE contaid = v_conta AND metaespecialid = p_metaespecialid;
  -- Não existe (ou é de outra conta): como antes, não apaga nada.
  IF NOT FOUND THEN RETURN; END IF;
  IF NOT public.pode('metas.especiais_editar', v_loja) THEN
    RAISE EXCEPTION 'Seu cargo não permite editar metas especiais desta loja.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF NOT public.pode('metas.especiais_ver', v_loja) THEN
    RAISE EXCEPTION 'Seu cargo não mostra as metas especiais desta loja, então não as edita.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF NOT public.pode('valores.ver_rs', v_loja) THEN
    RAISE EXCEPTION 'Seu cargo não mostra valores em R$ nesta loja, então não edita meta.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF v_data < date_trunc('month', public.hoje_da_conta(v_conta))::date THEN
    RAISE EXCEPTION 'Esta meta especial é de um mês que já passou: fica como foi.' USING ERRCODE = 'check_violation';
  END IF;
  DELETE FROM public.metasespeciais WHERE contaid = v_conta AND metaespecialid = p_metaespecialid;
END;
$function$;

-- ---------------------------------------------------------------------------
-- 10. As leituras do gerente pedem as permissões novas
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.metas_da_semana(p_lojaid integer)
RETURNS TABLE(diasemanaid integer, valormeta numeric, pontospremio integer)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT m.diasemanaid, m.valormeta, m.pontospremio
    FROM public.metasdiariasmodelos m
   WHERE m.lojaid = p_lojaid
     AND ((public.sou_master() AND m.contaid = public.minha_conta())
       OR (NOT public.sou_master() AND m.contaid = public.conta_do_gerente()
           AND public.pode('metas.ver', p_lojaid) AND public.pode('valores.ver_rs', p_lojaid)
           AND public.pode('metas.dia_ver', p_lojaid)))
   ORDER BY m.diasemanaid
$$;

CREATE OR REPLACE FUNCTION public.metas_especiais_da_loja(p_lojaid integer)
RETURNS TABLE(metaespecialid integer, data date, descricao text, valormeta numeric, pontospremio integer)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT m.metaespecialid, m.data, m.descricao, m.valormeta, m.pontospremio
    FROM public.metasespeciais m
   WHERE m.lojaid = p_lojaid
     AND ((public.sou_master() AND m.contaid = public.minha_conta())
       OR (NOT public.sou_master() AND m.contaid = public.conta_do_gerente()
           AND public.pode('metas.ver', p_lojaid) AND public.pode('valores.ver_rs', p_lojaid)
           AND public.pode('metas.especiais_ver', p_lojaid)))
   ORDER BY m.data DESC, m.metaespecialid DESC
   LIMIT 100
$$;

-- O mês da tela Lançar venda, para o gerente: a meta do mês só com "Ver meta
-- do mês"; a meta de cada dia (e a soma) só com "Ver meta por dia"; o valor de
-- dia com meta especial, só com "Ver metas especiais" também.
CREATE OR REPLACE FUNCTION public.metas_do_mes_gerente(p_lojaid integer, p_mes date)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  WITH ok AS (SELECT public.pode('metas.mes_ver', p_lojaid) AS mesver,
                     public.pode('metas.dia_ver', p_lojaid) AS diaver,
                     public.pode('metas.especiais_ver', p_lojaid) AS espver
               WHERE public.conta_do_gerente() IS NOT NULL
                 AND public.pode('metas.ver', p_lojaid) AND public.pode('valores.ver_rs', p_lojaid)),
  lim AS (
    SELECT date_trunc('month', p_mes)::date AS ini,
           (date_trunc('month', p_mes) + interval '1 month - 1 day')::date AS fim
  ),
  dias AS (
    SELECT g::date AS d FROM lim, generate_series(lim.ini, lim.fim, interval '1 day') g
  ),
  cru AS (
    SELECT d.d AS dia,
           a.apuracaoid, a.valordia,
           coalesce(a.valormetadia, md.valormeta) AS valormeta,
           CASE WHEN a.apuracaoid IS NOT NULL THEN a.pontosmetadia ELSE md.pontospremio END AS pontos,
           coalesce(a.origemmeta, md.origem) AS origem,
           coalesce(a.descricaometa, md.descricao) AS descricao,
           (SELECT count(*) FROM public.movimentospontos mv
              JOIN public.metaspremiacoes p ON p.premiacaoid = mv.premiacaoid
             WHERE p.apuracaoid = a.apuracaoid AND p.tipo = 'dia' AND p.estornadoem IS NULL
               AND mv.tipo = 'bonus') AS premiados
      FROM dias d
      JOIN ok ON true
      LEFT JOIN public.metasdiariasapuracoes a ON a.lojaid = p_lojaid AND a.dataapuracao = d.d
      LEFT JOIN LATERAL public.meta_do_dia(p_lojaid, d.d) md ON true
  ),
  linhas AS (
    SELECT c.dia, c.apuracaoid, c.valordia, c.premiados,
           (ok.diaver AND (c.origem IS DISTINCT FROM 'especial' OR ok.espver)) AS mostra,
           c.valormeta, c.pontos, c.origem, c.descricao
      FROM cru c, ok
  ),
  mes AS (
    SELECT m.metaprincipalid, m.nomemeta, m.valormetatotal, m.pontospremio,
           EXISTS (SELECT 1 FROM public.metaspremiacoes p
                    WHERE p.metaprincipalid = m.metaprincipalid AND p.tipo = 'mes' AND p.estornadoem IS NULL) AS premiado
      FROM public.metasprincipais m, lim, ok
     WHERE m.lojaid = p_lojaid AND m.datainicio = lim.ini AND ok.mesver
  )
  SELECT CASE WHEN EXISTS (SELECT 1 FROM ok) THEN jsonb_build_object(
    'mes',       (SELECT to_jsonb(mes) FROM mes),
    'vendido',   (SELECT coalesce(sum(valordia), 0) FROM linhas),
    'somametas', CASE WHEN (SELECT diaver AND espver FROM ok) THEN (SELECT coalesce(sum(valormeta), 0) FROM linhas) END,
    'diaslancados', (SELECT count(*) FROM linhas WHERE apuracaoid IS NOT NULL),
    'dias',      (SELECT coalesce(jsonb_agg(jsonb_build_object(
                    'dia', dia, 'apuracaoid', apuracaoid, 'vendido', valordia,
                    'meta', CASE WHEN mostra THEN valormeta END,
                    'pontos', CASE WHEN mostra THEN pontos END,
                    'origem', CASE WHEN mostra THEN origem END,
                    'descricao', CASE WHEN mostra THEN descricao END,
                    'bateu', mostra AND valordia IS NOT NULL AND coalesce(valormeta, 0) > 0 AND valordia >= valormeta,
                    'premiados', premiados) ORDER BY dia), '[]'::jsonb) FROM linhas),
    'primeirodiaeditavel', public.primeiro_dia_editavel_meta(),
    -- O que ele pode ver nesta loja (a tela diz "sem permissão" em vez de
    -- "não cadastrada"). Só no ramo do gerente: a resposta do master não muda.
    'pode', (SELECT jsonb_build_object('mesver', mesver, 'diaver', diaver, 'especiaisver', espver) FROM ok)
  ) END
$$;

-- ---------------------------------------------------------------------------
-- 11. A lista dos Estornos mostra toda mudança de meta
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.estornos_da_conta(p_lojaid integer DEFAULT NULL::integer)
 RETURNS TABLE(tipo text, quando timestamp with time zone, lojaid integer, loja text, pessoa text, descricao text, pontos integer, motivo text, quem text)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE v_conta integer := public.minha_conta();
BEGIN
  IF v_conta IS NULL OR NOT public.sou_master() THEN
    RAISE EXCEPTION 'Só o dono da conta vê a lista de estornos.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  RETURN QUERY
  SELECT 'entrega'::text, e.dataestorno, e.lojaid, l.nome::text, f.nomecompleto::text,
         t.titulo::text, -coalesce(e.pontosganhos, 0), e.motivoestorno::text,
         coalesce(public.autor_em(e.estornadopor, e.dataestorno), 'desconhecido')
    FROM public.entregas e
    JOIN public.lojas l ON l.contaid = e.contaid AND l.lojaid = e.lojaid
    LEFT JOIN public.funcionarios f ON f.contaid = e.contaid AND f.funcionarioid = e.funcionarioid
    LEFT JOIN public.tarefas t ON t.contaid = e.contaid AND t.tarefaid = e.tarefaid
   WHERE e.contaid = v_conta AND e.statusvalidacao = 'Estornada'
     AND (p_lojaid IS NULL OR e.lojaid = p_lojaid)
  UNION ALL
  -- Resgates cancelados (antes de entregar) e estornados (depois): os pontos
  -- voltam para a pessoa. Resgate registrado sem loja só aparece na lista de
  -- todas as lojas (p_lojaid vazio).
  SELECT CASE r.status WHEN 'Cancelado' THEN 'resgate cancelado' ELSE 'resgate estornado' END,
         CASE r.status WHEN 'Cancelado' THEN r.datacancelamento ELSE r.dataestorno END,
         r.lojaid, l.nome::text, f.nomecompleto::text,
         CASE WHEN r.valorreais IS NOT NULL THEN 'abate na comanda de ' || public.reais(r.valorreais) ELSE p.nome::text END,
         r.pontosgastos,
         (CASE r.status WHEN 'Cancelado' THEN r.motivocancelamento ELSE r.motivoestorno END)::text,
         coalesce(public.autor_em(CASE r.status WHEN 'Cancelado' THEN r.canceladopor ELSE r.estornadopor END,
                                  CASE r.status WHEN 'Cancelado' THEN r.datacancelamento ELSE r.dataestorno END), 'desconhecido')
    FROM public.resgates r
    LEFT JOIN public.lojas l ON l.contaid = r.contaid AND l.lojaid = r.lojaid
    LEFT JOIN public.funcionarios f ON f.contaid = r.contaid AND f.funcionarioid = r.funcionarioid
    LEFT JOIN public.produtosloja p ON p.contaid = r.contaid AND p.produtoid = r.produtoid
   WHERE r.contaid = v_conta AND r.status IN ('Cancelado', 'Estornado')
     AND (p_lojaid IS NULL OR r.lojaid = p_lojaid)
  UNION ALL
  -- Feedbacks anulados: o bônus sai de volta da pessoa. Feedback não tem
  -- loja: aparece na lista de todas as lojas e na de cada loja da pessoa.
  SELECT 'feedback anulado', fb.anuladoem, NULL::integer, NULL::text, f.nomecompleto::text,
         'Feedback de ' || to_char(fb.datafeedback, 'DD/MM/YYYY') || ' (nota ' || fb.notadia || ')',
         -coalesce(fb.pontosbonus, 0), fb.motivoanulacao::text,
         coalesce(public.autor_em(fb.anuladopor, fb.anuladoem), 'desconhecido')
    FROM public.feedbacks fb
    LEFT JOIN public.funcionarios f ON f.contaid = fb.contaid AND f.funcionarioid = fb.funcionarioid
   WHERE fb.contaid = v_conta AND fb.anuladoem IS NOT NULL
     AND (p_lojaid IS NULL OR EXISTS (SELECT 1 FROM public.funcionarioslojas fl
                                       WHERE fl.contaid = fb.contaid AND fl.funcionarioid = fb.funcionarioid AND fl.lojaid = p_lojaid))
  UNION ALL
  -- Entrega registrada por um GERENTE sem foto (30/09/2026, decisão do
  -- Wisley): não é bloqueada, fica à vista do master aqui.
  SELECT 'entrega sem foto', e.dataenvio, e.lojaid, l.nome::text, f.nomecompleto::text,
         t.titulo::text || ' (' || e.statusvalidacao || ')', coalesce(e.pontosganhos, 0), e.observacao::text,
         coalesce(public.autor_em(e.registradopor, e.dataenvio), 'desconhecido')
    FROM public.entregas e
    JOIN public.lojas l ON l.contaid = e.contaid AND l.lojaid = e.lojaid
    LEFT JOIN public.funcionarios f ON f.contaid = e.contaid AND f.funcionarioid = e.funcionarioid
    LEFT JOIN public.tarefas t ON t.contaid = e.contaid AND t.tarefaid = e.tarefaid
   WHERE e.contaid = v_conta AND e.pathfotoevidencia IS NULL
     AND EXISTS (SELECT 1 FROM public.contasusuarios cu
                  WHERE cu.contaid = e.contaid AND cu.userid = e.registradopor AND cu.papel = 'gerente')
     AND (p_lojaid IS NULL OR e.lojaid = p_lojaid)
  UNION ALL
  -- Toda mudança de meta (30/09/2026, decisão do Wisley): o master delega a
  -- meta e VÊ o que foi feito — quem, quando, o valor antes e o depois.
  SELECT 'meta alterada', ma.alteradoem, ma.lojaid, l.nome::text, NULL::text,
         ma.referencia || ': '
           || CASE WHEN ma.valorantes IS NULL AND ma.pontosantes IS NULL THEN 'criada, '
                   ELSE coalesce(public.reais(ma.valorantes), '—') || ' e ' || coalesce(ma.pontosantes::text, '—') || ' pontos → ' END
           || CASE WHEN ma.valordepois IS NULL AND ma.pontosdepois IS NULL THEN 'apagada'
                   ELSE coalesce(public.reais(ma.valordepois), '—') || ' e ' || coalesce(ma.pontosdepois::text, '—') || ' pontos' END,
         0, NULL::text,
         coalesce(public.autor_em(ma.alteradopor, ma.alteradoem), CASE WHEN ma.alteradopor IS NULL THEN 'Sistema' ELSE 'desconhecido' END)
    FROM public.metasalteracoes ma
    JOIN public.lojas l ON l.contaid = ma.contaid AND l.lojaid = ma.lojaid
   WHERE ma.contaid = v_conta
     AND (p_lojaid IS NULL OR ma.lojaid = p_lojaid)
   -- Desempate fixo: dois estornos no mesmo instante saem sempre na mesma ordem.
   ORDER BY 2 DESC, 1, 6, 5, 9, 8
   LIMIT 500;
END;
$function$;

COMMIT;
