-- =========================================================================
-- STGame — Jornadas (horários de expediente com nome, por dia da semana).
--
-- Como usar: Supabase -> SQL Editor -> New query -> colar TUDO -> Run.
-- Se der erro, NADA é aplicado: me mande a mensagem.
-- Pode rodar duas vezes sem problema: a migração dos horários só roda
-- enquanto houver o que migrar, e não duplica jornada.
--
-- ATENÇÃO: aplique tudo o que veio antes. E aplique ESTE ARQUIVO ANTES de
-- publicar a versão nova: a tela Equipe passa a ler a jornada, e o horário
-- solto na pessoa deixa de existir.
--
-- Este arquivo é UMA migração só:
--   20260929190000_jornadas.sql
--
-- O QUE MUDA PARA QUEM JÁ USA (nada de comportamento):
--   * Cada combinação de entrada e saída que já existe na conta vira uma
--     jornada com os sete dias iguais, nome automático ("08:00–17:00"), e as
--     pessoas ficam vinculadas a ela. Saída em branco (que valia entrada +
--     8h20) é gravada por extenso. Quem estava sem horário fica sem jornada.
--   * Provado num banco de teste: o bot decidiria exatamente igual antes e
--     depois, em 38.925 instantes de 15 em 15 minutos ao longo de 9 dias.
-- =========================================================================


BEGIN;

-- Jornadas: horários de EXPEDIENTE com nome, por dia da semana (27/09/2026).
--
-- ENQUADRAMENTO (CLAUDE.md: "o STGame não controla jornada"). Estes horários
-- servem para o sistema saber QUANDO enviar tarefas e avisos — nada além.
-- Não há total de horas, carga semanal, banco de horas, marcação de entrada
-- e saída, nem comparação entre previsto e feito. O intervalo é SILÊNCIO do
-- sistema, não marcação.
--
-- O que muda:
--   * Tabelas novas: jornadas (nome, intervalo, observação, ativa) e
--     jornadasdias (entrada e saída de cada dia da semana).
--   * funcionarios.jornadaid substitui as colunas horarionotificacao e
--     horariosaida, que são MIGRADAS e depois apagadas: a jornada passa a ser
--     a fonte única.
--   * jornada_da_pessoa (a única função que lia o horário) passa a ler da
--     jornada, com as MESMAS respostas; o bot não muda. Ganha o intervalo, e
--     bot_janela passa a respeitá-lo.
--   * A folga continua sendo de cada pessoa (funcionarios.diadefolga).
--
-- Aplicar duas vezes não duplica nada: a migração dos horários só roda
-- enquanto as colunas antigas existem, e ela mesma as apaga no fim.

-- ---------------------------------------------------------------------------
-- 1. As tabelas
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.jornadas (
  jornadaid    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contaid      integer NOT NULL DEFAULT public.minha_conta() REFERENCES public.contas (contaid) ON DELETE RESTRICT,
  nome         varchar(80) NOT NULL CHECK (btrim(nome) <> ''),
  -- Intervalo de SILÊNCIO (almoço): o sistema não envia nada nele. Os dois
  -- juntos, ou nenhum.
  pausainicio  time,
  pausafim     time,
  observacao   text,
  ativa        boolean NOT NULL DEFAULT true,
  criadoem     timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT jornadas_conta_unico UNIQUE (contaid, jornadaid),
  CONSTRAINT jornadas_nome_unico UNIQUE (contaid, nome),
  CONSTRAINT jornadas_pausa_completa CHECK ((pausainicio IS NULL) = (pausafim IS NULL)),
  CONSTRAINT jornadas_pausa_valida CHECK (pausainicio IS NULL OR pausainicio <> pausafim)
);
COMMENT ON TABLE public.jornadas IS
  'Horários de expediente com nome, para o sistema saber quando enviar tarefas e avisos. NÃO é controle de jornada: não soma horas nem compara previsto com feito. Nível conta.';

CREATE TABLE IF NOT EXISTS public.jornadasdias (
  contaid    integer NOT NULL DEFAULT public.minha_conta() REFERENCES public.contas (contaid) ON DELETE RESTRICT,
  jornadaid  integer NOT NULL,
  -- 1 = domingo ... 7 = sábado (a mesma convenção de funcionarios.diadefolga).
  diasemana  smallint NOT NULL CHECK (diasemana BETWEEN 1 AND 7),
  entrada    time NOT NULL,
  -- Saída menor que a entrada: turno da noite, acaba no dia seguinte.
  saida      time NOT NULL,
  PRIMARY KEY (jornadaid, diasemana),
  CONSTRAINT jornadasdias_jornada_fk FOREIGN KEY (contaid, jornadaid)
    REFERENCES public.jornadas (contaid, jornadaid) ON DELETE CASCADE,
  CONSTRAINT jornadasdias_horario_valido CHECK (entrada <> saida)
);
COMMENT ON TABLE public.jornadasdias IS
  'Entrada e saída de cada dia da semana de uma jornada. Dia sem linha = sem horário naquele dia (vale só o silêncio da empresa). Nível conta.';

ALTER TABLE public.jornadas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jornadasdias ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.jornadas, public.jornadasdias FROM anon, authenticated;
-- A tela LÊ direto; GRAVA pela função salvar_jornada (tudo ou nada) e apaga
-- direto (o banco recusa se houver gente vinculada).
GRANT SELECT, DELETE ON public.jornadas TO authenticated;
GRANT SELECT ON public.jornadasdias TO authenticated;
GRANT ALL ON public.jornadas, public.jornadasdias TO service_role;
DROP POLICY IF EXISTS jornadas_sel ON public.jornadas;
DROP POLICY IF EXISTS jornadas_del ON public.jornadas;
DROP POLICY IF EXISTS jornadasdias_sel ON public.jornadasdias;
CREATE POLICY jornadas_sel ON public.jornadas FOR SELECT TO authenticated
  USING (contaid = (select public.minha_conta()));
CREATE POLICY jornadas_del ON public.jornadas FOR DELETE TO authenticated
  USING (contaid = (select public.minha_conta_editavel()));
CREATE POLICY jornadasdias_sel ON public.jornadasdias FOR SELECT TO authenticated
  USING (contaid = (select public.minha_conta()));

-- A pessoa aponta para a jornada DA MESMA CONTA (chave composta).
ALTER TABLE public.funcionarios ADD COLUMN IF NOT EXISTS jornadaid integer;
ALTER TABLE public.funcionarios DROP CONSTRAINT IF EXISTS funcionarios_jornada_fk;
ALTER TABLE public.funcionarios ADD CONSTRAINT funcionarios_jornada_fk
  FOREIGN KEY (contaid, jornadaid) REFERENCES public.jornadas (contaid, jornadaid) ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS funcionarios_jornada_idx ON public.funcionarios (contaid, jornadaid) WHERE jornadaid IS NOT NULL;
-- Leitura liberada coluna por coluna em funcionarios: esta também. Gravar,
-- só por vincular_jornada.
GRANT SELECT (jornadaid) ON public.funcionarios TO authenticated;
COMMENT ON COLUMN public.funcionarios.jornadaid IS
  'Jornada (horário de expediente) da pessoa. Vazio = sem jornada: não recebe as mensagens do dia. A folga é da pessoa (diadefolga), não da jornada.';

-- ---------------------------------------------------------------------------
-- 2. Jornada com gente não se apaga nem se desativa
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.protege_jornada_em_uso()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE v_n integer;
BEGIN
  IF TG_OP = 'UPDATE' AND NOT (OLD.ativa AND NOT NEW.ativa) THEN
    RETURN NEW;
  END IF;
  SELECT count(*) INTO v_n FROM public.funcionarios
   WHERE contaid = OLD.contaid AND jornadaid = OLD.jornadaid;
  IF v_n > 0 THEN
    RAISE EXCEPTION 'A jornada "%" tem % pessoa(s) vinculada(s). Mova essas pessoas para outra jornada (ou "sem jornada") antes de %.',
      OLD.nome, v_n, CASE WHEN TG_OP = 'DELETE' THEN 'apagar' ELSE 'desativar' END
      USING ERRCODE = 'foreign_key_violation';
  END IF;
  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$;
REVOKE ALL ON FUNCTION public.protege_jornada_em_uso() FROM public, anon, authenticated;
DROP TRIGGER IF EXISTS jornadas_protege_em_uso ON public.jornadas;
CREATE TRIGGER jornadas_protege_em_uso
  BEFORE DELETE OR UPDATE OF ativa ON public.jornadas
  FOR EACH ROW EXECUTE FUNCTION public.protege_jornada_em_uso();

-- ---------------------------------------------------------------------------
-- 3. Salvar uma jornada (nome, intervalo e os dias), tudo ou nada
-- ---------------------------------------------------------------------------
-- p_dias: [{"dia": 1..7, "entrada": "HH:MM", "saida": "HH:MM"}, ...].
-- p_jornadaid vazio = jornada nova. Não recebe conta: é a de quem chamou.
CREATE OR REPLACE FUNCTION public.salvar_jornada(p_jornadaid integer, p_nome text, p_dias jsonb,
                                                 p_pausainicio time, p_pausafim time,
                                                 p_observacao text, p_ativa boolean)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_conta integer := public.exige_master_editavel();
  v_id    integer;
  d       jsonb;
BEGIN
  IF btrim(coalesce(p_nome, '')) = '' THEN
    RAISE EXCEPTION 'Dê um nome à jornada.' USING ERRCODE = 'check_violation';
  END IF;
  IF jsonb_typeof(p_dias) IS DISTINCT FROM 'array' OR jsonb_array_length(p_dias) = 0 THEN
    RAISE EXCEPTION 'Preencha a entrada e a saída de pelo menos um dia.' USING ERRCODE = 'check_violation';
  END IF;
  IF (p_pausainicio IS NULL) <> (p_pausafim IS NULL) THEN
    RAISE EXCEPTION 'O intervalo precisa de começo e fim (ou fica sem intervalo).' USING ERRCODE = 'check_violation';
  END IF;

  IF p_jornadaid IS NULL THEN
    INSERT INTO public.jornadas (contaid, nome, pausainicio, pausafim, observacao, ativa)
    VALUES (v_conta, btrim(p_nome), p_pausainicio, p_pausafim, nullif(btrim(coalesce(p_observacao, '')), ''),
            coalesce(p_ativa, true))
    RETURNING jornadaid INTO v_id;
  ELSE
    UPDATE public.jornadas
       SET nome = btrim(p_nome), pausainicio = p_pausainicio, pausafim = p_pausafim,
           observacao = nullif(btrim(coalesce(p_observacao, '')), ''), ativa = coalesce(p_ativa, true)
     WHERE contaid = v_conta AND jornadaid = p_jornadaid
    RETURNING jornadaid INTO v_id;
    IF v_id IS NULL THEN
      RAISE EXCEPTION 'Jornada não encontrada.' USING ERRCODE = 'no_data_found';
    END IF;
    DELETE FROM public.jornadasdias WHERE contaid = v_conta AND jornadaid = v_id;
  END IF;

  FOR d IN SELECT * FROM jsonb_array_elements(p_dias) LOOP
    IF (d->>'dia')::integer NOT BETWEEN 1 AND 7 THEN
      RAISE EXCEPTION 'Dia da semana inválido.' USING ERRCODE = 'check_violation';
    END IF;
    IF (d->>'entrada')::time = (d->>'saida')::time THEN
      RAISE EXCEPTION 'Entrada e saída iguais no mesmo dia.' USING ERRCODE = 'check_violation';
    END IF;
    INSERT INTO public.jornadasdias (contaid, jornadaid, diasemana, entrada, saida)
    VALUES (v_conta, v_id, (d->>'dia')::smallint, (d->>'entrada')::time, (d->>'saida')::time);
  END LOOP;
  RETURN v_id;
EXCEPTION WHEN unique_violation THEN
  RAISE EXCEPTION 'Já existe uma jornada com esse nome (ou o mesmo dia apareceu duas vezes).' USING ERRCODE = 'unique_violation';
END;
$$;
REVOKE ALL ON FUNCTION public.salvar_jornada(integer, text, jsonb, time, time, text, boolean) FROM public, anon;
GRANT  EXECUTE ON FUNCTION public.salvar_jornada(integer, text, jsonb, time, time, text, boolean) TO authenticated;

-- Vincular uma ou várias pessoas (NULL = sem jornada). Substitui
-- definir_horario_equipe.
CREATE OR REPLACE FUNCTION public.vincular_jornada(p_funcionarios integer[], p_jornadaid integer)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE v_conta integer := public.exige_master_editavel(); v_n integer;
BEGIN
  IF p_jornadaid IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.jornadas
                                              WHERE contaid = v_conta AND jornadaid = p_jornadaid AND ativa) THEN
    RAISE EXCEPTION 'Jornada não encontrada ou inativa.' USING ERRCODE = 'no_data_found';
  END IF;
  UPDATE public.funcionarios SET jornadaid = p_jornadaid
   WHERE contaid = v_conta AND funcionarioid = ANY (p_funcionarios) AND ativo;
  GET DIAGNOSTICS v_n = ROW_COUNT;
  RETURN v_n;
END;
$$;
REVOKE ALL ON FUNCTION public.vincular_jornada(integer[], integer) FROM public, anon;
GRANT  EXECUTE ON FUNCTION public.vincular_jornada(integer[], integer) TO authenticated;

-- ---------------------------------------------------------------------------
-- 4. A migração dos horários que já existem (só enquanto houver o que migrar)
-- ---------------------------------------------------------------------------
-- Cada combinação (entrada, saída) de cada conta vira uma jornada com os
-- sete dias iguais, com nome automático ("08:00–17:00"), e as pessoas são
-- vinculadas a ela. Saída vazia valia "entrada + 8h20": ela é gravada assim,
-- por extenso. Quem estava sem horário continua sem jornada.
DO $migra$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                  WHERE table_schema = 'public' AND table_name = 'funcionarios'
                    AND column_name = 'horarionotificacao') THEN
    RAISE NOTICE 'jornadas: os horários já tinham sido migrados; nada foi tocado.';
    RETURN;
  END IF;

  CREATE TEMP TABLE horariosvelhos ON COMMIT DROP AS
  SELECT DISTINCT f.contaid, f.horarionotificacao AS entrada,
         coalesce(f.horariosaida, f.horarionotificacao + interval '8 hours 20 minutes')::time AS saida
    FROM public.funcionarios f
   WHERE f.horarionotificacao IS NOT NULL;

  INSERT INTO public.jornadas (contaid, nome)
  SELECT h.contaid, to_char(h.entrada, 'HH24:MI') || '–' || to_char(h.saida, 'HH24:MI')
    FROM horariosvelhos h
  ON CONFLICT (contaid, nome) DO NOTHING;

  INSERT INTO public.jornadasdias (contaid, jornadaid, diasemana, entrada, saida)
  SELECT j.contaid, j.jornadaid, d, h.entrada, h.saida
    FROM horariosvelhos h
    JOIN public.jornadas j ON j.contaid = h.contaid
                          AND j.nome = to_char(h.entrada, 'HH24:MI') || '–' || to_char(h.saida, 'HH24:MI')
   CROSS JOIN generate_series(1, 7) d
  ON CONFLICT DO NOTHING;

  UPDATE public.funcionarios f SET jornadaid = j.jornadaid
    FROM public.jornadas j
   WHERE f.horarionotificacao IS NOT NULL AND j.contaid = f.contaid
     AND j.nome = to_char(f.horarionotificacao, 'HH24:MI') || '–'
                  || to_char(coalesce(f.horariosaida, f.horarionotificacao + interval '8 hours 20 minutes')::time, 'HH24:MI');

  -- A jornada vira a fonte única: as colunas antigas saem, e com elas a
  -- função que as gravava.
  DROP FUNCTION IF EXISTS public.definir_horario_equipe(integer[], time, time);
  ALTER TABLE public.funcionarios DROP COLUMN IF EXISTS horariosaida;
  ALTER TABLE public.funcionarios DROP COLUMN IF EXISTS horarionotificacao;
END
$migra$;

-- ---------------------------------------------------------------------------
-- 5. O horário da pessoa passa a vir da jornada (mesmas respostas)
-- ---------------------------------------------------------------------------
-- Parte da única versão (20260926100000). Mesmas quatro respostas, calculadas
-- da jornada do dia da semana; mais o intervalo (vazio quando não há). Ganha
-- colunas, por isso é recriada.
DROP FUNCTION IF EXISTS public.jornada_da_pessoa(integer, integer, date);
CREATE OR REPLACE FUNCTION public.jornada_da_pessoa(p_contaid integer, p_funcionarioid integer, p_dia date)
RETURNS TABLE (trabalha boolean, temhorario boolean, inicio timestamptz, fim timestamptz,
               pausainicio timestamptz, pausafim timestamptz)
LANGUAGE sql
STABLE
SET search_path = public, pg_temp
AS $$
  SELECT public.dia_de_trabalho(f.diadefolga, f.domingofolgamensal, f.datainicioafastamento,
                                f.datafimafastamento, p_dia),
         jd.entrada IS NOT NULL,
         public.instante_local(p_dia, jd.entrada),
         public.instante_local(p_dia, jd.entrada)
           + CASE WHEN jd.saida > jd.entrada THEN jd.saida - jd.entrada
                  ELSE jd.saida - jd.entrada + interval '24 hours' END,
         p.ini,
         p.ini + CASE WHEN jo.pausafim > jo.pausainicio THEN jo.pausafim - jo.pausainicio
                      ELSE jo.pausafim - jo.pausainicio + interval '24 hours' END
    FROM public.funcionarios f
    LEFT JOIN public.jornadas jo      ON jo.contaid = f.contaid AND jo.jornadaid = f.jornadaid
    LEFT JOIN public.jornadasdias jd  ON jd.contaid = f.contaid AND jd.jornadaid = f.jornadaid
                                     AND jd.diasemana = extract(dow FROM p_dia)::integer + 1
    -- O intervalo cai dentro do turno: no turno da noite, uma pausa às 02h é
    -- do dia seguinte.
    LEFT JOIN LATERAL (
      SELECT CASE WHEN jd.entrada IS NULL OR jo.pausainicio IS NULL THEN NULL
                  WHEN jo.pausainicio >= jd.entrada THEN public.instante_local(p_dia, jo.pausainicio)
                  ELSE public.instante_local(p_dia + 1, jo.pausainicio) END AS ini
    ) p ON true
   WHERE f.contaid = p_contaid AND f.funcionarioid = p_funcionarioid AND f.ativo
$$;
REVOKE ALL ON FUNCTION public.jornada_da_pessoa(integer, integer, date) FROM public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- 6. O bot respeita o intervalo
-- ---------------------------------------------------------------------------
-- Parte da versão mais recente (20260927100000), com o diff conferido: só
-- entra o intervalo, antes da conferência do turno.
CREATE OR REPLACE FUNCTION public.bot_janela(p_contaid integer, p_funcionarioid integer, p_agora timestamptz)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SET search_path = public, pg_temp
AS $$
DECLARE
  v_hoje  date;
  v_hora  time;
  v_fim   time := public.rotina_horario(p_contaid, 'HORARIO_SILENCIO_FIM', '07:00');
  j       record;
  d       date;
  v_trabalha_hoje boolean;
  v_pausafim timestamptz;
BEGIN
  SELECT x.dia, x.hora INTO v_hoje, v_hora FROM public.rotina_hora_local(p_agora) x;

  -- Grupo (ou o Telegram do master): só o silêncio.
  IF p_funcionarioid IS NULL THEN
    IF public.no_silencio(p_contaid, v_hora) THEN
      RETURN jsonb_build_object('pode', false, 'motivo', 'silencio',
        'proxima', CASE WHEN v_hora < v_fim THEN public.instante_local(v_hoje, v_fim)
                        ELSE public.instante_local(v_hoje + 1, v_fim) END);
    END IF;
    RETURN jsonb_build_object('pode', true);
  END IF;

  SELECT * INTO j FROM public.jornada_da_pessoa(p_contaid, p_funcionarioid, v_hoje);
  IF NOT FOUND THEN
    RETURN jsonb_build_object('pode', false, 'motivo', 'sem_pessoa');
  END IF;

  -- Guardado antes do laço abaixo, que reaproveita a variável j.
  v_trabalha_hoje := j.trabalha;

  IF j.temhorario THEN
    -- No INTERVALO da jornada (almoço): silêncio até ele acabar. Não é
    -- marcação de nada — só a hora em que o sistema não manda mensagem.
    SELECT t.pausafim INTO v_pausafim
      FROM generate_series(v_hoje - 1, v_hoje, interval '1 day') g
     CROSS JOIN LATERAL public.jornada_da_pessoa(p_contaid, p_funcionarioid, g::date) t
     WHERE t.trabalha AND t.pausainicio IS NOT NULL
       -- Só o intervalo que cai DENTRO do turno daquele dia.
       AND t.pausainicio >= t.inicio AND t.pausafim <= t.fim
       AND p_agora >= t.pausainicio AND p_agora < t.pausafim
     LIMIT 1;
    IF v_pausafim IS NOT NULL THEN
      RETURN jsonb_build_object('pode', false, 'motivo', 'intervalo', 'proxima', v_pausafim);
    END IF;
    -- Dentro do turno de hoje ou do que começou ontem (turno da noite)?
    IF EXISTS (
      SELECT 1 FROM generate_series(v_hoje - 1, v_hoje, interval '1 day') g
       CROSS JOIN LATERAL public.jornada_da_pessoa(p_contaid, p_funcionarioid, g::date) t
       WHERE t.trabalha AND p_agora >= t.inicio AND p_agora <= t.fim + interval '30 minutes') THEN
      RETURN jsonb_build_object('pode', true);
    END IF;
    -- Fora do turno: espera o próximo começo (até 8 dias à frente).
    -- Quem trabalha hoje está só fora do horário, não de folga: o aviso espera
    -- a próxima entrada, mesmo que ela seja amanhã.
    FOR d IN SELECT g::date FROM generate_series(v_hoje, v_hoje + 8, interval '1 day') g LOOP
      SELECT * INTO j FROM public.jornada_da_pessoa(p_contaid, p_funcionarioid, d);
      IF j.trabalha AND j.inicio > p_agora THEN
        RETURN jsonb_build_object('pode', false,
          'motivo', CASE WHEN d = v_hoje OR v_trabalha_hoje THEN 'fora_do_turno' ELSE 'folga' END,
          'proxima', j.inicio);
      END IF;
    END LOOP;
    RETURN jsonb_build_object('pode', false, 'motivo', 'folga', 'proxima', public.instante_local(v_hoje + 1, v_fim));
  END IF;

  -- Sem horário: valem a folga e o silêncio.
  IF NOT j.trabalha THEN
    FOR d IN SELECT g::date FROM generate_series(v_hoje + 1, v_hoje + 8, interval '1 day') g LOOP
      IF (SELECT t.trabalha FROM public.jornada_da_pessoa(p_contaid, p_funcionarioid, d) t) THEN
        RETURN jsonb_build_object('pode', false, 'motivo', 'folga', 'proxima', public.instante_local(d, v_fim));
      END IF;
    END LOOP;
    RETURN jsonb_build_object('pode', false, 'motivo', 'folga', 'proxima', public.instante_local(v_hoje + 1, v_fim));
  END IF;
  IF public.no_silencio(p_contaid, v_hora) THEN
    RETURN jsonb_build_object('pode', false, 'motivo', 'silencio',
      'proxima', CASE WHEN v_hora < v_fim THEN public.instante_local(v_hoje, v_fim)
                      ELSE public.instante_local(v_hoje + 1, v_fim) END);
  END IF;
  RETURN jsonb_build_object('pode', true);
END;
$$;

REVOKE ALL ON FUNCTION public.bot_janela(integer, integer, timestamptz) FROM public, anon, authenticated;

COMMIT;
