-- =========================================================================
-- STGame — Usuários gerenciais, PARTE 2, fatia 1: o Quadro.
--
-- Como usar: Supabase -> SQL Editor -> New query -> colar TUDO -> Run.
-- Se der erro, NADA é aplicado: me mande a mensagem.
-- Pode rodar duas vezes sem problema.
--
-- ATENÇÃO: aplique antes o aplicar-permissoes-parte-1-ajustes.sql (e os
-- anteriores). Aplique ESTE ARQUIVO ANTES de publicar a versão nova.
--
-- Este arquivo é UMA migração só:
--   20260929250000_quadro_permissoes.sql
--
-- O QUE MUDA: aprovar, recusar, estornar, registrar, revogar aceite e passar
-- tarefa de folga passam a conferir permissão e loja no banco (para o master
-- nada muda); ninguém aprova a própria entrega; o login que já fez algo não
-- se apaga; nova tela Estornos (só o master). Nenhum dado é alterado.
-- =========================================================================


BEGIN;

-- Usuários gerenciais, PARTE 2, fatia 1: o Quadro (29/09/2026).
--
-- 1. A TRAVA DO LOGIN QUE JÁ FEZ ALGUMA COISA: não se apaga, só se desativa
--    (bloqueio). Quem aprovou, estornou, lançou... nunca some dos registros.
-- 2. O NOME DE QUEM FEZ, NO MOMENTO: a tabela "autores" guarda cada nome que
--    um login já teve (gestor: o e-mail; colaborador: o nome do cadastro;
--    tablet: a loja), com a hora em que passou a valer. Qualquer "quem fez"
--    acha o nome daquela hora sem depender do login.
-- 3. O QUADRO COM PERMISSÃO E LOJA NO BANCO: registrar, aprovar, recusar,
--    estornar, revogar aceite e passar tarefa de folga chamam pode(); e
--    ninguém registra, aprova nem estorna a PRÓPRIA entrega.
-- 4. A LISTA DE ESTORNOS que o master vê (por ora, as entregas; prêmios e
--    feedbacks entram nas fatias deles).
-- Para o master nada muda: pode() é "sim" para ele em toda loja da conta.

-- ---------------------------------------------------------------------------
-- 1. Autores: o nome de cada login em cada momento
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.autores (
  autorid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contaid integer NOT NULL REFERENCES public.contas (contaid) ON DELETE RESTRICT,
  userid  uuid NOT NULL,
  nome    text NOT NULL,
  email   text,
  -- O relógio de verdade, não a hora do começo da transação: um ato e uma
  -- troca de nome na MESMA transação ficam em ordem.
  desde   timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE INDEX IF NOT EXISTS autores_login_idx ON public.autores (userid, desde DESC);
ALTER TABLE public.autores ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.autores FROM anon, authenticated;
GRANT SELECT ON public.autores TO authenticated;
GRANT ALL ON public.autores TO service_role;
DROP POLICY IF EXISTS autores_sel ON public.autores;
CREATE POLICY autores_sel ON public.autores FOR SELECT TO authenticated
  USING (contaid = (select public.minha_conta()) AND (select public.sou_master()));
COMMENT ON TABLE public.autores IS
  'O nome (e o e-mail) de cada login em cada momento, para "quem fez" nunca depender do login continuar existindo. Só recebe linha nova; na exclusão de dados (LGPD) o nome vira "pessoa removida".';

-- O nome que o login tem AGORA: a pessoa (colaborador, nome dado pelo
-- master), a loja (tablet) ou o E-MAIL do gestor. Nunca o nome de exibição
-- (user_metadata): o próprio usuário edita, e um "quem fez" que a pessoa
-- escolhe não é auditoria (e a seção 14 do teste proíbe ler). Interna.
CREATE OR REPLACE FUNCTION public.nome_do_login_agora(p_userid uuid)
RETURNS TABLE (contaid integer, nome text, email text)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT cu.contaid,
         CASE cu.papel
           WHEN 'colaborador' THEN (SELECT f.nomecompleto FROM public.funcionarios f
                                     WHERE f.contaid = cu.contaid AND f.funcionarioid = cu.funcionarioid)
           WHEN 'loja' THEN 'Tablet da ' || (SELECT l.nome FROM public.lojas l
                                              WHERE l.contaid = cu.contaid AND l.lojaid = cu.lojaid)
           ELSE au.email
         END,
         au.email::text
    FROM public.contasusuarios cu
    LEFT JOIN auth.users au ON au.id = cu.userid
   WHERE cu.userid = p_userid
$$;
REVOKE ALL ON FUNCTION public.nome_do_login_agora(uuid) FROM public, anon, authenticated;

-- Grava uma linha nova só se o nome ou o e-mail mudou. Interna.
CREATE OR REPLACE FUNCTION public.registrar_autor(p_userid uuid)
RETURNS void
LANGUAGE sql
VOLATILE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  INSERT INTO public.autores (contaid, userid, nome, email)
  SELECT n.contaid, p_userid, coalesce(n.nome, n.email, 'sem nome'), n.email
    FROM public.nome_do_login_agora(p_userid) n
   WHERE n.contaid IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM (SELECT a.nome, a.email FROM public.autores a
                                     WHERE a.userid = p_userid ORDER BY a.desde DESC, a.autorid DESC LIMIT 1) u
                      WHERE u.nome = coalesce(n.nome, n.email, 'sem nome') AND u.email IS NOT DISTINCT FROM n.email)
$$;
REVOKE ALL ON FUNCTION public.registrar_autor(uuid) FROM public, anon, authenticated;

-- "Nome (e-mail)" de quem era o login naquele momento. Interna.
CREATE OR REPLACE FUNCTION public.autor_em(p_userid uuid, p_em timestamptz)
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT CASE WHEN a.email IS NULL OR a.email = a.nome THEN a.nome ELSE a.nome || ' (' || a.email || ')' END
    FROM public.autores a
   WHERE a.userid = p_userid
   ORDER BY (a.desde <= coalesce(p_em, now())) DESC,   -- o nome que valia naquela hora
            CASE WHEN a.desde <= coalesce(p_em, now()) THEN a.desde END DESC,
            a.desde, a.autorid DESC
   LIMIT 1
$$;
REVOKE ALL ON FUNCTION public.autor_em(uuid, timestamptz) FROM public, anon, authenticated;

-- Quando o nome muda: login novo, e-mail, nome da pessoa (colaborador) ou da
-- loja (tablet).
CREATE OR REPLACE FUNCTION public.autor_mudou()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE u uuid;
BEGIN
  IF TG_TABLE_NAME = 'users' THEN
    PERFORM public.registrar_autor(NEW.id);
  ELSIF TG_TABLE_NAME = 'contasusuarios' THEN
    PERFORM public.registrar_autor(NEW.userid);
  ELSIF TG_TABLE_NAME = 'funcionarios' THEN
    FOR u IN SELECT cu.userid FROM public.contasusuarios cu
              WHERE cu.contaid = NEW.contaid AND cu.funcionarioid = NEW.funcionarioid LOOP
      PERFORM public.registrar_autor(u);
    END LOOP;
  ELSIF TG_TABLE_NAME = 'lojas' THEN
    FOR u IN SELECT cu.userid FROM public.contasusuarios cu
              WHERE cu.contaid = NEW.contaid AND cu.lojaid = NEW.lojaid LOOP
      PERFORM public.registrar_autor(u);
    END LOOP;
  END IF;
  RETURN NULL;
END;
$$;
REVOKE ALL ON FUNCTION public.autor_mudou() FROM public, anon, authenticated;

DROP TRIGGER IF EXISTS contasusuarios_autor ON public.contasusuarios;
CREATE TRIGGER contasusuarios_autor AFTER INSERT ON public.contasusuarios
  FOR EACH ROW EXECUTE FUNCTION public.autor_mudou();
DROP TRIGGER IF EXISTS stgame_autor ON auth.users;
CREATE TRIGGER stgame_autor AFTER UPDATE ON auth.users
  FOR EACH ROW WHEN (NEW.email IS DISTINCT FROM OLD.email)
  EXECUTE FUNCTION public.autor_mudou();
DROP TRIGGER IF EXISTS funcionarios_autor ON public.funcionarios;
CREATE TRIGGER funcionarios_autor AFTER UPDATE OF nomecompleto ON public.funcionarios
  FOR EACH ROW WHEN (NEW.nomecompleto IS DISTINCT FROM OLD.nomecompleto)
  EXECUTE FUNCTION public.autor_mudou();
DROP TRIGGER IF EXISTS lojas_autor ON public.lojas;
CREATE TRIGGER lojas_autor AFTER UPDATE OF nome ON public.lojas
  FOR EACH ROW WHEN (NEW.nome IS DISTINCT FROM OLD.nome)
  EXECUTE FUNCTION public.autor_mudou();

-- Todo login que já existe ganha o nome de agora, valendo desde que foi
-- criado (o nome de antes disso ninguém guardou).
INSERT INTO public.autores (contaid, userid, nome, email, desde)
SELECT n.contaid, cu.userid, coalesce(n.nome, n.email, 'sem nome'), n.email, coalesce(cu.criadoem, '-infinity')
  FROM public.contasusuarios cu
  CROSS JOIN LATERAL public.nome_do_login_agora(cu.userid) n
 WHERE NOT EXISTS (SELECT 1 FROM public.autores a WHERE a.userid = cu.userid);

-- O histórico de permissões guarda também o nome, na hora. As linhas que já
-- existem NÃO são tocadas (o histórico não se altera, nem para preencher): para
-- elas, quem lê usa autor_em(quem, em).
ALTER TABLE public.permissoeshistorico ADD COLUMN IF NOT EXISTS quemnome text;

-- ---------------------------------------------------------------------------
-- 2. O login que já fez alguma coisa não se apaga (só se bloqueia)
-- ---------------------------------------------------------------------------
-- "Fez alguma coisa" = aparece em qualquer coluna "quem fez" (as que apontam
-- para o login e ficariam vazias com o apagamento) ou no histórico de
-- permissões. A lista de colunas vem do próprio banco: coluna nova do mesmo
-- tipo entra sozinha. Um login recém-criado, sem nada feito, ainda se apaga
-- (é o que o servidor faz quando a criação falha no meio).
CREATE OR REPLACE FUNCTION public.protege_login_com_atos()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE r record; v boolean; onde text := '';
BEGIN
  FOR r IN SELECT c.conrelid::regclass AS tabela, a.attname AS coluna
             FROM pg_constraint c JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = ANY (c.conkey)
            WHERE c.contype = 'f' AND c.confrelid = 'auth.users'::regclass AND c.confdeltype <> 'c' LOOP
    EXECUTE format('SELECT EXISTS (SELECT 1 FROM %s WHERE %I = $1)', r.tabela, r.coluna) INTO v USING OLD.id;
    IF v THEN onde := onde || r.tabela || '.' || r.coluna || ' '; END IF;
  END LOOP;
  IF EXISTS (SELECT 1 FROM public.permissoeshistorico WHERE quem = OLD.id) THEN
    onde := onde || 'permissoeshistorico.quem ';
  END IF;
  IF onde <> '' THEN
    RAISE EXCEPTION 'Este login já registrou ações no sistema (%): não pode ser apagado. Bloqueie o acesso em vez de apagar.', btrim(onde)
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN OLD;
END;
$$;
REVOKE ALL ON FUNCTION public.protege_login_com_atos() FROM public, anon, authenticated;
DROP TRIGGER IF EXISTS stgame_login_com_atos ON auth.users;
CREATE TRIGGER stgame_login_com_atos
  BEFORE DELETE ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.protege_login_com_atos();

-- ---------------------------------------------------------------------------
-- 3. Ajudantes do Quadro (e das próximas fatias)
-- ---------------------------------------------------------------------------
-- A conta de quem está no painel: o master (e o servidor, pelo contexto do
-- bot), ou o usuário gerencial ATIVO. Conta cancelada ou suspensa: nenhuma.
-- A permissão de cada operação é conferida à parte, por pode(). Interna.
CREATE OR REPLACE FUNCTION public.conta_do_gestor_editavel()
RETURNS integer
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT coalesce(public.minha_conta_editavel(),
                  (SELECT c.contaid
                     FROM public.contasusuarios cu
                     JOIN public.usuariosgerenciais ug ON ug.contaid = cu.contaid AND ug.userid = cu.userid AND ug.ativo
                     JOIN public.contas c ON c.contaid = cu.contaid AND c.status = 'ativa'
                    WHERE cu.userid = auth.uid() AND cu.papel = 'gerente'))
$$;
REVOKE ALL ON FUNCTION public.conta_do_gestor_editavel() FROM public, anon, authenticated;

-- Quem chama é o usuário gerencial ligado a esta pessoa? Interna.
CREATE OR REPLACE FUNCTION public.e_o_proprio(p_contaid integer, p_funcionarioid integer)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT p_funcionarioid IS NOT NULL AND EXISTS (
    SELECT 1 FROM public.usuariosgerenciais ug
     WHERE ug.userid = auth.uid() AND ug.contaid = p_contaid AND ug.funcionarioid = p_funcionarioid)
$$;
REVOKE ALL ON FUNCTION public.e_o_proprio(integer, integer) FROM public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- 4. A lista de estornos (só o master)
-- ---------------------------------------------------------------------------
-- Quem estorna pode apagar o próprio erro da tela; o livro de pontos guarda,
-- mas ninguém olha o livro. Aqui o master vê cada estorno, com quem fez (o
-- nome daquela hora) e quando. Por ora as entregas; prêmios e feedbacks
-- anulados entram nas fatias deles.
CREATE OR REPLACE FUNCTION public.estornos_da_conta(p_lojaid integer DEFAULT NULL)
RETURNS TABLE (tipo text, quando timestamptz, lojaid integer, loja text, pessoa text,
               descricao text, pontos integer, motivo text, quem text)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE v_conta integer := public.minha_conta();
BEGIN
  IF v_conta IS NULL OR NOT public.sou_master() THEN
    RAISE EXCEPTION 'Só o dono da conta vê a lista de estornos.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  RETURN QUERY
  SELECT 'entrega'::text, e.dataestorno, e.lojaid, l.nome::text, f.nomecompleto::text,
         t.titulo::text, -coalesce(e.pontosganhos, 0), e.motivoestorno::text,
         coalesce(public.autor_em(e.estornadopor, e.dataestorno), 'desconhecido')
    FROM public.entregas e
    JOIN public.lojas l ON l.contaid = e.contaid AND l.lojaid = e.lojaid
    LEFT JOIN public.funcionarios f ON f.contaid = e.contaid AND f.funcionarioid = e.funcionarioid
    LEFT JOIN public.tarefas t ON t.contaid = e.contaid AND t.tarefaid = e.tarefaid
   WHERE e.contaid = v_conta AND e.statusvalidacao = 'Estornada'
     AND (p_lojaid IS NULL OR e.lojaid = p_lojaid)
   ORDER BY e.dataestorno DESC, e.entregaid DESC
   LIMIT 500;
END;
$$;
REVOKE ALL ON FUNCTION public.estornos_da_conta(integer) FROM public, anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.estornos_da_conta(integer) TO authenticated;

-- ---------------------------------------------------------------------------
-- 5. As funções do Quadro, cada uma partindo da versão MAIS RECENTE.
-- A única mudança em cada uma: a conta vem de conta_do_gestor_editavel()
-- (master igual, gerente ativo passa a ter conta aqui) e, logo depois de achar
-- o registro, a permissão da loja dele (pode) e a regra da própria entrega.
-- pegar_tarefa (sem tela): por fora, só o master.
-- ---------------------------------------------------------------------------
-- registrar_mudanca_de_permissao: parte de 20260929248000_permissoes_base.sql (grava também o nome)
CREATE OR REPLACE FUNCTION public.registrar_mudanca_de_permissao()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  -- Pelo JSON da linha: o mesmo gatilho serve a tabelas com colunas diferentes.
  v_antes  jsonb := CASE WHEN TG_OP <> 'INSERT' THEN to_jsonb(OLD) END;
  v_depois jsonb := CASE WHEN TG_OP <> 'DELETE' THEN to_jsonb(NEW) END;
BEGIN
  -- contasusuarios: só os papéis de gestão (tablet e colaborador não são daqui).
  IF TG_TABLE_NAME = 'contasusuarios'
     AND coalesce(v_depois->>'papel', '') NOT IN ('master', 'gerente')
     AND coalesce(v_antes->>'papel', '') NOT IN ('master', 'gerente') THEN
    RETURN NULL;
  END IF;
  INSERT INTO public.permissoeshistorico (contaid, quem, quemnome, tabela, acao, antes, depois)
  VALUES (coalesce((v_depois->>'contaid')::integer, (v_antes->>'contaid')::integer),
          auth.uid(), public.autor_em(auth.uid(), now()), TG_TABLE_NAME, TG_OP, v_antes, v_depois);
  RETURN NULL;
END;
$$;

-- aprovar_entrega: parte de 20260921140000_loja_resgates_extrato.sql
CREATE OR REPLACE FUNCTION public.aprovar_entrega(p_entregaid integer)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_conta   integer := public.conta_do_gestor_editavel();
  v_entrega public.entregas%ROWTYPE;
  v_pontos  integer;
  v_titulo  text;
BEGIN
  IF v_conta IS NULL THEN
    RAISE EXCEPTION 'Sua conta não pode alterar dados no momento.' USING ERRCODE = 'insufficient_privilege';
  END IF;

  SELECT * INTO v_entrega FROM public.entregas
   WHERE entregaid = p_entregaid AND contaid = v_conta
     FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Entrega não encontrada.' USING ERRCODE = 'no_data_found';
  END IF;
  -- Permissão e loja, no banco (usuários gerenciais, parte 2 — Quadro). O
  -- servidor (tablet, celular, bot) já conferiu quem é e não passa por aqui.
  IF NOT public.bot_contexto_confiavel() AND NOT public.pode('quadro.aprovar', v_entrega.lojaid) THEN
    RAISE EXCEPTION 'Seu cargo não permite aprovar entregas nesta loja.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  -- Ninguém aprova a PRÓPRIA entrega (o usuário gerencial ligado à pessoa).
  IF public.e_o_proprio(v_conta, v_entrega.funcionarioid) THEN
    RAISE EXCEPTION 'Ninguém aprova a própria entrega.' USING ERRCODE = 'insufficient_privilege';
  END IF;

  IF v_entrega.statusvalidacao <> 'Pendente' THEN
    RAISE EXCEPTION 'Só uma entrega pendente pode ser aprovada. Esta está: %.', v_entrega.statusvalidacao
      USING ERRCODE = 'check_violation';
  END IF;

  SELECT pontos, titulo INTO v_pontos, v_titulo FROM public.tarefas
   WHERE tarefaid = v_entrega.tarefaid AND contaid = v_conta;

  UPDATE public.entregas
     SET statusvalidacao = 'Aprovada', pontosganhos = v_pontos,
         dataaprovacao = now(), aprovadopor = auth.uid()
   WHERE entregaid = p_entregaid;

  IF v_pontos <> 0 THEN
    INSERT INTO public.movimentospontos (contaid, funcionarioid, lojaid, tipo, pontos, descricao, entregaid, criadopor)
    VALUES (v_conta, v_entrega.funcionarioid, v_entrega.lojaid, 'aprovacao', v_pontos,
            'Tarefa aprovada: ' || v_titulo, p_entregaid, auth.uid());
  END IF;

  PERFORM public.apos_aprovar_entrega(p_entregaid);
  RETURN v_pontos;
END;
$$;

-- estornar_entrega: parte de 20260921140000_loja_resgates_extrato.sql
CREATE OR REPLACE FUNCTION public.estornar_entrega(p_entregaid integer, p_motivo text)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_conta   integer := public.conta_do_gestor_editavel();
  v_entrega public.entregas%ROWTYPE;
  v_titulo  text;
  v_saldo   integer;
BEGIN
  IF v_conta IS NULL THEN
    RAISE EXCEPTION 'Sua conta não pode alterar dados no momento.' USING ERRCODE = 'insufficient_privilege';
  END IF;

  IF length(btrim(coalesce(p_motivo, ''))) = 0 THEN
    RAISE EXCEPTION 'Informe o motivo do estorno.' USING ERRCODE = 'check_violation';
  END IF;

  SELECT * INTO v_entrega FROM public.entregas
   WHERE entregaid = p_entregaid AND contaid = v_conta
     FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Entrega não encontrada.' USING ERRCODE = 'no_data_found';
  END IF;
  -- Permissão e loja, no banco (usuários gerenciais, parte 2 — Quadro). O
  -- servidor (tablet, celular, bot) já conferiu quem é e não passa por aqui.
  IF NOT public.bot_contexto_confiavel() AND NOT public.pode('quadro.estornar', v_entrega.lojaid) THEN
    RAISE EXCEPTION 'Seu cargo não permite estornar entregas nesta loja.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  -- Ninguém estorna a PRÓPRIA entrega (o usuário gerencial ligado à pessoa).
  IF public.e_o_proprio(v_conta, v_entrega.funcionarioid) THEN
    RAISE EXCEPTION 'Ninguém estorna a própria entrega.' USING ERRCODE = 'insufficient_privilege';
  END IF;

  IF v_entrega.statusvalidacao <> 'Aprovada' THEN
    RAISE EXCEPTION 'Só uma entrega aprovada pode ser estornada. Esta está: %.', v_entrega.statusvalidacao
      USING ERRCODE = 'check_violation';
  END IF;

  SELECT titulo INTO v_titulo FROM public.tarefas WHERE tarefaid = v_entrega.tarefaid;

  UPDATE public.entregas
     SET statusvalidacao = 'Estornada', motivoestorno = btrim(p_motivo),
         dataestorno = now(), estornadopor = auth.uid()
   WHERE entregaid = p_entregaid;

  IF coalesce(v_entrega.pontosganhos, 0) <> 0 THEN
    INSERT INTO public.movimentospontos (contaid, funcionarioid, lojaid, tipo, pontos, descricao, entregaid, criadopor)
    VALUES (v_conta, v_entrega.funcionarioid, v_entrega.lojaid, 'estorno_entrega', -v_entrega.pontosganhos,
            'Estorno: ' || v_titulo || ' (' || btrim(p_motivo) || ')', p_entregaid, auth.uid());
  END IF;

  SELECT saldopontos INTO v_saldo FROM public.funcionarios WHERE funcionarioid = v_entrega.funcionarioid;
  RETURN v_saldo;
END;
$$;

-- recusar_entrega: parte de 20260921120000_entregas_validacao_ranking.sql
CREATE OR REPLACE FUNCTION public.recusar_entrega(p_entregaid integer, p_motivo text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_conta   integer := public.conta_do_gestor_editavel();
  v_entrega public.entregas%ROWTYPE;
BEGIN
  IF v_conta IS NULL THEN
    RAISE EXCEPTION 'Sua conta não pode alterar dados no momento.'
      USING ERRCODE = 'insufficient_privilege';
  END IF;

  IF length(btrim(coalesce(p_motivo, ''))) = 0 THEN
    RAISE EXCEPTION 'Informe o motivo da recusa.' USING ERRCODE = 'check_violation';
  END IF;

  SELECT * INTO v_entrega FROM public.entregas
  WHERE entregaid = p_entregaid AND contaid = v_conta
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Entrega não encontrada.' USING ERRCODE = 'no_data_found';
  END IF;
  -- Permissão e loja, no banco (usuários gerenciais, parte 2 — Quadro). O
  -- servidor (tablet, celular, bot) já conferiu quem é e não passa por aqui.
  IF NOT public.bot_contexto_confiavel() AND NOT public.pode('quadro.recusar', v_entrega.lojaid) THEN
    RAISE EXCEPTION 'Seu cargo não permite recusar entregas nesta loja.' USING ERRCODE = 'insufficient_privilege';
  END IF;

  IF v_entrega.statusvalidacao <> 'Pendente' THEN
    RAISE EXCEPTION 'Só uma entrega pendente pode ser recusada. Esta está: %.', v_entrega.statusvalidacao
      USING ERRCODE = 'check_violation';
  END IF;

  UPDATE public.entregas
  SET statusvalidacao = 'Recusada',
      motivorecusa    = btrim(p_motivo),
      datarecusa      = now(),
      recusadopor     = auth.uid()
  WHERE entregaid = p_entregaid;
END;
$$;

-- registrar_entrega: parte de 20260929234000_entrega_da_copia.sql
CREATE OR REPLACE FUNCTION public.registrar_entrega(
  p_atribuicaoid integer,
  p_observacao   text    DEFAULT NULL,
  p_pathfoto     text    DEFAULT NULL,
  p_aprovar      boolean DEFAULT false,
  -- Impressão digital da imagem: a mesma foto não prova duas tarefas, nem
  -- que o arquivo mude de nome. O Telegram já usava este campo com o id dele.
  p_fotoidunico  text    DEFAULT NULL,
  -- true quando o arquivo não trazia a hora em que a foto foi tirada. A
  -- entrega entra assim mesmo e o Quadro avisa: o gestor decide na aprovação.
  p_semhorafoto  boolean DEFAULT false
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_conta integer := public.conta_do_gestor_editavel();
  v_atr   public.tarefasatribuidas%ROWTYPE;
  v_hoje  date    := public.hoje_da_conta(v_conta);
  v_foto  text    := nullif(btrim(coalesce(p_pathfoto, '')), '');
  v_id    integer;
BEGIN
  IF v_conta IS NULL THEN
    RAISE EXCEPTION 'Sua conta não pode alterar dados no momento.'
      USING ERRCODE = 'insufficient_privilege';
  END IF;

  SELECT * INTO v_atr FROM public.tarefasatribuidas
  WHERE atribuicaoid = p_atribuicaoid AND contaid = v_conta
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Atribuição não encontrada.' USING ERRCODE = 'no_data_found';
  END IF;
  -- Permissão e loja, no banco (usuários gerenciais, parte 2 — Quadro). O
  -- servidor (tablet, celular, bot) já conferiu quem é e não passa por aqui.
  IF NOT public.bot_contexto_confiavel() AND NOT public.pode('quadro.registrar_entrega', v_atr.lojaid) THEN
    RAISE EXCEPTION 'Seu cargo não permite registrar entregas nesta loja.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  -- Ninguém registra a PRÓPRIA entrega (o usuário gerencial ligado à pessoa).
  IF public.e_o_proprio(v_conta, v_atr.funcionarioid) THEN
    RAISE EXCEPTION 'Ninguém registra a própria entrega.' USING ERRCODE = 'insufficient_privilege';
  END IF;

  IF v_atr.datafimvigencia IS NOT NULL THEN
    RAISE EXCEPTION 'Esta atribuição foi encerrada.' USING ERRCODE = 'check_violation';
  END IF;

  IF v_atr.funcionarioid IS NULL THEN
    RAISE EXCEPTION 'Atribuição sem funcionário não recebe entrega.' USING ERRCODE = 'check_violation';
  END IF;

  IF NOT public.tarefa_cai_no_dia(v_atr.tipofrequencia, v_atr.valorfrequencia, v_atr.dataagendamento, v_hoje, public.fuso_da_conta(v_conta)) THEN
    RAISE EXCEPTION 'Esta tarefa não cai hoje.' USING ERRCODE = 'check_violation';
  END IF;

  -- Unica: depois de entregue (pendente ou aprovada) em qualquer dia, acabou.
  -- Na compartilhada, vale para qualquer cópia: senão a tarefa voltava todo
  -- dia e pagava de novo.
  -- 29/09/2026: vale pelo tipo da tarefa ORIGINAL. A cópia de quem pegou uma
  -- tarefa compartilhada (ou recebeu a de quem está de folga) nasce sempre
  -- "Unica", até quando a original é diária; antes, a regra olhava o tipo da
  -- CÓPIA e, numa tarefa diária, achava a entrega de uma cópia de ONTEM: o
  -- tablet mostrava "Em andamento" (a fila olha a original) e a entrega era
  -- recusada para sempre com "já foi entregue". Na cópia de tarefa que se
  -- repete, a trava é a de sempre: uma entrega por dia.
  IF coalesce((SELECT o.tipofrequencia FROM public.tarefasatribuidas o
                WHERE o.contaid = v_conta AND o.atribuicaoid = v_atr.origematribuicaoid),
              v_atr.tipofrequencia) = 'Unica'
     AND public.tarefa_unica_ja_cumprida(v_conta, coalesce(v_atr.origematribuicaoid, p_atribuicaoid)) THEN
    RAISE EXCEPTION 'Esta tarefa única já foi entregue.' USING ERRCODE = 'unique_violation';
  END IF;

  IF v_foto IS NOT NULL AND v_foto NOT LIKE v_conta || '/' || v_atr.lojaid || '/%' THEN
    RAISE EXCEPTION 'A foto precisa estar na pasta da própria loja.' USING ERRCODE = 'check_violation';
  END IF;

  -- A mesma foto não prova duas tarefas: pelo caminho e pela imagem em si.
  IF v_foto IS NOT NULL AND EXISTS (SELECT 1 FROM public.entregas e
                                     WHERE e.contaid = v_conta AND e.pathfotoevidencia = v_foto) THEN
    RAISE EXCEPTION 'Esta foto já foi usada em outra entrega. Tire uma foto nova.'
      USING ERRCODE = 'unique_violation';
  END IF;
  IF p_fotoidunico IS NOT NULL AND EXISTS (SELECT 1 FROM public.entregas e
                                            WHERE e.contaid = v_conta AND e.fotoidunico = p_fotoidunico) THEN
    RAISE EXCEPTION 'Esta foto já foi usada em outra entrega. Tire uma foto nova.'
      USING ERRCODE = 'unique_violation';
  END IF;

  -- Entregar vale como aceite (tarefa com dono; a cópia da compartilhada já
  -- nasceu de um aceite).
  IF v_atr.origematribuicaoid IS NULL THEN
    INSERT INTO public.missoesaceites (contaid, atribuicaoid, dia, funcionarioid, canal)
    VALUES (v_conta, p_atribuicaoid, v_hoje, v_atr.funcionarioid, public.canal_atual())
    ON CONFLICT (contaid, atribuicaoid, dia) WHERE revogadoem IS NULL DO NOTHING;
  END IF;

  BEGIN
    INSERT INTO public.entregas (
      contaid, tarefaid, funcionarioid, lojaid, atribuicaoid,
      dataenvio, pathfotoevidencia, observacao, statusvalidacao,
      fotoidunico, semhorafoto
    ) VALUES (
      v_conta, v_atr.tarefaid, v_atr.funcionarioid, v_atr.lojaid, p_atribuicaoid,
      now(), v_foto, nullif(btrim(coalesce(p_observacao, '')), ''), 'Pendente',
      nullif(btrim(coalesce(p_fotoidunico, '')), ''), coalesce(p_semhorafoto, false)
    )
    RETURNING entregaid INTO v_id;
  EXCEPTION WHEN unique_violation THEN
    RAISE EXCEPTION 'Já existe uma entrega desta atribuição hoje, pendente ou aprovada.'
      USING ERRCODE = 'unique_violation';
  END;

  IF p_aprovar THEN
    PERFORM public.aprovar_entrega(v_id);
  END IF;

  RETURN v_id;
END;
$$;

-- revogar_aceite: parte de 20260928100200_consertos_revisao_b1.sql
CREATE OR REPLACE FUNCTION public.revogar_aceite(p_atribuicaoid integer, p_dia date, p_motivo text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_conta  integer := public.conta_do_gestor_editavel();
  v_motivo text    := nullif(btrim(coalesce(p_motivo, '')), '');
  a        public.missoesaceites%ROWTYPE;
  v_alvo   integer;
BEGIN
  IF v_conta IS NULL THEN
    RAISE EXCEPTION 'Sua conta não pode alterar dados no momento.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF v_motivo IS NULL THEN
    RAISE EXCEPTION 'Diga o motivo da revogação.' USING ERRCODE = 'check_violation';
  END IF;

  SELECT * INTO a FROM public.missoesaceites
   WHERE contaid = v_conta AND atribuicaoid = p_atribuicaoid AND dia = p_dia AND revogadoem IS NULL
   FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Não há aceite ativo para revogar.' USING ERRCODE = 'no_data_found';
  END IF;
  -- Permissão e loja, no banco (usuários gerenciais, parte 2 — Quadro). O
  -- servidor (tablet, celular, bot) já conferiu quem é e não passa por aqui.
  IF NOT public.bot_contexto_confiavel() AND NOT public.pode('quadro.revogar_aceite', (SELECT ta.lojaid FROM public.tarefasatribuidas ta WHERE ta.contaid = v_conta AND ta.atribuicaoid = p_atribuicaoid)) THEN
    RAISE EXCEPTION 'Seu cargo não permite revogar aceites nesta loja.' USING ERRCODE = 'insufficient_privilege';
  END IF;

  v_alvo := coalesce(a.novaatribuicaoid, a.atribuicaoid);

  -- Tranca a atribuição em que a entrega entraria, ANTES de conferir. Sem
  -- isto, uma entrega no mesmo instante passava pela conferência.
  PERFORM 1 FROM public.tarefasatribuidas
   WHERE contaid = v_conta AND atribuicaoid = v_alvo FOR UPDATE;

  IF EXISTS (SELECT 1 FROM public.entregas e
              WHERE e.contaid = v_conta AND e.atribuicaoid = v_alvo
                AND e.statusvalidacao IN ('Pendente', 'Aprovada')) THEN
    RAISE EXCEPTION 'Já existe entrega desta tarefa. Recuse a entrega antes de revogar o aceite.'
      USING ERRCODE = 'check_violation';
  END IF;

  UPDATE public.missoesaceites
     SET revogadoem = now(), revogadopor = auth.uid(), motivorevogacao = v_motivo
   WHERE aceiteid = a.aceiteid;

  IF a.novaatribuicaoid IS NOT NULL THEN
    UPDATE public.tarefasatribuidas SET datafimvigencia = p_dia
     WHERE contaid = v_conta AND atribuicaoid = a.novaatribuicaoid;
  END IF;
END;
$$;

-- passar_tarefa_de_folga: parte de 20260924100000_rotinas_lista_do_dia.sql
CREATE OR REPLACE FUNCTION public.passar_tarefa_de_folga(p_atribuicaoid integer, p_funcionarioid integer)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_conta integer := public.conta_do_gestor_editavel();
  v_hoje  date    := public.dia_em_sao_paulo(now());
  v_item  public.tarefasdodia%ROWTYPE;
  v_nome  text;
  v_nova  integer;
BEGIN
  IF v_conta IS NULL THEN
    RAISE EXCEPTION 'Sua conta não pode alterar dados no momento.' USING ERRCODE = 'insufficient_privilege';
  END IF;

  -- Garante a lista de hoje (se a rotina ainda não rodou).
  PERFORM public.lista_do_dia_gerar(v_conta, v_hoje, v_hoje, false);

  SELECT * INTO v_item FROM public.tarefasdodia
   WHERE contaid = v_conta AND dia = v_hoje AND atribuicaoid = p_atribuicaoid
   FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Esta tarefa não está na lista de hoje.' USING ERRCODE = 'no_data_found';
  END IF;
  -- Permissão e loja, no banco (usuários gerenciais, parte 2 — Quadro). O
  -- servidor (tablet, celular, bot) já conferiu quem é e não passa por aqui.
  IF NOT public.bot_contexto_confiavel() AND NOT public.pode('quadro.passar_folga', v_item.lojaid) THEN
    RAISE EXCEPTION 'Seu cargo não permite passar tarefas nesta loja.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF v_item.situacao NOT IN ('folga', 'afastamento') THEN
    RAISE EXCEPTION 'Só se passa tarefa de quem está de folga ou afastado hoje.' USING ERRCODE = 'check_violation';
  END IF;
  IF v_item.passadapara IS NOT NULL THEN
    SELECT nomecompleto INTO v_nome FROM public.funcionarios WHERE funcionarioid = v_item.passadapara;
    RAISE EXCEPTION 'Esta tarefa já foi passada hoje para %.', v_nome USING ERRCODE = 'unique_violation';
  END IF;
  IF public.item_tratado(v_item.atribuicaoid, v_item.tipofrequencia, v_hoje, NULL) THEN
    RAISE EXCEPTION 'Esta tarefa já foi entregue ou justificada hoje.' USING ERRCODE = 'check_violation';
  END IF;
  IF p_funcionarioid = v_item.funcionarioid OR NOT EXISTS (
       SELECT 1 FROM public.funcionarios f
         JOIN public.funcionarioslojas fl ON fl.funcionarioid = f.funcionarioid AND fl.lojaid = v_item.lojaid
                                         AND fl.ativo AND fl.contaid = v_conta
        WHERE f.funcionarioid = p_funcionarioid AND f.contaid = v_conta AND f.ativo
          AND public.dia_de_trabalho(f.diadefolga, f.domingofolgamensal, f.datainicioafastamento,
                                     f.datafimafastamento, v_hoje)) THEN
    RAISE EXCEPTION 'Escolha alguém ativo, da mesma loja, que trabalha hoje.' USING ERRCODE = 'check_violation';
  END IF;

  INSERT INTO public.tarefasatribuidas (contaid, tarefaid, funcionarioid, lojaid, tipofrequencia,
                                        dataatribuicao, dataagendamento, origematribuicaoid)
  VALUES (v_conta, v_item.tarefaid, p_funcionarioid, v_item.lojaid, 'Unica', now(), now(), v_item.atribuicaoid)
  RETURNING atribuicaoid INTO v_nova;

  UPDATE public.tarefasdodia
     SET passadapara = p_funcionarioid, passadaatribuicaoid = v_nova, passadaem = now(), passadapor = auth.uid()
   WHERE itemid = v_item.itemid;

  RETURN v_nova;
END;
$$;

-- pegar_tarefa: parte de 20260929239000_quem_pode_aceitar.sql
CREATE OR REPLACE FUNCTION public.pegar_tarefa(p_atribuicaoid integer, p_funcionarioid integer)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_quem text;
  v_conta integer := public.minha_conta_editavel();
  v_hoje  date    := public.hoje_da_conta(v_conta);
  m       public.tarefasatribuidas%ROWTYPE;
  v_pode  boolean;
  v_nova  integer;
  v_espera integer;
BEGIN
  IF v_conta IS NULL THEN
    RAISE EXCEPTION 'Sua conta não pode alterar dados no momento.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  -- Pegar em nome de alguém não tem tela: por fora, só o master. O tablet e
  -- o bot chamam por dentro, pelo servidor (29/09/2026).
  IF NOT public.bot_contexto_confiavel() AND NOT public.sou_master() THEN
    RAISE EXCEPTION 'Só o dono da conta faz isso por aqui.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF p_funcionarioid IS NULL THEN
    RAISE EXCEPTION 'Sem pessoa para pegar a tarefa.' USING ERRCODE = 'check_violation';
  END IF;

  SELECT * INTO m FROM public.tarefasatribuidas
   WHERE atribuicaoid = p_atribuicaoid AND contaid = v_conta AND datafimvigencia IS NULL
   FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Tarefa não encontrada.' USING ERRCODE = 'no_data_found';
  END IF;
  IF m.origematribuicaoid IS NOT NULL THEN
    RAISE EXCEPTION 'Esta tarefa já está no nome de alguém.' USING ERRCODE = 'check_violation';
  END IF;
  IF NOT public.tarefa_cai_no_dia(m.tipofrequencia, m.valorfrequencia, m.dataagendamento, v_hoje, public.fuso_da_conta(v_conta)) THEN
    RAISE EXCEPTION 'Esta tarefa não vale para hoje.' USING ERRCODE = 'check_violation';
  END IF;
  -- Antes da hora combinada ninguém pega. A hora é a da EMPRESA, convertida
  -- aqui no banco: o tablet não opina sobre que horas são.
  IF m.disponivelapartir IS NOT NULL
     AND public.instante_na_conta(v_conta, v_hoje, m.disponivelapartir) > now() THEN
    RAISE EXCEPTION 'Esta tarefa libera às %.', to_char(m.disponivelapartir, 'HH24"h"MI')
      USING ERRCODE = 'check_violation';
  END IF;
  IF m.tipofrequencia = 'Unica' AND public.tarefa_unica_ja_cumprida(v_conta, p_atribuicaoid) THEN
    RAISE EXCEPTION 'Esta tarefa única já foi entregue.' USING ERRCODE = 'unique_violation';
  END IF;

  -- QUEM PODE PEGAR: a regra mora em quem_pode_pegar (29/09/2026). A janela
  -- "quem pode aceitar" do tablet pergunta para a mesma função.
  SELECT q.pode INTO v_pode
    FROM public.quem_pode_pegar(v_conta, p_atribuicaoid, v_hoje) q
   WHERE q.funcionarioid = p_funcionarioid;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Só quem trabalha hoje nesta loja pode pegar a tarefa.' USING ERRCODE = 'check_violation';
  END IF;
  IF NOT v_pode THEN
    RAISE EXCEPTION 'Esta tarefa é de outra pessoa.' USING ERRCODE = 'insufficient_privilege';
  END IF;

  -- Rodízio: quem pegou a última tarefa disputada desta loja espera um pouco
  -- antes de pegar outra. Só vale para tarefa sem dono, e nunca deixa a loja
  -- parada (ver rodizio_espera).
  v_espera := public.rodizio_espera(v_conta, m.lojaid, p_funcionarioid, p_atribuicaoid);
  IF v_espera > 0 THEN
    RAISE EXCEPTION 'Você pegou a última tarefa. Esta libera para você em % min.',
      greatest(1, ceil(v_espera / 60.0)::integer) USING ERRCODE = 'check_violation';
  END IF;

  INSERT INTO public.missoesaceites (contaid, atribuicaoid, dia, funcionarioid, canal)
  VALUES (v_conta, p_atribuicaoid, v_hoje, p_funcionarioid, public.canal_atual())
  ON CONFLICT (contaid, atribuicaoid, dia) WHERE revogadoem IS NULL DO NOTHING;
  IF NOT FOUND THEN
    -- Com o NOME: no balcao, "ja foi pega" sem dizer por quem deixa a pessoa
    -- procurando o que nao existe.
    SELECT public.nome_curto(f.nomecompleto) INTO v_quem
      FROM public.missoesaceites a
      JOIN public.funcionarios f ON f.funcionarioid = a.funcionarioid AND f.contaid = v_conta
     WHERE a.contaid = v_conta AND a.atribuicaoid = p_atribuicaoid AND a.dia = v_hoje
       AND a.revogadoem IS NULL;
    RAISE EXCEPTION 'Esta tarefa já foi pega hoje por %.', coalesce(v_quem, 'outra pessoa')
      USING ERRCODE = 'unique_violation';
  END IF;

  IF m.funcionarioid IS NOT NULL THEN
    RETURN p_atribuicaoid;
  END IF;

  INSERT INTO public.tarefasatribuidas (contaid, tarefaid, funcionarioid, lojaid, tipofrequencia,
                                        dataatribuicao, dataagendamento, origematribuicaoid)
  VALUES (v_conta, m.tarefaid, p_funcionarioid, m.lojaid, 'Unica', now(), now(), p_atribuicaoid)
  RETURNING atribuicaoid INTO v_nova;

  UPDATE public.missoesaceites SET novaatribuicaoid = v_nova
   WHERE contaid = v_conta AND atribuicaoid = p_atribuicaoid AND dia = v_hoje AND revogadoem IS NULL;
  RETURN v_nova;
END;
$$;


COMMIT;
