/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DefinirSenhaRouteImport } from './routes/definir-senha'
import { Route as MeuAcessoRouteImport } from './routes/meu-acesso'
import { Route as PrimeiroAcessoRouteImport } from './routes/primeiro-acesso'
import { Route as SemAcessoRouteImport } from './routes/sem-acesso'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedCanalConfidencialRouteImport } from './routes/_authenticated/canal-confidencial'
import { Route as AuthenticatedComunicadosRouteImport } from './routes/_authenticated/comunicados'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedConquistasRouteImport } from './routes/_authenticated/conquistas'
import { Route as AuthenticatedDocumentosPessoaisRouteImport } from './routes/_authenticated/documentos-pessoais'
import { Route as AuthenticatedExtratoRouteImport } from './routes/_authenticated/extrato'
import { Route as AuthenticatedFeedbacksRouteImport } from './routes/_authenticated/feedbacks'
import { Route as AuthenticatedFuncionariosRouteImport } from './routes/_authenticated/funcionarios'
import { Route as AuthenticatedGestaoRouteImport } from './routes/_authenticated/gestao'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedJustificativasRouteImport } from './routes/_authenticated/justificativas'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedOperacionalRouteImport } from './routes/_authenticated/operacional'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPremiosRouteImport } from './routes/_authenticated/premios'
import { Route as AuthenticatedRankingRouteImport } from './routes/_authenticated/ranking'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedSolicitacoesRouteImport } from './routes/_authenticated/solicitacoes'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminPerfilRouteImport } from './routes/admin/perfil'
import { Route as ECodigoRouteImport } from './routes/e.$codigo'
import { Route as TvCodigoRouteImport } from './routes/tv.$codigo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DefinirSenhaRoute = DefinirSenhaRouteImport.update({
  id: '/definir-senha',
  path: '/definir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const MeuAcessoRoute = MeuAcessoRouteImport.update({
  id: '/meu-acesso',
  path: '/meu-acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimeiroAcessoRoute = PrimeiroAcessoRouteImport.update({
  id: '/primeiro-acesso',
  path: '/primeiro-acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const SemAcessoRoute = SemAcessoRouteImport.update({
  id: '/sem-acesso',
  path: '/sem-acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCanalConfidencialRoute =
  AuthenticatedCanalConfidencialRouteImport.update({
    id: '/canal-confidencial',
    path: '/canal-confidencial',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComunicadosRoute =
  AuthenticatedComunicadosRouteImport.update({
    id: '/comunicados',
    path: '/comunicados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConquistasRoute = AuthenticatedConquistasRouteImport.update({
  id: '/conquistas',
  path: '/conquistas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentosPessoaisRoute =
  AuthenticatedDocumentosPessoaisRouteImport.update({
    id: '/documentos-pessoais',
    path: '/documentos-pessoais',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExtratoRoute = AuthenticatedExtratoRouteImport.update({
  id: '/extrato',
  path: '/extrato',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedbacksRoute = AuthenticatedFeedbacksRouteImport.update({
  id: '/feedbacks',
  path: '/feedbacks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFuncionariosRoute =
  AuthenticatedFuncionariosRouteImport.update({
    id: '/funcionarios',
    path: '/funcionarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGestaoRoute = AuthenticatedGestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJustificativasRoute =
  AuthenticatedJustificativasRouteImport.update({
    id: '/justificativas',
    path: '/justificativas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperacionalRoute =
  AuthenticatedOperacionalRouteImport.update({
    id: '/operacional',
    path: '/operacional',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPremiosRoute = AuthenticatedPremiosRouteImport.update({
  id: '/premios',
  path: '/premios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRankingRoute = AuthenticatedRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSolicitacoesRoute =
  AuthenticatedSolicitacoesRouteImport.update({
    id: '/solicitacoes',
    path: '/solicitacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPerfilRoute = AdminPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ECodigoRoute = ECodigoRouteImport.update({
  id: '/e/$codigo',
  path: '/e/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const TvCodigoRoute = TvCodigoRouteImport.update({
  id: '/tv/$codigo',
  path: '/tv/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/meu-acesso': typeof MeuAcessoRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/sem-acesso': typeof SemAcessoRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/canal-confidencial': typeof AuthenticatedCanalConfidencialRoute
  '/comunicados': typeof AuthenticatedComunicadosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conquistas': typeof AuthenticatedConquistasRoute
  '/documentos-pessoais': typeof AuthenticatedDocumentosPessoaisRoute
  '/extrato': typeof AuthenticatedExtratoRoute
  '/feedbacks': typeof AuthenticatedFeedbacksRoute
  '/funcionarios': typeof AuthenticatedFuncionariosRoute
  '/gestao': typeof AuthenticatedGestaoRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/justificativas': typeof AuthenticatedJustificativasRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/operacional': typeof AuthenticatedOperacionalRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/premios': typeof AuthenticatedPremiosRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/solicitacoes': typeof AuthenticatedSolicitacoesRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/admin/perfil': typeof AdminPerfilRoute
  '/e/$codigo': typeof ECodigoRoute
  '/tv/$codigo': typeof TvCodigoRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/meu-acesso': typeof MeuAcessoRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/sem-acesso': typeof SemAcessoRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/canal-confidencial': typeof AuthenticatedCanalConfidencialRoute
  '/comunicados': typeof AuthenticatedComunicadosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conquistas': typeof AuthenticatedConquistasRoute
  '/documentos-pessoais': typeof AuthenticatedDocumentosPessoaisRoute
  '/extrato': typeof AuthenticatedExtratoRoute
  '/feedbacks': typeof AuthenticatedFeedbacksRoute
  '/funcionarios': typeof AuthenticatedFuncionariosRoute
  '/gestao': typeof AuthenticatedGestaoRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/justificativas': typeof AuthenticatedJustificativasRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/operacional': typeof AuthenticatedOperacionalRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/premios': typeof AuthenticatedPremiosRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/solicitacoes': typeof AuthenticatedSolicitacoesRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/admin/perfil': typeof AdminPerfilRoute
  '/e/$codigo': typeof ECodigoRoute
  '/tv/$codigo': typeof TvCodigoRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/meu-acesso': typeof MeuAcessoRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/sem-acesso': typeof SemAcessoRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/canal-confidencial': typeof AuthenticatedCanalConfidencialRoute
  '/_authenticated/comunicados': typeof AuthenticatedComunicadosRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/conquistas': typeof AuthenticatedConquistasRoute
  '/_authenticated/documentos-pessoais': typeof AuthenticatedDocumentosPessoaisRoute
  '/_authenticated/extrato': typeof AuthenticatedExtratoRoute
  '/_authenticated/feedbacks': typeof AuthenticatedFeedbacksRoute
  '/_authenticated/funcionarios': typeof AuthenticatedFuncionariosRoute
  '/_authenticated/gestao': typeof AuthenticatedGestaoRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/justificativas': typeof AuthenticatedJustificativasRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/operacional': typeof AuthenticatedOperacionalRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/premios': typeof AuthenticatedPremiosRoute
  '/_authenticated/ranking': typeof AuthenticatedRankingRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/solicitacoes': typeof AuthenticatedSolicitacoesRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRoute
  '/admin/perfil': typeof AdminPerfilRoute
  '/e/$codigo': typeof ECodigoRoute
  '/tv/$codigo': typeof TvCodigoRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/definir-senha'
    | '/meu-acesso'
    | '/primeiro-acesso'
    | '/sem-acesso'
    | '/agenda'
    | '/canal-confidencial'
    | '/comunicados'
    | '/configuracoes'
    | '/conquistas'
    | '/documentos-pessoais'
    | '/extrato'
    | '/feedbacks'
    | '/funcionarios'
    | '/gestao'
    | '/inicio'
    | '/justificativas'
    | '/metas'
    | '/onboarding'
    | '/operacional'
    | '/painel'
    | '/perfil'
    | '/premios'
    | '/ranking'
    | '/relatorios'
    | '/solicitacoes'
    | '/tarefas'
    | '/admin/perfil'
    | '/e/$codigo'
    | '/tv/$codigo'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/definir-senha'
    | '/meu-acesso'
    | '/primeiro-acesso'
    | '/sem-acesso'
    | '/agenda'
    | '/canal-confidencial'
    | '/comunicados'
    | '/configuracoes'
    | '/conquistas'
    | '/documentos-pessoais'
    | '/extrato'
    | '/feedbacks'
    | '/funcionarios'
    | '/gestao'
    | '/inicio'
    | '/justificativas'
    | '/metas'
    | '/onboarding'
    | '/operacional'
    | '/painel'
    | '/perfil'
    | '/premios'
    | '/ranking'
    | '/relatorios'
    | '/solicitacoes'
    | '/tarefas'
    | '/admin/perfil'
    | '/e/$codigo'
    | '/tv/$codigo'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/definir-senha'
    | '/meu-acesso'
    | '/primeiro-acesso'
    | '/sem-acesso'
    | '/_authenticated/agenda'
    | '/_authenticated/canal-confidencial'
    | '/_authenticated/comunicados'
    | '/_authenticated/configuracoes'
    | '/_authenticated/conquistas'
    | '/_authenticated/documentos-pessoais'
    | '/_authenticated/extrato'
    | '/_authenticated/feedbacks'
    | '/_authenticated/funcionarios'
    | '/_authenticated/gestao'
    | '/_authenticated/inicio'
    | '/_authenticated/justificativas'
    | '/_authenticated/metas'
    | '/_authenticated/onboarding'
    | '/_authenticated/operacional'
    | '/_authenticated/painel'
    | '/_authenticated/perfil'
    | '/_authenticated/premios'
    | '/_authenticated/ranking'
    | '/_authenticated/relatorios'
    | '/_authenticated/solicitacoes'
    | '/_authenticated/tarefas'
    | '/admin/perfil'
    | '/e/$codigo'
    | '/tv/$codigo'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DefinirSenhaRoute: typeof DefinirSenhaRoute
  MeuAcessoRoute: typeof MeuAcessoRoute
  PrimeiroAcessoRoute: typeof PrimeiroAcessoRoute
  SemAcessoRoute: typeof SemAcessoRoute
  ECodigoRoute: typeof ECodigoRoute
  TvCodigoRoute: typeof TvCodigoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/definir-senha': {
      id: '/definir-senha'
      path: '/definir-senha'
      fullPath: '/definir-senha'
      preLoaderRoute: typeof DefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meu-acesso': {
      id: '/meu-acesso'
      path: '/meu-acesso'
      fullPath: '/meu-acesso'
      preLoaderRoute: typeof MeuAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primeiro-acesso': {
      id: '/primeiro-acesso'
      path: '/primeiro-acesso'
      fullPath: '/primeiro-acesso'
      preLoaderRoute: typeof PrimeiroAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sem-acesso': {
      id: '/sem-acesso'
      path: '/sem-acesso'
      fullPath: '/sem-acesso'
      preLoaderRoute: typeof SemAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/canal-confidencial': {
      id: '/_authenticated/canal-confidencial'
      path: '/canal-confidencial'
      fullPath: '/canal-confidencial'
      preLoaderRoute: typeof AuthenticatedCanalConfidencialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comunicados': {
      id: '/_authenticated/comunicados'
      path: '/comunicados'
      fullPath: '/comunicados'
      preLoaderRoute: typeof AuthenticatedComunicadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conquistas': {
      id: '/_authenticated/conquistas'
      path: '/conquistas'
      fullPath: '/conquistas'
      preLoaderRoute: typeof AuthenticatedConquistasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentos-pessoais': {
      id: '/_authenticated/documentos-pessoais'
      path: '/documentos-pessoais'
      fullPath: '/documentos-pessoais'
      preLoaderRoute: typeof AuthenticatedDocumentosPessoaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/extrato': {
      id: '/_authenticated/extrato'
      path: '/extrato'
      fullPath: '/extrato'
      preLoaderRoute: typeof AuthenticatedExtratoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feedbacks': {
      id: '/_authenticated/feedbacks'
      path: '/feedbacks'
      fullPath: '/feedbacks'
      preLoaderRoute: typeof AuthenticatedFeedbacksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funcionarios': {
      id: '/_authenticated/funcionarios'
      path: '/funcionarios'
      fullPath: '/funcionarios'
      preLoaderRoute: typeof AuthenticatedFuncionariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestao': {
      id: '/_authenticated/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof AuthenticatedGestaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/justificativas': {
      id: '/_authenticated/justificativas'
      path: '/justificativas'
      fullPath: '/justificativas'
      preLoaderRoute: typeof AuthenticatedJustificativasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacional': {
      id: '/_authenticated/operacional'
      path: '/operacional'
      fullPath: '/operacional'
      preLoaderRoute: typeof AuthenticatedOperacionalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/premios': {
      id: '/_authenticated/premios'
      path: '/premios'
      fullPath: '/premios'
      preLoaderRoute: typeof AuthenticatedPremiosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ranking': {
      id: '/_authenticated/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AuthenticatedRankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solicitacoes': {
      id: '/_authenticated/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/solicitacoes'
      preLoaderRoute: typeof AuthenticatedSolicitacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/perfil': {
      id: '/admin/perfil'
      path: '/perfil'
      fullPath: '/admin/perfil'
      preLoaderRoute: typeof AdminPerfilRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/e/$codigo': {
      id: '/e/$codigo'
      path: '/e/$codigo'
      fullPath: '/e/$codigo'
      preLoaderRoute: typeof ECodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$codigo': {
      id: '/tv/$codigo'
      path: '/tv/$codigo'
      fullPath: '/tv/$codigo'
      preLoaderRoute: typeof TvCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedCanalConfidencialRoute: typeof AuthenticatedCanalConfidencialRoute
  AuthenticatedComunicadosRoute: typeof AuthenticatedComunicadosRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedConquistasRoute: typeof AuthenticatedConquistasRoute
  AuthenticatedDocumentosPessoaisRoute: typeof AuthenticatedDocumentosPessoaisRoute
  AuthenticatedExtratoRoute: typeof AuthenticatedExtratoRoute
  AuthenticatedFeedbacksRoute: typeof AuthenticatedFeedbacksRoute
  AuthenticatedFuncionariosRoute: typeof AuthenticatedFuncionariosRoute
  AuthenticatedGestaoRoute: typeof AuthenticatedGestaoRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedJustificativasRoute: typeof AuthenticatedJustificativasRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOperacionalRoute: typeof AuthenticatedOperacionalRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPremiosRoute: typeof AuthenticatedPremiosRoute
  AuthenticatedRankingRoute: typeof AuthenticatedRankingRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedSolicitacoesRoute: typeof AuthenticatedSolicitacoesRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedCanalConfidencialRoute: AuthenticatedCanalConfidencialRoute,
  AuthenticatedComunicadosRoute: AuthenticatedComunicadosRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedConquistasRoute: AuthenticatedConquistasRoute,
  AuthenticatedDocumentosPessoaisRoute: AuthenticatedDocumentosPessoaisRoute,
  AuthenticatedExtratoRoute: AuthenticatedExtratoRoute,
  AuthenticatedFeedbacksRoute: AuthenticatedFeedbacksRoute,
  AuthenticatedFuncionariosRoute: AuthenticatedFuncionariosRoute,
  AuthenticatedGestaoRoute: AuthenticatedGestaoRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedJustificativasRoute: AuthenticatedJustificativasRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOperacionalRoute: AuthenticatedOperacionalRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPremiosRoute: AuthenticatedPremiosRoute,
  AuthenticatedRankingRoute: AuthenticatedRankingRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedSolicitacoesRoute: AuthenticatedSolicitacoesRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminPerfilRoute: typeof AdminPerfilRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminPerfilRoute: AdminPerfilRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DefinirSenhaRoute: DefinirSenhaRoute,
  MeuAcessoRoute: MeuAcessoRoute,
  PrimeiroAcessoRoute: PrimeiroAcessoRoute,
  SemAcessoRoute: SemAcessoRoute,
  ECodigoRoute: ECodigoRoute,
  TvCodigoRoute: TvCodigoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
