-- Etapa 1.9 (antiga Fase 9): agenda por loja.
-- Decisoes do Wisley em 22/09/2026, registradas em docs/PLANO_MIGRACAO.md.
--
-- - Agendamento por loja; responsavel = responsavel da loja ou outro que
--   trabalhe nela. Situacoes: Confirmado -> Realizado (pode voltar com
--   motivo) ou -> Cancelado (motivo obrigatorio, final). Nada se apaga.
-- - Pagamento: Pendente / Sinal pago / Pago, com valor opcional.
-- - A tarefa "Atender agendamento" acompanha: remarcou, muda de dia; trocou
--   o responsavel, muda de pessoa; cancelou, e encerrada.
-- - Historico de tudo (quem, quando, antes e depois), que nunca muda.
-- - Anexos no Storage, pasta privada <conta>/<loja>/<agendamento>/.
-- - Na TV so hora e tipo; nome, CPF, telefone, observacoes e valor nunca
--   saem do banco para a TV.
-- - WhatsApp (1.13): campos prontos, nada e enviado.

-- ===========================================================================
-- 1. Tipos de evento, por conta. Conta nova comeca com "Evento".
-- ===========================================================================

CREATE TABLE public.tiposevento (
  tipoeventoid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contaid      integer NOT NULL DEFAULT public.minha_conta() REFERENCES public.contas(contaid) ON DELETE RESTRICT,
  nome         varchar(100) NOT NULL CHECK (length(btrim(nome)) > 0),
  ativo        boolean NOT NULL DEFAULT true,
  criadoem     timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT tiposevento_conta_unico UNIQUE (contaid, tipoeventoid)
);
CREATE UNIQUE INDEX tiposevento_nome_por_conta ON public.tiposevento (contaid, lower(btrim(nome)));

ALTER TABLE public.tiposevento ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.tiposevento FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.tiposevento TO authenticated;
GRANT ALL ON public.tiposevento TO service_role;
CREATE POLICY tiposevento_sel ON public.tiposevento FOR SELECT TO authenticated
  USING (contaid = (select public.minha_conta()));
CREATE POLICY tiposevento_ins ON public.tiposevento FOR INSERT TO authenticated
  WITH CHECK (contaid = (select public.minha_conta_editavel()));
CREATE POLICY tiposevento_upd ON public.tiposevento FOR UPDATE TO authenticated
  USING (contaid = (select public.minha_conta_editavel())) WITH CHECK (contaid = (select public.minha_conta_editavel()));

-- Semeia o tipo generico de uma conta nova. So o servidor chama.
CREATE OR REPLACE FUNCTION public.cria_tipos_evento_padrao(p_contaid integer)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  INSERT INTO public.tiposevento (contaid, nome)
  SELECT p_contaid, 'Evento'
   WHERE NOT EXISTS (SELECT 1 FROM public.tiposevento WHERE contaid = p_contaid);
$$;

-- ===========================================================================
-- 2. Agendamentos
-- ===========================================================================

UPDATE public.agendamentos SET statusagendamento = 'Confirmado'
 WHERE statusagendamento IS NULL OR statusagendamento NOT IN ('Confirmado', 'Realizado', 'Cancelado');
UPDATE public.agendamentos SET statuspagamento = 'Pendente'
 WHERE statuspagamento IS NULL OR statuspagamento NOT IN ('Pendente', 'Sinal pago', 'Pago');

ALTER TABLE public.agendamentos
  ADD COLUMN tipoeventoid       integer,
  ADD COLUMN valor              numeric(12,2),
  ADD COLUMN aceitawhatsapp     boolean NOT NULL DEFAULT false,
  ADD COLUMN registradopor      uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  ADD COLUMN atualizadoem       timestamptz NOT NULL DEFAULT now(),
  ADD COLUMN realizadoem        timestamptz,
  ADD COLUMN realizadopor       uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  ADD COLUMN canceladoem        timestamptz,
  ADD COLUMN canceladopor       uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  ADD COLUMN motivocancelamento text;

-- As marcas do WhatsApp viram "enviada em" (usadas so na Etapa 1.13).
ALTER TABLE public.agendamentos ALTER COLUMN msgcriacaoenviada DROP DEFAULT;
ALTER TABLE public.agendamentos ALTER COLUMN msgconfirmacaoenviada DROP DEFAULT;
ALTER TABLE public.agendamentos ALTER COLUMN msgposvendaenviada DROP DEFAULT;
ALTER TABLE public.agendamentos ALTER COLUMN msgcriacaoenviada TYPE timestamptz USING NULL;
ALTER TABLE public.agendamentos ALTER COLUMN msgconfirmacaoenviada TYPE timestamptz USING NULL;
ALTER TABLE public.agendamentos ALTER COLUMN msgposvendaenviada TYPE timestamptz USING NULL;

ALTER TABLE public.agendamentos ADD CONSTRAINT agendamentos_status_valido
  CHECK (statusagendamento IN ('Confirmado', 'Realizado', 'Cancelado'));
ALTER TABLE public.agendamentos ADD CONSTRAINT agendamentos_pagamento_valido
  CHECK (statuspagamento IN ('Pendente', 'Sinal pago', 'Pago'));
ALTER TABLE public.agendamentos ADD CONSTRAINT agendamentos_valor_valido
  CHECK (valor IS NULL OR (valor >= 0 AND valor < 100000000));
ALTER TABLE public.agendamentos ADD CONSTRAINT agendamentos_cancelado_com_motivo
  CHECK (statusagendamento <> 'Cancelado' OR length(btrim(coalesce(motivocancelamento, ''))) > 0);
ALTER TABLE public.agendamentos ADD CONSTRAINT agendamentos_cpf_valido
  CHECK (cpfcliente IS NULL OR cpfcliente ~ '^[0-9]{11}$');
ALTER TABLE public.agendamentos ADD CONSTRAINT agendamentos_tipo_fk
  FOREIGN KEY (contaid, tipoeventoid) REFERENCES public.tiposevento (contaid, tipoeventoid) ON DELETE RESTRICT;
-- O responsavel (funcionarioid) trabalha na loja do agendamento.
ALTER TABLE public.agendamentos ADD CONSTRAINT agendamentos_responsavel_trabalha_na_loja
  FOREIGN KEY (funcionarioid, lojaid) REFERENCES public.funcionarioslojas (funcionarioid, lojaid) ON DELETE RESTRICT;
CREATE INDEX agendamentos_loja_data_idx ON public.agendamentos (lojaid, dataevento);

REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON public.agendamentos FROM anon, authenticated;

-- A tarefa gerada aponta para o agendamento.
ALTER TABLE public.tarefasatribuidas ADD CONSTRAINT tarefasatribuidas_agendamento_fk
  FOREIGN KEY (contaid, agendamentoid) REFERENCES public.agendamentos (contaid, agendamentoid) ON DELETE RESTRICT;

-- Historico (nunca muda nem se apaga).
CREATE TABLE public.agendamentoshistorico (
  historicoid    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contaid        integer NOT NULL DEFAULT public.minha_conta() REFERENCES public.contas(contaid) ON DELETE RESTRICT,
  lojaid         integer NOT NULL,
  agendamentoid  integer NOT NULL,
  acao           varchar(20) NOT NULL CHECK (acao IN ('criado', 'editado', 'remarcado', 'responsavel', 'pagamento',
                                                     'realizado', 'reaberto', 'cancelado', 'anexo', 'anexo_removido')),
  valoranterior  text,
  valornovo      text,
  motivo         text,
  alteradopor    uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  alteradoem     timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT agendamentoshistorico_loja_fk FOREIGN KEY (contaid, lojaid)
    REFERENCES public.lojas (contaid, lojaid) ON DELETE RESTRICT,
  CONSTRAINT agendamentoshistorico_agendamento_fk FOREIGN KEY (contaid, agendamentoid)
    REFERENCES public.agendamentos (contaid, agendamentoid) ON DELETE RESTRICT
);
CREATE INDEX agendamentoshistorico_agendamento_idx ON public.agendamentoshistorico (agendamentoid, alteradoem);

ALTER TABLE public.agendamentoshistorico ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.agendamentoshistorico FROM anon, authenticated;
GRANT SELECT ON public.agendamentoshistorico TO authenticated;
GRANT ALL ON public.agendamentoshistorico TO service_role;
CREATE POLICY agendamentoshistorico_sel ON public.agendamentoshistorico FOR SELECT TO authenticated
  USING (contaid = (select public.minha_conta()));
CREATE TRIGGER agendamentoshistorico_imutavel
  BEFORE UPDATE OR DELETE ON public.agendamentoshistorico
  FOR EACH ROW EXECUTE FUNCTION public.historico_imutavel();

-- Nada se apaga; situacao so pelas transicoes permitidas, para todo caminho.
CREATE OR REPLACE FUNCTION public.valida_agendamento()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'Agendamento não se apaga; cancele com motivo.' USING ERRCODE = 'restrict_violation';
  END IF;
  IF NEW.statusagendamento IS DISTINCT FROM OLD.statusagendamento AND NOT (
       (OLD.statusagendamento = 'Confirmado' AND NEW.statusagendamento IN ('Realizado', 'Cancelado'))
    OR (OLD.statusagendamento = 'Realizado'  AND NEW.statusagendamento = 'Confirmado')) THEN
    RAISE EXCEPTION 'Não é possível passar de "%" para "%".', OLD.statusagendamento, NEW.statusagendamento
      USING ERRCODE = 'check_violation';
  END IF;
  IF OLD.statusagendamento = 'Cancelado' THEN
    RAISE EXCEPTION 'Agendamento cancelado não muda mais.' USING ERRCODE = 'check_violation';
  END IF;
  IF NEW.contaid IS DISTINCT FROM OLD.contaid OR NEW.lojaid IS DISTINCT FROM OLD.lojaid THEN
    RAISE EXCEPTION 'O agendamento não muda de loja.' USING ERRCODE = 'restrict_violation';
  END IF;
  NEW.atualizadoem := now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER agendamentos_valida
  BEFORE UPDATE OR DELETE ON public.agendamentos
  FOR EACH ROW EXECUTE FUNCTION public.valida_agendamento();

-- A tarefa ligada a um agendamento so nasce e muda pelas funcoes da agenda
-- (senao remarcar e cancelar ficariam dessincronizados).
CREATE OR REPLACE FUNCTION public.protege_tarefa_da_agenda()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
DECLARE marca varchar(40);
BEGIN
  IF coalesce(current_setting('gamegb.agenda', true), '') = 'sim' THEN
    RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
  END IF;
  IF TG_OP = 'INSERT' THEN
    SELECT sistema INTO marca FROM public.tarefas WHERE tarefaid = NEW.tarefaid;
    IF NEW.agendamentoid IS NOT NULL OR marca = 'modelo_agendamento' THEN
      RAISE EXCEPTION 'A tarefa de atender agendamento nasce sozinha, ao criar o agendamento.' USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NEW;
  END IF;
  IF OLD.agendamentoid IS NOT NULL OR (TG_OP = 'UPDATE' AND NEW.agendamentoid IS DISTINCT FROM OLD.agendamentoid) THEN
    RAISE EXCEPTION 'Esta tarefa acompanha um agendamento: mude pela Agenda.' USING ERRCODE = 'restrict_violation';
  END IF;
  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$;

CREATE TRIGGER tarefasatribuidas_da_agenda
  BEFORE INSERT OR UPDATE OR DELETE ON public.tarefasatribuidas
  FOR EACH ROW EXECUTE FUNCTION public.protege_tarefa_da_agenda();

-- ===========================================================================
-- 3. Funcoes da agenda
-- ===========================================================================

-- Confere o responsavel: trabalha na loja (vinculo ativo) e esta ativo.
CREATE OR REPLACE FUNCTION public.responsavel_valido(p_contaid integer, p_lojaid integer, p_funcionarioid integer)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.funcionarioslojas fl
      JOIN public.funcionarios f ON f.funcionarioid = fl.funcionarioid AND f.contaid = fl.contaid
     WHERE fl.contaid = p_contaid AND fl.lojaid = p_lojaid AND fl.funcionarioid = p_funcionarioid
       AND fl.ativo AND f.ativo)
$$;

CREATE OR REPLACE FUNCTION public.registra_agenda(
  p_contaid integer, p_lojaid integer, p_agendamentoid integer, p_acao text,
  p_antes text, p_depois text, p_motivo text
)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  INSERT INTO public.agendamentoshistorico (contaid, lojaid, agendamentoid, acao, valoranterior, valornovo, motivo, alteradopor)
  VALUES (p_contaid, p_lojaid, p_agendamentoid, p_acao, p_antes, p_depois, nullif(btrim(coalesce(p_motivo, '')), ''), auth.uid())
$$;

-- Texto da tarefa: "15:00 — Aniversario". Nunca leva dados do cliente.
CREATE OR REPLACE FUNCTION public.texto_da_tarefa_agenda(p_dataevento timestamptz, p_tipo text)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = public, pg_temp
AS $$
  SELECT to_char(p_dataevento AT TIME ZONE 'America/Sao_Paulo', 'HH24:MI') || ' — ' || p_tipo
$$;

CREATE OR REPLACE FUNCTION public.so_digitos(p_texto text)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = public, pg_temp
AS $$
  SELECT nullif(regexp_replace(coalesce(p_texto, ''), '[^0-9]', '', 'g'), '')
$$;

-- A tarefa do agendamento ja foi entregue (pendente ou aprovada)?
CREATE OR REPLACE FUNCTION public.tarefa_da_agenda_entregue(p_atribuicaoid integer)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT EXISTS (SELECT 1 FROM public.entregas
                  WHERE atribuicaoid = p_atribuicaoid AND statusvalidacao IN ('Pendente', 'Aprovada'))
$$;

CREATE OR REPLACE FUNCTION public.criar_agendamento(
  p_lojaid         integer,
  p_tipoeventoid   integer,
  p_dataevento     timestamptz,
  p_nomecliente    text,
  p_cpf            text    DEFAULT NULL,
  p_telefone       text    DEFAULT NULL,
  p_observacoes    text    DEFAULT NULL,
  p_valor          numeric DEFAULT NULL,
  p_pagamento      text    DEFAULT 'Pendente',
  p_responsavelid  integer DEFAULT NULL,
  p_aceitawhatsapp boolean DEFAULT false
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_conta  integer := public.minha_conta_editavel();
  v_loja   public.lojas%ROWTYPE;
  v_tipo   text;
  v_resp   integer;
  v_cpf    text := public.so_digitos(p_cpf);
  v_tel    text := public.so_digitos(p_telefone);
  v_modelo integer;
  v_id     integer;
BEGIN
  IF v_conta IS NULL THEN
    RAISE EXCEPTION 'Sua conta não pode alterar dados no momento.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  SELECT * INTO v_loja FROM public.lojas WHERE lojaid = p_lojaid AND contaid = v_conta AND ativa;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Loja não encontrada.' USING ERRCODE = 'no_data_found';
  END IF;
  SELECT nome INTO v_tipo FROM public.tiposevento WHERE tipoeventoid = p_tipoeventoid AND contaid = v_conta AND ativo;
  IF v_tipo IS NULL THEN
    RAISE EXCEPTION 'Escolha o tipo de evento.' USING ERRCODE = 'check_violation';
  END IF;
  IF length(btrim(coalesce(p_nomecliente, ''))) = 0 THEN
    RAISE EXCEPTION 'Informe o nome do cliente.' USING ERRCODE = 'check_violation';
  END IF;
  IF p_dataevento IS NULL OR public.dia_em_sao_paulo(p_dataevento) < public.dia_em_sao_paulo(now()) THEN
    RAISE EXCEPTION 'A data do evento não pode estar no passado.' USING ERRCODE = 'check_violation';
  END IF;
  IF v_cpf IS NOT NULL AND length(v_cpf) <> 11 THEN
    RAISE EXCEPTION 'O CPF precisa ter 11 números.' USING ERRCODE = 'check_violation';
  END IF;
  IF v_tel IS NOT NULL AND length(v_tel) NOT BETWEEN 10 AND 13 THEN
    RAISE EXCEPTION 'Telefone inválido: use DDD e número.' USING ERRCODE = 'check_violation';
  END IF;
  v_resp := coalesce(p_responsavelid, v_loja.responsavelagendamentosid);
  IF v_resp IS NULL THEN
    RAISE EXCEPTION 'Escolha o responsável (a loja não tem responsável pelos agendamentos definido).' USING ERRCODE = 'check_violation';
  END IF;
  IF NOT public.responsavel_valido(v_conta, p_lojaid, v_resp) THEN
    RAISE EXCEPTION 'O responsável precisa trabalhar nesta loja.' USING ERRCODE = 'check_violation';
  END IF;

  INSERT INTO public.agendamentos (contaid, lojaid, nomecliente, cpfcliente, telefonecliente, tipoevento, tipoeventoid,
                                   dataevento, statuspagamento, valor, funcionarioid, observacoes, aceitawhatsapp, registradopor)
  VALUES (v_conta, p_lojaid, btrim(p_nomecliente), v_cpf, v_tel, v_tipo, p_tipoeventoid, p_dataevento,
          coalesce(p_pagamento, 'Pendente'), p_valor, v_resp, nullif(btrim(coalesce(p_observacoes, '')), ''),
          coalesce(p_aceitawhatsapp, false), auth.uid())
  RETURNING agendamentoid INTO v_id;

  -- A tarefa "Atender agendamento" para o responsavel, no dia do evento.
  SELECT tarefaid INTO v_modelo FROM public.tarefas WHERE contaid = v_conta AND sistema = 'modelo_agendamento';
  IF v_modelo IS NOT NULL THEN
    PERFORM set_config('gamegb.agenda', 'sim', true);
    INSERT INTO public.tarefasatribuidas (contaid, tarefaid, funcionarioid, lojaid, tipofrequencia, dataagendamento,
                                          descricaooverride, agendamentoid)
    VALUES (v_conta, v_modelo, v_resp, p_lojaid, 'Unica', p_dataevento,
            public.texto_da_tarefa_agenda(p_dataevento, v_tipo), v_id);
    PERFORM set_config('gamegb.agenda', '', true);
  END IF;

  PERFORM public.registra_agenda(v_conta, p_lojaid, v_id, 'criado', NULL,
                                 to_char(p_dataevento AT TIME ZONE 'America/Sao_Paulo', 'DD/MM/YYYY HH24:MI') || ' — ' || v_tipo, NULL);
  RETURN v_id;
END;
$$;

-- Busca o agendamento da conta, travado para mudar. Interna.
CREATE OR REPLACE FUNCTION public.agendamento_para_mudar(p_agendamentoid integer)
RETURNS public.agendamentos
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_conta integer := public.minha_conta_editavel();
  a public.agendamentos%ROWTYPE;
BEGIN
  IF v_conta IS NULL THEN
    RAISE EXCEPTION 'Sua conta não pode alterar dados no momento.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  SELECT * INTO a FROM public.agendamentos WHERE agendamentoid = p_agendamentoid AND contaid = v_conta FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Agendamento não encontrado.' USING ERRCODE = 'no_data_found';
  END IF;
  RETURN a;
END;
$$;

CREATE OR REPLACE FUNCTION public.remarcar_agendamento(p_agendamentoid integer, p_novadata timestamptz, p_motivo text DEFAULT NULL)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE a public.agendamentos%ROWTYPE; t record;
BEGIN
  a := public.agendamento_para_mudar(p_agendamentoid);
  IF a.statusagendamento <> 'Confirmado' THEN
    RAISE EXCEPTION 'Só dá para remarcar agendamento confirmado.' USING ERRCODE = 'check_violation';
  END IF;
  IF p_novadata IS NULL OR public.dia_em_sao_paulo(p_novadata) < public.dia_em_sao_paulo(now()) THEN
    RAISE EXCEPTION 'A nova data não pode estar no passado.' USING ERRCODE = 'check_violation';
  END IF;
  IF p_novadata = a.dataevento THEN
    RETURN;
  END IF;

  UPDATE public.agendamentos SET dataevento = p_novadata WHERE agendamentoid = a.agendamentoid;

  -- A tarefa vai junto, se ainda nao foi entregue.
  PERFORM set_config('gamegb.agenda', 'sim', true);
  FOR t IN SELECT atribuicaoid FROM public.tarefasatribuidas
            WHERE agendamentoid = a.agendamentoid AND datafimvigencia IS NULL LOOP
    IF NOT public.tarefa_da_agenda_entregue(t.atribuicaoid) THEN
      UPDATE public.tarefasatribuidas
         SET dataagendamento = p_novadata,
             descricaooverride = public.texto_da_tarefa_agenda(p_novadata, a.tipoevento)
       WHERE atribuicaoid = t.atribuicaoid;
    END IF;
  END LOOP;
  PERFORM set_config('gamegb.agenda', '', true);

  PERFORM public.registra_agenda(a.contaid, a.lojaid, a.agendamentoid, 'remarcado',
    to_char(a.dataevento AT TIME ZONE 'America/Sao_Paulo', 'DD/MM/YYYY HH24:MI'),
    to_char(p_novadata AT TIME ZONE 'America/Sao_Paulo', 'DD/MM/YYYY HH24:MI'), p_motivo);
END;
$$;

CREATE OR REPLACE FUNCTION public.trocar_responsavel_agendamento(p_agendamentoid integer, p_funcionarioid integer)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE a public.agendamentos%ROWTYPE; t record; v_antes text; v_depois text;
BEGIN
  a := public.agendamento_para_mudar(p_agendamentoid);
  IF a.statusagendamento <> 'Confirmado' THEN
    RAISE EXCEPTION 'Só dá para trocar o responsável de agendamento confirmado.' USING ERRCODE = 'check_violation';
  END IF;
  IF p_funcionarioid = a.funcionarioid THEN
    RETURN;
  END IF;
  IF NOT public.responsavel_valido(a.contaid, a.lojaid, p_funcionarioid) THEN
    RAISE EXCEPTION 'O responsável precisa trabalhar nesta loja.' USING ERRCODE = 'check_violation';
  END IF;
  SELECT nomecompleto INTO v_antes FROM public.funcionarios WHERE funcionarioid = a.funcionarioid;
  SELECT nomecompleto INTO v_depois FROM public.funcionarios WHERE funcionarioid = p_funcionarioid;

  UPDATE public.agendamentos SET funcionarioid = p_funcionarioid WHERE agendamentoid = a.agendamentoid;

  PERFORM set_config('gamegb.agenda', 'sim', true);
  FOR t IN SELECT atribuicaoid FROM public.tarefasatribuidas
            WHERE agendamentoid = a.agendamentoid AND datafimvigencia IS NULL LOOP
    IF NOT public.tarefa_da_agenda_entregue(t.atribuicaoid) THEN
      UPDATE public.tarefasatribuidas SET funcionarioid = p_funcionarioid WHERE atribuicaoid = t.atribuicaoid;
    END IF;
  END LOOP;
  PERFORM set_config('gamegb.agenda', '', true);

  PERFORM public.registra_agenda(a.contaid, a.lojaid, a.agendamentoid, 'responsavel', v_antes, v_depois, NULL);
END;
$$;

CREATE OR REPLACE FUNCTION public.alterar_pagamento_agendamento(p_agendamentoid integer, p_status text, p_valor numeric DEFAULT NULL)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE a public.agendamentos%ROWTYPE;
BEGIN
  a := public.agendamento_para_mudar(p_agendamentoid);
  IF a.statusagendamento = 'Cancelado' THEN
    RAISE EXCEPTION 'Agendamento cancelado não muda mais.' USING ERRCODE = 'check_violation';
  END IF;
  IF p_status NOT IN ('Pendente', 'Sinal pago', 'Pago') THEN
    RAISE EXCEPTION 'Situação de pagamento inválida.' USING ERRCODE = 'check_violation';
  END IF;
  IF p_status = a.statuspagamento AND p_valor IS NOT DISTINCT FROM a.valor THEN
    RETURN;
  END IF;
  UPDATE public.agendamentos SET statuspagamento = p_status, valor = p_valor WHERE agendamentoid = a.agendamentoid;
  PERFORM public.registra_agenda(a.contaid, a.lojaid, a.agendamentoid, 'pagamento',
    a.statuspagamento || coalesce(' (' || public.reais(a.valor) || ')', ''),
    p_status || coalesce(' (' || public.reais(p_valor) || ')', ''), NULL);
END;
$$;

-- Dados do cliente, tipo e observacoes. O historico registra que mudou,
-- sem copiar CPF nem telefone.
CREATE OR REPLACE FUNCTION public.editar_agendamento(
  p_agendamentoid integer, p_tipoeventoid integer, p_nomecliente text, p_cpf text, p_telefone text,
  p_observacoes text, p_aceitawhatsapp boolean
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  a public.agendamentos%ROWTYPE;
  v_tipo text;
  v_cpf text := public.so_digitos(p_cpf);
  v_tel text := public.so_digitos(p_telefone);
  t record;
BEGIN
  a := public.agendamento_para_mudar(p_agendamentoid);
  IF a.statusagendamento <> 'Confirmado' THEN
    RAISE EXCEPTION 'Só dá para editar agendamento confirmado.' USING ERRCODE = 'check_violation';
  END IF;
  SELECT nome INTO v_tipo FROM public.tiposevento WHERE tipoeventoid = p_tipoeventoid AND contaid = a.contaid;
  IF v_tipo IS NULL THEN
    RAISE EXCEPTION 'Escolha o tipo de evento.' USING ERRCODE = 'check_violation';
  END IF;
  IF length(btrim(coalesce(p_nomecliente, ''))) = 0 THEN
    RAISE EXCEPTION 'Informe o nome do cliente.' USING ERRCODE = 'check_violation';
  END IF;
  IF v_cpf IS NOT NULL AND length(v_cpf) <> 11 THEN
    RAISE EXCEPTION 'O CPF precisa ter 11 números.' USING ERRCODE = 'check_violation';
  END IF;
  IF v_tel IS NOT NULL AND length(v_tel) NOT BETWEEN 10 AND 13 THEN
    RAISE EXCEPTION 'Telefone inválido: use DDD e número.' USING ERRCODE = 'check_violation';
  END IF;

  UPDATE public.agendamentos
     SET tipoeventoid = p_tipoeventoid, tipoevento = v_tipo, nomecliente = btrim(p_nomecliente),
         cpfcliente = v_cpf, telefonecliente = v_tel,
         observacoes = nullif(btrim(coalesce(p_observacoes, '')), ''), aceitawhatsapp = coalesce(p_aceitawhatsapp, false)
   WHERE agendamentoid = a.agendamentoid;

  IF v_tipo IS DISTINCT FROM a.tipoevento THEN
    PERFORM set_config('gamegb.agenda', 'sim', true);
    FOR t IN SELECT atribuicaoid FROM public.tarefasatribuidas
              WHERE agendamentoid = a.agendamentoid AND datafimvigencia IS NULL LOOP
      UPDATE public.tarefasatribuidas SET descricaooverride = public.texto_da_tarefa_agenda(a.dataevento, v_tipo)
       WHERE atribuicaoid = t.atribuicaoid;
    END LOOP;
    PERFORM set_config('gamegb.agenda', '', true);
  END IF;

  PERFORM public.registra_agenda(a.contaid, a.lojaid, a.agendamentoid, 'editado',
    CASE WHEN v_tipo IS DISTINCT FROM a.tipoevento THEN a.tipoevento END,
    CASE WHEN v_tipo IS DISTINCT FROM a.tipoevento THEN v_tipo END, 'dados do agendamento alterados');
END;
$$;

CREATE OR REPLACE FUNCTION public.marcar_agendamento_realizado(p_agendamentoid integer)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE a public.agendamentos%ROWTYPE;
BEGIN
  a := public.agendamento_para_mudar(p_agendamentoid);
  IF a.statusagendamento <> 'Confirmado' THEN
    RAISE EXCEPTION 'Só agendamento confirmado pode ser marcado como realizado.' USING ERRCODE = 'check_violation';
  END IF;
  UPDATE public.agendamentos SET statusagendamento = 'Realizado', realizadoem = now(), realizadopor = auth.uid()
   WHERE agendamentoid = a.agendamentoid;
  PERFORM public.registra_agenda(a.contaid, a.lojaid, a.agendamentoid, 'realizado', 'Confirmado', 'Realizado', NULL);
END;
$$;

-- Realizado por engano volta para Confirmado, com motivo.
CREATE OR REPLACE FUNCTION public.reabrir_agendamento(p_agendamentoid integer, p_motivo text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE a public.agendamentos%ROWTYPE;
BEGIN
  a := public.agendamento_para_mudar(p_agendamentoid);
  IF a.statusagendamento <> 'Realizado' THEN
    RAISE EXCEPTION 'Só agendamento realizado pode voltar para confirmado.' USING ERRCODE = 'check_violation';
  END IF;
  IF length(btrim(coalesce(p_motivo, ''))) = 0 THEN
    RAISE EXCEPTION 'Informe o motivo.' USING ERRCODE = 'check_violation';
  END IF;
  UPDATE public.agendamentos SET statusagendamento = 'Confirmado', realizadoem = NULL, realizadopor = NULL
   WHERE agendamentoid = a.agendamentoid;
  PERFORM public.registra_agenda(a.contaid, a.lojaid, a.agendamentoid, 'reaberto', 'Realizado', 'Confirmado', p_motivo);
END;
$$;

CREATE OR REPLACE FUNCTION public.cancelar_agendamento(p_agendamentoid integer, p_motivo text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE a public.agendamentos%ROWTYPE; t record;
BEGIN
  a := public.agendamento_para_mudar(p_agendamentoid);
  IF a.statusagendamento <> 'Confirmado' THEN
    RAISE EXCEPTION 'Só dá para cancelar agendamento confirmado.' USING ERRCODE = 'check_violation';
  END IF;
  IF length(btrim(coalesce(p_motivo, ''))) = 0 THEN
    RAISE EXCEPTION 'Para cancelar, informe o motivo.' USING ERRCODE = 'check_violation';
  END IF;
  UPDATE public.agendamentos
     SET statusagendamento = 'Cancelado', canceladoem = now(), canceladopor = auth.uid(), motivocancelamento = btrim(p_motivo)
   WHERE agendamentoid = a.agendamentoid;

  -- A tarefa e encerrada (se ainda nao foi entregue).
  PERFORM set_config('gamegb.agenda', 'sim', true);
  FOR t IN SELECT atribuicaoid FROM public.tarefasatribuidas
            WHERE agendamentoid = a.agendamentoid AND datafimvigencia IS NULL LOOP
    IF NOT public.tarefa_da_agenda_entregue(t.atribuicaoid) THEN
      UPDATE public.tarefasatribuidas SET datafimvigencia = public.dia_em_sao_paulo(now())
       WHERE atribuicaoid = t.atribuicaoid;
    END IF;
  END LOOP;
  PERFORM set_config('gamegb.agenda', '', true);

  PERFORM public.registra_agenda(a.contaid, a.lojaid, a.agendamentoid, 'cancelado', 'Confirmado', 'Cancelado', p_motivo);
END;
$$;

-- Agendamentos confirmados perto do horario (aviso, sem bloquear).
CREATE OR REPLACE FUNCTION public.conflitos_agendamento(p_lojaid integer, p_dataevento timestamptz, p_ignorar integer DEFAULT NULL)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
  SELECT coalesce(jsonb_agg(jsonb_build_object('quando', dataevento, 'tipo', tipoevento) ORDER BY dataevento), '[]'::jsonb)
    FROM public.agendamentos
   WHERE lojaid = p_lojaid AND statusagendamento = 'Confirmado'
     AND (p_ignorar IS NULL OR agendamentoid <> p_ignorar)
     AND dataevento BETWEEN p_dataevento - interval '2 hours' AND p_dataevento + interval '2 hours'
$$;

-- ===========================================================================
-- 4. Anexos: Storage privado, pasta <conta>/<loja>/<agendamento>/
-- ===========================================================================

INSERT INTO storage.buckets (id, name, public) VALUES ('agendamentos', 'agendamentos', false)
ON CONFLICT (id) DO NOTHING;

-- No Supabase de verdade o bucket aceita limite de tamanho e de tipo.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns
              WHERE table_schema = 'storage' AND table_name = 'buckets' AND column_name = 'file_size_limit') THEN
    EXECUTE $q$UPDATE storage.buckets
                  SET file_size_limit = 10485760,
                      allowed_mime_types = ARRAY['application/pdf', 'image/jpeg', 'image/png']
                WHERE id = 'agendamentos'$q$;
  END IF;
END $$;

-- A pasta e <conta>/<loja>/<agendamento>/...: o agendamento tem de ser
-- daquela loja e daquela conta.
CREATE OR REPLACE FUNCTION public.pasta_de_agendamento_minha(p_nome text, p_editavel boolean)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.agendamentos a
     WHERE a.contaid = CASE WHEN p_editavel THEN public.minha_conta_editavel() ELSE public.minha_conta() END
       AND split_part(p_nome, '/', 1) = a.contaid::text
       AND split_part(p_nome, '/', 2) = a.lojaid::text
       AND split_part(p_nome, '/', 3) = a.agendamentoid::text
       AND split_part(p_nome, '/', 4) <> '')
$$;

CREATE POLICY agendamentos_arq_sel ON storage.objects FOR SELECT TO authenticated
  USING (bucket_id = 'agendamentos' AND split_part(name, '/', 1) = (select public.minha_conta())::text
         AND public.pasta_de_agendamento_minha(name, false));
CREATE POLICY agendamentos_arq_ins ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'agendamentos' AND split_part(name, '/', 1) = (select public.minha_conta_editavel())::text
              AND public.pasta_de_agendamento_minha(name, true));
CREATE POLICY agendamentos_arq_del ON storage.objects FOR DELETE TO authenticated
  USING (bucket_id = 'agendamentos' AND split_part(name, '/', 1) = (select public.minha_conta_editavel())::text
         AND public.pasta_de_agendamento_minha(name, true));

CREATE TABLE public.agendamentosanexos (
  anexoid        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contaid        integer NOT NULL DEFAULT public.minha_conta() REFERENCES public.contas(contaid) ON DELETE RESTRICT,
  lojaid         integer NOT NULL,
  agendamentoid  integer NOT NULL,
  caminho        text    NOT NULL UNIQUE,
  nomearquivo    varchar(200) NOT NULL,
  tipoarquivo    varchar(50) NOT NULL CHECK (tipoarquivo IN ('application/pdf', 'image/jpeg', 'image/png')),
  tamanho        integer NOT NULL CHECK (tamanho > 0 AND tamanho <= 10485760),
  enviadopor     uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  enviadoem      timestamptz NOT NULL DEFAULT now(),
  removidoem     timestamptz,
  removidopor    uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  CONSTRAINT agendamentosanexos_loja_fk FOREIGN KEY (contaid, lojaid)
    REFERENCES public.lojas (contaid, lojaid) ON DELETE RESTRICT,
  CONSTRAINT agendamentosanexos_agendamento_fk FOREIGN KEY (contaid, agendamentoid)
    REFERENCES public.agendamentos (contaid, agendamentoid) ON DELETE RESTRICT
);
CREATE INDEX agendamentosanexos_agendamento_idx ON public.agendamentosanexos (agendamentoid);

ALTER TABLE public.agendamentosanexos ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.agendamentosanexos FROM anon, authenticated;
GRANT SELECT ON public.agendamentosanexos TO authenticated;
GRANT ALL ON public.agendamentosanexos TO service_role;
CREATE POLICY agendamentosanexos_sel ON public.agendamentosanexos FOR SELECT TO authenticated
  USING (contaid = (select public.minha_conta()));

-- Registra o anexo depois do envio ao Storage (o arquivo tem de estar na
-- pasta certa e existir).
CREATE OR REPLACE FUNCTION public.registrar_anexo_agendamento(
  p_agendamentoid integer, p_caminho text, p_nomearquivo text, p_tipo text, p_tamanho integer
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE a public.agendamentos%ROWTYPE; v_id integer;
BEGIN
  a := public.agendamento_para_mudar(p_agendamentoid);
  IF a.statusagendamento = 'Cancelado' THEN
    RAISE EXCEPTION 'Agendamento cancelado não muda mais.' USING ERRCODE = 'check_violation';
  END IF;
  IF split_part(p_caminho, '/', 1) <> a.contaid::text OR split_part(p_caminho, '/', 2) <> a.lojaid::text
     OR split_part(p_caminho, '/', 3) <> a.agendamentoid::text OR split_part(p_caminho, '/', 4) = '' THEN
    RAISE EXCEPTION 'Arquivo fora da pasta do agendamento.' USING ERRCODE = 'check_violation';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM storage.objects WHERE bucket_id = 'agendamentos' AND name = p_caminho) THEN
    RAISE EXCEPTION 'Arquivo não encontrado. Envie de novo.' USING ERRCODE = 'no_data_found';
  END IF;
  INSERT INTO public.agendamentosanexos (contaid, lojaid, agendamentoid, caminho, nomearquivo, tipoarquivo, tamanho, enviadopor)
  VALUES (a.contaid, a.lojaid, a.agendamentoid, p_caminho, left(btrim(p_nomearquivo), 200), p_tipo, p_tamanho, auth.uid())
  RETURNING anexoid INTO v_id;
  PERFORM public.registra_agenda(a.contaid, a.lojaid, a.agendamentoid, 'anexo', NULL, left(btrim(p_nomearquivo), 200), NULL);
  RETURN v_id;
END;
$$;

-- Marca o anexo como removido (a tela apaga o arquivo do Storage em seguida).
CREATE OR REPLACE FUNCTION public.remover_anexo_agendamento(p_anexoid integer)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE v_conta integer := public.minha_conta_editavel(); x public.agendamentosanexos%ROWTYPE;
BEGIN
  IF v_conta IS NULL THEN
    RAISE EXCEPTION 'Sua conta não pode alterar dados no momento.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  SELECT * INTO x FROM public.agendamentosanexos WHERE anexoid = p_anexoid AND contaid = v_conta FOR UPDATE;
  IF NOT FOUND OR x.removidoem IS NOT NULL THEN
    RAISE EXCEPTION 'Anexo não encontrado.' USING ERRCODE = 'no_data_found';
  END IF;
  UPDATE public.agendamentosanexos SET removidoem = now(), removidopor = auth.uid() WHERE anexoid = p_anexoid;
  PERFORM public.registra_agenda(x.contaid, x.lojaid, x.agendamentoid, 'anexo_removido', x.nomearquivo, NULL, NULL);
  RETURN x.caminho;
END;
$$;

-- ===========================================================================
-- 5. Proximos agendamentos no painel (logado: hora, tipo e primeiro nome)
--    e na TV (so hora e tipo). Interna (chamada pelo montar_painel).
-- ===========================================================================

CREATE OR REPLACE FUNCTION public.agenda_para_painel(p_contaid integer, p_lojaid integer, p_tv boolean)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT coalesce(jsonb_agg(
           CASE WHEN p_tv
                THEN jsonb_build_object('quando', dataevento, 'tipo', tipoevento)
                ELSE jsonb_build_object('quando', dataevento, 'tipo', tipoevento,
                                        'cliente', split_part(btrim(nomecliente), ' ', 1))
           END ORDER BY dataevento), '[]'::jsonb)
    FROM (
      SELECT dataevento, tipoevento, nomecliente
        FROM public.agendamentos
       WHERE contaid = p_contaid AND lojaid = p_lojaid AND statusagendamento = 'Confirmado'
         AND dataevento >= now() - interval '1 hour'
       ORDER BY dataevento
       LIMIT CASE WHEN p_tv THEN 8 ELSE 5 END
    ) s
$$;

-- ===========================================================================
-- 6. Painel da loja e TV ganham os proximos agendamentos (copia da versao
--    anterior do montar_painel com uma chave a mais).
-- ===========================================================================

CREATE OR REPLACE FUNCTION public.montar_painel(p_contaid integer, p_lojaid integer, p_tv boolean)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_hoje       date := public.dia_em_sao_paulo(now());
  v_loja       text;
  v_dia        jsonb;
  v_validacao  jsonb;
  v_pendentes  integer;
  v_podio      jsonb;
  v_atividade  jsonb;
BEGIN
  SELECT nome INTO v_loja FROM public.lojas WHERE lojaid = p_lojaid AND contaid = p_contaid;
  IF NOT FOUND THEN
    RETURN NULL;
  END IF;

  -- Tarefas do dia e a situacao de cada uma hoje.
  WITH dia AS (
    SELECT t.titulo,
           t.pontos,
           CASE WHEN p_tv THEN public.nome_curto(f.nomecompleto) ELSE f.nomecompleto END AS pessoa,
           (ta.tipofrequencia = 'Unica' AND ta.dataagendamento IS NOT NULL
            AND public.dia_em_sao_paulo(ta.dataagendamento) < v_hoje) AS atrasada,
           (SELECT e.statusvalidacao
              FROM public.entregas e
             WHERE e.atribuicaoid = ta.atribuicaoid
               AND e.statusvalidacao IN ('Pendente', 'Aprovada')
               AND public.dia_em_sao_paulo(e.dataenvio) = v_hoje
             ORDER BY e.entregaid DESC
             LIMIT 1) AS situacao
      FROM public.tarefasatribuidas ta
      JOIN public.tarefas t            ON t.tarefaid = ta.tarefaid
      JOIN public.funcionarios f       ON f.funcionarioid = ta.funcionarioid
      JOIN public.funcionarioslojas fl ON fl.funcionarioid = ta.funcionarioid AND fl.lojaid = ta.lojaid
     WHERE ta.contaid = p_contaid
       AND ta.lojaid = p_lojaid
       AND ta.datafimvigencia IS NULL
       AND f.ativo AND fl.ativo AND coalesce(t.ativa, true)
       AND public.tarefa_cai_no_dia(ta.tipofrequencia, ta.valorfrequencia, ta.dataagendamento, v_hoje)
       -- Justificada como "nao se aplica" (pendente ou aceita) nao e tarefa de hoje.
       AND NOT public.tem_justificativa(ta.atribuicaoid, ta.tipofrequencia, v_hoje, false)
       -- Unica entregue num dia anterior ja nao e tarefa de hoje.
       AND NOT (ta.tipofrequencia = 'Unica' AND EXISTS (
             SELECT 1 FROM public.entregas e2
              WHERE e2.atribuicaoid = ta.atribuicaoid
                AND e2.statusvalidacao IN ('Pendente', 'Aprovada')
                AND public.dia_em_sao_paulo(e2.dataenvio) < v_hoje))
  )
  SELECT jsonb_build_object(
           'total',       count(*),
           'aprovadas',   count(*) FILTER (WHERE situacao = 'Aprovada'),
           'emvalidacao', count(*) FILTER (WHERE situacao = 'Pendente'),
           'parafazer',   coalesce(
                            jsonb_agg(
                              jsonb_build_object('titulo', titulo, 'pessoa', pessoa,
                                                 'pontos', pontos, 'atrasada', atrasada)
                              ORDER BY atrasada DESC, pessoa, titulo
                            ) FILTER (WHERE situacao IS NULL),
                            '[]'::jsonb))
    INTO v_dia
    FROM dia;

  -- Em validacao: todas as pendentes da loja, de qualquer dia.
  SELECT count(*) INTO v_pendentes
    FROM public.entregas
   WHERE contaid = p_contaid AND lojaid = p_lojaid AND statusvalidacao = 'Pendente';

  SELECT coalesce(jsonb_agg(
           jsonb_build_object('titulo', titulo, 'pessoa', pessoa, 'pontos', pontos,
                              'enviadaem', dataenvio, 'dehoje', dehoje)
           ORDER BY dataenvio), '[]'::jsonb)
    INTO v_validacao
    FROM (
      SELECT t.titulo, t.pontos, e.dataenvio,
             CASE WHEN p_tv THEN public.nome_curto(f.nomecompleto) ELSE f.nomecompleto END AS pessoa,
             public.dia_em_sao_paulo(e.dataenvio) = v_hoje AS dehoje
        FROM public.entregas e
        JOIN public.tarefas t      ON t.tarefaid = e.tarefaid
        JOIN public.funcionarios f ON f.funcionarioid = e.funcionarioid
       WHERE e.contaid = p_contaid AND e.lojaid = p_lojaid AND e.statusvalidacao = 'Pendente'
       ORDER BY e.dataenvio
       LIMIT 50
    ) s;

  -- Podio do dia: pontos aprovados hoje na loja.
  SELECT coalesce(jsonb_agg(jsonb_build_object('pessoa', pessoa, 'pontos', pontos)
                            ORDER BY pontos DESC, pessoa), '[]'::jsonb)
    INTO v_podio
    FROM (
      SELECT CASE WHEN p_tv THEN public.nome_curto(f.nomecompleto) ELSE f.nomecompleto END AS pessoa,
             sum(e.pontosganhos)::integer AS pontos
        FROM public.entregas e
        JOIN public.funcionarios f ON f.funcionarioid = e.funcionarioid
       WHERE e.contaid = p_contaid AND e.lojaid = p_lojaid
         AND e.statusvalidacao = 'Aprovada'
         AND public.dia_em_sao_paulo(e.dataaprovacao) = v_hoje
       GROUP BY f.funcionarioid, f.nomecompleto
       ORDER BY sum(e.pontosganhos) DESC, f.nomecompleto
       LIMIT 3
    ) s;

  -- Atividade recente: as ultimas aprovacoes do dia.
  SELECT coalesce(jsonb_agg(jsonb_build_object('titulo', titulo, 'pessoa', pessoa,
                                               'pontos', pontos, 'aprovadaem', dataaprovacao)
                            ORDER BY dataaprovacao DESC), '[]'::jsonb)
    INTO v_atividade
    FROM (
      SELECT t.titulo, e.pontosganhos AS pontos, e.dataaprovacao,
             CASE WHEN p_tv THEN public.nome_curto(f.nomecompleto) ELSE f.nomecompleto END AS pessoa
        FROM public.entregas e
        JOIN public.tarefas t      ON t.tarefaid = e.tarefaid
        JOIN public.funcionarios f ON f.funcionarioid = e.funcionarioid
       WHERE e.contaid = p_contaid AND e.lojaid = p_lojaid
         AND e.statusvalidacao = 'Aprovada'
         AND public.dia_em_sao_paulo(e.dataaprovacao) = v_hoje
       ORDER BY e.dataaprovacao DESC
       LIMIT 10
    ) s;

  RETURN jsonb_build_object(
    'loja',         v_loja,
    'hoje',         v_hoje,
    'atualizadoem', now(),
    'progresso',    jsonb_build_object('total',       v_dia->'total',
                                       'aprovadas',   v_dia->'aprovadas',
                                       'emvalidacao', v_dia->'emvalidacao'),
    'parafazer',    v_dia->'parafazer',
    'emvalidacao',  v_validacao,
    'pendentes',    v_pendentes,
    'podio',        v_podio,
    'atividade',    v_atividade,
    'meta',         public.meta_para_painel(p_contaid, p_lojaid, p_tv),
    'agenda',       public.agenda_para_painel(p_contaid, p_lojaid, p_tv)
  );
END;
$$;

-- ===========================================================================
-- 7. Permissoes (negadas por padrao).
-- ===========================================================================

REVOKE EXECUTE ON FUNCTION
  public.cria_tipos_evento_padrao(integer),
  public.responsavel_valido(integer, integer, integer),
  public.registra_agenda(integer, integer, integer, text, text, text, text),
  public.tarefa_da_agenda_entregue(integer),
  public.agendamento_para_mudar(integer),
  public.agenda_para_painel(integer, integer, boolean),
  public.montar_painel(integer, integer, boolean)
FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION
  public.criar_agendamento(integer, integer, timestamptz, text, text, text, text, numeric, text, integer, boolean),
  public.remarcar_agendamento(integer, timestamptz, text),
  public.trocar_responsavel_agendamento(integer, integer),
  public.alterar_pagamento_agendamento(integer, text, numeric),
  public.editar_agendamento(integer, integer, text, text, text, text, boolean),
  public.marcar_agendamento_realizado(integer),
  public.reabrir_agendamento(integer, text),
  public.cancelar_agendamento(integer, text),
  public.conflitos_agendamento(integer, timestamptz, integer),
  public.registrar_anexo_agendamento(integer, text, text, text, integer),
  public.remover_anexo_agendamento(integer),
  public.pasta_de_agendamento_minha(text, boolean),
  public.texto_da_tarefa_agenda(timestamptz, text),
  public.so_digitos(text)
TO authenticated;

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO service_role;
