-- Etapa 1.12, parte A (3/3): PIN do tablet, travas de tentativa e criação dos
-- acessos.
--
-- Como o PIN é guardado (decisão do Wisley, 23/09/2026):
--   * 6 dígitos, único na conta inteira (cobre quem trabalha em várias lojas).
--   * O banco NUNCA vê o número. Quem embaralha é o servidor, com HMAC e uma
--     chave que só ele tem (STGAME_PIN_PEPPER, fora do banco). Aqui só entra o
--     resultado embaralhado, de 64 letras.
--   * Por ser sempre o mesmo resultado para o mesmo número, o banco acha a
--     pessoa DIRETO pelo índice: a janela do tablet responde igual com 5 ou
--     500 pessoas. Comparar uma a uma (como se faz com senha) ficaria lento.
--   * Quem tiver só o banco não consegue testar número nenhum: falta a chave.
--
-- Tentativas: toda tentativa de senha ou de PIN fica registrada, SEM o que foi
-- digitado. Nem o CPF entra: guarda-se o mesmo embaralhado do servidor.

-- ---------------------------------------------------------------------------
-- 1. O PIN na pessoa
-- ---------------------------------------------------------------------------
ALTER TABLE public.funcionarios ADD COLUMN pinhash char(64);
COMMENT ON COLUMN public.funcionarios.pinhash IS
  'PIN do tablet, embaralhado pelo servidor (HMAC com chave fora do banco). O número nunca é guardado.';

-- Único entre as pessoas ativas da conta. A tela nunca diz de quem é o número
-- repetido: só "escolha outro número".
CREATE UNIQUE INDEX funcionarios_pin_unico_na_conta
  ON public.funcionarios (contaid, pinhash) WHERE pinhash IS NOT NULL AND ativo;

-- Nem o master escreve o PIN direto: em funcionarios o UPDATE é liberado
-- coluna por coluna, e coluna nova nasce sem permissão. O PIN entra só pelas
-- funções abaixo.
-- O master consegue LER esta coluna (o SELECT da tabela é dele), e tudo bem:
-- sem a chave do servidor, o embaralhado não vira número nenhum.

-- ---------------------------------------------------------------------------
-- 2. Registro de tentativas
-- ---------------------------------------------------------------------------
CREATE TABLE public.tentativasacesso (
  tentativaid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Vazio só nas tentativas de senha do master, quando o e-mail digitado
  -- ainda não achou conta nenhuma (a tabela é interna: ninguém a lê pelo
  -- navegador, e nada dela sai para as telas).
  contaid     integer REFERENCES public.contas (contaid) ON DELETE RESTRICT,
  tipo        varchar(10) NOT NULL CHECK (tipo IN ('senha', 'pin')),
  chave       char(64) NOT NULL,
  origem      varchar(40) NOT NULL,
  sucesso     boolean NOT NULL,
  em          timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.tentativasacesso IS
  'Tentativas de entrar (senha) e de usar o PIN. Nunca guarda o que foi digitado: "chave" é o CPF/e-mail embaralhado pelo servidor.';
CREATE INDEX tentativasacesso_chave_idx  ON public.tentativasacesso (contaid, tipo, chave, em DESC);
CREATE INDEX tentativasacesso_origem_idx ON public.tentativasacesso (contaid, tipo, origem, em DESC);

ALTER TABLE public.tentativasacesso ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.tentativasacesso FROM anon, authenticated;
GRANT ALL ON public.tentativasacesso TO service_role;

-- ---------------------------------------------------------------------------
-- 3. Trava: 5 erros seguidos
-- ---------------------------------------------------------------------------
-- PIN: 5 erros em 1 minuto travam a janela DAQUELE tablet. Num PIN errado não
-- existe pessoa identificada, então a conta é por tablet — e um acerto zera.
-- Senha: 5 erros em 15 minutos travam, contados pelo CPF/e-mail E pela origem
-- (só trocar de CPF na mesma tela não adianta).
CREATE OR REPLACE FUNCTION public.acesso_travado(p_contaid integer, p_tipo text, p_chave text, p_origem text)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SET search_path = public, pg_temp
AS $$
DECLARE
  v_janela interval := CASE WHEN p_tipo = 'pin' THEN interval '1 minute' ELSE interval '15 minutes' END;
  v_erros  integer;
BEGIN
  IF NOT public.bot_contexto_confiavel() THEN
    RAISE EXCEPTION 'Só o servidor confere a trava de acesso.' USING ERRCODE = 'insufficient_privilege';
  END IF;

  -- Erros desta origem desde o último acerto dela.
  SELECT count(*) INTO v_erros FROM public.tentativasacesso t
   WHERE t.contaid IS NOT DISTINCT FROM p_contaid AND t.tipo = p_tipo AND t.origem = p_origem AND NOT t.sucesso
     AND t.em > now() - v_janela
     AND t.em > coalesce((SELECT max(s.em) FROM public.tentativasacesso s
                           WHERE s.contaid IS NOT DISTINCT FROM p_contaid AND s.tipo = p_tipo
                             AND s.origem = p_origem AND s.sucesso),
                         '-infinity'::timestamptz);
  IF v_erros >= 5 THEN
    RETURN true;
  END IF;

  IF p_tipo = 'pin' THEN
    RETURN false;
  END IF;

  -- Senha: também pelo CPF/e-mail, para não bastar trocar de aparelho.
  SELECT count(*) INTO v_erros FROM public.tentativasacesso t
   WHERE t.contaid IS NOT DISTINCT FROM p_contaid AND t.tipo = p_tipo AND t.chave = p_chave AND NOT t.sucesso
     AND t.em > now() - v_janela
     AND t.em > coalesce((SELECT max(s.em) FROM public.tentativasacesso s
                           WHERE s.contaid IS NOT DISTINCT FROM p_contaid AND s.tipo = p_tipo
                             AND s.chave = p_chave AND s.sucesso),
                         '-infinity'::timestamptz);
  RETURN v_erros >= 5;
END;
$$;

CREATE OR REPLACE FUNCTION public.registrar_tentativa(p_contaid integer, p_tipo text, p_chave text,
                                                      p_origem text, p_sucesso boolean)
RETURNS void
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
BEGIN
  IF NOT public.bot_contexto_confiavel() THEN
    RAISE EXCEPTION 'Só o servidor registra tentativa de acesso.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  INSERT INTO public.tentativasacesso (contaid, tipo, chave, origem, sucesso)
  VALUES (p_contaid, p_tipo, left(coalesce(p_chave, ''), 64), left(coalesce(p_origem, 'app'), 40), p_sucesso);
  -- Não vira histórico: o que passou de 7 dias sai.
  DELETE FROM public.tentativasacesso WHERE em < now() - interval '7 days';
END;
$$;

-- ---------------------------------------------------------------------------
-- 4. Criar e mexer nos acessos (só pelo servidor)
-- ---------------------------------------------------------------------------
-- O servidor cria o login no Supabase Auth e chama estas funções para amarrar
-- o login à conta. Elas conferem tudo de novo do lado do banco.
CREATE OR REPLACE FUNCTION public.criar_acesso_loja(p_contaid integer, p_lojaid integer, p_userid uuid, p_quem uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF NOT public.bot_contexto_confiavel() THEN
    RAISE EXCEPTION 'Só o servidor cria acesso.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.lojas WHERE contaid = p_contaid AND lojaid = p_lojaid AND ativa) THEN
    RAISE EXCEPTION 'Loja não encontrada nesta conta.' USING ERRCODE = 'no_data_found';
  END IF;
  INSERT INTO public.contasusuarios (contaid, userid, papel, lojaid, criadopor)
  VALUES (p_contaid, p_userid, 'loja', p_lojaid, p_quem);
END;
$$;

CREATE OR REPLACE FUNCTION public.criar_acesso_colaborador(p_contaid integer, p_funcionarioid integer,
                                                           p_userid uuid, p_pinhash text, p_quem uuid)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE v_compin boolean := true;
BEGIN
  IF NOT public.bot_contexto_confiavel() THEN
    RAISE EXCEPTION 'Só o servidor cria acesso.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.funcionarios
                  WHERE contaid = p_contaid AND funcionarioid = p_funcionarioid AND ativo AND cpf IS NOT NULL) THEN
    RAISE EXCEPTION 'Pessoa não encontrada, inativa ou sem CPF.' USING ERRCODE = 'no_data_found';
  END IF;

  INSERT INTO public.contasusuarios (contaid, userid, papel, funcionarioid, criadopor)
  VALUES (p_contaid, p_userid, 'colaborador', p_funcionarioid, p_quem);

  -- O PIN inicial são os 6 primeiros dígitos do CPF. Se outra pessoa da conta
  -- já usa esse número, a pessoa entra SEM PIN e o gestor vê "PIN pendente".
  BEGIN
    UPDATE public.funcionarios
       SET senhaprovisoria = true, pinprovisorio = true, pinhash = left(p_pinhash, 64)
     WHERE contaid = p_contaid AND funcionarioid = p_funcionarioid;
  EXCEPTION WHEN unique_violation THEN
    v_compin := false;
    UPDATE public.funcionarios
       SET senhaprovisoria = true, pinprovisorio = true, pinhash = NULL
     WHERE contaid = p_contaid AND funcionarioid = p_funcionarioid;
  END;
  RETURN v_compin;
END;
$$;

-- A pessoa escolhe o PIN dela (ou o gestor redefine para o inicial).
CREATE OR REPLACE FUNCTION public.definir_pin(p_contaid integer, p_funcionarioid integer,
                                              p_pinhash text, p_provisorio boolean DEFAULT false)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF NOT public.bot_contexto_confiavel() THEN
    RAISE EXCEPTION 'Só o servidor define PIN.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  UPDATE public.funcionarios
     SET pinhash = left(p_pinhash, 64), pinprovisorio = coalesce(p_provisorio, false)
   WHERE contaid = p_contaid AND funcionarioid = p_funcionarioid AND ativo;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Pessoa não encontrada.' USING ERRCODE = 'no_data_found';
  END IF;
EXCEPTION WHEN unique_violation THEN
  -- Nunca dizer de quem é o número.
  RAISE EXCEPTION 'Escolha outro número.' USING ERRCODE = 'unique_violation';
END;
$$;

CREATE OR REPLACE FUNCTION public.marcar_senha_trocada(p_contaid integer, p_funcionarioid integer)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF NOT public.bot_contexto_confiavel() THEN
    RAISE EXCEPTION 'Só o servidor muda a marca de senha.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  UPDATE public.funcionarios
     SET senhaprovisoria = false,
         primeiroacessoem = coalesce(primeiroacessoem, now())
   WHERE contaid = p_contaid AND funcionarioid = p_funcionarioid;
END;
$$;

-- "Redefinir acesso" na Equipe: senha e PIN voltam para os 6 primeiros dígitos
-- do CPF, com registro de quem redefiniu e quando. Quem confere se p_quem é o
-- master é a função de servidor, com o token de quem pediu.
CREATE OR REPLACE FUNCTION public.redefinir_acesso(p_contaid integer, p_funcionarioid integer,
                                                   p_pinhash text, p_quem uuid)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE v_compin boolean := true;
BEGIN
  IF NOT public.bot_contexto_confiavel() THEN
    RAISE EXCEPTION 'Só o servidor redefine acesso.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.funcionarios
                  WHERE contaid = p_contaid AND funcionarioid = p_funcionarioid AND ativo) THEN
    RAISE EXCEPTION 'Pessoa não encontrada.' USING ERRCODE = 'no_data_found';
  END IF;

  BEGIN
    UPDATE public.funcionarios
       SET senhaprovisoria = true, pinprovisorio = true, pinhash = left(p_pinhash, 64),
           acessoredefinidoem = now(), acessoredefinidopor = p_quem
     WHERE contaid = p_contaid AND funcionarioid = p_funcionarioid AND ativo;
  EXCEPTION WHEN unique_violation THEN
    -- O PIN inicial já é de outra pessoa: fica sem PIN, como pendente.
    v_compin := false;
    UPDATE public.funcionarios
       SET senhaprovisoria = true, pinprovisorio = true, pinhash = NULL,
           acessoredefinidoem = now(), acessoredefinidopor = p_quem
     WHERE contaid = p_contaid AND funcionarioid = p_funcionarioid AND ativo;
  END;
  RETURN v_compin;
END;
$$;

-- Situação do acesso de cada pessoa, para a tela Equipe. Não devolve o PIN
-- nem o CPF: só as marcas.
CREATE OR REPLACE FUNCTION public.situacao_dos_acessos()
RETURNS TABLE (funcionarioid integer, temacesso boolean, nuncaentrou boolean,
               senhaprovisoria boolean, pinprovisorio boolean, sempin boolean,
               redefinidoem timestamptz)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT f.funcionarioid,
         cu.userid IS NOT NULL,
         cu.userid IS NOT NULL AND f.primeiroacessoem IS NULL,
         f.senhaprovisoria,
         f.pinprovisorio,
         f.pinhash IS NULL,
         f.acessoredefinidoem
    FROM public.funcionarios f
    LEFT JOIN public.contasusuarios cu
           ON cu.contaid = f.contaid AND cu.funcionarioid = f.funcionarioid AND cu.papel = 'colaborador'
   WHERE f.contaid = (select public.minha_conta()) AND (select public.sou_master())
$$;

-- ---------------------------------------------------------------------------
-- 5. Permissões
-- ---------------------------------------------------------------------------
DO $$
DECLARE f text;
BEGIN
  -- Recebem conta/pessoa por parâmetro: só o servidor, nunca o navegador.
  FOREACH f IN ARRAY ARRAY[
    'public.acesso_travado(integer, text, text, text)',
    'public.registrar_tentativa(integer, text, text, text, boolean)',
    'public.criar_acesso_loja(integer, integer, uuid, uuid)',
    'public.criar_acesso_colaborador(integer, integer, uuid, text, uuid)',
    'public.definir_pin(integer, integer, text, boolean)',
    'public.marcar_senha_trocada(integer, integer)',
    'public.redefinir_acesso(integer, integer, text, uuid)'
  ] LOOP
    EXECUTE format('REVOKE ALL ON FUNCTION %s FROM public, anon, authenticated', f);
    EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO service_role', f);
  END LOOP;
END $$;

-- Fala só da própria conta e só para o master: pode ir para a tela.
REVOKE ALL ON FUNCTION public.situacao_dos_acessos() FROM public, anon;
GRANT  EXECUTE ON FUNCTION public.situacao_dos_acessos() TO authenticated;
