-- Fase 6: painel operacional da loja, resumo das lojas e Modo TV.
-- Decisoes do Wisley em 21/09/2026, registradas em docs/PLANO_MIGRACAO.md.

-- ===========================================================================
-- 1. Nome curto para a TV: "Ana Souza" -> "Ana S."
--    A TV fica a vista dos clientes da loja (LGPD).
-- ===========================================================================

CREATE OR REPLACE FUNCTION public.nome_curto(p_nome text)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = public, pg_temp
AS $$
  SELECT CASE
           WHEN coalesce(array_length(p, 1), 0) = 0 OR p[1] = '' THEN ''
           WHEN array_length(p, 1) = 1 THEN p[1]
           ELSE p[1] || ' ' || upper(left(p[array_length(p, 1)], 1)) || '.'
         END
  FROM (SELECT regexp_split_to_array(btrim(coalesce(p_nome, '')), '\s+') AS p) x
$$;

-- ===========================================================================
-- 2. Links de TV (nivel loja)
--    O banco guarda so a "impressao digital" (sha256) do codigo. O codigo em
--    si aparece uma unica vez, na criacao.
-- ===========================================================================

CREATE TABLE public.linkstv (
  linktvid   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contaid    integer NOT NULL DEFAULT public.minha_conta() REFERENCES public.contas(contaid) ON DELETE RESTRICT,
  lojaid     integer NOT NULL,
  nome       varchar(100) NOT NULL,
  tokenhash  char(64) NOT NULL UNIQUE,
  criadoem   timestamptz NOT NULL DEFAULT now(),
  criadopor  uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  revogadoem timestamptz,
  ultimouso  timestamptz,
  CONSTRAINT linkstv_loja_fk FOREIGN KEY (contaid, lojaid)
    REFERENCES public.lojas (contaid, lojaid) ON DELETE RESTRICT
);

CREATE INDEX linkstv_contaid_idx ON public.linkstv (contaid);
CREATE INDEX linkstv_lojaid_idx  ON public.linkstv (lojaid);

ALTER TABLE public.linkstv ENABLE ROW LEVEL SECURITY;

-- O dono le os proprios links, mas nunca a impressao digital, e so cria e
-- revoga pelas funcoes abaixo.
REVOKE ALL ON public.linkstv FROM anon, authenticated;
GRANT SELECT (linktvid, contaid, lojaid, nome, criadoem, revogadoem, ultimouso)
  ON public.linkstv TO authenticated;
GRANT ALL ON public.linkstv TO service_role;

CREATE POLICY linkstv_sel ON public.linkstv FOR SELECT TO authenticated
  USING (contaid = (select public.minha_conta()));

-- ===========================================================================
-- 3. Os dados do painel de uma loja. Uma so fonte para o painel logado, a TV
--    e o resumo da Gestao, para os tres nunca discordarem.
--
--    Nao devolve NENHUM id, foto, observacao, telefone ou CPF: so nomes,
--    titulos de tarefa, pontos e horarios. No modo TV, os nomes vem curtos.
--
--    Barra do dia (decisao de 21/09/2026):
--      total        = atribuicoes da loja que caem hoje (e Unicas atrasadas),
--                     de pessoas ativas que continuam na loja;
--      aprovadas    = entregues HOJE e aprovadas;
--      emvalidacao  = entregues HOJE e ainda pendentes;
--      sem bonus (bonus nao tem atribuicao); recusada/estornada volta a fazer.
--    A coluna "Em validacao" mostra TODAS as pendentes, de qualquer dia.
--
--    Interna: ninguem chama direto. So painel_da_loja, resumo_das_lojas e
--    painel_da_tv, que conferem quem pede.
-- ===========================================================================

CREATE OR REPLACE FUNCTION public.montar_painel(p_contaid integer, p_lojaid integer, p_tv boolean)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_hoje       date := public.dia_em_sao_paulo(now());
  v_loja       text;
  v_dia        jsonb;
  v_validacao  jsonb;
  v_pendentes  integer;
  v_podio      jsonb;
  v_atividade  jsonb;
BEGIN
  SELECT nome INTO v_loja FROM public.lojas WHERE lojaid = p_lojaid AND contaid = p_contaid;
  IF NOT FOUND THEN
    RETURN NULL;
  END IF;

  -- Tarefas do dia e a situacao de cada uma hoje.
  WITH dia AS (
    SELECT t.titulo,
           t.pontos,
           CASE WHEN p_tv THEN public.nome_curto(f.nomecompleto) ELSE f.nomecompleto END AS pessoa,
           (ta.tipofrequencia = 'Unica' AND ta.dataagendamento IS NOT NULL
            AND public.dia_em_sao_paulo(ta.dataagendamento) < v_hoje) AS atrasada,
           (SELECT e.statusvalidacao
              FROM public.entregas e
             WHERE e.atribuicaoid = ta.atribuicaoid
               AND e.statusvalidacao IN ('Pendente', 'Aprovada')
               AND public.dia_em_sao_paulo(e.dataenvio) = v_hoje
             ORDER BY e.entregaid DESC
             LIMIT 1) AS situacao
      FROM public.tarefasatribuidas ta
      JOIN public.tarefas t            ON t.tarefaid = ta.tarefaid
      JOIN public.funcionarios f       ON f.funcionarioid = ta.funcionarioid
      JOIN public.funcionarioslojas fl ON fl.funcionarioid = ta.funcionarioid AND fl.lojaid = ta.lojaid
     WHERE ta.contaid = p_contaid
       AND ta.lojaid = p_lojaid
       AND ta.datafimvigencia IS NULL
       AND f.ativo AND fl.ativo AND coalesce(t.ativa, true)
       AND public.tarefa_cai_no_dia(ta.tipofrequencia, ta.valorfrequencia, ta.dataagendamento, v_hoje)
       -- Unica entregue num dia anterior ja nao e tarefa de hoje.
       AND NOT (ta.tipofrequencia = 'Unica' AND EXISTS (
             SELECT 1 FROM public.entregas e2
              WHERE e2.atribuicaoid = ta.atribuicaoid
                AND e2.statusvalidacao IN ('Pendente', 'Aprovada')
                AND public.dia_em_sao_paulo(e2.dataenvio) < v_hoje))
  )
  SELECT jsonb_build_object(
           'total',       count(*),
           'aprovadas',   count(*) FILTER (WHERE situacao = 'Aprovada'),
           'emvalidacao', count(*) FILTER (WHERE situacao = 'Pendente'),
           'parafazer',   coalesce(
                            jsonb_agg(
                              jsonb_build_object('titulo', titulo, 'pessoa', pessoa,
                                                 'pontos', pontos, 'atrasada', atrasada)
                              ORDER BY atrasada DESC, pessoa, titulo
                            ) FILTER (WHERE situacao IS NULL),
                            '[]'::jsonb))
    INTO v_dia
    FROM dia;

  -- Em validacao: todas as pendentes da loja, de qualquer dia.
  SELECT count(*) INTO v_pendentes
    FROM public.entregas
   WHERE contaid = p_contaid AND lojaid = p_lojaid AND statusvalidacao = 'Pendente';

  SELECT coalesce(jsonb_agg(
           jsonb_build_object('titulo', titulo, 'pessoa', pessoa, 'pontos', pontos,
                              'enviadaem', dataenvio, 'dehoje', dehoje)
           ORDER BY dataenvio), '[]'::jsonb)
    INTO v_validacao
    FROM (
      SELECT t.titulo, t.pontos, e.dataenvio,
             CASE WHEN p_tv THEN public.nome_curto(f.nomecompleto) ELSE f.nomecompleto END AS pessoa,
             public.dia_em_sao_paulo(e.dataenvio) = v_hoje AS dehoje
        FROM public.entregas e
        JOIN public.tarefas t      ON t.tarefaid = e.tarefaid
        JOIN public.funcionarios f ON f.funcionarioid = e.funcionarioid
       WHERE e.contaid = p_contaid AND e.lojaid = p_lojaid AND e.statusvalidacao = 'Pendente'
       ORDER BY e.dataenvio
       LIMIT 50
    ) s;

  -- Podio do dia: pontos aprovados hoje na loja.
  SELECT coalesce(jsonb_agg(jsonb_build_object('pessoa', pessoa, 'pontos', pontos)
                            ORDER BY pontos DESC, pessoa), '[]'::jsonb)
    INTO v_podio
    FROM (
      SELECT CASE WHEN p_tv THEN public.nome_curto(f.nomecompleto) ELSE f.nomecompleto END AS pessoa,
             sum(e.pontosganhos)::integer AS pontos
        FROM public.entregas e
        JOIN public.funcionarios f ON f.funcionarioid = e.funcionarioid
       WHERE e.contaid = p_contaid AND e.lojaid = p_lojaid
         AND e.statusvalidacao = 'Aprovada'
         AND public.dia_em_sao_paulo(e.dataaprovacao) = v_hoje
       GROUP BY f.funcionarioid, f.nomecompleto
       ORDER BY sum(e.pontosganhos) DESC, f.nomecompleto
       LIMIT 3
    ) s;

  -- Atividade recente: as ultimas aprovacoes do dia.
  SELECT coalesce(jsonb_agg(jsonb_build_object('titulo', titulo, 'pessoa', pessoa,
                                               'pontos', pontos, 'aprovadaem', dataaprovacao)
                            ORDER BY dataaprovacao DESC), '[]'::jsonb)
    INTO v_atividade
    FROM (
      SELECT t.titulo, e.pontosganhos AS pontos, e.dataaprovacao,
             CASE WHEN p_tv THEN public.nome_curto(f.nomecompleto) ELSE f.nomecompleto END AS pessoa
        FROM public.entregas e
        JOIN public.tarefas t      ON t.tarefaid = e.tarefaid
        JOIN public.funcionarios f ON f.funcionarioid = e.funcionarioid
       WHERE e.contaid = p_contaid AND e.lojaid = p_lojaid
         AND e.statusvalidacao = 'Aprovada'
         AND public.dia_em_sao_paulo(e.dataaprovacao) = v_hoje
       ORDER BY e.dataaprovacao DESC
       LIMIT 10
    ) s;

  RETURN jsonb_build_object(
    'loja',         v_loja,
    'hoje',         v_hoje,
    'atualizadoem', now(),
    'progresso',    jsonb_build_object('total',       v_dia->'total',
                                       'aprovadas',   v_dia->'aprovadas',
                                       'emvalidacao', v_dia->'emvalidacao'),
    'parafazer',    v_dia->'parafazer',
    'emvalidacao',  v_validacao,
    'pendentes',    v_pendentes,
    'podio',        v_podio,
    'atividade',    v_atividade
  );
END;
$$;

-- ===========================================================================
-- 4. Painel para quem esta logado: so lojas da propria conta.
--    Conta suspensa continua enxergando (so leitura).
-- ===========================================================================

CREATE OR REPLACE FUNCTION public.painel_da_loja(p_lojaid integer)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_conta   integer := public.minha_conta();
  v_painel  jsonb;
BEGIN
  IF v_conta IS NULL THEN
    RAISE EXCEPTION 'Sem acesso.' USING ERRCODE = 'insufficient_privilege';
  END IF;

  v_painel := public.montar_painel(v_conta, p_lojaid, false);
  IF v_painel IS NULL THEN
    RAISE EXCEPTION 'Loja não encontrada.' USING ERRCODE = 'no_data_found';
  END IF;

  RETURN v_painel;
END;
$$;

-- Resumo lado a lado de todas as lojas ativas da conta (Gestao).
CREATE OR REPLACE FUNCTION public.resumo_das_lojas()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_conta integer := public.minha_conta();
BEGIN
  IF v_conta IS NULL THEN
    RAISE EXCEPTION 'Sem acesso.' USING ERRCODE = 'insufficient_privilege';
  END IF;

  RETURN (
    SELECT coalesce(jsonb_agg(
             jsonb_build_object(
               'lojaid',    l.lojaid,
               'nome',      l.nome,
               'progresso', p.painel->'progresso',
               'pendentes', p.painel->'pendentes',
               'lider',     p.painel->'podio'->0)
             ORDER BY l.nome), '[]'::jsonb)
      FROM public.lojas l
      CROSS JOIN LATERAL (SELECT public.montar_painel(v_conta, l.lojaid, false) AS painel) p
     WHERE l.contaid = v_conta AND l.ativa
  );
END;
$$;

-- ===========================================================================
-- 5. Criar e revogar links de TV (dono da conta, conta ativa).
-- ===========================================================================

CREATE OR REPLACE FUNCTION public.criar_link_tv(p_lojaid integer, p_nome text)
RETURNS text
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_conta  integer := public.minha_conta_editavel();
  v_codigo text;
BEGIN
  IF v_conta IS NULL THEN
    RAISE EXCEPTION 'Sua conta não pode alterar dados no momento.' USING ERRCODE = 'insufficient_privilege';
  END IF;

  IF length(btrim(coalesce(p_nome, ''))) = 0 THEN
    RAISE EXCEPTION 'Dê um nome ao link (ex.: TV do balcão).' USING ERRCODE = 'check_violation';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.lojas WHERE lojaid = p_lojaid AND contaid = v_conta AND ativa) THEN
    RAISE EXCEPTION 'Loja não encontrada ou desativada.' USING ERRCODE = 'no_data_found';
  END IF;

  -- 64 caracteres aleatorios (duas UUID v4): impossivel de adivinhar.
  v_codigo := replace(gen_random_uuid()::text, '-', '') || replace(gen_random_uuid()::text, '-', '');

  INSERT INTO public.linkstv (contaid, lojaid, nome, tokenhash, criadopor)
  VALUES (v_conta, p_lojaid, btrim(p_nome),
          encode(sha256(convert_to(v_codigo, 'UTF8')), 'hex'), auth.uid());

  RETURN v_codigo;
END;
$$;

CREATE OR REPLACE FUNCTION public.revogar_link_tv(p_linktvid integer)
RETURNS void
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_conta integer := public.minha_conta_editavel();
BEGIN
  IF v_conta IS NULL THEN
    RAISE EXCEPTION 'Sua conta não pode alterar dados no momento.' USING ERRCODE = 'insufficient_privilege';
  END IF;

  UPDATE public.linkstv
     SET revogadoem = now()
   WHERE linktvid = p_linktvid AND contaid = v_conta AND revogadoem IS NULL;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Link não encontrado ou já revogado.' USING ERRCODE = 'no_data_found';
  END IF;
END;
$$;

-- ===========================================================================
-- 6. O painel da TV. A UNICA coisa que um visitante sem login pode chamar.
--    Recebe o codigo e devolve so o painel daquela loja, com nomes curtos.
--    Link revogado, codigo inventado, loja desativada, conta suspensa ou
--    cancelada: todos recebem a mesma resposta, sem dizer por que.
--    Registra o ultimo uso (no maximo uma gravacao por minuto por link).
-- ===========================================================================

CREATE OR REPLACE FUNCTION public.painel_da_tv(p_codigo text)
RETURNS jsonb
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_link public.linkstv%ROWTYPE;
BEGIN
  IF p_codigo IS NULL OR length(p_codigo) <> 64 THEN
    RETURN jsonb_build_object('disponivel', false);
  END IF;

  SELECT k.* INTO v_link
    FROM public.linkstv k
    JOIN public.lojas  l ON l.lojaid = k.lojaid AND l.contaid = k.contaid
    JOIN public.contas c ON c.contaid = k.contaid
   WHERE k.tokenhash = encode(sha256(convert_to(p_codigo, 'UTF8')), 'hex')
     AND k.revogadoem IS NULL
     AND l.ativa
     AND c.status = 'ativa';

  IF NOT FOUND THEN
    RETURN jsonb_build_object('disponivel', false);
  END IF;

  UPDATE public.linkstv
     SET ultimouso = now()
   WHERE linktvid = v_link.linktvid
     AND (ultimouso IS NULL OR ultimouso < now() - interval '1 minute');

  RETURN public.montar_painel(v_link.contaid, v_link.lojaid, true)
         || jsonb_build_object('disponivel', true);
END;
$$;

-- ===========================================================================
-- 7. Funcoes: NEGADAS POR PADRAO, liberadas por lista explicita.
--    O Supabase da EXECUTE automatico a anon e a authenticated em toda funcao
--    nova do schema public. Duas vezes isso ja abriu um furo (cria_* na Fase 5
--    e montar_painel aqui, que recebe o contaid e deixaria um cliente ler o
--    painel de outro). A partir daqui, funcao nova nasce sem permissao para
--    ninguem, e cada migracao libera o que precisa.
--
--    Visitante sem login (anon): so painel_da_tv, e nenhuma tabela. Antes a
--    RLS ja impedia a leitura, mas o acesso existia; agora nem o acesso existe.
-- ===========================================================================

REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA public FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL TABLES    IN SCHEMA public FROM anon;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon;

-- E para tudo o que for criado daqui para frente.
-- Atencao: a permissao padrao de PUBLIC em funcoes so pode ser retirada de
-- forma GLOBAL. Com "IN SCHEMA" o Postgres aceita o comando e nao faz nada.
ALTER DEFAULT PRIVILEGES REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE EXECUTE ON FUNCTIONS FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES    FROM anon;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM anon;

GRANT EXECUTE ON FUNCTION public.painel_da_tv(text) TO anon;

-- Quem esta logado: a lista explicita do que pode chamar. montar_painel,
-- apos_aprovar_entrega e as cria_* ficam de fora de proposito.
GRANT EXECUTE ON FUNCTION
  public.minha_conta(),
  public.minha_conta_editavel(),
  public.eh_admin_geral(),
  public.tarefa_cai_no_dia(varchar, integer, timestamptz, date),
  public.dia_em_sao_paulo(timestamptz),
  public.nome_curto(text),
  public.registrar_entrega(integer, text, text, boolean),
  public.aprovar_entrega(integer),
  public.recusar_entrega(integer, text),
  public.estornar_entrega(integer, text),
  public.atribuicoes_para_entregar(integer),
  public.ranking_pontos(date, date, integer),
  public.painel_da_loja(integer),
  public.resumo_das_lojas(),
  public.criar_link_tv(integer, text),
  public.revogar_link_tv(integer),
  public.painel_da_tv(text)
TO authenticated;

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO service_role;

-- ===========================================================================
-- 8. Tempo real para o painel logado.
--    O Supabase so avisa das mudancas das tabelas desta publicacao, e sempre
--    respeitando a RLS de quem escuta. No Postgres de teste ela nao existe.
-- ===========================================================================

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    IF NOT EXISTS (SELECT 1 FROM pg_publication_tables
                    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'entregas') THEN
      ALTER PUBLICATION supabase_realtime ADD TABLE public.entregas;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_publication_tables
                    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'tarefasatribuidas') THEN
      ALTER PUBLICATION supabase_realtime ADD TABLE public.tarefasatribuidas;
    END IF;
  END IF;
END $$;
