-- Fundacao multi-empresa (Fase 2.1 e 2.3): contas, lojas e as funcoes de isolamento.
-- Referencia: docs/PLANO_MIGRACAO.md

-- ---------------------------------------------------------------------------
-- Conta = cliente = usuario master
-- ---------------------------------------------------------------------------

CREATE TABLE public.contas (
  contaid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(200) NOT NULL,
  email varchar(255) NOT NULL,
  telefone varchar(50),
  cidade varchar(100),
  limitelojas integer NOT NULL DEFAULT 1 CHECK (limitelojas >= 0),
  status varchar(20) NOT NULL DEFAULT 'ativa' CHECK (status IN ('ativa', 'suspensa', 'cancelada')),
  observacoes text,
  criadoem timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX contas_email_unico ON public.contas (lower(email));

-- Liga um login do Supabase Auth a uma conta.
CREATE TABLE public.contasusuarios (
  contaid integer NOT NULL REFERENCES public.contas(contaid) ON DELETE RESTRICT,
  userid uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  papel varchar(20) NOT NULL DEFAULT 'master' CHECK (papel IN ('master', 'gerente')),
  criadoem timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (contaid, userid)
);

-- Regra do plano: um login pertence a uma unica conta.
CREATE UNIQUE INDEX contasusuarios_um_login_uma_conta ON public.contasusuarios (userid);

-- ---------------------------------------------------------------------------
-- Funcoes de isolamento.
-- security definer + search_path fixo: leem contasusuarios/auth.users sem
-- passar pela RLS (senao a policy que usa minha_conta() se chamaria em loop).
-- ---------------------------------------------------------------------------

-- Conta do usuario logado. NULL se o login nao pertence a nenhuma conta.
CREATE OR REPLACE FUNCTION public.minha_conta()
RETURNS integer
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT contaid FROM public.contasusuarios WHERE userid = auth.uid()
$$;

-- Mesma coisa, mas so devolve a conta quando ela esta ativa.
-- Usada nas policies de escrita: conta suspensa ou cancelada fica so leitura.
CREATE OR REPLACE FUNCTION public.minha_conta_editavel()
RETURNS integer
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT cu.contaid
  FROM public.contasusuarios cu
  JOIN public.contas c ON c.contaid = cu.contaid
  WHERE cu.userid = auth.uid() AND c.status = 'ativa'
$$;

-- Administrador geral da plataforma. Fixo no banco, nao vem do navegador.
CREATE OR REPLACE FUNCTION public.eh_admin_geral()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, auth, pg_temp
AS $$
  SELECT EXISTS (
    SELECT 1 FROM auth.users
    WHERE id = auth.uid()
      AND lower(email) = 'wisley_anderson@hotmail.com'
      AND email_confirmed_at IS NOT NULL
  )
$$;

REVOKE EXECUTE ON FUNCTION public.minha_conta() FROM public;
REVOKE EXECUTE ON FUNCTION public.minha_conta_editavel() FROM public;
REVOKE EXECUTE ON FUNCTION public.eh_admin_geral() FROM public;
GRANT EXECUTE ON FUNCTION public.minha_conta() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.minha_conta_editavel() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.eh_admin_geral() TO authenticated, service_role;

-- ---------------------------------------------------------------------------
-- Lojas
-- ---------------------------------------------------------------------------

CREATE TABLE public.lojas (
  lojaid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contaid integer NOT NULL DEFAULT public.minha_conta() REFERENCES public.contas(contaid) ON DELETE RESTRICT,
  nome varchar(150) NOT NULL,
  cidade varchar(100),
  endereco varchar(255),
  ativa boolean NOT NULL DEFAULT true,
  criadoem timestamptz NOT NULL DEFAULT now(),
  -- alvo das chaves estrangeiras compostas (contaid, lojaid)
  UNIQUE (contaid, lojaid)
);

CREATE UNIQUE INDEX lojas_nome_por_conta ON public.lojas (contaid, lower(nome));

-- Limite de lojas ativas contratado pela conta.
CREATE OR REPLACE FUNCTION public.checa_limite_lojas()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  limite integer;
  usadas integer;
BEGIN
  IF NEW.ativa IS NOT TRUE THEN
    RETURN NEW;
  END IF;

  SELECT limitelojas INTO limite FROM public.contas WHERE contaid = NEW.contaid;

  SELECT count(*) INTO usadas
  FROM public.lojas
  WHERE contaid = NEW.contaid
    AND ativa
    AND lojaid IS DISTINCT FROM NEW.lojaid;

  IF usadas + 1 > limite THEN
    RAISE EXCEPTION
      'A conta % ja usa % de % lojas liberadas. Fale com o suporte para ampliar.',
      NEW.contaid, usadas, limite
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER lojas_limite
  BEFORE INSERT OR UPDATE ON public.lojas
  FOR EACH ROW EXECUTE FUNCTION public.checa_limite_lojas();
