-- Etapa 1.11, parte 1: registro de execuções, lista do dia congelada e
-- "passar tarefa de quem está de folga".
--
-- Regras (decisões do Wisley, 22/09/2026):
--   * As rotinas rodam para todas as contas ativas, cada uma no seu horário
--     (configuracoes), no fuso America/Sao_Paulo. Pulam contas suspensas e
--     lojas desativadas. Uma conta com erro não trava as outras.
--   * Rodar duas vezes nunca duplica. Depois de uma parada, recupera no
--     máximo 7 dias, marcados como "recuperado".
--   * A lista de HOJE é ajustada a cada rodada (acrescenta o que falta,
--     cancela o que deixou de valer), sem mexer em item entregue, justificado
--     ou passado. Os dias passados nunca mudam.
--   * Os pontos de cada item são os do dia em que foi gerado.
--   * As funções da rotina recebem contaid e rodam com poder total (o papel
--     do pg_cron ignora a RLS): por isso filtram a conta em TODA consulta e
--     não são liberadas para ninguém.

-- ---------------------------------------------------------------------------
-- 1. Registro de execuções
-- ---------------------------------------------------------------------------
CREATE TABLE public.rotinasexecucoes (
  execucaoid  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contaid     integer NOT NULL DEFAULT public.minha_conta() REFERENCES public.contas (contaid) ON DELETE RESTRICT,
  rotina      varchar(30) NOT NULL
              CHECK (rotina IN ('lista_do_dia', 'fechamento_mensal', 'conferencia_livro', 'limpeza')),
  referencia  date,
  origem      varchar(10) NOT NULL DEFAULT 'agendada' CHECK (origem IN ('agendada', 'manual')),
  recuperado  boolean NOT NULL DEFAULT false,
  iniciadoem  timestamptz NOT NULL DEFAULT now(),
  terminadoem timestamptz,
  resultado   varchar(10) NOT NULL CHECK (resultado IN ('ok', 'erro')),
  detalhe     jsonb,
  erro        text,
  CONSTRAINT rotinasexecucoes_conta_unico UNIQUE (contaid, execucaoid)
);
CREATE INDEX rotinasexecucoes_conta_idx ON public.rotinasexecucoes (contaid, rotina, iniciadoem DESC);
CREATE INDEX rotinasexecucoes_limpeza_idx ON public.rotinasexecucoes (iniciadoem);

ALTER TABLE public.rotinasexecucoes ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.rotinasexecucoes TO authenticated;
GRANT ALL ON public.rotinasexecucoes TO service_role;
CREATE POLICY rotinasexecucoes_sel ON public.rotinasexecucoes FOR SELECT TO authenticated
  USING (contaid = (select public.minha_conta()));

-- ---------------------------------------------------------------------------
-- 2. Dias com lista gerada (nunca é limpo: diz de onde vêm os números)
-- ---------------------------------------------------------------------------
CREATE TABLE public.diasgerados (
  contaid    integer NOT NULL DEFAULT public.minha_conta() REFERENCES public.contas (contaid) ON DELETE RESTRICT,
  dia        date NOT NULL,
  recuperado boolean NOT NULL DEFAULT false,
  geradoem   timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (contaid, dia)
);
ALTER TABLE public.diasgerados ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.diasgerados TO authenticated;
GRANT ALL ON public.diasgerados TO service_role;
CREATE POLICY diasgerados_sel ON public.diasgerados FOR SELECT TO authenticated
  USING (contaid = (select public.minha_conta()));

-- ---------------------------------------------------------------------------
-- 3. Lista do dia (o que cada pessoa devia fazer em cada dia)
-- ---------------------------------------------------------------------------
CREATE TABLE public.tarefasdodia (
  itemid              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contaid             integer NOT NULL DEFAULT public.minha_conta() REFERENCES public.contas (contaid) ON DELETE RESTRICT,
  lojaid              integer NOT NULL,
  dia                 date NOT NULL,
  atribuicaoid        integer NOT NULL,
  funcionarioid       integer NOT NULL,
  tarefaid            integer NOT NULL,
  tipofrequencia      varchar(20) NOT NULL,
  pontos              integer NOT NULL,
  situacao            varchar(12) NOT NULL CHECK (situacao IN ('devida', 'folga', 'afastamento', 'cancelada')),
  passadapara         integer,
  passadaatribuicaoid integer,
  passadaem           timestamptz,
  passadapor          uuid,
  recuperado          boolean NOT NULL DEFAULT false,
  geradoem            timestamptz NOT NULL DEFAULT now(),
  atualizadoem        timestamptz,
  CONSTRAINT tarefasdodia_um_por_dia UNIQUE (contaid, dia, atribuicaoid),
  CONSTRAINT tarefasdodia_conta_unico UNIQUE (contaid, itemid),
  CONSTRAINT tarefasdodia_loja_fk FOREIGN KEY (contaid, lojaid) REFERENCES public.lojas (contaid, lojaid) ON DELETE RESTRICT,
  CONSTRAINT tarefasdodia_atribuicao_fk FOREIGN KEY (contaid, atribuicaoid)
    REFERENCES public.tarefasatribuidas (contaid, atribuicaoid) ON DELETE RESTRICT,
  CONSTRAINT tarefasdodia_funcionario_fk FOREIGN KEY (contaid, funcionarioid)
    REFERENCES public.funcionarios (contaid, funcionarioid) ON DELETE RESTRICT,
  CONSTRAINT tarefasdodia_tarefa_fk FOREIGN KEY (contaid, tarefaid) REFERENCES public.tarefas (contaid, tarefaid) ON DELETE RESTRICT,
  CONSTRAINT tarefasdodia_passadapara_fk FOREIGN KEY (contaid, passadapara)
    REFERENCES public.funcionarios (contaid, funcionarioid) ON DELETE RESTRICT,
  CONSTRAINT tarefasdodia_passadaatribuicao_fk FOREIGN KEY (contaid, passadaatribuicaoid)
    REFERENCES public.tarefasatribuidas (contaid, atribuicaoid) ON DELETE RESTRICT,
  -- Só se passa tarefa de quem está de folga ou afastado.
  CONSTRAINT tarefasdodia_passada_so_de_folga CHECK (passadapara IS NULL OR situacao IN ('folga', 'afastamento'))
);
CREATE INDEX tarefasdodia_dia_idx ON public.tarefasdodia (contaid, dia);
CREATE INDEX tarefasdodia_pessoa_idx ON public.tarefasdodia (funcionarioid, dia);
CREATE INDEX tarefasdodia_atribuicao_idx ON public.tarefasdodia (atribuicaoid, dia);

ALTER TABLE public.tarefasdodia ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.tarefasdodia TO authenticated;
GRANT ALL ON public.tarefasdodia TO service_role;
CREATE POLICY tarefasdodia_sel ON public.tarefasdodia FOR SELECT TO authenticated
  USING (contaid = (select public.minha_conta()));

-- Dia que já passou não muda, por nenhum caminho.
CREATE OR REPLACE FUNCTION public.protege_lista_do_dia()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
BEGIN
  IF OLD.dia < public.dia_em_sao_paulo(now()) THEN
    RAISE EXCEPTION 'A lista de um dia que já passou não muda.' USING ERRCODE = 'restrict_violation';
  END IF;
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'Item da lista do dia não se apaga: é cancelado.' USING ERRCODE = 'restrict_violation';
  END IF;
  IF NEW.contaid <> OLD.contaid OR NEW.dia <> OLD.dia OR NEW.atribuicaoid <> OLD.atribuicaoid
     OR NEW.funcionarioid <> OLD.funcionarioid OR NEW.pontos <> OLD.pontos OR NEW.lojaid <> OLD.lojaid THEN
    RAISE EXCEPTION 'Só a situação e o repasse de um item mudam.' USING ERRCODE = 'restrict_violation';
  END IF;
  IF OLD.passadapara IS NOT NULL AND (NEW.passadapara IS DISTINCT FROM OLD.passadapara OR NEW.situacao <> OLD.situacao) THEN
    RAISE EXCEPTION 'Tarefa já passada para outra pessoa não muda mais.' USING ERRCODE = 'restrict_violation';
  END IF;
  NEW.atualizadoem := now();
  RETURN NEW;
END;
$$;
CREATE TRIGGER tarefasdodia_protege BEFORE UPDATE OR DELETE ON public.tarefasdodia
  FOR EACH ROW EXECUTE FUNCTION public.protege_lista_do_dia();

-- Tarefa passada nasce como única de hoje, com origematribuicaoid apontando
-- para a original. Uma vez por dia, no máximo.
CREATE UNIQUE INDEX tarefasatribuidas_passada_uma_vez
  ON public.tarefasatribuidas (contaid, origematribuicaoid, public.dia_em_sao_paulo(dataagendamento))
  WHERE origematribuicaoid IS NOT NULL;

-- ---------------------------------------------------------------------------
-- 4. Horários novos
-- ---------------------------------------------------------------------------
INSERT INTO public.configuracoes (contaid, chave, valor, descricao)
SELECT c.contaid, x.chave, x.valor, x.descricao
  FROM public.contas c
 CROSS JOIN (VALUES
   ('HORARIO_GERACAO_TAREFAS',   '00:05', 'Hora em que a lista de tarefas do dia é gerada.'),
   ('HORARIO_CONFERENCIA_LIVRO', '03:00', 'Hora da conferência diária do livro de pontos e da limpeza do registro de rotinas.')
 ) AS x(chave, valor, descricao)
ON CONFLICT (contaid, chave) DO NOTHING;

CREATE OR REPLACE FUNCTION public.cria_configuracoes_padrao(p_contaid integer)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $fn$
  INSERT INTO public.configuracoes (contaid, chave, valor, descricao) VALUES
    (p_contaid, 'TAXA_CONVERSAO_PONTO_REAL',     '0.03',  'Quanto vale 1 ponto em reais.'),
    (p_contaid, 'PONTOS_BONUS_FEEDBACK_DIARIO',  '5',     'Pontos de bonus por enviar o feedback do dia.'),
    (p_contaid, 'PONTOS_BONUS_NOTA_FISCAL',      '10',    'Pontos de bonus por enviar uma nota fiscal.'),
    (p_contaid, 'MAX_DIFERENCA_FOTO_SEGUNDOS',   '120',   'Tolerancia, em segundos, entre a hora da foto (EXIF) e o envio.'),
    (p_contaid, 'HORARIO_GERACAO_TAREFAS',       '00:05', 'Hora em que a lista de tarefas do dia é gerada.'),
    (p_contaid, 'HORARIO_CONFERENCIA_LIVRO',     '03:00', 'Hora da conferência diária do livro de pontos e da limpeza do registro de rotinas.'),
    (p_contaid, 'HORARIO_FECHAMENTO_MENSAL',     '08:00', 'Hora do fechamento mensal do ranking (executa no dia 1).'),
    (p_contaid, 'HORARIO_DELEGACAO_FOLGA',       '09:05', 'Hora da delegacao automatica das tarefas de quem esta de folga.'),
    (p_contaid, 'HORARIO_LEMBRETE_COMUNICADOS',  '09:00', 'Hora do lembrete de comunicados pendentes de leitura.'),
    (p_contaid, 'HORARIO_LEMBRETE_HOJE',         '08:00', 'Hora do lembrete dos agendamentos de hoje.'),
    (p_contaid, 'HORARIO_LEMBRETE_DIARIO_AMANHA','09:00', 'Hora do lembrete dos agendamentos de amanha.'),
    (p_contaid, 'HORARIO_LEMBRETE_SEMANAL',      '08:00', 'Hora do lembrete semanal de agendamentos.'),
    (p_contaid, 'TAREFA_ID_FEEDBACK_DIARIO',           '', 'ID da tarefa de feedback diario. Preenchido pelo sistema.'),
    (p_contaid, 'TAREFA_ID_LEITURA',                   '', 'ID da tarefa de leitura de comunicado. Preenchido pelo sistema.'),
    (p_contaid, 'TAREFA_MODELO_AGENDAMENTO_ID',        '', 'ID da tarefa modelo usada ao criar um agendamento.'),
    (p_contaid, 'TAREFA_ID_PONTOS_META',               '', 'ID da tarefa que credita os pontos da meta diaria.'),
    (p_contaid, 'TAREFA_ID_NOTA_FISCAL',               '', 'ID da tarefa de envio de nota fiscal.'),
    (p_contaid, 'TAREFA_ID_GUARDAR_MERCADORIA_MODELO', '', 'ID da tarefa modelo de guardar mercadoria.')
  ON CONFLICT (contaid, chave) DO NOTHING;
$fn$;
REVOKE EXECUTE ON FUNCTION public.cria_configuracoes_padrao(integer) FROM public, anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.cria_configuracoes_padrao(integer) TO service_role;

-- ---------------------------------------------------------------------------
-- 5. Peças da rotina (internas)
-- ---------------------------------------------------------------------------

-- Dia e hora locais de um instante. Com horário de verão, uma hora que "não
-- existe" (relógio pula) conta como passada assim que o relógio a ultrapassa;
-- a hora repetida não duplica nada porque as rotinas não repetem o que já fizeram.
CREATE OR REPLACE FUNCTION public.rotina_hora_local(p_agora timestamptz, p_fuso text DEFAULT 'America/Sao_Paulo')
RETURNS TABLE (dia date, hora time)
LANGUAGE sql
STABLE
SET search_path = public, pg_temp
AS $$
  SELECT (p_agora AT TIME ZONE p_fuso)::date, (p_agora AT TIME ZONE p_fuso)::time
$$;

-- Horário configurado da conta (ou o padrão).
CREATE OR REPLACE FUNCTION public.rotina_horario(p_contaid integer, p_chave text, p_padrao time)
RETURNS time
LANGUAGE sql
STABLE
SET search_path = public, pg_temp
AS $$
  SELECT coalesce((SELECT nullif(btrim(valor), '')::time FROM public.configuracoes
                    WHERE contaid = p_contaid AND chave = p_chave), p_padrao)
$$;

-- Grava uma execução. O mesmo erro repetido só é gravado uma vez por hora.
CREATE OR REPLACE FUNCTION public.rotina_registrar(
  p_contaid    integer,
  p_rotina     text,
  p_referencia date,
  p_origem     text,
  p_inicio     timestamptz,
  p_resultado  text,
  p_detalhe    jsonb,
  p_erro       text,
  p_recuperado boolean DEFAULT false
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF p_resultado = 'erro' AND EXISTS (
       SELECT 1 FROM public.rotinasexecucoes
        WHERE contaid = p_contaid AND rotina = p_rotina AND resultado = 'erro'
          AND referencia IS NOT DISTINCT FROM p_referencia
          AND erro IS NOT DISTINCT FROM p_erro
          AND iniciadoem > clock_timestamp() - interval '1 hour') THEN
    RETURN;
  END IF;
  INSERT INTO public.rotinasexecucoes (contaid, rotina, referencia, origem, recuperado, iniciadoem, terminadoem,
                                       resultado, detalhe, erro)
  VALUES (p_contaid, p_rotina, p_referencia, p_origem, coalesce(p_recuperado, false), p_inicio, clock_timestamp(),
          p_resultado, p_detalhe, left(p_erro, 500));
END;
$$;

-- Atribuições que valem num dia, com a situação da pessoa nesse dia.
-- Filtra a conta em todas as tabelas (roda também com poder total).
CREATE OR REPLACE FUNCTION public.lista_candidatos(p_contaid integer, p_dia date)
RETURNS TABLE (
  atribuicaoid   integer,
  lojaid         integer,
  funcionarioid  integer,
  tarefaid       integer,
  tipofrequencia varchar,
  pontos         integer,
  situacao       text
)
LANGUAGE sql
STABLE
SET search_path = public, pg_temp
AS $$
  SELECT ta.atribuicaoid, ta.lojaid, ta.funcionarioid, ta.tarefaid, ta.tipofrequencia, t.pontos,
         CASE
           WHEN f.datainicioafastamento IS NOT NULL AND f.datafimafastamento IS NOT NULL
                AND p_dia BETWEEN f.datainicioafastamento AND f.datafimafastamento THEN 'afastamento'
           WHEN NOT public.dia_de_trabalho(f.diadefolga, f.domingofolgamensal, NULL, NULL, p_dia) THEN 'folga'
           ELSE 'devida'
         END
    FROM public.tarefasatribuidas ta
    JOIN public.tarefas t            ON t.tarefaid = ta.tarefaid AND t.contaid = p_contaid
    JOIN public.funcionarios f       ON f.funcionarioid = ta.funcionarioid AND f.contaid = p_contaid
    JOIN public.funcionarioslojas fl ON fl.funcionarioid = ta.funcionarioid AND fl.lojaid = ta.lojaid
                                    AND fl.contaid = p_contaid
    JOIN public.lojas l              ON l.lojaid = ta.lojaid AND l.contaid = p_contaid
   WHERE ta.contaid = p_contaid
     AND ta.funcionarioid IS NOT NULL
     AND ta.origematribuicaoid IS NULL          -- tarefa recebida de quem está de folga é extra
     AND f.ativo AND fl.ativo AND l.ativa AND coalesce(t.ativa, true)
     AND (
       (ta.tipofrequencia IN ('Diaria', 'Semanal', 'Mensal')
        AND public.tarefa_cai_no_dia(ta.tipofrequencia, ta.valorfrequencia, ta.dataagendamento, p_dia)
        AND p_dia >= coalesce(public.dia_em_sao_paulo(ta.dataatribuicao), p_dia)
        AND p_dia >= coalesce(ta.datainiciovigencia, p_dia)
        AND (ta.datafimvigencia IS NULL OR p_dia < ta.datafimvigencia))
       OR
       (ta.tipofrequencia = 'Unica'
        AND public.dia_em_sao_paulo(coalesce(ta.dataagendamento, ta.dataatribuicao)) = p_dia
        AND (ta.datafimvigencia IS NULL OR ta.datafimvigencia > p_dia))
     )
$$;

-- O item já foi "tratado" (entregue, justificado ou passado)? Então a
-- reconciliação não mexe nele.
CREATE OR REPLACE FUNCTION public.item_tratado(p_atribuicaoid integer, p_tipo varchar, p_dia date, p_passadapara integer)
RETURNS boolean
LANGUAGE sql
STABLE
SET search_path = public, pg_temp
AS $$
  SELECT p_passadapara IS NOT NULL
      OR EXISTS (SELECT 1 FROM public.entregas e
                  WHERE e.atribuicaoid = p_atribuicaoid
                    AND e.statusvalidacao IN ('Pendente', 'Aprovada')
                    AND (p_tipo = 'Unica' OR public.dia_em_sao_paulo(e.dataenvio) = p_dia))
      OR public.tem_justificativa(p_atribuicaoid, p_tipo, p_dia, false)
$$;

-- Gera (ou ajusta) a lista de um dia de uma conta.
--   p_dia < p_hoje: só acrescenta o que falta (dia recuperado); não muda nada.
--   p_dia = p_hoje: acrescenta o que falta, cancela o que deixou de valer e
--                   atualiza folga/afastamento; nunca mexe em item tratado.
CREATE OR REPLACE FUNCTION public.lista_do_dia_gerar(p_contaid integer, p_dia date, p_hoje date, p_recuperado boolean)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_novos      integer := 0;
  v_cancelados integer := 0;
  v_ajustados  integer := 0;
BEGIN
  IF p_dia > p_hoje THEN
    RAISE EXCEPTION 'Não se gera lista de um dia que ainda não chegou.' USING ERRCODE = 'check_violation';
  END IF;
  -- Uma geração por conta de cada vez (duas rodadas simultâneas esperam).
  PERFORM pg_advisory_xact_lock(7311, p_contaid);

  INSERT INTO public.tarefasdodia (contaid, lojaid, dia, atribuicaoid, funcionarioid, tarefaid,
                                   tipofrequencia, pontos, situacao, recuperado)
  SELECT p_contaid, c.lojaid, p_dia, c.atribuicaoid, c.funcionarioid, c.tarefaid,
         c.tipofrequencia, c.pontos, c.situacao, p_recuperado
    FROM public.lista_candidatos(p_contaid, p_dia) c
  ON CONFLICT (contaid, dia, atribuicaoid) DO NOTHING;
  GET DIAGNOSTICS v_novos = ROW_COUNT;

  IF p_dia = p_hoje THEN
    UPDATE public.tarefasdodia i
       SET situacao = 'cancelada'
     WHERE i.contaid = p_contaid AND i.dia = p_dia AND i.situacao <> 'cancelada'
       AND NOT EXISTS (SELECT 1 FROM public.lista_candidatos(p_contaid, p_dia) c WHERE c.atribuicaoid = i.atribuicaoid)
       AND NOT public.item_tratado(i.atribuicaoid, i.tipofrequencia, i.dia, i.passadapara);
    GET DIAGNOSTICS v_cancelados = ROW_COUNT;

    UPDATE public.tarefasdodia i
       SET situacao = c.situacao
      FROM public.lista_candidatos(p_contaid, p_dia) c
     WHERE i.contaid = p_contaid AND i.dia = p_dia AND i.atribuicaoid = c.atribuicaoid
       AND i.situacao IS DISTINCT FROM c.situacao
       AND NOT public.item_tratado(i.atribuicaoid, i.tipofrequencia, i.dia, i.passadapara);
    GET DIAGNOSTICS v_ajustados = ROW_COUNT;
  END IF;

  INSERT INTO public.diasgerados (contaid, dia, recuperado)
  VALUES (p_contaid, p_dia, p_recuperado)
  ON CONFLICT (contaid, dia) DO NOTHING;

  RETURN jsonb_build_object(
    'dia', p_dia, 'novos', v_novos, 'cancelados', v_cancelados, 'ajustados', v_ajustados,
    'devidas',  (SELECT count(*) FROM public.tarefasdodia WHERE contaid = p_contaid AND dia = p_dia AND situacao = 'devida'),
    'folgas',   (SELECT count(*) FROM public.tarefasdodia WHERE contaid = p_contaid AND dia = p_dia
                   AND situacao IN ('folga', 'afastamento')),
    'canceladas', (SELECT count(*) FROM public.tarefasdodia WHERE contaid = p_contaid AND dia = p_dia AND situacao = 'cancelada'));
END;
$$;

-- A rotina da lista para uma conta: recupera dias perdidos (até 7) e gera ou
-- ajusta o dia de hoje (a partir do horário da conta).
CREATE OR REPLACE FUNCTION public.rotina_lista_do_dia(p_contaid integer, p_agora timestamptz, p_origem text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_hoje     date;
  v_hora     time;
  v_primeiro date;
  v_ja       boolean;
  v_inicio   timestamptz;
  v_res      jsonb;
  v_hoje_res jsonb;
  v_recup    integer := 0;
  d          date;
BEGIN
  SELECT x.dia, x.hora INTO v_hoje, v_hora FROM public.rotina_hora_local(p_agora) x;

  -- Dias perdidos: só depois da primeira geração da conta, no máximo 7 para trás.
  SELECT min(dia) INTO v_primeiro FROM public.diasgerados WHERE contaid = p_contaid;
  IF v_primeiro IS NOT NULL THEN
    FOR d IN
      SELECT g::date FROM generate_series(greatest(v_primeiro, v_hoje - 7), v_hoje - 1, interval '1 day') g
       WHERE NOT EXISTS (SELECT 1 FROM public.diasgerados dg WHERE dg.contaid = p_contaid AND dg.dia = g::date)
       ORDER BY 1
    LOOP
      v_inicio := clock_timestamp();
      BEGIN
        v_res := public.lista_do_dia_gerar(p_contaid, d, v_hoje, true);
        PERFORM public.rotina_registrar(p_contaid, 'lista_do_dia', d, p_origem, v_inicio, 'ok', v_res, NULL, true);
        v_recup := v_recup + 1;
      EXCEPTION WHEN OTHERS THEN
        PERFORM public.rotina_registrar(p_contaid, 'lista_do_dia', d, p_origem, v_inicio, 'erro', NULL, SQLERRM, true);
      END;
    END LOOP;
  END IF;

  -- Hoje.
  v_inicio := clock_timestamp();
  BEGIN
    v_ja := EXISTS (SELECT 1 FROM public.diasgerados WHERE contaid = p_contaid AND dia = v_hoje);
    IF p_origem = 'manual' OR v_ja
       OR v_hora >= public.rotina_horario(p_contaid, 'HORARIO_GERACAO_TAREFAS', '00:05') THEN
      v_hoje_res := public.lista_do_dia_gerar(p_contaid, v_hoje, v_hoje, false);
      -- Registra a primeira geração do dia, a rodada manual e qualquer ajuste.
      IF NOT v_ja OR p_origem = 'manual'
         OR (v_hoje_res->>'novos')::integer + (v_hoje_res->>'cancelados')::integer
            + (v_hoje_res->>'ajustados')::integer > 0 THEN
        PERFORM public.rotina_registrar(p_contaid, 'lista_do_dia', v_hoje, p_origem, v_inicio, 'ok',
                                        v_hoje_res || jsonb_build_object('ajuste', v_ja), NULL, false);
      END IF;
    END IF;
  EXCEPTION WHEN OTHERS THEN
    PERFORM public.rotina_registrar(p_contaid, 'lista_do_dia', v_hoje, p_origem, v_inicio, 'erro', NULL, SQLERRM, false);
    v_hoje_res := jsonb_build_object('erro', SQLERRM);
  END;

  RETURN jsonb_build_object('recuperados', v_recup, 'hoje', v_hoje_res);
END;
$$;

-- ---------------------------------------------------------------------------
-- 6. O que o master chama
-- ---------------------------------------------------------------------------

-- "Rodar agora": gera ou ajusta a lista de hoje da própria conta.
CREATE OR REPLACE FUNCTION public.rodar_geracao_hoje()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_conta integer := public.minha_conta_editavel();
BEGIN
  IF v_conta IS NULL THEN
    RAISE EXCEPTION 'Sua conta não pode alterar dados no momento.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF NOT public.sou_master() THEN
    RAISE EXCEPTION 'Só o responsável pela conta roda a rotina.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  RETURN public.rotina_lista_do_dia(v_conta, now(), 'manual');
END;
$$;

-- A tarefa foi passada hoje para outra pessoa? (a original sai do quadro)
CREATE OR REPLACE FUNCTION public.passada_hoje(p_atribuicaoid integer, p_dia date)
RETURNS boolean
LANGUAGE sql
STABLE
SET search_path = public, pg_temp
AS $$
  SELECT EXISTS (SELECT 1 FROM public.tarefasdodia
                  WHERE atribuicaoid = p_atribuicaoid AND dia = p_dia AND passadapara IS NOT NULL)
$$;

-- Tarefas de hoje de quem está de folga ou afastado, numa loja.
CREATE OR REPLACE FUNCTION public.tarefas_de_folga_hoje(p_lojaid integer)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
  WITH hoje AS (SELECT public.dia_em_sao_paulo(now()) AS dia),
  itens AS (
    SELECT c.atribuicaoid, c.funcionarioid, c.tarefaid, c.tipofrequencia, c.pontos, c.situacao, i.passadapara
      FROM hoje CROSS JOIN LATERAL public.lista_candidatos(public.minha_conta(), hoje.dia) c
      LEFT JOIN public.tarefasdodia i ON i.atribuicaoid = c.atribuicaoid AND i.dia = hoje.dia
     WHERE c.lojaid = p_lojaid AND c.situacao IN ('folga', 'afastamento')
  )
  SELECT coalesce(jsonb_agg(jsonb_build_object(
           'atribuicaoid', it.atribuicaoid,
           'titulo',       t.titulo,
           'pontos',       it.pontos,
           'pessoa',       f.nomecompleto,
           'motivo',       it.situacao,
           'passadapara',  p.nomecompleto,
           'entregue',     EXISTS (SELECT 1 FROM public.entregas e, hoje
                                    WHERE e.atribuicaoid = it.atribuicaoid
                                      AND e.statusvalidacao IN ('Pendente', 'Aprovada')
                                      AND (it.tipofrequencia = 'Unica' OR public.dia_em_sao_paulo(e.dataenvio) = hoje.dia)))
           ORDER BY f.nomecompleto, t.titulo), '[]'::jsonb)
    FROM itens it
    JOIN public.tarefas t      ON t.tarefaid = it.tarefaid
    JOIN public.funcionarios f ON f.funcionarioid = it.funcionarioid
    LEFT JOIN public.funcionarios p ON p.funcionarioid = it.passadapara
$$;

-- Quem trabalha hoje na loja (pode receber uma tarefa de quem está de folga).
CREATE OR REPLACE FUNCTION public.quem_trabalha_hoje(p_lojaid integer)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
  SELECT coalesce(jsonb_agg(jsonb_build_object('funcionarioid', f.funcionarioid, 'nome', f.nomecompleto)
                            ORDER BY f.nomecompleto), '[]'::jsonb)
    FROM public.funcionarios f
    JOIN public.funcionarioslojas fl ON fl.funcionarioid = f.funcionarioid AND fl.lojaid = p_lojaid AND fl.ativo
   WHERE f.ativo
     AND public.dia_de_trabalho(f.diadefolga, f.domingofolgamensal, f.datainicioafastamento,
                                f.datafimafastamento, public.dia_em_sao_paulo(now()))
$$;

-- Passa a tarefa de hoje de quem está de folga para quem trabalha hoje.
-- Vira uma tarefa única de hoje, com os mesmos pontos (a tarefa é a mesma).
-- Para quem recebe é esforço extra: não entra nos pontos possíveis.
CREATE OR REPLACE FUNCTION public.passar_tarefa_de_folga(p_atribuicaoid integer, p_funcionarioid integer)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_conta integer := public.minha_conta_editavel();
  v_hoje  date    := public.dia_em_sao_paulo(now());
  v_item  public.tarefasdodia%ROWTYPE;
  v_nome  text;
  v_nova  integer;
BEGIN
  IF v_conta IS NULL THEN
    RAISE EXCEPTION 'Sua conta não pode alterar dados no momento.' USING ERRCODE = 'insufficient_privilege';
  END IF;

  -- Garante a lista de hoje (se a rotina ainda não rodou).
  PERFORM public.lista_do_dia_gerar(v_conta, v_hoje, v_hoje, false);

  SELECT * INTO v_item FROM public.tarefasdodia
   WHERE contaid = v_conta AND dia = v_hoje AND atribuicaoid = p_atribuicaoid
   FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Esta tarefa não está na lista de hoje.' USING ERRCODE = 'no_data_found';
  END IF;
  IF v_item.situacao NOT IN ('folga', 'afastamento') THEN
    RAISE EXCEPTION 'Só se passa tarefa de quem está de folga ou afastado hoje.' USING ERRCODE = 'check_violation';
  END IF;
  IF v_item.passadapara IS NOT NULL THEN
    SELECT nomecompleto INTO v_nome FROM public.funcionarios WHERE funcionarioid = v_item.passadapara;
    RAISE EXCEPTION 'Esta tarefa já foi passada hoje para %.', v_nome USING ERRCODE = 'unique_violation';
  END IF;
  IF public.item_tratado(v_item.atribuicaoid, v_item.tipofrequencia, v_hoje, NULL) THEN
    RAISE EXCEPTION 'Esta tarefa já foi entregue ou justificada hoje.' USING ERRCODE = 'check_violation';
  END IF;
  IF p_funcionarioid = v_item.funcionarioid OR NOT EXISTS (
       SELECT 1 FROM public.funcionarios f
         JOIN public.funcionarioslojas fl ON fl.funcionarioid = f.funcionarioid AND fl.lojaid = v_item.lojaid
                                         AND fl.ativo AND fl.contaid = v_conta
        WHERE f.funcionarioid = p_funcionarioid AND f.contaid = v_conta AND f.ativo
          AND public.dia_de_trabalho(f.diadefolga, f.domingofolgamensal, f.datainicioafastamento,
                                     f.datafimafastamento, v_hoje)) THEN
    RAISE EXCEPTION 'Escolha alguém ativo, da mesma loja, que trabalha hoje.' USING ERRCODE = 'check_violation';
  END IF;

  INSERT INTO public.tarefasatribuidas (contaid, tarefaid, funcionarioid, lojaid, tipofrequencia,
                                        dataatribuicao, dataagendamento, origematribuicaoid)
  VALUES (v_conta, v_item.tarefaid, p_funcionarioid, v_item.lojaid, 'Unica', now(), now(), v_item.atribuicaoid)
  RETURNING atribuicaoid INTO v_nova;

  UPDATE public.tarefasdodia
     SET passadapara = p_funcionarioid, passadaatribuicaoid = v_nova, passadaem = now(), passadapor = auth.uid()
   WHERE itemid = v_item.itemid;

  RETURN v_nova;
END;
$$;

-- A original, depois de passada, não recebe entrega hoje.
CREATE OR REPLACE FUNCTION public.entrega_nao_passada()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF NEW.atribuicaoid IS NOT NULL
     AND public.passada_hoje(NEW.atribuicaoid, public.dia_em_sao_paulo(coalesce(NEW.dataenvio, now()))) THEN
    RAISE EXCEPTION 'Esta tarefa foi passada para outra pessoa hoje.' USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER entregas_nao_passada BEFORE INSERT ON public.entregas
  FOR EACH ROW EXECUTE FUNCTION public.entrega_nao_passada();

-- ---------------------------------------------------------------------------
-- 7. Nota do mês, pendências e justificativas: dias gerados vêm da lista
--    congelada; dias sem lista (antes da primeira geração ou numa parada
--    maior que 7 dias) continuam pela regra do cadastro.
--    Tarefa recebida de quem estava de folga (origematribuicaoid) é esforço
--    extra: conta nos pontos ganhos, não nos possíveis nem na confiabilidade.
-- ---------------------------------------------------------------------------

-- Versão por conta, usada pela tela (com a conta de quem está logado) e pelo
-- fechamento mensal. Filtra a conta em todas as tabelas.
CREATE OR REPLACE FUNCTION public.ranking_mensal_da_conta(
  p_contaid integer, p_ano integer, p_mes integer, p_lojaid integer, p_fim date
)
RETURNS TABLE (
  funcionarioid   integer,
  nomecompleto    varchar,
  pontosganhos    integer,
  pontosregulares integer,
  pontospossiveis integer,
  confiabilidade  numeric,
  esforco         numeric,
  nota            numeric
)
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
  WITH janela AS (
    SELECT make_date(p_ano, p_mes, 1) AS ini,
           least((make_date(p_ano, p_mes, 1) + interval '1 month - 1 day')::date, p_fim) AS fim
  ),
  gerados AS (
    SELECT dg.dia FROM public.diasgerados dg, janela j
     WHERE dg.contaid = p_contaid AND dg.dia BETWEEN j.ini AND j.fim
  ),
  lista AS (
    SELECT i.funcionarioid AS fid, sum(i.pontos)::integer AS pts
      FROM public.tarefasdodia i
      JOIN gerados g ON g.dia = i.dia
     WHERE i.contaid = p_contaid
       AND i.situacao = 'devida'
       AND (p_lojaid IS NULL OR i.lojaid = p_lojaid)
       AND NOT public.tem_justificativa(i.atribuicaoid, i.tipofrequencia, i.dia, true)
     GROUP BY i.funcionarioid
  ),
  recorrentes AS (
    SELECT ta.funcionarioid AS fid, sum(t.pontos)::integer AS pts
      FROM public.tarefasatribuidas ta
      JOIN public.tarefas t      ON t.tarefaid = ta.tarefaid AND t.contaid = p_contaid
      JOIN public.funcionarios f ON f.funcionarioid = ta.funcionarioid AND f.contaid = p_contaid
      CROSS JOIN janela j
      CROSS JOIN LATERAL generate_series(
        greatest(j.ini,
                 coalesce(public.dia_em_sao_paulo(ta.dataatribuicao), j.ini),
                 coalesce(ta.datainiciovigencia, j.ini)),
        least(j.fim, coalesce(ta.datafimvigencia - 1, j.fim)),
        interval '1 day') AS g(d)
     WHERE ta.contaid = p_contaid
       AND ta.funcionarioid IS NOT NULL
       AND ta.origematribuicaoid IS NULL
       AND ta.tipofrequencia IN ('Diaria', 'Semanal', 'Mensal')
       AND (p_lojaid IS NULL OR ta.lojaid = p_lojaid)
       AND g.d::date NOT IN (SELECT dia FROM gerados)
       AND public.tarefa_cai_no_dia(ta.tipofrequencia, ta.valorfrequencia, ta.dataagendamento, g.d::date)
       AND public.dia_de_trabalho(f.diadefolga, f.domingofolgamensal,
                                  f.datainicioafastamento, f.datafimafastamento, g.d::date)
       AND NOT public.tem_justificativa(ta.atribuicaoid, ta.tipofrequencia, g.d::date, true)
     GROUP BY ta.funcionarioid
  ),
  unicas AS (
    SELECT ta.funcionarioid AS fid, sum(t.pontos)::integer AS pts
      FROM public.tarefasatribuidas ta
      JOIN public.tarefas t ON t.tarefaid = ta.tarefaid AND t.contaid = p_contaid
      CROSS JOIN janela j
     WHERE ta.contaid = p_contaid
       AND ta.funcionarioid IS NOT NULL
       AND ta.origematribuicaoid IS NULL
       AND ta.tipofrequencia = 'Unica'
       AND (p_lojaid IS NULL OR ta.lojaid = p_lojaid)
       AND public.dia_em_sao_paulo(coalesce(ta.dataagendamento, ta.dataatribuicao)) BETWEEN j.ini AND j.fim
       AND public.dia_em_sao_paulo(coalesce(ta.dataagendamento, ta.dataatribuicao)) NOT IN (SELECT dia FROM gerados)
       AND (ta.datafimvigencia IS NULL
            OR ta.datafimvigencia > public.dia_em_sao_paulo(coalesce(ta.dataagendamento, ta.dataatribuicao)))
       AND NOT public.tem_justificativa(ta.atribuicaoid, 'Unica', NULL, true)
     GROUP BY ta.funcionarioid
  ),
  regulares AS (
    SELECT e.funcionarioid AS fid, sum(e.pontosganhos)::integer AS pts
      FROM public.entregas e
      JOIN public.tarefasatribuidas ta ON ta.atribuicaoid = e.atribuicaoid AND ta.contaid = p_contaid
      CROSS JOIN janela j
     WHERE e.contaid = p_contaid
       AND e.statusvalidacao = 'Aprovada'
       AND ta.origematribuicaoid IS NULL
       AND (p_lojaid IS NULL OR e.lojaid = p_lojaid)
       AND public.dia_em_sao_paulo(e.dataenvio) BETWEEN j.ini AND j.fim
     GROUP BY e.funcionarioid
  ),
  ganhos AS (
    SELECT e.funcionarioid AS fid, sum(e.pontosganhos)::integer AS pts
      FROM public.entregas e
      CROSS JOIN janela j
     WHERE e.contaid = p_contaid
       AND e.statusvalidacao = 'Aprovada'
       AND (p_lojaid IS NULL OR e.lojaid = p_lojaid)
       AND public.dia_em_sao_paulo(e.dataaprovacao) BETWEEN j.ini AND j.fim
     GROUP BY e.funcionarioid
  ),
  pessoas AS (
    SELECT fid FROM lista UNION SELECT fid FROM recorrentes UNION SELECT fid FROM unicas
    UNION SELECT fid FROM regulares UNION SELECT fid FROM ganhos
  ),
  base AS (
    SELECT p.fid,
           f.nomecompleto AS nome,
           coalesce(g.pts, 0)                                        AS ganhos,
           coalesce(r.pts, 0)                                        AS regulares,
           coalesce(li.pts, 0) + coalesce(rc.pts, 0) + coalesce(u.pts, 0) AS possiveis
      FROM pessoas p
      JOIN public.funcionarios f ON f.funcionarioid = p.fid AND f.contaid = p_contaid
      LEFT JOIN ganhos g       ON g.fid = p.fid
      LEFT JOIN regulares r    ON r.fid = p.fid
      LEFT JOIN lista li       ON li.fid = p.fid
      LEFT JOIN recorrentes rc ON rc.fid = p.fid
      LEFT JOIN unicas u       ON u.fid = p.fid
  ),
  calc AS (
    SELECT b.*,
           CASE WHEN b.possiveis > 0 THEN least(100, round(b.regulares * 100.0 / b.possiveis, 2)) ELSE 0 END AS conf,
           CASE WHEN max(b.ganhos) OVER () > 0 THEN round(b.ganhos * 100.0 / max(b.ganhos) OVER (), 2) ELSE 0 END AS esf
      FROM base b
  )
  SELECT c.fid, c.nome, c.ganhos, c.regulares, c.possiveis, c.conf, c.esf,
         round(c.conf * 0.5 + c.esf * 0.5, 2)
    FROM calc c
   ORDER BY 8 DESC, 3 DESC, 2
$$;

-- A tela continua chamando ranking_mensal: agora é a versão da conta de quem
-- está logado, até ontem.
CREATE OR REPLACE FUNCTION public.ranking_mensal(p_ano integer, p_mes integer, p_lojaid integer DEFAULT NULL)
RETURNS TABLE (
  funcionarioid   integer,
  nomecompleto    varchar,
  pontosganhos    integer,
  pontosregulares integer,
  pontospossiveis integer,
  confiabilidade  numeric,
  esforco         numeric,
  nota            numeric
)
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
  SELECT * FROM public.ranking_mensal_da_conta(public.minha_conta(), p_ano, p_mes, p_lojaid,
                                               public.dia_em_sao_paulo(now()) - 1)
$$;

CREATE OR REPLACE FUNCTION public.pendencias_da_pessoa(p_funcionarioid integer, p_de date, p_ate date)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
  WITH lim AS (
    SELECT greatest(p_de, p_ate - 92) AS ini,
           least(p_ate, public.dia_em_sao_paulo(now()) - 1) AS fim
  ),
  gerados AS (
    SELECT dg.dia FROM public.diasgerados dg, lim
     WHERE dg.contaid = public.minha_conta() AND dg.dia BETWEEN lim.ini AND lim.fim
  ),
  itens AS (
    -- Dias com lista congelada.
    SELECT i.dia, i.atribuicaoid, i.tipofrequencia, t.titulo, i.pontos, l.nome AS loja
      FROM public.tarefasdodia i
      JOIN gerados g           ON g.dia = i.dia
      JOIN public.tarefas t    ON t.tarefaid = i.tarefaid
      LEFT JOIN public.lojas l ON l.lojaid = i.lojaid
     WHERE i.funcionarioid = p_funcionarioid
       AND i.situacao = 'devida'
       AND NOT EXISTS (SELECT 1 FROM public.entregas e
                        WHERE e.atribuicaoid = i.atribuicaoid
                          AND e.statusvalidacao IN ('Pendente', 'Aprovada')
                          AND (i.tipofrequencia = 'Unica' OR public.dia_em_sao_paulo(e.dataenvio) = i.dia))
    UNION ALL
    -- Dias sem lista: regra do cadastro.
    SELECT g.d::date, ta.atribuicaoid, ta.tipofrequencia, t.titulo, t.pontos, l.nome
      FROM public.tarefasatribuidas ta
      JOIN public.tarefas t      ON t.tarefaid = ta.tarefaid
      JOIN public.funcionarios f ON f.funcionarioid = ta.funcionarioid
      LEFT JOIN public.lojas l   ON l.lojaid = ta.lojaid
      CROSS JOIN lim
      CROSS JOIN LATERAL generate_series(
        greatest(lim.ini, coalesce(public.dia_em_sao_paulo(ta.dataatribuicao), lim.ini),
                 coalesce(ta.datainiciovigencia, lim.ini)),
        least(lim.fim, coalesce(ta.datafimvigencia - 1, lim.fim)),
        interval '1 day') AS g(d)
     WHERE ta.funcionarioid = p_funcionarioid
       AND ta.origematribuicaoid IS NULL
       AND ta.tipofrequencia IN ('Diaria', 'Semanal', 'Mensal')
       AND g.d::date NOT IN (SELECT dia FROM gerados)
       AND public.tarefa_cai_no_dia(ta.tipofrequencia, ta.valorfrequencia, ta.dataagendamento, g.d::date)
       AND public.dia_de_trabalho(f.diadefolga, f.domingofolgamensal,
                                  f.datainicioafastamento, f.datafimafastamento, g.d::date)
       AND NOT EXISTS (SELECT 1 FROM public.entregas e
                        WHERE e.atribuicaoid = ta.atribuicaoid
                          AND e.statusvalidacao IN ('Pendente', 'Aprovada')
                          AND public.dia_em_sao_paulo(e.dataenvio) = g.d::date)
    UNION ALL
    SELECT public.dia_em_sao_paulo(coalesce(ta.dataagendamento, ta.dataatribuicao)), ta.atribuicaoid,
           ta.tipofrequencia, t.titulo, t.pontos, l.nome
      FROM public.tarefasatribuidas ta
      JOIN public.tarefas t    ON t.tarefaid = ta.tarefaid
      LEFT JOIN public.lojas l ON l.lojaid = ta.lojaid
      CROSS JOIN lim
     WHERE ta.funcionarioid = p_funcionarioid
       AND ta.origematribuicaoid IS NULL
       AND ta.tipofrequencia = 'Unica'
       AND ta.datafimvigencia IS NULL
       AND public.dia_em_sao_paulo(coalesce(ta.dataagendamento, ta.dataatribuicao)) BETWEEN lim.ini AND lim.fim
       AND public.dia_em_sao_paulo(coalesce(ta.dataagendamento, ta.dataatribuicao)) NOT IN (SELECT dia FROM gerados)
       AND NOT EXISTS (SELECT 1 FROM public.entregas e
                        WHERE e.atribuicaoid = ta.atribuicaoid
                          AND e.statusvalidacao IN ('Pendente', 'Aprovada'))
  )
  SELECT coalesce(jsonb_agg(jsonb_build_object(
           'dia', i.dia, 'atribuicaoid', i.atribuicaoid, 'titulo', i.titulo, 'pontos', i.pontos, 'loja', i.loja,
           'justificativa', (SELECT j.status FROM public.justificativas j
                              WHERE j.atribuicaoid = i.atribuicaoid
                                AND (i.tipofrequencia = 'Unica' OR j.dia = i.dia)
                              ORDER BY j.justificativaid DESC LIMIT 1))
           ORDER BY i.dia DESC, i.titulo), '[]'::jsonb)
    FROM itens i
   WHERE NOT public.tem_justificativa(i.atribuicaoid, i.tipofrequencia, i.dia, true)
$$;

-- Também é chamada por registrar_justificativa (com poder total): por isso a
-- conta vem do próprio funcionário, não da sessão.
CREATE OR REPLACE FUNCTION public.justificaveis(p_funcionarioid integer, p_dia date)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
  WITH pessoa AS (
    SELECT f.contaid, f.diadefolga, f.domingofolgamensal, f.datainicioafastamento, f.datafimafastamento
      FROM public.funcionarios f WHERE f.funcionarioid = p_funcionarioid
  ),
  congelado AS (
    SELECT p_dia < public.dia_em_sao_paulo(now())
           AND EXISTS (SELECT 1 FROM public.diasgerados dg, pessoa
                        WHERE dg.contaid = pessoa.contaid AND dg.dia = p_dia) AS sim
  ),
  itens AS (
    -- Dia com lista congelada.
    SELECT i.atribuicaoid, t.titulo, i.pontos, l.nome AS loja
      FROM public.tarefasdodia i
      JOIN pessoa ON pessoa.contaid = i.contaid
      JOIN public.tarefas t    ON t.tarefaid = i.tarefaid
      LEFT JOIN public.lojas l ON l.lojaid = i.lojaid
      CROSS JOIN congelado
     WHERE congelado.sim
       AND i.funcionarioid = p_funcionarioid AND i.dia = p_dia AND i.situacao = 'devida'
       AND NOT public.tem_justificativa(i.atribuicaoid, i.tipofrequencia, p_dia, false)
       AND NOT EXISTS (SELECT 1 FROM public.entregas e
                        WHERE e.atribuicaoid = i.atribuicaoid
                          AND e.statusvalidacao IN ('Pendente', 'Aprovada')
                          AND (i.tipofrequencia = 'Unica' OR public.dia_em_sao_paulo(e.dataenvio) = p_dia))
    UNION ALL
    -- Hoje, ou dia sem lista: regra do cadastro.
    SELECT ta.atribuicaoid, t.titulo, t.pontos, l.nome
      FROM public.tarefasatribuidas ta
      JOIN public.tarefas t    ON t.tarefaid = ta.tarefaid
      LEFT JOIN public.lojas l ON l.lojaid = ta.lojaid
      CROSS JOIN pessoa
      CROSS JOIN congelado
     WHERE NOT congelado.sim
       AND ta.funcionarioid = p_funcionarioid
       AND ta.origematribuicaoid IS NULL
       AND p_dia <= public.dia_em_sao_paulo(now())
       AND public.dia_de_trabalho(pessoa.diadefolga, pessoa.domingofolgamensal,
                                  pessoa.datainicioafastamento, pessoa.datafimafastamento, p_dia)
       AND NOT public.tem_justificativa(ta.atribuicaoid, ta.tipofrequencia, p_dia, false)
       AND (
         (ta.tipofrequencia IN ('Diaria', 'Semanal', 'Mensal')
          AND public.tarefa_cai_no_dia(ta.tipofrequencia, ta.valorfrequencia, ta.dataagendamento, p_dia)
          AND p_dia >= coalesce(public.dia_em_sao_paulo(ta.dataatribuicao), p_dia)
          AND p_dia >= coalesce(ta.datainiciovigencia, p_dia)
          AND (ta.datafimvigencia IS NULL OR p_dia < ta.datafimvigencia)
          AND NOT EXISTS (SELECT 1 FROM public.entregas e
                           WHERE e.atribuicaoid = ta.atribuicaoid
                             AND e.statusvalidacao IN ('Pendente', 'Aprovada')
                             AND public.dia_em_sao_paulo(e.dataenvio) = p_dia))
         OR
         (ta.tipofrequencia = 'Unica'
          AND ta.datafimvigencia IS NULL
          AND public.dia_em_sao_paulo(coalesce(ta.dataagendamento, ta.dataatribuicao)) = p_dia
          AND NOT EXISTS (SELECT 1 FROM public.entregas e
                           WHERE e.atribuicaoid = ta.atribuicaoid
                             AND e.statusvalidacao IN ('Pendente', 'Aprovada')))
       )
  )
  SELECT coalesce(jsonb_agg(jsonb_build_object('atribuicaoid', atribuicaoid, 'titulo', titulo,
                                               'pontos', pontos, 'loja', loja) ORDER BY titulo), '[]'::jsonb)
    FROM itens
$$;

-- ---------------------------------------------------------------------------
-- 8. Tarefa passada para outra pessoa sai do quadro, do painel, da TV e do
--    Início de quem estava de folga (a tarefa nova aparece para quem recebeu).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.montar_painel(p_contaid integer, p_lojaid integer, p_tv boolean)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_hoje       date := public.dia_em_sao_paulo(now());
  v_loja       text;
  v_dia        jsonb;
  v_validacao  jsonb;
  v_pendentes  integer;
  v_podio      jsonb;
  v_atividade  jsonb;
BEGIN
  SELECT nome INTO v_loja FROM public.lojas WHERE lojaid = p_lojaid AND contaid = p_contaid;
  IF NOT FOUND THEN
    RETURN NULL;
  END IF;

  -- Tarefas do dia e a situacao de cada uma hoje.
  WITH dia AS (
    SELECT t.titulo,
           t.pontos,
           CASE WHEN p_tv THEN public.nome_curto(f.nomecompleto) ELSE f.nomecompleto END AS pessoa,
           (ta.tipofrequencia = 'Unica' AND ta.dataagendamento IS NOT NULL
            AND public.dia_em_sao_paulo(ta.dataagendamento) < v_hoje) AS atrasada,
           (SELECT e.statusvalidacao
              FROM public.entregas e
             WHERE e.atribuicaoid = ta.atribuicaoid
               AND e.statusvalidacao IN ('Pendente', 'Aprovada')
               AND public.dia_em_sao_paulo(e.dataenvio) = v_hoje
             ORDER BY e.entregaid DESC
             LIMIT 1) AS situacao
      FROM public.tarefasatribuidas ta
      JOIN public.tarefas t            ON t.tarefaid = ta.tarefaid
      JOIN public.funcionarios f       ON f.funcionarioid = ta.funcionarioid
      JOIN public.funcionarioslojas fl ON fl.funcionarioid = ta.funcionarioid AND fl.lojaid = ta.lojaid
     WHERE ta.contaid = p_contaid
       AND ta.lojaid = p_lojaid
       AND ta.datafimvigencia IS NULL
       AND f.ativo AND fl.ativo AND coalesce(t.ativa, true)
       AND public.tarefa_cai_no_dia(ta.tipofrequencia, ta.valorfrequencia, ta.dataagendamento, v_hoje)
       -- Justificada como "nao se aplica" (pendente ou aceita) nao e tarefa de hoje.
       AND NOT public.tem_justificativa(ta.atribuicaoid, ta.tipofrequencia, v_hoje, false)
       -- Passada hoje para quem está trabalhando: sai da lista de quem está de folga.
       AND NOT public.passada_hoje(ta.atribuicaoid, v_hoje)
       -- Unica entregue num dia anterior ja nao e tarefa de hoje.
       AND NOT (ta.tipofrequencia = 'Unica' AND EXISTS (
             SELECT 1 FROM public.entregas e2
              WHERE e2.atribuicaoid = ta.atribuicaoid
                AND e2.statusvalidacao IN ('Pendente', 'Aprovada')
                AND public.dia_em_sao_paulo(e2.dataenvio) < v_hoje))
  )
  SELECT jsonb_build_object(
           'total',       count(*),
           'aprovadas',   count(*) FILTER (WHERE situacao = 'Aprovada'),
           'emvalidacao', count(*) FILTER (WHERE situacao = 'Pendente'),
           'parafazer',   coalesce(
                            jsonb_agg(
                              jsonb_build_object('titulo', titulo, 'pessoa', pessoa,
                                                 'pontos', pontos, 'atrasada', atrasada)
                              ORDER BY atrasada DESC, pessoa, titulo
                            ) FILTER (WHERE situacao IS NULL),
                            '[]'::jsonb))
    INTO v_dia
    FROM dia;

  -- Em validacao: todas as pendentes da loja, de qualquer dia.
  SELECT count(*) INTO v_pendentes
    FROM public.entregas
   WHERE contaid = p_contaid AND lojaid = p_lojaid AND statusvalidacao = 'Pendente';

  SELECT coalesce(jsonb_agg(
           jsonb_build_object('titulo', titulo, 'pessoa', pessoa, 'pontos', pontos,
                              'enviadaem', dataenvio, 'dehoje', dehoje)
           ORDER BY dataenvio), '[]'::jsonb)
    INTO v_validacao
    FROM (
      SELECT t.titulo, t.pontos, e.dataenvio,
             CASE WHEN p_tv THEN public.nome_curto(f.nomecompleto) ELSE f.nomecompleto END AS pessoa,
             public.dia_em_sao_paulo(e.dataenvio) = v_hoje AS dehoje
        FROM public.entregas e
        JOIN public.tarefas t      ON t.tarefaid = e.tarefaid
        JOIN public.funcionarios f ON f.funcionarioid = e.funcionarioid
       WHERE e.contaid = p_contaid AND e.lojaid = p_lojaid AND e.statusvalidacao = 'Pendente'
       ORDER BY e.dataenvio
       LIMIT 50
    ) s;

  -- Podio do dia: pontos aprovados hoje na loja.
  SELECT coalesce(jsonb_agg(jsonb_build_object('pessoa', pessoa, 'pontos', pontos)
                            ORDER BY pontos DESC, pessoa), '[]'::jsonb)
    INTO v_podio
    FROM (
      SELECT CASE WHEN p_tv THEN public.nome_curto(f.nomecompleto) ELSE f.nomecompleto END AS pessoa,
             sum(e.pontosganhos)::integer AS pontos
        FROM public.entregas e
        JOIN public.funcionarios f ON f.funcionarioid = e.funcionarioid
       WHERE e.contaid = p_contaid AND e.lojaid = p_lojaid
         AND e.statusvalidacao = 'Aprovada'
         AND public.dia_em_sao_paulo(e.dataaprovacao) = v_hoje
       GROUP BY f.funcionarioid, f.nomecompleto
       ORDER BY sum(e.pontosganhos) DESC, f.nomecompleto
       LIMIT 3
    ) s;

  -- Atividade recente: as ultimas aprovacoes do dia.
  SELECT coalesce(jsonb_agg(jsonb_build_object('titulo', titulo, 'pessoa', pessoa,
                                               'pontos', pontos, 'aprovadaem', dataaprovacao)
                            ORDER BY dataaprovacao DESC), '[]'::jsonb)
    INTO v_atividade
    FROM (
      SELECT t.titulo, e.pontosganhos AS pontos, e.dataaprovacao,
             CASE WHEN p_tv THEN public.nome_curto(f.nomecompleto) ELSE f.nomecompleto END AS pessoa
        FROM public.entregas e
        JOIN public.tarefas t      ON t.tarefaid = e.tarefaid
        JOIN public.funcionarios f ON f.funcionarioid = e.funcionarioid
       WHERE e.contaid = p_contaid AND e.lojaid = p_lojaid
         AND e.statusvalidacao = 'Aprovada'
         AND public.dia_em_sao_paulo(e.dataaprovacao) = v_hoje
       ORDER BY e.dataaprovacao DESC
       LIMIT 10
    ) s;

  RETURN jsonb_build_object(
    'loja',         v_loja,
    'hoje',         v_hoje,
    'atualizadoem', now(),
    'progresso',    jsonb_build_object('total',       v_dia->'total',
                                       'aprovadas',   v_dia->'aprovadas',
                                       'emvalidacao', v_dia->'emvalidacao'),
    'parafazer',    v_dia->'parafazer',
    'emvalidacao',  v_validacao,
    'pendentes',    v_pendentes,
    'podio',        v_podio,
    'atividade',    v_atividade,
    'meta',         public.meta_para_painel(p_contaid, p_lojaid, p_tv),
    'agenda',       public.agenda_para_painel(p_contaid, p_lojaid, p_tv)
  );
END;
$$;
CREATE OR REPLACE FUNCTION public.painel_inicio(p_lojaid integer DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_hoje      date := public.dia_em_sao_paulo(now());
  v_mes_ini   date := date_trunc('month', public.dia_em_sao_paulo(now()))::date;
  v_mes_fim   date := (date_trunc('month', public.dia_em_sao_paulo(now())) + interval '1 month - 1 day')::date;
  v_sem_ini   date := (date_trunc('week', public.dia_em_sao_paulo(now())) - interval '7 weeks')::date;
  v_lojas     integer[];
  v_cartoes   jsonb;
  v_tarefas   jsonb;
  v_metadia   jsonb;
  v_metames   jsonb;
  v_vendas    jsonb;
  v_pontos    jsonb;
  v_entregas  jsonb;
  v_ranking   jsonb;
  v_agenda    jsonb;
  v_validar   jsonb;
  v_guia      jsonb;
BEGIN
  IF public.minha_conta() IS NULL THEN
    RAISE EXCEPTION 'Sem acesso.' USING ERRCODE = 'insufficient_privilege';
  END IF;

  -- Lojas consideradas: a escolhida ou todas as ativas (a RLS já limita à conta).
  IF p_lojaid IS NULL THEN
    SELECT coalesce(array_agg(lojaid), '{}') INTO v_lojas FROM public.lojas WHERE ativa;
  ELSE
    SELECT array_agg(lojaid) INTO v_lojas FROM public.lojas WHERE lojaid = p_lojaid;
    IF v_lojas IS NULL THEN
      RAISE EXCEPTION 'Loja não encontrada.' USING ERRCODE = 'no_data_found';
    END IF;
  END IF;

  -- Tarefas de hoje (mesma regra do painel da loja).
  WITH dia AS (
    SELECT (SELECT e.statusvalidacao
              FROM public.entregas e
             WHERE e.atribuicaoid = ta.atribuicaoid
               AND e.statusvalidacao IN ('Pendente', 'Aprovada')
               AND public.dia_em_sao_paulo(e.dataenvio) = v_hoje
             ORDER BY e.entregaid DESC
             LIMIT 1) AS situacao
      FROM public.tarefasatribuidas ta
      JOIN public.tarefas t            ON t.tarefaid = ta.tarefaid
      JOIN public.funcionarios f       ON f.funcionarioid = ta.funcionarioid
      JOIN public.funcionarioslojas fl ON fl.funcionarioid = ta.funcionarioid AND fl.lojaid = ta.lojaid
     WHERE ta.lojaid = ANY (v_lojas)
       AND ta.datafimvigencia IS NULL
       AND f.ativo AND fl.ativo AND coalesce(t.ativa, true)
       AND public.tarefa_cai_no_dia(ta.tipofrequencia, ta.valorfrequencia, ta.dataagendamento, v_hoje)
       AND NOT public.tem_justificativa(ta.atribuicaoid, ta.tipofrequencia, v_hoje, false)
       AND NOT public.passada_hoje(ta.atribuicaoid, v_hoje)
       AND NOT (ta.tipofrequencia = 'Unica' AND EXISTS (
             SELECT 1 FROM public.entregas e2
              WHERE e2.atribuicaoid = ta.atribuicaoid
                AND e2.statusvalidacao IN ('Pendente', 'Aprovada')
                AND public.dia_em_sao_paulo(e2.dataenvio) < v_hoje))
  )
  SELECT jsonb_build_object(
           'total',       count(*),
           'feitas',      count(*) FILTER (WHERE situacao IS NOT NULL),
           'aprovadas',   count(*) FILTER (WHERE situacao = 'Aprovada'),
           'emvalidacao', count(*) FILTER (WHERE situacao = 'Pendente'))
    INTO v_tarefas
    FROM dia;

  -- Meta do dia: soma das lojas que têm meta hoje.
  WITH m AS (
    SELECT coalesce(a.valormetadia, md.valormeta) AS meta,
           coalesce(a.valordia, 0)                AS vendido,
           a.apuracaoid IS NOT NULL               AS lancado
      FROM unnest(v_lojas) AS l(lojaid)
      LEFT JOIN public.metasdiariasapuracoes a ON a.lojaid = l.lojaid AND a.dataapuracao = v_hoje
      LEFT JOIN LATERAL public.meta_do_dia(l.lojaid, v_hoje) md ON true
  )
  SELECT CASE WHEN coalesce(sum(meta) FILTER (WHERE meta > 0), 0) > 0 THEN
           jsonb_build_object(
             'meta',       sum(meta) FILTER (WHERE meta > 0),
             'vendido',    sum(vendido) FILTER (WHERE meta > 0),
             'percentual', round(sum(vendido) FILTER (WHERE meta > 0) * 100 / sum(meta) FILTER (WHERE meta > 0), 1),
             'lancadas',   count(*) FILTER (WHERE meta > 0 AND lancado),
             'lojas',      count(*) FILTER (WHERE meta > 0))
         END
    INTO v_metadia
    FROM m;

  -- Meta do mês: soma das metas do mês das lojas.
  WITH m AS (
    SELECT mp.lojaid, mp.valormetatotal,
           (SELECT coalesce(sum(a.valordia), 0) FROM public.metasdiariasapuracoes a
             WHERE a.lojaid = mp.lojaid AND a.dataapuracao BETWEEN mp.datainicio AND mp.datafim) AS vendido
      FROM public.metasprincipais mp
     WHERE mp.lojaid = ANY (v_lojas) AND v_hoje BETWEEN mp.datainicio AND mp.datafim
  )
  SELECT CASE WHEN count(*) > 0 THEN
           jsonb_build_object(
             'meta',       sum(valormetatotal),
             'vendido',    sum(vendido),
             'percentual', round(sum(vendido) * 100 / nullif(sum(valormetatotal), 0), 1),
             'lojas',      count(*))
         END
    INTO v_metames
    FROM m;

  v_cartoes := jsonb_build_object(
    'tarefas',      v_tarefas,
    'metadia',      v_metadia,
    'metames',      v_metames,
    'validar',      (SELECT count(*) FROM public.entregas
                      WHERE lojaid = ANY (v_lojas) AND statusvalidacao = 'Pendente'),
    'agendahoje',   (SELECT count(*) FROM public.agendamentos
                      WHERE lojaid = ANY (v_lojas) AND statusagendamento <> 'Cancelado'
                        AND public.dia_em_sao_paulo(dataevento) = v_hoje),
    'comunicados',  (SELECT jsonb_build_object('comunicados', count(DISTINCT s.documentoid),
                                               'pessoas',     count(DISTINCT s.funcionarioid))
                       FROM public.documentosassinaturas s
                       JOIN public.documentos d   ON d.documentoid = s.documentoid AND d.status = 'Publicado'
                       JOIN public.funcionarios f ON f.funcionarioid = s.funcionarioid AND f.ativo
                      WHERE s.statusassinatura = 'Pendente'
                        AND (p_lojaid IS NULL OR EXISTS (
                              SELECT 1 FROM public.funcionarioslojas fl
                               WHERE fl.funcionarioid = s.funcionarioid AND fl.lojaid = p_lojaid AND fl.ativo))),
    'onboarding',   (SELECT count(*) FROM public.onboardingstatus o
                       JOIN public.funcionarios f ON f.funcionarioid = o.funcionarioid AND f.ativo
                      WHERE o.statusworkflow = 'Em andamento'
                        AND (p_lojaid IS NULL OR EXISTS (
                              SELECT 1 FROM public.funcionarioslojas fl
                               WHERE fl.funcionarioid = o.funcionarioid AND fl.lojaid = p_lojaid AND fl.ativo))),
    'solicitacoes', (SELECT count(*) FROM public.solicitacoesinternas
                      WHERE lojaid = ANY (v_lojas) AND status IN ('Aberta', 'Em andamento')),
    'justificativas', (SELECT count(*) FROM public.justificativas
                        WHERE lojaid = ANY (v_lojas) AND status = 'Pendente'));

  -- Vendas do mês, dia a dia, contra a meta (soma das lojas).
  WITH dias AS (
    SELECT g::date AS d FROM generate_series(v_mes_ini, v_mes_fim, interval '1 day') g
  ),
  linhas AS (
    SELECT d.d,
           sum(a.valordia)                            AS vendido,
           sum(coalesce(a.valormetadia, md.valormeta)) AS meta
      FROM dias d
      CROSS JOIN unnest(v_lojas) AS l(lojaid)
      LEFT JOIN public.metasdiariasapuracoes a ON a.lojaid = l.lojaid AND a.dataapuracao = d.d
      LEFT JOIN LATERAL public.meta_do_dia(l.lojaid, d.d) md ON true
     GROUP BY d.d
  )
  SELECT coalesce(jsonb_agg(jsonb_build_object('dia', d, 'vendido', vendido, 'meta', meta) ORDER BY d), '[]'::jsonb)
    INTO v_vendas
    FROM linhas;

  -- Pontos por semana (últimas 8, começando na segunda), pelo livro.
  -- Entraram: aprovações e bônus, já descontados os estornos.
  -- Saíram: resgates, já descontados cancelamentos e estornos de resgate.
  WITH semanas AS (
    SELECT g::date AS ini FROM generate_series(v_sem_ini, date_trunc('week', v_hoje)::date, interval '1 week') g
  ),
  mov AS (
    SELECT date_trunc('week', public.dia_em_sao_paulo(mv.datamovimento))::date AS ini, mv.tipo, mv.pontos
      FROM public.movimentospontos mv
     WHERE mv.datamovimento >= (v_sem_ini::timestamp AT TIME ZONE 'America/Sao_Paulo')
       AND (p_lojaid IS NULL OR mv.lojaid = p_lojaid)
  )
  SELECT coalesce(jsonb_agg(jsonb_build_object(
           'semana',   s.ini,
           'entraram', coalesce((SELECT sum(pontos) FROM mov
                                  WHERE mov.ini = s.ini
                                    AND tipo IN ('aprovacao', 'estorno_entrega', 'bonus', 'estorno_bonus')), 0),
           'sairam',   coalesce((SELECT -sum(pontos) FROM mov
                                  WHERE mov.ini = s.ini
                                    AND tipo IN ('resgate', 'cancelamento_resgate', 'estorno_resgate')), 0))
           ORDER BY s.ini), '[]'::jsonb)
    INTO v_pontos
    FROM semanas s;

  -- Entregas aprovadas x recusadas por semana do mês (pelo dia da decisão).
  WITH semanas AS (
    SELECT g::date AS ini
      FROM generate_series(date_trunc('week', v_mes_ini)::date, date_trunc('week', v_hoje)::date, interval '1 week') g
  ),
  dec AS (
    SELECT date_trunc('week', public.dia_em_sao_paulo(e.dataaprovacao))::date AS ini, 'a'::text AS r
      FROM public.entregas e
     WHERE e.lojaid = ANY (v_lojas) AND e.statusvalidacao = 'Aprovada'
       AND public.dia_em_sao_paulo(e.dataaprovacao) BETWEEN v_mes_ini AND v_hoje
    UNION ALL
    SELECT date_trunc('week', public.dia_em_sao_paulo(e.datarecusa))::date, 'r'
      FROM public.entregas e
     WHERE e.lojaid = ANY (v_lojas) AND e.statusvalidacao = 'Recusada'
       AND public.dia_em_sao_paulo(e.datarecusa) BETWEEN v_mes_ini AND v_hoje
  )
  SELECT coalesce(jsonb_agg(jsonb_build_object(
           'semana',    greatest(s.ini, v_mes_ini),
           'aprovadas', (SELECT count(*) FROM dec WHERE dec.ini = s.ini AND r = 'a'),
           'recusadas', (SELECT count(*) FROM dec WHERE dec.ini = s.ini AND r = 'r'))
           ORDER BY s.ini), '[]'::jsonb)
    INTO v_entregas
    FROM semanas s;

  -- Top 5 do mês (pontos aprovados no mês).
  SELECT coalesce(jsonb_agg(jsonb_build_object('nome', r.nomecompleto, 'pontos', r.pontos, 'entregas', r.entregas)
                            ORDER BY r.pontos DESC, r.nomecompleto), '[]'::jsonb)
    INTO v_ranking
    FROM (SELECT * FROM public.ranking_pontos(v_mes_ini, v_hoje, p_lojaid) LIMIT 5) r;

  -- Próximos agendamentos: hora, tipo e responsável (sem dados do cliente).
  SELECT coalesce(jsonb_agg(jsonb_build_object(
           'quando', s.dataevento, 'tipo', s.tipoevento, 'responsavel', s.responsavel, 'loja', s.loja)
           ORDER BY s.dataevento), '[]'::jsonb)
    INTO v_agenda
    FROM (
      SELECT a.dataevento, a.tipoevento, l.nome AS loja,
             split_part(btrim(f.nomecompleto), ' ', 1) AS responsavel
        FROM public.agendamentos a
        JOIN public.lojas l             ON l.lojaid = a.lojaid
        LEFT JOIN public.funcionarios f ON f.funcionarioid = a.funcionarioid
       WHERE a.lojaid = ANY (v_lojas) AND a.statusagendamento = 'Confirmado'
         AND a.dataevento >= now() - interval '1 hour'
       ORDER BY a.dataevento
       LIMIT 5
    ) s;

  -- Últimas entregas esperando validação.
  SELECT coalesce(jsonb_agg(jsonb_build_object(
           'titulo', s.titulo, 'pessoa', s.pessoa, 'pontos', s.pontos, 'enviadaem', s.dataenvio, 'loja', s.loja)
           ORDER BY s.dataenvio DESC), '[]'::jsonb)
    INTO v_validar
    FROM (
      SELECT t.titulo, e.pontosganhos AS pontos, e.dataenvio, l.nome AS loja,
             public.nome_curto(f.nomecompleto) AS pessoa
        FROM public.entregas e
        JOIN public.tarefas t      ON t.tarefaid = e.tarefaid
        JOIN public.funcionarios f ON f.funcionarioid = e.funcionarioid
        JOIN public.lojas l        ON l.lojaid = e.lojaid
       WHERE e.lojaid = ANY (v_lojas) AND e.statusvalidacao = 'Pendente'
       ORDER BY e.dataenvio DESC
       LIMIT 5
    ) s;

  -- Guia de primeiros passos (vale para a conta toda).
  v_guia := jsonb_build_object(
    'loja',    EXISTS (SELECT 1 FROM public.lojas WHERE ativa),
    'equipe',  EXISTS (SELECT 1 FROM public.funcionarios f
                         JOIN public.funcionarioslojas fl ON fl.funcionarioid = f.funcionarioid AND fl.ativo
                        WHERE f.ativo),
    'tarefas', EXISTS (SELECT 1 FROM public.tarefasatribuidas ta
                         JOIN public.tarefas t ON t.tarefaid = ta.tarefaid
                        WHERE ta.datafimvigencia IS NULL AND t.sistema IS NULL),
    'meta',    EXISTS (SELECT 1 FROM public.metasdiariasmodelos WHERE valormeta > 0)
               OR EXISTS (SELECT 1 FROM public.metasprincipais),
    'tv',      EXISTS (SELECT 1 FROM public.linkstv WHERE revogadoem IS NULL));

  RETURN jsonb_build_object(
    'hoje',         v_hoje,
    'atualizadoem', now(),
    'cartoes',      v_cartoes,
    'vendas',       v_vendas,
    'pontos',       v_pontos,
    'entregas',     v_entregas,
    'ranking',      v_ranking,
    'agenda',       v_agenda,
    'validar',      v_validar,
    'guia',         v_guia);
END;
$$;
CREATE OR REPLACE FUNCTION public.atribuicoes_para_entregar(p_lojaid integer)
RETURNS TABLE (
  atribuicaoid    integer,
  titulo          varchar,
  pontos          integer,
  funcionarioid   integer,
  nomecompleto    varchar,
  tipofrequencia  varchar,
  atrasada        boolean
)
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
  WITH hoje AS (SELECT public.dia_em_sao_paulo(now()) AS dia)
  SELECT ta.atribuicaoid, t.titulo, t.pontos, f.funcionarioid, f.nomecompleto, ta.tipofrequencia,
         (ta.tipofrequencia = 'Unica'
          AND ta.dataagendamento IS NOT NULL
          AND public.dia_em_sao_paulo(ta.dataagendamento) < hoje.dia) AS atrasada
  FROM public.tarefasatribuidas ta
  CROSS JOIN hoje
  JOIN public.tarefas t      ON t.tarefaid = ta.tarefaid
  JOIN public.funcionarios f ON f.funcionarioid = ta.funcionarioid
  WHERE ta.lojaid = p_lojaid
    AND ta.datafimvigencia IS NULL
    AND ta.funcionarioid IS NOT NULL
    AND public.tarefa_cai_no_dia(ta.tipofrequencia, ta.valorfrequencia, ta.dataagendamento, hoje.dia)
    AND NOT public.tem_justificativa(ta.atribuicaoid, ta.tipofrequencia, hoje.dia, false)
    AND NOT public.passada_hoje(ta.atribuicaoid, hoje.dia)
    AND NOT EXISTS (
      SELECT 1 FROM public.entregas e
      WHERE e.atribuicaoid = ta.atribuicaoid
        AND e.statusvalidacao IN ('Pendente', 'Aprovada')
        AND (ta.tipofrequencia = 'Unica' OR public.dia_em_sao_paulo(e.dataenvio) = hoje.dia)
    )
  ORDER BY f.nomecompleto, t.titulo
$$;

-- ---------------------------------------------------------------------------
-- 9. Permissões (negadas por padrão)
-- ---------------------------------------------------------------------------
REVOKE ALL ON FUNCTION public.rotina_hora_local(timestamptz, text)                    FROM public, anon, authenticated;
REVOKE ALL ON FUNCTION public.rotina_horario(integer, text, time)                     FROM public, anon, authenticated;
REVOKE ALL ON FUNCTION public.rotina_registrar(integer, text, date, text, timestamptz, text, jsonb, text, boolean)
                                                                                      FROM public, anon, authenticated;
REVOKE ALL ON FUNCTION public.item_tratado(integer, varchar, date, integer)           FROM public, anon, authenticated;
REVOKE ALL ON FUNCTION public.lista_do_dia_gerar(integer, date, date, boolean)        FROM public, anon, authenticated;
REVOKE ALL ON FUNCTION public.rotina_lista_do_dia(integer, timestamptz, text)         FROM public, anon, authenticated;
REVOKE ALL ON FUNCTION public.protege_lista_do_dia()                                  FROM public, anon, authenticated;
REVOKE ALL ON FUNCTION public.entrega_nao_passada()                                   FROM public, anon, authenticated;

-- Com a permissão de quem chama (a RLS vale): outra conta devolve vazio.
REVOKE ALL ON FUNCTION public.lista_candidatos(integer, date)                         FROM public, anon;
REVOKE ALL ON FUNCTION public.ranking_mensal_da_conta(integer, integer, integer, integer, date) FROM public, anon;
REVOKE ALL ON FUNCTION public.passada_hoje(integer, date)                             FROM public, anon;
REVOKE ALL ON FUNCTION public.tarefas_de_folga_hoje(integer)                          FROM public, anon;
REVOKE ALL ON FUNCTION public.quem_trabalha_hoje(integer)                             FROM public, anon;
GRANT EXECUTE ON FUNCTION public.lista_candidatos(integer, date)                      TO authenticated;
GRANT EXECUTE ON FUNCTION public.ranking_mensal_da_conta(integer, integer, integer, integer, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.passada_hoje(integer, date)                          TO authenticated;
GRANT EXECUTE ON FUNCTION public.tarefas_de_folga_hoje(integer)                       TO authenticated;
GRANT EXECUTE ON FUNCTION public.quem_trabalha_hoje(integer)                          TO authenticated;

-- Conferem quem chamou (sem receber conta nem loja).
REVOKE ALL ON FUNCTION public.rodar_geracao_hoje()                                    FROM public, anon;
REVOKE ALL ON FUNCTION public.passar_tarefa_de_folga(integer, integer)                FROM public, anon;
GRANT EXECUTE ON FUNCTION public.rodar_geracao_hoje()                                 TO authenticated;
GRANT EXECUTE ON FUNCTION public.passar_tarefa_de_folga(integer, integer)             TO authenticated;
