-- Fase 7, parte 1: livro de movimentos de pontos, loja de premios, resgates,
-- abate na comanda e extrato.
-- Decisoes do Wisley em 21/09/2026, registradas em docs/PLANO_MIGRACAO.md.

-- ===========================================================================
-- 0. "R$ 15,50"
-- ===========================================================================

CREATE OR REPLACE FUNCTION public.reais(p_valor numeric)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = public, pg_temp
AS $$
  SELECT 'R$ ' || replace(to_char(round(p_valor, 2), 'FM999999990.00'), '.', ',')
$$;

-- ===========================================================================
-- 1. O livro de movimentos (nivel conta; a loja e opcional).
--    Toda entrada e toda saida de pontos vira uma linha aqui, que NUNCA e
--    alterada nem apagada. O saldo e a soma destas linhas.
-- ===========================================================================

CREATE TABLE public.movimentospontos (
  movimentoid   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contaid       integer NOT NULL DEFAULT public.minha_conta() REFERENCES public.contas(contaid) ON DELETE RESTRICT,
  funcionarioid integer NOT NULL,
  lojaid        integer,
  datamovimento timestamptz NOT NULL DEFAULT now(),
  tipo          varchar(30) NOT NULL CHECK (tipo IN (
                  'aprovacao', 'estorno_entrega', 'bonus',
                  'resgate', 'cancelamento_resgate', 'estorno_resgate',
                  'ajuste_abertura')),
  pontos        integer NOT NULL CHECK (pontos <> 0),
  descricao     text NOT NULL,
  entregaid     integer,
  resgateid     integer,
  criadopor     uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  CONSTRAINT movimentospontos_funcionario_fk FOREIGN KEY (contaid, funcionarioid)
    REFERENCES public.funcionarios (contaid, funcionarioid) ON DELETE RESTRICT,
  CONSTRAINT movimentospontos_loja_fk FOREIGN KEY (contaid, lojaid)
    REFERENCES public.lojas (contaid, lojaid) ON DELETE RESTRICT,
  CONSTRAINT movimentospontos_entrega_fk FOREIGN KEY (contaid, entregaid)
    REFERENCES public.entregas (contaid, entregaid) ON DELETE RESTRICT,
  CONSTRAINT movimentospontos_resgate_fk FOREIGN KEY (contaid, resgateid)
    REFERENCES public.resgates (contaid, resgateid) ON DELETE RESTRICT
);

CREATE INDEX movimentospontos_contaid_idx ON public.movimentospontos (contaid);
CREATE INDEX movimentospontos_lojaid_idx  ON public.movimentospontos (lojaid);
CREATE INDEX movimentospontos_extrato_idx ON public.movimentospontos (funcionarioid, datamovimento, movimentoid);

ALTER TABLE public.movimentospontos ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.movimentospontos FROM anon, authenticated;
GRANT SELECT ON public.movimentospontos TO authenticated;
GRANT ALL ON public.movimentospontos TO service_role;
CREATE POLICY movimentospontos_sel ON public.movimentospontos FOR SELECT TO authenticated
  USING (contaid = (select public.minha_conta()));

-- Nunca se altera nem se apaga um movimento: corrige-se com outro movimento.
CREATE OR REPLACE FUNCTION public.movimento_e_imutavel()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
BEGIN
  RAISE EXCEPTION 'Movimento de pontos não pode ser alterado nem apagado. Registre outro movimento.'
    USING ERRCODE = 'restrict_violation';
END;
$$;

CREATE TRIGGER movimentospontos_imutavel
  BEFORE UPDATE OR DELETE ON public.movimentospontos
  FOR EACH ROW EXECUTE FUNCTION public.movimento_e_imutavel();

-- ===========================================================================
-- 2. O UNICO caminho que altera o saldo: gravar um movimento.
--    Este gatilho soma o movimento em saldopontos (e em pontostotal, quando e
--    ponto ganho). Ele avisa que e ele quem esta mexendo, e o protetor abaixo
--    so deixa passar alteracao de saldo que venha daqui.
-- ===========================================================================

CREATE OR REPLACE FUNCTION public.aplica_movimento_no_saldo()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_linhas integer;
BEGIN
  PERFORM set_config('gamegb.aplicando_movimento', 'sim', true);

  UPDATE public.funcionarios
     SET saldopontos = saldopontos + NEW.pontos,
         pontostotal = coalesce(pontostotal, 0)
                       + CASE WHEN NEW.tipo IN ('aprovacao', 'estorno_entrega', 'bonus') THEN NEW.pontos ELSE 0 END
   WHERE funcionarioid = NEW.funcionarioid AND contaid = NEW.contaid;
  -- Guardado antes do PERFORM seguinte, que sobrescreveria o FOUND.
  GET DIAGNOSTICS v_linhas = ROW_COUNT;

  PERFORM set_config('gamegb.aplicando_movimento', 'nao', true);

  IF v_linhas = 0 THEN
    RAISE EXCEPTION 'Funcionário do movimento não encontrado.' USING ERRCODE = 'foreign_key_violation';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER movimentospontos_aplica
  AFTER INSERT ON public.movimentospontos
  FOR EACH ROW EXECUTE FUNCTION public.aplica_movimento_no_saldo();

-- ===========================================================================
-- 3. Os dados que ja existem: o livro nasce a partir das entregas aprovadas e
--    estornadas. Se o saldo de alguem nao bater, entra um "Ajuste de abertura"
--    visivel, nunca uma diferenca escondida.
-- ===========================================================================

CREATE TEMP TABLE saldo_anterior AS
  SELECT funcionarioid, contaid, saldopontos AS saldo FROM public.funcionarios;

UPDATE public.funcionarios SET saldopontos = 0, pontostotal = 0
 WHERE saldopontos <> 0 OR coalesce(pontostotal, 0) <> 0;

INSERT INTO public.movimentospontos (contaid, funcionarioid, lojaid, datamovimento, tipo, pontos, descricao, entregaid, criadopor)
SELECT e.contaid, e.funcionarioid, e.lojaid, coalesce(e.dataaprovacao, e.dataenvio), 'aprovacao',
       e.pontosganhos, 'Tarefa aprovada: ' || t.titulo, e.entregaid, e.aprovadopor
  FROM public.entregas e
  JOIN public.tarefas t ON t.tarefaid = e.tarefaid
 WHERE e.statusvalidacao IN ('Aprovada', 'Estornada') AND coalesce(e.pontosganhos, 0) <> 0
 ORDER BY coalesce(e.dataaprovacao, e.dataenvio);

INSERT INTO public.movimentospontos (contaid, funcionarioid, lojaid, datamovimento, tipo, pontos, descricao, entregaid, criadopor)
SELECT e.contaid, e.funcionarioid, e.lojaid, coalesce(e.dataestorno, now()), 'estorno_entrega',
       -e.pontosganhos, 'Estorno: ' || t.titulo, e.entregaid, e.estornadopor
  FROM public.entregas e
  JOIN public.tarefas t ON t.tarefaid = e.tarefaid
 WHERE e.statusvalidacao = 'Estornada' AND coalesce(e.pontosganhos, 0) <> 0
 ORDER BY e.dataestorno;

INSERT INTO public.movimentospontos (contaid, funcionarioid, tipo, pontos, descricao)
SELECT a.contaid, a.funcionarioid, 'ajuste_abertura', a.saldo - f.saldopontos,
       'Ajuste de abertura do extrato (saldo anterior ao livro de movimentos)'
  FROM saldo_anterior a
  JOIN public.funcionarios f ON f.funcionarioid = a.funcionarioid
 WHERE a.saldo <> f.saldopontos;

DROP TABLE saldo_anterior;

-- ===========================================================================
-- 4. Protetor do saldo. Qualquer INSERT ou UPDATE em funcionarios que mexa em
--    saldopontos/pontostotal e recusado, a menos que venha do gatilho acima.
--    Vale para o navegador, para funcoes com poder total, para o servidor e
--    ate para o dono do banco. Regra permanente: ver CLAUDE.md.
-- ===========================================================================

CREATE OR REPLACE FUNCTION public.protege_saldo()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
DECLARE
  pelo_livro boolean := current_setting('gamegb.aplicando_movimento', true) = 'sim'
                        AND pg_trigger_depth() >= 2;
BEGIN
  IF pelo_livro THEN
    RETURN NEW;
  END IF;

  IF TG_OP = 'INSERT' AND (coalesce(NEW.saldopontos, 0) <> 0 OR coalesce(NEW.pontostotal, 0) <> 0) THEN
    RAISE EXCEPTION 'Funcionário novo começa com saldo zero. Pontos só entram pelo livro de movimentos.'
      USING ERRCODE = 'restrict_violation';
  END IF;

  IF TG_OP = 'UPDATE' AND (NEW.saldopontos IS DISTINCT FROM OLD.saldopontos
                        OR NEW.pontostotal IS DISTINCT FROM OLD.pontostotal) THEN
    RAISE EXCEPTION 'O saldo só muda gravando um movimento em movimentospontos.'
      USING ERRCODE = 'restrict_violation';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER funcionarios_protege_saldo
  BEFORE INSERT OR UPDATE ON public.funcionarios
  FOR EACH ROW EXECUTE FUNCTION public.protege_saldo();

-- ===========================================================================
-- 5. Aprovar e estornar entrega passam a gravar o movimento em vez de mexer
--    no saldo direto. Comportamento para quem usa: o mesmo.
-- ===========================================================================

CREATE OR REPLACE FUNCTION public.aprovar_entrega(p_entregaid integer)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_conta   integer := public.minha_conta_editavel();
  v_entrega public.entregas%ROWTYPE;
  v_pontos  integer;
  v_titulo  text;
BEGIN
  IF v_conta IS NULL THEN
    RAISE EXCEPTION 'Sua conta não pode alterar dados no momento.' USING ERRCODE = 'insufficient_privilege';
  END IF;

  SELECT * INTO v_entrega FROM public.entregas
   WHERE entregaid = p_entregaid AND contaid = v_conta
     FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Entrega não encontrada.' USING ERRCODE = 'no_data_found';
  END IF;

  IF v_entrega.statusvalidacao <> 'Pendente' THEN
    RAISE EXCEPTION 'Só uma entrega pendente pode ser aprovada. Esta está: %.', v_entrega.statusvalidacao
      USING ERRCODE = 'check_violation';
  END IF;

  SELECT pontos, titulo INTO v_pontos, v_titulo FROM public.tarefas
   WHERE tarefaid = v_entrega.tarefaid AND contaid = v_conta;

  UPDATE public.entregas
     SET statusvalidacao = 'Aprovada', pontosganhos = v_pontos,
         dataaprovacao = now(), aprovadopor = auth.uid()
   WHERE entregaid = p_entregaid;

  IF v_pontos <> 0 THEN
    INSERT INTO public.movimentospontos (contaid, funcionarioid, lojaid, tipo, pontos, descricao, entregaid, criadopor)
    VALUES (v_conta, v_entrega.funcionarioid, v_entrega.lojaid, 'aprovacao', v_pontos,
            'Tarefa aprovada: ' || v_titulo, p_entregaid, auth.uid());
  END IF;

  PERFORM public.apos_aprovar_entrega(p_entregaid);
  RETURN v_pontos;
END;
$$;

CREATE OR REPLACE FUNCTION public.estornar_entrega(p_entregaid integer, p_motivo text)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_conta   integer := public.minha_conta_editavel();
  v_entrega public.entregas%ROWTYPE;
  v_titulo  text;
  v_saldo   integer;
BEGIN
  IF v_conta IS NULL THEN
    RAISE EXCEPTION 'Sua conta não pode alterar dados no momento.' USING ERRCODE = 'insufficient_privilege';
  END IF;

  IF length(btrim(coalesce(p_motivo, ''))) = 0 THEN
    RAISE EXCEPTION 'Informe o motivo do estorno.' USING ERRCODE = 'check_violation';
  END IF;

  SELECT * INTO v_entrega FROM public.entregas
   WHERE entregaid = p_entregaid AND contaid = v_conta
     FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Entrega não encontrada.' USING ERRCODE = 'no_data_found';
  END IF;

  IF v_entrega.statusvalidacao <> 'Aprovada' THEN
    RAISE EXCEPTION 'Só uma entrega aprovada pode ser estornada. Esta está: %.', v_entrega.statusvalidacao
      USING ERRCODE = 'check_violation';
  END IF;

  SELECT titulo INTO v_titulo FROM public.tarefas WHERE tarefaid = v_entrega.tarefaid;

  UPDATE public.entregas
     SET statusvalidacao = 'Estornada', motivoestorno = btrim(p_motivo),
         dataestorno = now(), estornadopor = auth.uid()
   WHERE entregaid = p_entregaid;

  IF coalesce(v_entrega.pontosganhos, 0) <> 0 THEN
    INSERT INTO public.movimentospontos (contaid, funcionarioid, lojaid, tipo, pontos, descricao, entregaid, criadopor)
    VALUES (v_conta, v_entrega.funcionarioid, v_entrega.lojaid, 'estorno_entrega', -v_entrega.pontosganhos,
            'Estorno: ' || v_titulo || ' (' || btrim(p_motivo) || ')', p_entregaid, auth.uid());
  END IF;

  SELECT saldopontos INTO v_saldo FROM public.funcionarios WHERE funcionarioid = v_entrega.funcionarioid;
  RETURN v_saldo;
END;
$$;

-- ===========================================================================
-- 6. Premios. Estoque em branco = ilimitado; 0 = esgotado.
--    O "Abate na comanda" e um premio do sistema, escondido do catalogo.
-- ===========================================================================

ALTER TABLE public.produtosloja ADD COLUMN sistema varchar(40)
  CHECK (sistema IS NULL OR sistema IN ('abate_comanda'));
CREATE UNIQUE INDEX produtosloja_sistema_por_conta
  ON public.produtosloja (contaid, sistema) WHERE sistema IS NOT NULL;

ALTER TABLE public.produtosloja ADD CONSTRAINT produtosloja_estoque_valido
  CHECK (estoquedisponivel IS NULL OR estoquedisponivel >= 0);
ALTER TABLE public.produtosloja ADD CONSTRAINT produtosloja_custo_valido
  CHECK (sistema IS NOT NULL OR custoempontos > 0);

-- O navegador cadastra e edita o catalogo, mas nao marca premio do sistema.
REVOKE INSERT, UPDATE ON public.produtosloja FROM anon, authenticated;
GRANT INSERT (nome, descricao, custoempontos, estoquedisponivel, ativo) ON public.produtosloja TO authenticated;
GRANT UPDATE (nome, descricao, custoempontos, estoquedisponivel, ativo) ON public.produtosloja TO authenticated;

CREATE OR REPLACE FUNCTION public.protege_premio_do_sistema()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
BEGIN
  IF OLD.sistema IS NOT NULL THEN
    RAISE EXCEPTION 'O prêmio "%" é do sistema e não pode ser apagado.', OLD.nome USING ERRCODE = 'restrict_violation';
  END IF;
  RETURN OLD;
END;
$$;

CREATE TRIGGER produtosloja_protege_sistema
  BEFORE DELETE ON public.produtosloja
  FOR EACH ROW EXECUTE FUNCTION public.protege_premio_do_sistema();

CREATE OR REPLACE FUNCTION public.cria_produtos_do_sistema(p_contaid integer)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  INSERT INTO public.produtosloja (contaid, nome, descricao, custoempontos, estoquedisponivel, ativo, sistema)
  VALUES (p_contaid, 'Abate na comanda', 'Pontos usados como dinheiro para abater o consumo na comanda.',
          0, NULL, true, 'abate_comanda')
  ON CONFLICT (contaid, sistema) WHERE sistema IS NOT NULL DO NOTHING;
$$;

DO $$
DECLARE c record;
BEGIN
  FOR c IN SELECT contaid FROM public.contas LOOP
    PERFORM public.cria_produtos_do_sistema(c.contaid);
  END LOOP;
END $$;

-- ===========================================================================
-- 7. Resgates: Pendente -> Entregue, Pendente -> Cancelado, Entregue -> Estornado.
--    Na comanda, o resgate guarda o valor em R$ e a taxa usada: mudar a taxa
--    depois so vale para comandas novas.
-- ===========================================================================

UPDATE public.resgates SET status = 'Entregue'  WHERE status = 'Aprovado';
UPDATE public.resgates SET status = 'Cancelado' WHERE status = 'Recusado';

ALTER TABLE public.resgates
  ADD COLUMN valorreais        numeric(10,2),
  ADD COLUMN taxaconversao     numeric(10,4),
  ADD COLUMN registradopor     uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  ADD COLUMN dataentrega       timestamptz,
  ADD COLUMN entreguepor       uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  ADD COLUMN datacancelamento  timestamptz,
  ADD COLUMN canceladopor      uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  ADD COLUMN motivocancelamento text,
  ADD COLUMN dataestorno       timestamptz,
  ADD COLUMN estornadopor      uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  ADD COLUMN motivoestorno     text;

ALTER TABLE public.resgates ADD CONSTRAINT resgates_status_valido
  CHECK (status IN ('Pendente', 'Entregue', 'Cancelado', 'Estornado'));
ALTER TABLE public.resgates ADD CONSTRAINT resgates_cancelamento_tem_motivo
  CHECK (status <> 'Cancelado' OR length(btrim(coalesce(motivocancelamento, ''))) > 0);
ALTER TABLE public.resgates ADD CONSTRAINT resgates_estorno_tem_motivo
  CHECK (status <> 'Estornado' OR length(btrim(coalesce(motivoestorno, ''))) > 0);
ALTER TABLE public.resgates ADD CONSTRAINT resgates_pontos_positivos CHECK (pontosgastos > 0);

-- Resgate so muda pelas funcoes.
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON public.resgates FROM anon, authenticated;

-- Le a taxa ponto -> real da conta. NULL se nao estiver configurada direito.
CREATE OR REPLACE FUNCTION public.taxa_da_conta(p_contaid integer)
RETURNS numeric
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE v_texto text; v_taxa numeric;
BEGIN
  SELECT valor INTO v_texto FROM public.configuracoes
   WHERE contaid = p_contaid AND chave = 'TAXA_CONVERSAO_PONTO_REAL';
  BEGIN
    v_taxa := nullif(replace(btrim(coalesce(v_texto, '')), ',', '.'), '')::numeric;
  EXCEPTION WHEN others THEN
    v_taxa := NULL;
  END;
  RETURN CASE WHEN v_taxa > 0 THEN v_taxa END;
END;
$$;

-- A taxa da conta de quem esta logado, lida com a RLS dele (nunca a de outro).
CREATE OR REPLACE FUNCTION public.minha_taxa()
RETURNS numeric
LANGUAGE plpgsql
STABLE
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
DECLARE v_texto text; v_taxa numeric;
BEGIN
  SELECT valor INTO v_texto FROM public.configuracoes WHERE chave = 'TAXA_CONVERSAO_PONTO_REAL';
  BEGIN
    v_taxa := nullif(replace(btrim(coalesce(v_texto, '')), ',', '.'), '')::numeric;
  EXCEPTION WHEN others THEN
    v_taxa := NULL;
  END;
  RETURN CASE WHEN v_taxa > 0 THEN v_taxa END;
END;
$$;

-- Resgate de um premio do catalogo.
-- Trava a pessoa e depois o premio (sempre nesta ordem, para dois resgates
-- simultaneos esperarem um pelo outro em vez de se atropelarem).
CREATE OR REPLACE FUNCTION public.registrar_resgate(
  p_funcionarioid integer,
  p_produtoid     integer,
  p_lojaid        integer DEFAULT NULL,
  p_entregar      boolean DEFAULT true
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_conta integer := public.minha_conta_editavel();
  v_func  public.funcionarios%ROWTYPE;
  v_prod  public.produtosloja%ROWTYPE;
  v_id    integer;
BEGIN
  IF v_conta IS NULL THEN
    RAISE EXCEPTION 'Sua conta não pode alterar dados no momento.' USING ERRCODE = 'insufficient_privilege';
  END IF;

  SELECT * INTO v_func FROM public.funcionarios
   WHERE funcionarioid = p_funcionarioid AND contaid = v_conta
     FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Funcionário não encontrado.' USING ERRCODE = 'no_data_found';
  END IF;
  IF NOT v_func.ativo THEN
    RAISE EXCEPTION 'Funcionário inativo não resgata prêmios.' USING ERRCODE = 'check_violation';
  END IF;

  SELECT * INTO v_prod FROM public.produtosloja
   WHERE produtoid = p_produtoid AND contaid = v_conta
     FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Prêmio não encontrado.' USING ERRCODE = 'no_data_found';
  END IF;
  IF v_prod.sistema IS NOT NULL THEN
    RAISE EXCEPTION 'Para abater na comanda, use o abate na comanda.' USING ERRCODE = 'check_violation';
  END IF;
  IF NOT v_prod.ativo THEN
    RAISE EXCEPTION 'O prêmio "%" está desativado.', v_prod.nome USING ERRCODE = 'check_violation';
  END IF;
  IF v_prod.estoquedisponivel IS NOT NULL AND v_prod.estoquedisponivel <= 0 THEN
    RAISE EXCEPTION 'Esgotado: não há mais "%" em estoque.', v_prod.nome USING ERRCODE = 'check_violation';
  END IF;
  IF v_func.saldopontos < v_prod.custoempontos THEN
    RAISE EXCEPTION 'Saldo insuficiente: % tem % pontos e "%" custa %.',
      v_func.nomecompleto, v_func.saldopontos, v_prod.nome, v_prod.custoempontos
      USING ERRCODE = 'check_violation';
  END IF;
  IF p_lojaid IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.lojas WHERE lojaid = p_lojaid AND contaid = v_conta) THEN
    RAISE EXCEPTION 'Loja não encontrada.' USING ERRCODE = 'no_data_found';
  END IF;

  INSERT INTO public.resgates (contaid, funcionarioid, produtoid, lojaid, pontosgastos, datasolicitacao,
                               status, registradopor, dataentrega, entreguepor)
  VALUES (v_conta, p_funcionarioid, p_produtoid, p_lojaid, v_prod.custoempontos, now(),
          CASE WHEN p_entregar THEN 'Entregue' ELSE 'Pendente' END, auth.uid(),
          CASE WHEN p_entregar THEN now() END, CASE WHEN p_entregar THEN auth.uid() END)
  RETURNING resgateid INTO v_id;

  IF v_prod.estoquedisponivel IS NOT NULL THEN
    UPDATE public.produtosloja SET estoquedisponivel = estoquedisponivel - 1 WHERE produtoid = p_produtoid;
  END IF;

  INSERT INTO public.movimentospontos (contaid, funcionarioid, lojaid, tipo, pontos, descricao, resgateid, criadopor)
  VALUES (v_conta, p_funcionarioid, p_lojaid, 'resgate', -v_prod.custoempontos,
          'Resgate: ' || v_prod.nome, v_id, auth.uid());

  RETURN v_id;
END;
$$;

-- Abate na comanda: pontos = valor / taxa, arredondado PARA CIMA.
CREATE OR REPLACE FUNCTION public.registrar_abate_comanda(
  p_funcionarioid integer,
  p_valorreais    numeric,
  p_lojaid        integer DEFAULT NULL,
  p_entregar      boolean DEFAULT true
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_conta   integer := public.minha_conta_editavel();
  v_func    public.funcionarios%ROWTYPE;
  v_produto integer;
  v_valor   numeric(10,2) := round(p_valorreais, 2);
  v_taxa    numeric;
  v_pontos  integer;
  v_id      integer;
BEGIN
  IF v_conta IS NULL THEN
    RAISE EXCEPTION 'Sua conta não pode alterar dados no momento.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF v_valor IS NULL OR v_valor <= 0 THEN
    RAISE EXCEPTION 'Informe um valor maior que zero.' USING ERRCODE = 'check_violation';
  END IF;

  v_taxa := public.taxa_da_conta(v_conta);
  IF v_taxa IS NULL THEN
    RAISE EXCEPTION 'A taxa de conversão de pontos em reais não está configurada.' USING ERRCODE = 'check_violation';
  END IF;
  v_pontos := ceil(v_valor / v_taxa)::integer;

  SELECT * INTO v_func FROM public.funcionarios
   WHERE funcionarioid = p_funcionarioid AND contaid = v_conta
     FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Funcionário não encontrado.' USING ERRCODE = 'no_data_found';
  END IF;
  IF NOT v_func.ativo THEN
    RAISE EXCEPTION 'Funcionário inativo não resgata prêmios.' USING ERRCODE = 'check_violation';
  END IF;
  IF v_func.saldopontos < v_pontos THEN
    RAISE EXCEPTION 'Saldo insuficiente: % tem % pontos (%) e abater % custa % pontos.',
      v_func.nomecompleto, v_func.saldopontos, public.reais(v_func.saldopontos * v_taxa),
      public.reais(v_valor), v_pontos
      USING ERRCODE = 'check_violation';
  END IF;
  IF p_lojaid IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.lojas WHERE lojaid = p_lojaid AND contaid = v_conta) THEN
    RAISE EXCEPTION 'Loja não encontrada.' USING ERRCODE = 'no_data_found';
  END IF;

  SELECT produtoid INTO v_produto FROM public.produtosloja WHERE contaid = v_conta AND sistema = 'abate_comanda';
  IF v_produto IS NULL THEN
    RAISE EXCEPTION 'O abate na comanda não está configurado nesta conta.' USING ERRCODE = 'no_data_found';
  END IF;

  INSERT INTO public.resgates (contaid, funcionarioid, produtoid, lojaid, pontosgastos, valorreais, taxaconversao,
                               datasolicitacao, status, registradopor, dataentrega, entreguepor)
  VALUES (v_conta, p_funcionarioid, v_produto, p_lojaid, v_pontos, v_valor, v_taxa, now(),
          CASE WHEN p_entregar THEN 'Entregue' ELSE 'Pendente' END, auth.uid(),
          CASE WHEN p_entregar THEN now() END, CASE WHEN p_entregar THEN auth.uid() END)
  RETURNING resgateid INTO v_id;

  INSERT INTO public.movimentospontos (contaid, funcionarioid, lojaid, tipo, pontos, descricao, resgateid, criadopor)
  VALUES (v_conta, p_funcionarioid, p_lojaid, 'resgate', -v_pontos,
          'Abate na comanda: ' || public.reais(v_valor), v_id, auth.uid());

  RETURN v_id;
END;
$$;

-- Pendente -> Entregue. Nao mexe em pontos (ja sairam no pedido).
CREATE OR REPLACE FUNCTION public.entregar_resgate(p_resgateid integer)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_conta  integer := public.minha_conta_editavel();
  v_status text;
BEGIN
  IF v_conta IS NULL THEN
    RAISE EXCEPTION 'Sua conta não pode alterar dados no momento.' USING ERRCODE = 'insufficient_privilege';
  END IF;

  SELECT status INTO v_status FROM public.resgates
   WHERE resgateid = p_resgateid AND contaid = v_conta
     FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Resgate não encontrado.' USING ERRCODE = 'no_data_found';
  END IF;
  IF v_status <> 'Pendente' THEN
    RAISE EXCEPTION 'Só um resgate pendente pode ser entregue. Este está: %.', v_status USING ERRCODE = 'check_violation';
  END IF;

  UPDATE public.resgates SET status = 'Entregue', dataentrega = now(), entreguepor = auth.uid()
   WHERE resgateid = p_resgateid;
END;
$$;

-- Desfaz um resgate: devolve os pontos e o estoque. Uso interno de
-- cancelar_resgate e estornar_resgate.
CREATE OR REPLACE FUNCTION public.desfazer_resgate(p_resgateid integer, p_de text, p_para text, p_motivo text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_conta   integer := public.minha_conta_editavel();
  v_resgate public.resgates%ROWTYPE;
  v_nome    text;
BEGIN
  IF v_conta IS NULL THEN
    RAISE EXCEPTION 'Sua conta não pode alterar dados no momento.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF length(btrim(coalesce(p_motivo, ''))) = 0 THEN
    RAISE EXCEPTION 'Informe o motivo.' USING ERRCODE = 'check_violation';
  END IF;

  SELECT * INTO v_resgate FROM public.resgates
   WHERE resgateid = p_resgateid AND contaid = v_conta
     FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Resgate não encontrado.' USING ERRCODE = 'no_data_found';
  END IF;
  IF v_resgate.status <> p_de THEN
    RAISE EXCEPTION 'Só um resgate % pode ser %. Este está: %.',
      lower(p_de), CASE p_para WHEN 'Cancelado' THEN 'cancelado' ELSE 'estornado' END, v_resgate.status
      USING ERRCODE = 'check_violation';
  END IF;

  -- Mesma ordem de travas do resgate: pessoa, depois premio.
  PERFORM 1 FROM public.funcionarios WHERE funcionarioid = v_resgate.funcionarioid FOR UPDATE;
  SELECT nome INTO v_nome FROM public.produtosloja WHERE produtoid = v_resgate.produtoid FOR UPDATE;

  IF p_para = 'Cancelado' THEN
    UPDATE public.resgates SET status = 'Cancelado', motivocancelamento = btrim(p_motivo),
           datacancelamento = now(), canceladopor = auth.uid()
     WHERE resgateid = p_resgateid;
  ELSE
    UPDATE public.resgates SET status = 'Estornado', motivoestorno = btrim(p_motivo),
           dataestorno = now(), estornadopor = auth.uid()
     WHERE resgateid = p_resgateid;
  END IF;

  UPDATE public.produtosloja SET estoquedisponivel = estoquedisponivel + 1
   WHERE produtoid = v_resgate.produtoid AND estoquedisponivel IS NOT NULL;

  INSERT INTO public.movimentospontos (contaid, funcionarioid, lojaid, tipo, pontos, descricao, resgateid, criadopor)
  VALUES (v_conta, v_resgate.funcionarioid, v_resgate.lojaid,
          CASE WHEN p_para = 'Cancelado' THEN 'cancelamento_resgate' ELSE 'estorno_resgate' END,
          v_resgate.pontosgastos,
          CASE WHEN p_para = 'Cancelado' THEN 'Resgate cancelado: ' ELSE 'Resgate estornado: ' END
            || CASE WHEN v_resgate.valorreais IS NOT NULL
                    THEN 'abate na comanda de ' || public.reais(v_resgate.valorreais) ELSE v_nome END
            || ' (' || btrim(p_motivo) || ')',
          p_resgateid, auth.uid());
END;
$$;

CREATE OR REPLACE FUNCTION public.cancelar_resgate(p_resgateid integer, p_motivo text)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$ SELECT public.desfazer_resgate(p_resgateid, 'Pendente', 'Cancelado', p_motivo) $$;

CREATE OR REPLACE FUNCTION public.estornar_resgate(p_resgateid integer, p_motivo text)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$ SELECT public.desfazer_resgate(p_resgateid, 'Entregue', 'Estornado', p_motivo) $$;

-- ===========================================================================
-- 8. Extrato de uma pessoa num periodo. Roda com a RLS de quem pede.
--    Saldo inicial + movimentos do periodo = saldo final; e o saldo atual e a
--    soma de todos os movimentos. Traz a taxa atual para mostrar em R$.
-- ===========================================================================

CREATE OR REPLACE FUNCTION public.extrato_pontos(p_funcionarioid integer, p_de date, p_ate date)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_nome     text;
  v_conta    integer;
  v_saldo    integer;
  v_inicial  integer;
  v_periodo  integer;
  v_soma     integer;
  v_mov      jsonb;
BEGIN
  SELECT nomecompleto, contaid, saldopontos INTO v_nome, v_conta, v_saldo
    FROM public.funcionarios WHERE funcionarioid = p_funcionarioid;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Funcionário não encontrado.' USING ERRCODE = 'no_data_found';
  END IF;

  SELECT coalesce(sum(pontos), 0) INTO v_inicial FROM public.movimentospontos
   WHERE funcionarioid = p_funcionarioid AND public.dia_em_sao_paulo(datamovimento) < p_de;

  SELECT coalesce(sum(pontos), 0) INTO v_periodo FROM public.movimentospontos
   WHERE funcionarioid = p_funcionarioid AND public.dia_em_sao_paulo(datamovimento) BETWEEN p_de AND p_ate;

  SELECT coalesce(sum(pontos), 0) INTO v_soma FROM public.movimentospontos
   WHERE funcionarioid = p_funcionarioid;

  WITH todos AS (
    SELECT m.*, sum(m.pontos) OVER (ORDER BY m.datamovimento, m.movimentoid) AS saldoapos
      FROM public.movimentospontos m
     WHERE m.funcionarioid = p_funcionarioid
  )
  SELECT coalesce(jsonb_agg(jsonb_build_object(
           'data', t.datamovimento, 'tipo', t.tipo, 'descricao', t.descricao,
           'loja', l.nome, 'pontos', t.pontos, 'saldoapos', t.saldoapos)
           ORDER BY t.datamovimento, t.movimentoid), '[]'::jsonb)
    INTO v_mov
    FROM todos t
    LEFT JOIN public.lojas l ON l.lojaid = t.lojaid
   WHERE public.dia_em_sao_paulo(t.datamovimento) BETWEEN p_de AND p_ate;

  RETURN jsonb_build_object(
    'nome',         v_nome,
    'saldoatual',   v_saldo,
    'saldoinicial', v_inicial,
    'saldofinal',   v_inicial + v_periodo,
    'confere',      v_soma = v_saldo,
    'taxa',         public.minha_taxa(),
    'movimentos',   v_mov
  );
END;
$$;

-- ===========================================================================
-- 9. Permissoes (negadas por padrao desde a Fase 6).
-- ===========================================================================

REVOKE EXECUTE ON FUNCTION
  public.cria_produtos_do_sistema(integer),
  public.desfazer_resgate(integer, text, text, text),
  public.aplica_movimento_no_saldo(),
  public.taxa_da_conta(integer)
FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION
  public.reais(numeric),
  public.minha_taxa(),
  public.registrar_resgate(integer, integer, integer, boolean),
  public.registrar_abate_comanda(integer, numeric, integer, boolean),
  public.entregar_resgate(integer),
  public.cancelar_resgate(integer, text),
  public.estornar_resgate(integer, text),
  public.extrato_pontos(integer, date, date)
TO authenticated;

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO service_role;
