-- Etapa 1.12, parte A — consertos da revisão adversarial (23/09/2026).
--
-- O que a revisão achou e o que muda aqui:
--
-- 1) A trava de tentativas era opcional: dava para falar direto com o Supabase,
--    pulando o nosso servidor. E a senha inicial (6 primeiros do CPF) era
--    adivinhável por quem soubesse o CPF.
--    → A senha do colaborador passa a ser conferida por NÓS: o resumo dela fica
--      em funcionarios.senhahashapp (PBKDF2 calculado no servidor, com sal por
--      pessoa). A senha que o Supabase guarda vira um valor que ninguém conhece
--      nem consegue adivinhar (o servidor recalcula quando precisa). Falar
--      direto com o Supabase deixa de servir para alguma coisa.
--    → Não existe mais "senha padrão". Quem ainda não criou a senha entra uma
--      única vez com um CÓDIGO sorteado pelo gestor (uso único, 7 dias).
--
-- 2) A tela de escolher o PIN era um adivinhador sem limite ("escolha outro
--    número" dizia que o número era de alguém).
--    → Toda tentativa de PIN passa pela trava, com teto por dia.
--
-- 3) Médias: PIN e senha somem quando a pessoa é desativada; trocar o CPF passa
--    a valer para o login; o master não lê mais as colunas de segredo; a origem
--    da tentativa é definida pelo servidor; foto presa no expurgo vira aviso.
--
-- O PIN inicial também deixa de existir: a pessoa escolhe o dela no primeiro
-- acesso.

-- ---------------------------------------------------------------------------
-- 1. A senha do app é nossa
-- ---------------------------------------------------------------------------
ALTER TABLE public.funcionarios ADD COLUMN senhahashapp text;
COMMENT ON COLUMN public.funcionarios.senhahashapp IS
  'Resumo da senha do app (PBKDF2 com sal por pessoa, calculado no servidor). Vazio = ainda não criou senha: só entra com o código de primeiro acesso.';

-- As marcas de "provisório" não fazem mais sentido: agora o que vale é existir
-- ou não existir senha e PIN.
ALTER TABLE public.funcionarios DROP COLUMN IF EXISTS senhaprovisoria;
ALTER TABLE public.funcionarios DROP COLUMN IF EXISTS pinprovisorio;

-- ---------------------------------------------------------------------------
-- 2. Código de primeiro acesso (uso único, com validade)
-- ---------------------------------------------------------------------------
CREATE TABLE public.codigosacesso (
  codigoid      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contaid       integer NOT NULL REFERENCES public.contas (contaid) ON DELETE RESTRICT,
  funcionarioid integer NOT NULL,
  codigohash    char(64) NOT NULL UNIQUE,
  expiraem      timestamptz NOT NULL,
  usadoem       timestamptz,
  canceladoem   timestamptz,
  criadopor     uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  criadoem      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT codigosacesso_funcionario_fk FOREIGN KEY (contaid, funcionarioid)
    REFERENCES public.funcionarios (contaid, funcionarioid) ON DELETE RESTRICT,
  CONSTRAINT codigosacesso_conta_unico UNIQUE (contaid, codigoid)
);
COMMENT ON TABLE public.codigosacesso IS
  'Código de primeiro acesso: uso único, validade curta, só o resumo (HMAC do servidor) é guardado. Gerar outro cancela o anterior.';
CREATE INDEX codigosacesso_pendentes_idx ON public.codigosacesso (contaid, funcionarioid)
  WHERE usadoem IS NULL AND canceladoem IS NULL;

ALTER TABLE public.codigosacesso ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.codigosacesso FROM anon, authenticated;
GRANT ALL ON public.codigosacesso TO service_role;

-- Gera o código (o texto vem pronto do servidor; aqui entra só o resumo).
CREATE OR REPLACE FUNCTION public.criar_codigo_acesso(p_contaid integer, p_funcionarioid integer,
                                                      p_codigohash text, p_dias integer, p_quem uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF NOT public.bot_contexto_confiavel() THEN
    RAISE EXCEPTION 'Só o servidor gera código de acesso.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.funcionarios
                  WHERE contaid = p_contaid AND funcionarioid = p_funcionarioid AND ativo) THEN
    RAISE EXCEPTION 'Pessoa não encontrada ou desativada.' USING ERRCODE = 'no_data_found';
  END IF;
  -- Gerar outro cancela o anterior: só um código vale por vez.
  UPDATE public.codigosacesso SET canceladoem = now()
   WHERE contaid = p_contaid AND funcionarioid = p_funcionarioid
     AND usadoem IS NULL AND canceladoem IS NULL;
  INSERT INTO public.codigosacesso (contaid, funcionarioid, codigohash, expiraem, criadopor)
  VALUES (p_contaid, p_funcionarioid, left(p_codigohash, 64),
          now() + make_interval(days => greatest(coalesce(p_dias, 7), 1)), p_quem);
END;
$$;

-- Usa o código: devolve a pessoa, ou nada. Uso único de verdade (a marca de
-- usado entra na mesma operação que confere).
CREATE OR REPLACE FUNCTION public.usar_codigo_acesso(p_contaid integer, p_cpf text, p_codigohash text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE c record;
BEGIN
  IF NOT public.bot_contexto_confiavel() THEN
    RAISE EXCEPTION 'Só o servidor usa código de acesso.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  SELECT k.codigoid, k.funcionarioid, f.nomecompleto
    INTO c
    FROM public.codigosacesso k
    JOIN public.funcionarios f ON f.contaid = k.contaid AND f.funcionarioid = k.funcionarioid AND f.ativo
   WHERE k.contaid = p_contaid
     AND k.codigohash = left(p_codigohash, 64)
     AND k.usadoem IS NULL AND k.canceladoem IS NULL
     AND k.expiraem > now()
     AND f.cpf = regexp_replace(coalesce(p_cpf, ''), '[^0-9]', '', 'g')
     FOR UPDATE OF k;
  IF NOT FOUND THEN
    RETURN NULL;
  END IF;
  UPDATE public.codigosacesso SET usadoem = now() WHERE codigoid = c.codigoid;
  RETURN jsonb_build_object('funcionarioid', c.funcionarioid, 'nome', c.nomecompleto);
END;
$$;

-- ---------------------------------------------------------------------------
-- 3. Senha e PIN: guardar e conferir
-- ---------------------------------------------------------------------------
-- O servidor confere a senha; o banco só guarda e entrega o resumo.
CREATE OR REPLACE FUNCTION public.senha_app_de(p_contaid integer, p_cpf text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE f record;
BEGIN
  IF NOT public.bot_contexto_confiavel() THEN
    RAISE EXCEPTION 'Só o servidor confere senha.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  SELECT fu.funcionarioid, fu.senhahashapp, cu.userid
    INTO f
    FROM public.funcionarios fu
    JOIN public.contasusuarios cu
      ON cu.contaid = fu.contaid AND cu.funcionarioid = fu.funcionarioid AND cu.papel = 'colaborador'
   WHERE fu.contaid = p_contaid AND fu.ativo
     AND fu.cpf = regexp_replace(coalesce(p_cpf, ''), '[^0-9]', '', 'g');
  IF NOT FOUND THEN
    RETURN NULL;
  END IF;
  RETURN jsonb_build_object('funcionarioid', f.funcionarioid, 'userid', f.userid, 'senhahash', f.senhahashapp);
END;
$$;

CREATE OR REPLACE FUNCTION public.definir_senha_app(p_contaid integer, p_funcionarioid integer, p_hash text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF NOT public.bot_contexto_confiavel() THEN
    RAISE EXCEPTION 'Só o servidor define senha.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  UPDATE public.funcionarios
     SET senhahashapp = p_hash,
         primeiroacessoem = coalesce(primeiroacessoem, now())
   WHERE contaid = p_contaid AND funcionarioid = p_funcionarioid AND ativo;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Pessoa não encontrada.' USING ERRCODE = 'no_data_found';
  END IF;
END;
$$;

-- A pessoa escolhe o PIN dela. Não existe mais PIN inicial.
CREATE OR REPLACE FUNCTION public.definir_pin(p_contaid integer, p_funcionarioid integer,
                                              p_pinhash text, p_provisorio boolean DEFAULT false)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF NOT public.bot_contexto_confiavel() THEN
    RAISE EXCEPTION 'Só o servidor define PIN.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  UPDATE public.funcionarios
     SET pinhash = left(p_pinhash, 64)
   WHERE contaid = p_contaid AND funcionarioid = p_funcionarioid AND ativo;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Pessoa não encontrada.' USING ERRCODE = 'no_data_found';
  END IF;
EXCEPTION WHEN unique_violation THEN
  RAISE EXCEPTION 'Escolha outro número.' USING ERRCODE = 'unique_violation';
END;
$$;

-- ---------------------------------------------------------------------------
-- 4. Trava: agora com teto por dia (a tela do PIN era um adivinhador)
-- ---------------------------------------------------------------------------
-- PIN: 5 erros em 1 minuto travam aquele tablet (um acerto zera) E no máximo
-- 30 tentativas por dia da mesma chave — o que mata o adivinhador, mesmo que
-- alguém espere entre uma tentativa e outra.
-- Senha: 5 erros em 15 minutos, contados pela chave e pela origem.
CREATE OR REPLACE FUNCTION public.acesso_travado(p_contaid integer, p_tipo text, p_chave text, p_origem text)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SET search_path = public, pg_temp
AS $$
DECLARE
  v_janela interval := CASE WHEN p_tipo = 'pin' THEN interval '1 minute' ELSE interval '15 minutes' END;
  -- Teto por dia: o que mata o adivinhador de PIN mesmo com espera entre as
  -- tentativas. (Fica em variável porque o IF do Postgres não aceita CASE.)
  v_teto   integer := CASE WHEN p_tipo = 'pin' THEN 30 ELSE 50 END;
  v_erros  integer;
BEGIN
  IF NOT public.bot_contexto_confiavel() THEN
    RAISE EXCEPTION 'Só o servidor confere a trava de acesso.' USING ERRCODE = 'insufficient_privilege';
  END IF;

  -- Teto do dia, por chave (pessoa ou tablet): vale para senha e para PIN.
  SELECT count(*) INTO v_erros FROM public.tentativasacesso t
   WHERE t.contaid IS NOT DISTINCT FROM p_contaid AND t.tipo = p_tipo AND t.chave = p_chave
     AND t.em > now() - interval '1 day';
  IF v_erros >= v_teto THEN
    RETURN true;
  END IF;

  -- Erros desta origem desde o último acerto dela.
  SELECT count(*) INTO v_erros FROM public.tentativasacesso t
   WHERE t.contaid IS NOT DISTINCT FROM p_contaid AND t.tipo = p_tipo AND t.origem = p_origem AND NOT t.sucesso
     AND t.em > now() - v_janela
     AND t.em > coalesce((SELECT max(s.em) FROM public.tentativasacesso s
                           WHERE s.contaid IS NOT DISTINCT FROM p_contaid AND s.tipo = p_tipo
                             AND s.origem = p_origem AND s.sucesso),
                         '-infinity'::timestamptz);
  IF v_erros >= 5 THEN
    RETURN true;
  END IF;

  -- E pela chave (CPF, e-mail ou pessoa), para não bastar trocar de aparelho.
  SELECT count(*) INTO v_erros FROM public.tentativasacesso t
   WHERE t.contaid IS NOT DISTINCT FROM p_contaid AND t.tipo = p_tipo AND t.chave = p_chave AND NOT t.sucesso
     AND t.em > now() - v_janela
     AND t.em > coalesce((SELECT max(s.em) FROM public.tentativasacesso s
                           WHERE s.contaid IS NOT DISTINCT FROM p_contaid AND s.tipo = p_tipo
                             AND s.chave = p_chave AND s.sucesso),
                         '-infinity'::timestamptz);
  RETURN v_erros >= 5;
END;
$$;

-- ---------------------------------------------------------------------------
-- 5. Desativar a pessoa apaga os segredos dela
-- ---------------------------------------------------------------------------
-- O login no Supabase é derrubado pelo servidor (a tela chama a função de
-- desativar); aqui garantimos que senha e PIN somem por qualquer caminho.
CREATE OR REPLACE FUNCTION public.limpa_acesso_ao_desativar()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
BEGIN
  IF OLD.ativo AND NOT NEW.ativo THEN
    NEW.pinhash := NULL;
    NEW.senhahashapp := NULL;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER funcionarios_limpa_acesso
  BEFORE UPDATE OF ativo ON public.funcionarios
  FOR EACH ROW EXECUTE FUNCTION public.limpa_acesso_ao_desativar();

-- Cancela os códigos pendentes de quem foi desativado.
CREATE OR REPLACE FUNCTION public.cancela_codigos_ao_desativar()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
BEGIN
  IF OLD.ativo AND NOT NEW.ativo THEN
    UPDATE public.codigosacesso SET canceladoem = now()
     WHERE contaid = NEW.contaid AND funcionarioid = NEW.funcionarioid
       AND usadoem IS NULL AND canceladoem IS NULL;
  END IF;
  RETURN NULL;
END;
$$;

CREATE TRIGGER funcionarios_cancela_codigos
  AFTER UPDATE OF ativo ON public.funcionarios
  FOR EACH ROW EXECUTE FUNCTION public.cancela_codigos_ao_desativar();

-- ---------------------------------------------------------------------------
-- 6. Trocar o CPF de quem já tem acesso só pelo caminho certo
-- ---------------------------------------------------------------------------
-- O CPF é o login. Trocar direto na tabela deixaria a pessoa sem conseguir
-- entrar, sem aviso nenhum. A troca passa a exigir a função de servidor, que
-- muda o CPF e o login no mesmo movimento.
CREATE OR REPLACE FUNCTION public.protege_troca_de_cpf()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER   -- precisa enxergar o contexto do servidor (como os outros gatilhos)
SET search_path = public, pg_temp
AS $$
BEGIN
  IF NEW.cpf IS DISTINCT FROM OLD.cpf
     AND OLD.cpf IS NOT NULL
     AND EXISTS (SELECT 1 FROM public.contasusuarios
                  WHERE contaid = NEW.contaid AND funcionarioid = NEW.funcionarioid AND papel = 'colaborador')
     AND NOT public.bot_contexto_confiavel() THEN
    RAISE EXCEPTION 'Esta pessoa já entra no app pelo CPF. Use "Trocar CPF" na Equipe, para o login mudar junto.'
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER funcionarios_protege_cpf
  BEFORE UPDATE OF cpf ON public.funcionarios
  FOR EACH ROW EXECUTE FUNCTION public.protege_troca_de_cpf();

-- ---------------------------------------------------------------------------
-- 7. Nem o master lê os segredos
-- ---------------------------------------------------------------------------
-- A tabela funcionarios tinha SELECT no nível da tabela, então o master lia
-- pinhash e senhahashapp. Agora o SELECT é coluna a coluna, menos essas duas.
DO $$
DECLARE v_colunas text;
BEGIN
  SELECT string_agg(quote_ident(column_name), ', ' ORDER BY ordinal_position) INTO v_colunas
    FROM information_schema.columns
   WHERE table_schema = 'public' AND table_name = 'funcionarios'
     AND column_name NOT IN ('pinhash', 'senhahashapp');
  EXECUTE 'REVOKE SELECT ON public.funcionarios FROM authenticated';
  EXECUTE format('GRANT SELECT (%s) ON public.funcionarios TO authenticated', v_colunas);
END $$;

-- ---------------------------------------------------------------------------
-- 8. Situação do acesso, sem as marcas antigas
-- ---------------------------------------------------------------------------
-- As colunas devolvidas mudaram, então a função é recriada do zero.
DROP FUNCTION IF EXISTS public.situacao_dos_acessos();
CREATE OR REPLACE FUNCTION public.situacao_dos_acessos()
RETURNS TABLE (funcionarioid integer, temacesso boolean, nuncaentrou boolean,
               semsenha boolean, sempin boolean, codigopendente boolean,
               codigoexpiraem timestamptz, redefinidoem timestamptz)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT f.funcionarioid,
         cu.userid IS NOT NULL,
         cu.userid IS NOT NULL AND f.primeiroacessoem IS NULL,
         f.senhahashapp IS NULL,
         f.pinhash IS NULL,
         k.codigoid IS NOT NULL,
         k.expiraem,
         f.acessoredefinidoem
    FROM public.funcionarios f
    LEFT JOIN public.contasusuarios cu
           ON cu.contaid = f.contaid AND cu.funcionarioid = f.funcionarioid AND cu.papel = 'colaborador'
    LEFT JOIN LATERAL (SELECT codigoid, expiraem FROM public.codigosacesso k2
                        WHERE k2.contaid = f.contaid AND k2.funcionarioid = f.funcionarioid
                          AND k2.usadoem IS NULL AND k2.canceladoem IS NULL AND k2.expiraem > now()
                        ORDER BY k2.criadoem DESC LIMIT 1) k ON true
   WHERE f.contaid = (select public.minha_conta()) AND (select public.sou_master())
$$;

CREATE OR REPLACE FUNCTION public.meu_acesso()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_uid uuid := auth.uid();
  a     record;
BEGIN
  IF v_uid IS NULL THEN
    RETURN jsonb_build_object('tipo', 'nenhum');
  END IF;
  IF public.eh_admin_geral() THEN
    RETURN jsonb_build_object('tipo', 'admin');
  END IF;

  SELECT cu.papel, cu.contaid, cu.lojaid, cu.funcionarioid,
         c.status AS statusconta, c.nome AS nomeconta,
         l.nome AS nomeloja, l.ativa AS lojaativa,
         f.nomecompleto AS nomepessoa, f.ativo AS pessoaativa,
         f.senhahashapp IS NULL AS semsenha, f.pinhash IS NULL AS sempin
    INTO a
    FROM public.contasusuarios cu
    JOIN public.contas c ON c.contaid = cu.contaid
    LEFT JOIN public.lojas l ON l.contaid = cu.contaid AND l.lojaid = cu.lojaid
    LEFT JOIN public.funcionarios f ON f.contaid = cu.contaid AND f.funcionarioid = cu.funcionarioid
   WHERE cu.userid = v_uid;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('tipo', 'nenhum');
  END IF;

  -- Desligado na hora: pessoa inativa, loja desativada ou conta cancelada.
  IF a.statusconta = 'cancelada'
     OR (a.papel = 'loja' AND coalesce(a.lojaativa, false) = false)
     OR (a.papel = 'colaborador' AND coalesce(a.pessoaativa, false) = false) THEN
    RETURN jsonb_build_object('tipo', 'desligado');
  END IF;

  RETURN jsonb_build_object(
    'tipo', a.papel,
    'conta', a.nomeconta,
    'loja', a.nomeloja,
    'nome', coalesce(a.nomepessoa, a.nomeloja, a.nomeconta),
    'somenteleitura', a.statusconta <> 'ativa',
    'semsenha', coalesce(a.semsenha, false),
    'sempin', coalesce(a.sempin, false),
    'politicapendente', CASE WHEN a.papel = 'colaborador'
                             THEN public.politica_pendente(a.contaid, a.funcionarioid) ELSE false END);
END;
$$;

-- Criar o acesso não define mais PIN nem senha: quem define é a pessoa, no
-- primeiro acesso, depois de usar o código.
CREATE OR REPLACE FUNCTION public.criar_acesso_colaborador(p_contaid integer, p_funcionarioid integer,
                                                           p_userid uuid, p_pinhash text, p_quem uuid)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF NOT public.bot_contexto_confiavel() THEN
    RAISE EXCEPTION 'Só o servidor cria acesso.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.funcionarios
                  WHERE contaid = p_contaid AND funcionarioid = p_funcionarioid AND ativo AND cpf IS NOT NULL) THEN
    RAISE EXCEPTION 'Pessoa não encontrada, inativa ou sem CPF.' USING ERRCODE = 'no_data_found';
  END IF;
  INSERT INTO public.contasusuarios (contaid, userid, papel, funcionarioid, criadopor)
  VALUES (p_contaid, p_userid, 'colaborador', p_funcionarioid, p_quem);
  -- Sem senha e sem PIN: a pessoa cria os dois no primeiro acesso.
  UPDATE public.funcionarios SET senhahashapp = NULL, pinhash = NULL
   WHERE contaid = p_contaid AND funcionarioid = p_funcionarioid;
  RETURN true;
END;
$$;

-- Redefinir acesso: apaga senha e PIN e deixa a pessoa pronta para o código novo.
CREATE OR REPLACE FUNCTION public.redefinir_acesso(p_contaid integer, p_funcionarioid integer,
                                                   p_pinhash text, p_quem uuid)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF NOT public.bot_contexto_confiavel() THEN
    RAISE EXCEPTION 'Só o servidor redefine acesso.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  UPDATE public.funcionarios
     SET senhahashapp = NULL, pinhash = NULL,
         acessoredefinidoem = now(), acessoredefinidopor = p_quem
   WHERE contaid = p_contaid AND funcionarioid = p_funcionarioid AND ativo;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Pessoa não encontrada.' USING ERRCODE = 'no_data_found';
  END IF;
  RETURN true;
END;
$$;

-- Trocar o CPF de quem já entra pelo app (o servidor muda o login junto).
CREATE OR REPLACE FUNCTION public.trocar_cpf(p_contaid integer, p_funcionarioid integer, p_cpf text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF NOT public.bot_contexto_confiavel() THEN
    RAISE EXCEPTION 'Só o servidor troca o CPF de quem tem acesso.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  UPDATE public.funcionarios SET cpf = p_cpf
   WHERE contaid = p_contaid AND funcionarioid = p_funcionarioid AND ativo;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Pessoa não encontrada.' USING ERRCODE = 'no_data_found';
  END IF;
END;
$$;

-- ---------------------------------------------------------------------------
-- 9. Expurgo: foto presa vira aviso (antes sumia em silêncio)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.rotina_expurgo_fotos(p_contaid integer, p_agora timestamptz)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_hoje   date;
  v_hora   time;
  v_inicio timestamptz := clock_timestamp();
  v_dias   integer;
  v_n      integer;
  v_presas integer;
BEGIN
  SELECT x.dia, x.hora INTO v_hoje, v_hora FROM public.rotina_hora_local(p_agora) x;
  BEGIN
    IF v_hora < public.rotina_horario(p_contaid, 'HORARIO_CONFERENCIA_LIVRO', '03:00') THEN
      RETURN jsonb_build_object('acao', 'antes do horario');
    END IF;
    IF EXISTS (SELECT 1 FROM public.rotinasexecucoes
                WHERE contaid = p_contaid AND rotina = 'expurgo_fotos' AND referencia = v_hoje AND resultado = 'ok') THEN
      RETURN jsonb_build_object('acao', 'ja rodou hoje');
    END IF;

    v_dias := public.dias_guardar_foto(p_contaid);

    WITH vencidas AS (
      SELECT e.entregaid, e.pathfotoevidencia
        FROM public.entregas e
       WHERE e.contaid = p_contaid
         AND e.pathfotoevidencia IS NOT NULL
         AND e.fotoexpiradaem IS NULL
         AND e.dataenvio < p_agora - make_interval(days => v_dias)
       ORDER BY e.dataenvio
       LIMIT 2000
    ), na_fila AS (
      INSERT INTO public.fotosexpurgo (contaid, entregaid, caminho)
      SELECT p_contaid, v.entregaid, v.pathfotoevidencia FROM vencidas v
      ON CONFLICT (contaid, caminho) DO NOTHING
      RETURNING entregaid
    )
    UPDATE public.entregas e
       SET fotoexpiradaem = p_agora, pathfotoevidencia = NULL
      FROM vencidas v
     WHERE e.contaid = p_contaid AND e.entregaid = v.entregaid;
    GET DIAGNOSTICS v_n = ROW_COUNT;

    -- Arquivo que falhou 5 vezes: o banco já diz "apagada", mas o arquivo
    -- continua lá. Isso NÃO pode passar em silêncio.
    SELECT count(*) INTO v_presas FROM public.fotosexpurgo
     WHERE contaid = p_contaid AND removidoem IS NULL AND tentativas >= 5;
    IF v_presas > 0 THEN
      INSERT INTO public.avisossistema (contaid, tipo, texto)
      SELECT p_contaid, 'expurgo_preso',
             v_presas || ' foto(s) marcada(s) como apagada(s) continuam no armazenamento: a remoção falhou 5 vezes.'
       WHERE NOT EXISTS (SELECT 1 FROM public.avisossistema
                          WHERE contaid = p_contaid AND tipo = 'expurgo_preso' AND lidoem IS NULL);
      PERFORM public.rotina_registrar(p_contaid, 'expurgo_fotos', v_hoje, 'agendada', v_inicio, 'erro',
                                      jsonb_build_object('fotos', v_n, 'dias', v_dias, 'presas', v_presas),
                                      v_presas || ' foto(s) não saíram do armazenamento');
      RETURN jsonb_build_object('fotos', v_n, 'dias', v_dias, 'presas', v_presas);
    END IF;

    PERFORM public.rotina_registrar(p_contaid, 'expurgo_fotos', v_hoje, 'agendada', v_inicio, 'ok',
                                    jsonb_build_object('fotos', v_n, 'dias', v_dias), NULL);
    IF v_n > 0 THEN
      PERFORM public.fotos_expurgo_disparar();
    END IF;
    RETURN jsonb_build_object('fotos', v_n, 'dias', v_dias);
  EXCEPTION WHEN OTHERS THEN
    PERFORM public.rotina_registrar(p_contaid, 'expurgo_fotos', v_hoje, 'agendada', v_inicio, 'erro', NULL, SQLERRM);
    RETURN jsonb_build_object('erro', SQLERRM);
  END;
END;
$$;

-- ---------------------------------------------------------------------------
-- 10. Permissões
-- ---------------------------------------------------------------------------
DO $$
DECLARE f text;
BEGIN
  FOREACH f IN ARRAY ARRAY[
    'public.criar_codigo_acesso(integer, integer, text, integer, uuid)',
    'public.usar_codigo_acesso(integer, text, text)',
    'public.senha_app_de(integer, text)',
    'public.definir_senha_app(integer, integer, text)',
    'public.trocar_cpf(integer, integer, text)'
  ] LOOP
    EXECUTE format('REVOKE ALL ON FUNCTION %s FROM public, anon, authenticated', f);
    EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO service_role', f);
  END LOOP;
END $$;

-- O endereço público que devolvia o nome da empresa some (era código morto e
-- servia para descobrir a carteira de clientes).
DROP FUNCTION IF EXISTS public.conta_por_codigo(text);

-- Procura a empresa pelo código, só para o servidor (sem devolver nome).
CREATE OR REPLACE FUNCTION public.conta_do_codigo(p_codigo text)
RETURNS integer
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE v_id integer;
BEGIN
  IF NOT public.bot_contexto_confiavel() THEN
    RAISE EXCEPTION 'Só o servidor procura empresa por código.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  SELECT contaid INTO v_id FROM public.contas
   WHERE codigo = lower(btrim(coalesce(p_codigo, ''))) AND status <> 'cancelada';
  RETURN v_id;
END;
$$;
REVOKE ALL ON FUNCTION public.conta_do_codigo(text) FROM public, anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.conta_do_codigo(text) TO service_role;

-- Código de empresa novo deixa de ser adivinhável (antes era o nome + o número
-- da conta, o que permitia enumerar a carteira de clientes).
CREATE OR REPLACE FUNCTION public.codigo_padrao_da_conta()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
DECLARE v text;
BEGIN
  IF btrim(coalesce(NEW.codigo, '')) <> '' THEN
    NEW.codigo := lower(btrim(NEW.codigo));
    RETURN NEW;
  END IF;
  v := left(regexp_replace(lower(translate(coalesce(NEW.nome, ''),
         'áàâãäéèêëíìîïóòôõöúùûüçÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ',
         'aaaaaeeeeiiiiooooouuuucAAAAAEEEEIIIIOOOOOUUUUC')),
       '[^a-z0-9]+', '', 'g'), 18);
  IF v = '' THEN v := 'empresa'; END IF;
  NEW.codigo := v || '-' || left(replace(gen_random_uuid()::text, '-', ''), 6);
  RETURN NEW;
END;
$$;
