-- CLASSIFICAÇÃO: ACRESCENTA
-- (cria uma tabela da plataforma e uma função interna; muda por dentro a
-- chamada do apagamento, o despachante das rotinas e a leitura da /saude, sem
-- mudar o que recebem nem o que o site no ar lê delas.)
--
-- O que ninguém conferia (30/09/2026, pedido do Wisley). As fotos vencidas
-- não foram apagadas de 28 a 30/09 e ninguém ficou sabendo: a rotina "rodava",
-- mas a chamada à função que apaga o arquivo nunca acontecia (faltavam os
-- segredos do cofre), e mesmo quando acontece o banco só guarda a resposta
-- por 6 horas. Agora:
--   1. Toda tentativa de chamar a função de apagar fica registrada
--      (chamadasdoservidor, tabela da PLATAFORMA, só do admin geral), inclusive
--      a que NÃO chamou por falta de segredo; e a resposta (200 = apagou N,
--      401 = a senha do cofre e a da função não são iguais, 404 = a função não
--      está publicada) é copiada para ela pelo despachante, a cada 5 minutos,
--      antes de o banco jogar fora.
--   2. A espera pela resposta passa de 60 s para 400 s: apagar um lote grande
--      demora mais de um minuto, e com 60 s a resposta de um apagamento que
--      deu certo aparecia como "sem resposta".
--   3. A /saude (saude_das_rotinas) passa a dizer, além do que já dizia:
--      - cada agendamento (os três), se o comando é o certo, a última vez que
--        rodou e se está atrasado;
--      - cada rotina diária, a última vez que rodou e em quantas contas está
--        atrasada ou com erro;
--      - a fila de apagamento (na fila, presas, apagadas nas últimas 24 h e 7
--        dias, a mais antiga) e a última chamada à função, com a resposta;
--      - contado NO PRÓPRIO STORAGE (storage.objects), e não no que o sistema
--        acha que fez: arquivos vencidos ainda guardados, arquivos marcados
--        como apagados que continuam lá (tem de ser 0) e arquivos que nenhuma
--        entrega usa.
-- Nenhum dado de cliente é alterado.

-- ---------------------------------------------------------------------------
-- 1. As chamadas do banco às funções do servidor (tabela da PLATAFORMA)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.chamadasdoservidor (
  chamadaid    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  funcao       text NOT NULL CHECK (funcao IN ('expurgo-fotos')),
  -- NULL = não chamou (o motivo fica em erro).
  requestid    bigint,
  pedidaem     timestamptz NOT NULL DEFAULT now(),
  respondidaem timestamptz,
  status       integer,
  apagados     integer,
  erro         text
);
COMMENT ON TABLE public.chamadasdoservidor IS
  'Tabela da PLATAFORMA (sem conta): cada vez que o banco chamou (ou tentou chamar) uma função do servidor, e o que ela respondeu. Só o admin geral; a /saude lê pela chave de servidor.';
CREATE INDEX IF NOT EXISTS chamadasdoservidor_funcao_idx ON public.chamadasdoservidor (funcao, pedidaem DESC);
CREATE INDEX IF NOT EXISTS chamadasdoservidor_pendentes_idx ON public.chamadasdoservidor (requestid) WHERE respondidaem IS NULL;
ALTER TABLE public.chamadasdoservidor ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.chamadasdoservidor FROM anon, authenticated;
GRANT ALL ON public.chamadasdoservidor TO service_role;
DROP POLICY IF EXISTS chamadasdoservidor_admin_le ON public.chamadasdoservidor;
CREATE POLICY chamadasdoservidor_admin_le ON public.chamadasdoservidor FOR SELECT TO authenticated
  USING ((SELECT public.eh_admin_geral()));

-- A fila de apagamento lida pelo caminho (a conferência no Storage).
CREATE INDEX IF NOT EXISTS fotosexpurgo_caminho_idx ON public.fotosexpurgo (caminho);

-- ---------------------------------------------------------------------------
-- 2. A chamada do apagamento fica registrada. Parte da versão viva (de 20260927100100_expurgo_fotos_entrega.sql).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.fotos_expurgo_disparar()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE v_url text; v_segredo text; v_pedido bigint;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.fotosexpurgo WHERE removidoem IS NULL AND tentativas < 5) THEN
    RETURN;
  END IF;
  -- Tem o que apagar e não dá para chamar: fica registrado (30/09/2026). Antes
  -- a volta era calada, e as fotos ficaram dois dias sem sair sem ninguém ver.
  IF to_regclass('vault.decrypted_secrets') IS NULL OR to_regproc('net.http_post') IS NULL THEN
    INSERT INTO public.chamadasdoservidor (funcao, respondidaem, erro)
    VALUES ('expurgo-fotos', now(), 'não chamou: o cofre (Vault) ou o pg_net não está ligado');
    RETURN;
  END IF;
  EXECUTE $q$SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'stgame_funcoes_url'$q$ INTO v_url;
  EXECUTE $q$SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'stgame_expurgo_segredo'$q$ INTO v_segredo;
  IF v_url IS NULL OR v_segredo IS NULL THEN
    INSERT INTO public.chamadasdoservidor (funcao, respondidaem, erro)
    VALUES ('expurgo-fotos', now(), 'não chamou: falta ' ||
            concat_ws(' e ', CASE WHEN v_url IS NULL THEN 'stgame_funcoes_url' END,
                             CASE WHEN v_segredo IS NULL THEN 'stgame_expurgo_segredo' END) || ' no cofre');
    RETURN;
  END IF;
  -- 400 s: um lote grande leva mais de um minuto (30/09/2026).
  EXECUTE 'SELECT net.http_post(url := $1, body := $2, headers := $3, timeout_milliseconds := 400000)'
    INTO v_pedido
    USING rtrim(v_url, '/') || '/expurgo-fotos', '{}'::jsonb,
          jsonb_build_object('Content-Type', 'application/json', 'x-expurgo-segredo', v_segredo);
  INSERT INTO public.chamadasdoservidor (funcao, requestid) VALUES ('expurgo-fotos', v_pedido);
  DELETE FROM public.chamadasdoservidor WHERE pedidaem < now() - interval '90 days';
END;
$function$;

-- ---------------------------------------------------------------------------
-- 3. A resposta, copiada antes de o banco jogar fora (o pg_net guarda 6 horas)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.registrar_respostas_do_servidor()
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE v_n integer := 0;
BEGIN
  IF to_regclass('net._http_response') IS NOT NULL THEN
    EXECUTE $q$
      UPDATE public.chamadasdoservidor c
         SET respondidaem = coalesce(r.created, now()),
             status       = r.status_code,
             apagados     = CASE WHEN r.status_code = 200
                                 THEN (substring(r.content FROM '"apagados"\s*:\s*([0-9]+)'))::integer END,
             erro         = CASE WHEN r.status_code IS DISTINCT FROM 200
                                 THEN left(coalesce(nullif(r.error_msg, ''), nullif(r.content, ''), 'sem detalhe'), 300) END
        FROM net._http_response r
       WHERE r.id = c.requestid AND c.respondidaem IS NULL
    $q$;
    GET DIAGNOSTICS v_n = ROW_COUNT;
  END IF;
  -- Pedido sem resposta depois de 7 horas: o banco já jogou fora (ou nunca
  -- chegou). Não fica "esperando" para sempre.
  UPDATE public.chamadasdoservidor
     SET respondidaem = now(), erro = 'sem resposta registrada (o banco guarda a resposta só por 6 horas)'
   WHERE respondidaem IS NULL AND pedidaem < now() - interval '7 hours';
  RETURN v_n;
END;
$$;
REVOKE ALL ON FUNCTION public.registrar_respostas_do_servidor() FROM public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- 4. O despachante copia as respostas. Parte da versão viva (de 20260927100100_expurgo_fotos_entrega.sql).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.rotinas_despachar(p_agora timestamp with time zone DEFAULT now())
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE c record; v_n integer := 0; v_erros integer := 0;
BEGIN
  IF NOT pg_try_advisory_xact_lock(7310) THEN
    RETURN jsonb_build_object('ocupado', true);
  END IF;

  -- A resposta das chamadas ao servidor (o apagamento das fotos), antes de o
  -- banco jogar fora (30/09/2026). Um erro aqui não atrapalha as rotinas.
  BEGIN
    PERFORM public.registrar_respostas_do_servidor();
  EXCEPTION WHEN OTHERS THEN
    NULL;
  END;

  FOR c IN SELECT contaid FROM public.contas WHERE status = 'ativa' ORDER BY contaid LOOP
    BEGIN
      PERFORM public.rotina_lista_do_dia(c.contaid, p_agora, 'agendada');
      PERFORM public.rotina_fechamento_mensal(c.contaid, p_agora);
      PERFORM public.rotina_conferencia_livro(c.contaid, p_agora);
      PERFORM public.rotina_limpeza(c.contaid, p_agora);
      PERFORM public.rotina_expurgo_fotos(c.contaid, p_agora);
      v_n := v_n + 1;
    EXCEPTION WHEN OTHERS THEN
      v_erros := v_erros + 1;
      PERFORM public.rotina_registrar(c.contaid, 'lista_do_dia', NULL, 'agendada', clock_timestamp(), 'erro', NULL, SQLERRM);
    END;
    -- As mensagens ficam num bloco próprio: um erro aqui não atrapalha a lista do dia.
    BEGIN
      PERFORM public.rotina_mensagens(c.contaid, p_agora);
    EXCEPTION WHEN OTHERS THEN
      v_erros := v_erros + 1;
      PERFORM public.rotina_registrar(c.contaid, 'mensagens', NULL, 'agendada', clock_timestamp(), 'erro', NULL, SQLERRM);
    END;
  END LOOP;

  RETURN jsonb_build_object('contas', v_n, 'erros', v_erros);
END;
$function$;

-- ---------------------------------------------------------------------------
-- 5. A /saude confere o que ninguém conferia. Parte da versão viva (de 20260929237000_foto_da_fila.sql).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.saude_das_rotinas()
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_segredos jsonb := '{}'::jsonb;
  v_jobs     jsonb := '[]'::jsonb;
  v_nome     text;
  v_existe   boolean;
  v_fotos    jsonb;
  v_fila     jsonb;
  v_diarias  jsonb;
  v_apagar   jsonb;
  v_storage  jsonb;
BEGIN
  IF to_regclass('vault.decrypted_secrets') IS NOT NULL THEN
    FOREACH v_nome IN ARRAY ARRAY['stgame_funcoes_url', 'stgame_fila_segredo', 'stgame_expurgo_segredo'] LOOP
      EXECUTE 'SELECT EXISTS (SELECT 1 FROM vault.decrypted_secrets WHERE name = $1 AND coalesce(decrypted_secret, '''') <> '''')'
        INTO v_existe USING v_nome;
      v_segredos := v_segredos || jsonb_build_object(v_nome, v_existe);
    END LOOP;
  END IF;

  IF to_regclass('cron.job') IS NOT NULL THEN
    -- Os TRÊS agendamentos, com o comando que cada um deve rodar, de quanto
    -- em quanto tempo, e se está atrasado: sem rodar há mais de 3 intervalos
    -- (no mínimo 15 minutos), ou nunca rodou (30/09/2026).
    EXECUTE $q$
      SELECT coalesce(jsonb_agg(jsonb_build_object(
               'nome', n.nome,
               'existe', j.jobid IS NOT NULL,
               'ativo', coalesce(j.active, false),
               'comandocerto', j.command IS NOT NULL AND btrim(j.command) = n.comando,
               'intervalosegundos', n.segundos,
               'ultimaexecucao', r.end_time,
               'ultimostatus', r.status,
               'atrasado', j.jobid IS NULL OR r.end_time IS NULL
                           OR r.end_time < now() - make_interval(secs => greatest(3 * n.segundos, 900)))
             ORDER BY n.nome), '[]'::jsonb)
        FROM (VALUES ('gamegb-rotinas', 'SELECT public.rotinas_despachar()', 300),
                     ('stgame-codigos-vencidos', 'SELECT public.limpar_codigos_vencidos()', 300),
                     ('stgame-telegram-fila', 'SELECT public.bot_fila_disparar()', 15)) n(nome, comando, segundos)
        LEFT JOIN cron.job j ON j.jobname = n.nome
        LEFT JOIN LATERAL (SELECT d.end_time, d.status FROM cron.job_run_details d
                            WHERE d.jobid = j.jobid ORDER BY d.start_time DESC LIMIT 1) r ON true
    $q$ INTO v_jobs;
  END IF;

  SELECT jsonb_build_object(
           'vencidas', coalesce(sum((f->>'vencidas')::integer), 0),
           'diasdeatraso', coalesce(max((f->>'diasdeatraso')::integer), 0),
           'presas', coalesce(sum((f->>'presas')::integer), 0))
    INTO v_fotos
    FROM (SELECT public.fotos_vencidas_da_conta(c.contaid) f FROM public.contas c) x;

  -- Dias sem foto da fila: quantos, em quantas contas, e o mais recente.
  SELECT jsonb_build_object(
           'dias', coalesce(sum((f->>'dias')::integer), 0),
           'contas', count(*) FILTER (WHERE (f->>'dias')::integer > 0),
           'ultimo', max((f->>'ultimo')::date))
    INTO v_fila
    FROM (SELECT public.fila_dias_sem_foto(c.contaid) f FROM public.contas c WHERE c.status = 'ativa') x;

  -- Cada rotina diária: a última vez que rodou (em qualquer conta) e em
  -- quantas contas ativas ela está atrasada (sem rodar há mais de 30 horas;
  -- conta criada há menos de 30 horas não conta) ou com erro na última vez.
  SELECT coalesce(jsonb_agg(jsonb_build_object(
           'rotina', x.rotina, 'ultima', x.ultima, 'contas', x.contas,
           'atrasadas', x.atrasadas, 'comerro', x.comerro) ORDER BY x.ordem), '[]'::jsonb)
    INTO v_diarias
    FROM (SELECT n.rotina, n.ordem, max(u.ultima) AS ultima, count(c.contaid) AS contas,
                 count(c.contaid) FILTER (WHERE c.criadoem < now() - interval '30 hours'
                                            AND (u.ultima IS NULL OR u.ultima < now() - interval '30 hours')) AS atrasadas,
                 count(c.contaid) FILTER (WHERE u.resultado = 'erro') AS comerro
            FROM (VALUES ('lista_do_dia', 1), ('foto_da_fila', 2), ('conferencia_livro', 3),
                         ('limpeza', 4), ('expurgo_fotos', 5)) n(rotina, ordem)
            CROSS JOIN public.contas c
            LEFT JOIN LATERAL (SELECT e.iniciadoem AS ultima, e.resultado
                                 FROM public.rotinasexecucoes e
                                WHERE e.contaid = c.contaid AND e.rotina = n.rotina
                                ORDER BY e.iniciadoem DESC LIMIT 1) u ON true
           WHERE c.status = 'ativa'
           GROUP BY n.rotina, n.ordem) x;

  -- O apagamento: a fila e a última chamada à função que apaga (com a resposta).
  SELECT jsonb_build_object(
           'nafila',       count(*) FILTER (WHERE f.removidoem IS NULL AND f.tentativas < 5),
           'presas',       count(*) FILTER (WHERE f.removidoem IS NULL AND f.tentativas >= 5),
           'maisantiga',   min(f.criadoem) FILTER (WHERE f.removidoem IS NULL),
           'apagadas24h',  count(*) FILTER (WHERE f.removidoem >= now() - interval '24 hours'),
           'apagadas7d',   count(*) FILTER (WHERE f.removidoem >= now() - interval '7 days'),
           'ultimachamada', (SELECT jsonb_build_object('pedidaem', c.pedidaem, 'chamou', c.requestid IS NOT NULL,
                                                        'respondidaem', c.respondidaem, 'status', c.status,
                                                        'apagados', c.apagados, 'erro', c.erro)
                               FROM public.chamadasdoservidor c WHERE c.funcao = 'expurgo-fotos'
                              ORDER BY c.pedidaem DESC, c.chamadaid DESC LIMIT 1),
           'ultimosucesso', (SELECT max(c.pedidaem) FROM public.chamadasdoservidor c
                              WHERE c.funcao = 'expurgo-fotos' AND c.status = 200),
           -- Até 5 caminhos apagados nos últimos 7 dias: a /saude pergunta ao
           -- próprio Storage se eles sumiram (o caminho não vai para a tela).
           'amostraapagadas', coalesce((SELECT jsonb_agg(s.caminho) FROM (
                                SELECT f2.caminho FROM public.fotosexpurgo f2
                                 WHERE f2.removidoem >= now() - interval '7 days'
                                 ORDER BY f2.removidoem DESC LIMIT 5) s), '[]'::jsonb))
    INTO v_apagar
    FROM public.fotosexpurgo f;

  -- CONTADO NO PRÓPRIO STORAGE (storage.objects, o índice do Storage), e não
  -- no que o sistema acha que fez. Bucket das fotos de entrega; a conta vem
  -- do começo do caminho (<contaid>/<lojaid>/...).
  IF to_regclass('storage.objects') IS NOT NULL THEN
    WITH prazo AS (
      SELECT c.contaid, public.dias_guardar_foto(c.contaid) AS dias FROM public.contas c
    ), arq AS (
      SELECT o.name, o.created_at, p.contaid, p.dias
        FROM storage.objects o
        LEFT JOIN prazo p ON o.name ~ '^[0-9]+/' AND p.contaid = split_part(o.name, '/', 1)::integer
       WHERE o.bucket_id = 'entregas'
    ), ent AS (
      -- Uma linha por arquivo: a entrega mais recente que o usa.
      SELECT e.contaid, e.pathfotoevidencia AS name, max(e.dataenvio) AS ultimoenvio
        FROM public.entregas e WHERE e.pathfotoevidencia IS NOT NULL
       GROUP BY 1, 2
    ), fila AS (
      SELECT f.contaid, f.caminho AS name,
             bool_or(f.removidoem IS NULL) AS na_fila, bool_or(f.removidoem IS NOT NULL) AS dado_como_apagado
        FROM public.fotosexpurgo f GROUP BY 1, 2
    ), classe AS (
      SELECT a.*,
             coalesce(en.ultimoenvio >= now() - make_interval(days => a.dias), false) AS serve_no_prazo,
             en.name IS NOT NULL AS tem_entrega,
             coalesce(fi.na_fila, false) AS na_fila,
             coalesce(fi.dado_como_apagado, false) AS dado_como_apagado
        FROM arq a
        LEFT JOIN ent en ON en.contaid = a.contaid AND en.name = a.name
        LEFT JOIN fila fi ON fi.contaid = a.contaid AND fi.name = a.name
    )
    SELECT jsonb_build_object(
             'arquivos', count(*),
             -- Vencido e ainda guardado: mais velho que o prazo da conta e não
             -- serve a nenhuma entrega dentro do prazo.
             'vencidos', count(*) FILTER (WHERE created_at < now() - make_interval(days => coalesce(dias, 90))
                                            AND NOT serve_no_prazo),
             'vencidomaisantigo', min(created_at) FILTER (WHERE created_at < now() - make_interval(days => coalesce(dias, 90))
                                                           AND NOT serve_no_prazo),
             -- O sistema diz que apagou e o arquivo continua lá: tem de ser 0.
             'apagadosquecontinuam', count(*) FILTER (WHERE dado_como_apagado),
             -- Nenhuma entrega usa e não está na fila: nunca será apagado.
             'semdono', count(*) FILTER (WHERE NOT tem_entrega AND NOT na_fila AND NOT dado_como_apagado),
             'semdonomaisantigo', min(created_at) FILTER (WHERE NOT tem_entrega AND NOT na_fila AND NOT dado_como_apagado))
      INTO v_storage
      FROM classe;
  END IF;

  RETURN jsonb_build_object(
    'diarias', v_diarias,
    'apagamento', v_apagar,
    'storage', v_storage,
    'cofre', to_regclass('vault.decrypted_secrets') IS NOT NULL,
    'pgnet', to_regproc('net.http_post') IS NOT NULL,
    'segredos', v_segredos,
    'agendador', to_regclass('cron.job') IS NOT NULL,
    'jobs', v_jobs,
    'mensagensfalhadas', (SELECT count(*) FROM public.mensagensfila
                           WHERE status = 'falhou' AND criadoem >= now() - interval '24 hours'),
    'fotos', v_fotos,
    'fila', v_fila);
END;
$function$;
