-- Expurgo automático das fotos de entrega (decisão do Wisley, 23/09/2026).
--
-- A política de uso diz que a foto é guardada por tempo limitado e depois
-- apagada. Isto faz a frase virar verdade.
--
-- Regras:
--   * Prazo POR CONTA em configuracoes: DIAS_GUARDAR_FOTO_ENTREGA, padrão 180,
--     mínimo 90. O master muda na tela Configurações.
--   * Apaga só o ARQUIVO. O registro da entrega, os pontos e o histórico ficam
--     de pé: a entrega passa a mostrar "foto removida por tempo"
--     (entregas.fotoexpiradaem).
--   * NÃO vale para documento de RH, que tem regra própria (documentospessoais).
--   * SQL não apaga arquivo do Storage. Então a rotina só marca e guarda o
--     caminho numa fila (fotosexpurgo); quem apaga de verdade é a Edge Function
--     expurgo-fotos, no mesmo molde da fila do Telegram (pg_net + Vault +
--     cabeçalho secreto + chave de servidor).
--   * fotoidunico NÃO é apagado: é a marca que impede reenviar a mesma foto.

-- ---------------------------------------------------------------------------
-- 1. Marca na entrega
-- ---------------------------------------------------------------------------
ALTER TABLE public.entregas ADD COLUMN fotoexpiradaem timestamptz;
COMMENT ON COLUMN public.entregas.fotoexpiradaem IS
  'Quando a foto foi apagada por tempo. Preenchida pela rotina de expurgo; a entrega continua valendo.';

-- ---------------------------------------------------------------------------
-- 2. Fila do que precisa sair do Storage
-- ---------------------------------------------------------------------------
CREATE TABLE public.fotosexpurgo (
  expurgoid   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contaid     integer NOT NULL DEFAULT public.minha_conta() REFERENCES public.contas (contaid) ON DELETE RESTRICT,
  entregaid   integer NOT NULL,
  caminho     text NOT NULL,
  criadoem    timestamptz NOT NULL DEFAULT now(),
  removidoem  timestamptz,
  tentativas  integer NOT NULL DEFAULT 0,
  erro        text,
  CONSTRAINT fotosexpurgo_entrega_fk FOREIGN KEY (contaid, entregaid)
    REFERENCES public.entregas (contaid, entregaid) ON DELETE RESTRICT,
  CONSTRAINT fotosexpurgo_conta_unico UNIQUE (contaid, expurgoid)
);
CREATE INDEX fotosexpurgo_pendentes_idx ON public.fotosexpurgo (criadoem) WHERE removidoem IS NULL;
CREATE UNIQUE INDEX fotosexpurgo_caminho_unico ON public.fotosexpurgo (contaid, caminho);

-- Ninguém lê nem escreve pelo navegador: é serviço interno, e o caminho do
-- arquivo não interessa a nenhuma tela. RLS ligada e sem policy = nega tudo.
ALTER TABLE public.fotosexpurgo ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.fotosexpurgo FROM anon, authenticated;
GRANT ALL ON public.fotosexpurgo TO service_role;

-- ---------------------------------------------------------------------------
-- 3. Configuração nova (prazo em dias) — funções recriadas por inteiro
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.cria_configuracoes_padrao(p_contaid integer)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $fn$
  INSERT INTO public.configuracoes (contaid, chave, valor, descricao) VALUES
    (p_contaid, 'TAXA_CONVERSAO_PONTO_REAL',     '0.03',  'Quanto vale 1 ponto em reais.'),
    (p_contaid, 'PONTOS_BONUS_FEEDBACK_DIARIO',  '5',     'Pontos de bonus por enviar o feedback do dia.'),
    (p_contaid, 'PONTOS_BONUS_NOTA_FISCAL',      '10',    'Pontos de bonus por enviar uma nota fiscal.'),
    (p_contaid, 'MAX_DIFERENCA_FOTO_SEGUNDOS',   '120',   'Tolerancia, em segundos, entre a hora da foto (EXIF) e o envio.'),
    (p_contaid, 'DIAS_GUARDAR_FOTO_ENTREGA',     '180',   'Por quantos dias a foto da entrega fica guardada. Depois disso o arquivo é apagado; a entrega e os pontos ficam. Mínimo 90.'),
    (p_contaid, 'HORARIO_GERACAO_TAREFAS',       '00:05', 'Hora em que a lista de tarefas do dia é gerada.'),
    (p_contaid, 'HORARIO_CONFERENCIA_LIVRO',     '03:00', 'Hora da conferência diária do livro de pontos, da limpeza do registro de rotinas e do expurgo de fotos.'),
    (p_contaid, 'HORARIO_FECHAMENTO_MENSAL',     '08:00', 'Hora do fechamento mensal do ranking (executa no dia 1).'),
    (p_contaid, 'HORARIO_DELEGACAO_FOLGA',       '09:05', 'Hora da delegacao automatica das tarefas de quem esta de folga.'),
    (p_contaid, 'HORARIO_LEMBRETE_COMUNICADOS',  '09:00', 'Hora do lembrete de comunicados pendentes de leitura.'),
    (p_contaid, 'HORARIO_LEMBRETE_HOJE',         '08:00', 'Hora do lembrete dos agendamentos de hoje.'),
    (p_contaid, 'HORARIO_LEMBRETE_DIARIO_AMANHA','09:00', 'Hora do lembrete dos agendamentos de amanha.'),
    (p_contaid, 'HORARIO_LEMBRETE_SEMANAL',      '08:00', 'Hora do lembrete semanal de agendamentos.'),
    (p_contaid, 'HORARIO_SILENCIO_INICIO',       '22:00', 'A partir desta hora o bot não manda mensagem automática (não vale dentro do turno da pessoa).'),
    (p_contaid, 'HORARIO_SILENCIO_FIM',          '07:00', 'A partir desta hora o bot volta a mandar mensagem automática.'),
    (p_contaid, 'MAX_MENSAGENS_AUTOMATICAS_DIA', '8',     'Máximo de mensagens automáticas por pessoa por dia.'),
    (p_contaid, 'MAX_TAREFAS_FOLGA_POR_PESSOA',  '3',     'Máximo de tarefas de folga que uma pessoa pode pegar por dia pelo grupo.'),
    (p_contaid, 'CONTATO_PRIVACIDADE',           '',      'Nome e contato de quem responde sobre dados pessoais (aparece na política de uso).'),
    (p_contaid, 'TAREFA_ID_FEEDBACK_DIARIO',           '', 'ID da tarefa de feedback diario. Preenchido pelo sistema.'),
    (p_contaid, 'TAREFA_ID_LEITURA',                   '', 'ID da tarefa de leitura de comunicado. Preenchido pelo sistema.'),
    (p_contaid, 'TAREFA_MODELO_AGENDAMENTO_ID',        '', 'ID da tarefa modelo usada ao criar um agendamento.'),
    (p_contaid, 'TAREFA_ID_PONTOS_META',               '', 'ID da tarefa que credita os pontos da meta diaria.'),
    (p_contaid, 'TAREFA_ID_NOTA_FISCAL',               '', 'ID da tarefa de envio de nota fiscal.'),
    (p_contaid, 'TAREFA_ID_GUARDAR_MERCADORIA_MODELO', '', 'ID da tarefa modelo de guardar mercadoria.')
  ON CONFLICT (contaid, chave) DO NOTHING;
$fn$;
REVOKE EXECUTE ON FUNCTION public.cria_configuracoes_padrao(integer) FROM public, anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.cria_configuracoes_padrao(integer) TO service_role;

-- As contas que já existem também ganham as chaves novas.
DO $$
DECLARE c record;
BEGIN
  FOR c IN SELECT contaid FROM public.contas LOOP
    PERFORM public.cria_configuracoes_padrao(c.contaid);
  END LOOP;
END $$;

CREATE OR REPLACE FUNCTION public.valida_configuracao()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
DECLARE
  v_texto text := btrim(coalesce(NEW.valor, ''));
  v_num   numeric;
BEGIN
  IF NEW.chave = 'TAXA_CONVERSAO_PONTO_REAL' THEN
    BEGIN
      v_num := replace(v_texto, ',', '.')::numeric;
    EXCEPTION WHEN others THEN
      RAISE EXCEPTION 'A taxa precisa ser um número, como 0,03.' USING ERRCODE = 'check_violation';
    END;
    IF v_num IS NULL OR v_num <= 0 OR v_num > 10 THEN
      RAISE EXCEPTION 'A taxa precisa ser maior que zero e no máximo R$ 10 por ponto.' USING ERRCODE = 'check_violation';
    END IF;
    NEW.valor := v_num::text;

  ELSIF NEW.chave LIKE 'PONTOS_BONUS_%' OR NEW.chave = 'MAX_DIFERENCA_FOTO_SEGUNDOS' THEN
    IF v_texto !~ '^[0-9]+$' THEN
      RAISE EXCEPTION 'O valor precisa ser um número inteiro, sem vírgula.' USING ERRCODE = 'check_violation';
    END IF;
    v_num := CASE WHEN NEW.chave LIKE 'PONTOS_BONUS_%' THEN 10000 ELSE 86400 END;
    IF v_texto::numeric > v_num THEN
      RAISE EXCEPTION 'Valor alto demais para %.', NEW.chave USING ERRCODE = 'check_violation';
    END IF;
    NEW.valor := v_texto::integer::text;

  -- Prazo da foto: nunca menos de 90 dias (a política de uso promete um prazo,
  -- e um prazo curto demais apagaria prova de entrega ainda em discussão).
  ELSIF NEW.chave = 'DIAS_GUARDAR_FOTO_ENTREGA' THEN
    IF v_texto !~ '^[0-9]+$' THEN
      RAISE EXCEPTION 'O prazo precisa ser um número inteiro de dias.' USING ERRCODE = 'check_violation';
    END IF;
    IF v_texto::integer < 90 OR v_texto::integer > 3650 THEN
      RAISE EXCEPTION 'O prazo precisa ser de 90 a 3650 dias.' USING ERRCODE = 'check_violation';
    END IF;
    NEW.valor := v_texto::integer::text;

  ELSIF NEW.chave IN ('MAX_MENSAGENS_AUTOMATICAS_DIA', 'MAX_TAREFAS_FOLGA_POR_PESSOA') THEN
    IF v_texto !~ '^[0-9]+$' OR v_texto::integer < 1 OR v_texto::integer > 50 THEN
      RAISE EXCEPTION 'O valor precisa ser um número inteiro de 1 a 50.' USING ERRCODE = 'check_violation';
    END IF;
    NEW.valor := v_texto::integer::text;

  ELSIF NEW.chave LIKE 'HORARIO_%' THEN
    IF v_texto !~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' THEN
      RAISE EXCEPTION 'O horário precisa estar no formato HH:MM, entre 00:00 e 23:59.' USING ERRCODE = 'check_violation';
    END IF;
    NEW.valor := v_texto;

  ELSIF NEW.chave = 'CONTATO_PRIVACIDADE' THEN
    IF length(v_texto) > 200 THEN
      RAISE EXCEPTION 'O contato pode ter no máximo 200 letras.' USING ERRCODE = 'check_violation';
    END IF;
    NEW.valor := v_texto;

  ELSIF NEW.chave LIKE 'TAREFA_%' THEN
    IF v_texto <> '' AND v_texto !~ '^[0-9]+$' THEN
      RAISE EXCEPTION 'ID de tarefa inválido.' USING ERRCODE = 'check_violation';
    END IF;
  END IF;

  IF TG_OP = 'UPDATE' THEN
    NEW.atualizadoem := now();
  END IF;
  RETURN NEW;
END;
$$;

-- ---------------------------------------------------------------------------
-- 4. A rotina
-- ---------------------------------------------------------------------------
ALTER TABLE public.rotinasexecucoes DROP CONSTRAINT rotinasexecucoes_rotina_check;
ALTER TABLE public.rotinasexecucoes ADD CONSTRAINT rotinasexecucoes_rotina_check
  CHECK (rotina IN ('lista_do_dia', 'fechamento_mensal', 'conferencia_livro', 'limpeza', 'mensagens', 'expurgo_fotos'));

-- Avisa a Edge Function que há arquivo para apagar (pg_net). Sem pg_net/Vault
-- (testes), não faz nada: a rotina do dia seguinte tenta de novo.
CREATE OR REPLACE FUNCTION public.fotos_expurgo_disparar()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE v_url text; v_segredo text;
BEGIN
  IF to_regclass('vault.decrypted_secrets') IS NULL OR to_regproc('net.http_post') IS NULL THEN
    RETURN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.fotosexpurgo WHERE removidoem IS NULL AND tentativas < 5) THEN
    RETURN;
  END IF;
  EXECUTE $q$SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'stgame_funcoes_url'$q$ INTO v_url;
  EXECUTE $q$SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'stgame_expurgo_segredo'$q$ INTO v_segredo;
  IF v_url IS NULL OR v_segredo IS NULL THEN
    RETURN;
  END IF;
  EXECUTE 'SELECT net.http_post(url := $1, body := $2, headers := $3, timeout_milliseconds := 60000)'
    USING rtrim(v_url, '/') || '/expurgo-fotos', '{}'::jsonb,
          jsonb_build_object('Content-Type', 'application/json', 'x-expurgo-segredo', v_segredo);
END;
$$;

-- Quantos dias esta conta guarda a foto (mínimo 90, mesmo se alguém gravar
-- um valor esquisito direto no banco).
CREATE OR REPLACE FUNCTION public.dias_guardar_foto(p_contaid integer)
RETURNS integer
LANGUAGE sql
STABLE
SET search_path = public, pg_temp
AS $$
  SELECT greatest(90, coalesce((SELECT nullif(btrim(valor), '')::integer
                                  FROM public.configuracoes
                                 WHERE contaid = p_contaid AND chave = 'DIAS_GUARDAR_FOTO_ENTREGA'), 180))
$$;

-- Marca as fotos vencidas e põe o caminho na fila de remoção. Uma vez por dia,
-- depois do horário da conferência. No máximo 2.000 por rodada, para não
-- travar o banco numa conta com muita foto antiga.
CREATE OR REPLACE FUNCTION public.rotina_expurgo_fotos(p_contaid integer, p_agora timestamptz)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_hoje   date;
  v_hora   time;
  v_inicio timestamptz := clock_timestamp();
  v_dias   integer;
  v_n      integer;
BEGIN
  SELECT x.dia, x.hora INTO v_hoje, v_hora FROM public.rotina_hora_local(p_agora) x;
  BEGIN
    IF v_hora < public.rotina_horario(p_contaid, 'HORARIO_CONFERENCIA_LIVRO', '03:00') THEN
      RETURN jsonb_build_object('acao', 'antes do horario');
    END IF;
    IF EXISTS (SELECT 1 FROM public.rotinasexecucoes
                WHERE contaid = p_contaid AND rotina = 'expurgo_fotos' AND referencia = v_hoje AND resultado = 'ok') THEN
      RETURN jsonb_build_object('acao', 'ja rodou hoje');
    END IF;

    v_dias := public.dias_guardar_foto(p_contaid);

    WITH vencidas AS (
      SELECT e.entregaid, e.pathfotoevidencia
        FROM public.entregas e
       WHERE e.contaid = p_contaid
         AND e.pathfotoevidencia IS NOT NULL
         AND e.fotoexpiradaem IS NULL
         AND e.dataenvio < p_agora - make_interval(days => v_dias)
       ORDER BY e.dataenvio
       LIMIT 2000
    ), na_fila AS (
      INSERT INTO public.fotosexpurgo (contaid, entregaid, caminho)
      SELECT p_contaid, v.entregaid, v.pathfotoevidencia FROM vencidas v
      ON CONFLICT (contaid, caminho) DO NOTHING
      RETURNING entregaid
    )
    UPDATE public.entregas e
       SET fotoexpiradaem = p_agora, pathfotoevidencia = NULL
      FROM vencidas v
     WHERE e.contaid = p_contaid AND e.entregaid = v.entregaid;
    GET DIAGNOSTICS v_n = ROW_COUNT;

    PERFORM public.rotina_registrar(p_contaid, 'expurgo_fotos', v_hoje, 'agendada', v_inicio, 'ok',
                                    jsonb_build_object('fotos', v_n, 'dias', v_dias), NULL);
    IF v_n > 0 THEN
      PERFORM public.fotos_expurgo_disparar();
    END IF;
    RETURN jsonb_build_object('fotos', v_n, 'dias', v_dias);
  EXCEPTION WHEN OTHERS THEN
    PERFORM public.rotina_registrar(p_contaid, 'expurgo_fotos', v_hoje, 'agendada', v_inicio, 'erro', NULL, SQLERRM);
    RETURN jsonb_build_object('erro', SQLERRM);
  END;
END;
$$;

-- ---------------------------------------------------------------------------
-- 5. Quem apaga o arquivo: a Edge Function expurgo-fotos
-- ---------------------------------------------------------------------------

-- A Edge Function pede a lista do que apagar (só a chave de servidor chama).
CREATE OR REPLACE FUNCTION public.expurgo_pegar(p_limite integer DEFAULT 100)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE v_out jsonb;
BEGIN
  IF NOT public.bot_contexto_confiavel() THEN
    RAISE EXCEPTION 'Só o servidor pode pedir a lista de expurgo.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  -- Conta a tentativa na hora de entregar a lista: se a Edge Function morrer no
  -- meio, o mesmo caminho não fica sendo tentado para sempre (para em 5).
  WITH alvo AS (
    SELECT expurgoid FROM public.fotosexpurgo
     WHERE removidoem IS NULL AND tentativas < 5
     ORDER BY criadoem
     LIMIT greatest(coalesce(p_limite, 100), 1)
     FOR UPDATE SKIP LOCKED
  ), pegos AS (
    UPDATE public.fotosexpurgo f
       SET tentativas = f.tentativas + 1
      FROM alvo a
     WHERE f.expurgoid = a.expurgoid
     RETURNING f.expurgoid, f.caminho, f.criadoem
  )
  SELECT coalesce(jsonb_agg(jsonb_build_object('id', expurgoid, 'caminho', caminho) ORDER BY criadoem), '[]'::jsonb)
    INTO v_out FROM pegos;
  RETURN v_out;
END;
$$;

-- A Edge Function conta o que apagou.
CREATE OR REPLACE FUNCTION public.expurgo_resultado(p_ids integer[], p_erro text DEFAULT NULL)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF NOT public.bot_contexto_confiavel() THEN
    RAISE EXCEPTION 'Só o servidor registra o resultado do expurgo.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF p_erro IS NULL THEN
    UPDATE public.fotosexpurgo SET removidoem = now(), erro = NULL
     WHERE expurgoid = ANY (p_ids) AND removidoem IS NULL;
  ELSE
    UPDATE public.fotosexpurgo SET erro = left(p_erro, 500)
     WHERE expurgoid = ANY (p_ids) AND removidoem IS NULL;
  END IF;
END;
$$;

-- ---------------------------------------------------------------------------
-- 6. O despachante passa a chamar o expurgo (função recriada por inteiro)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.rotinas_despachar(p_agora timestamptz DEFAULT now())
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE c record; v_n integer := 0; v_erros integer := 0;
BEGIN
  IF NOT pg_try_advisory_xact_lock(7310) THEN
    RETURN jsonb_build_object('ocupado', true);
  END IF;

  FOR c IN SELECT contaid FROM public.contas WHERE status = 'ativa' ORDER BY contaid LOOP
    BEGIN
      PERFORM public.rotina_lista_do_dia(c.contaid, p_agora, 'agendada');
      PERFORM public.rotina_fechamento_mensal(c.contaid, p_agora);
      PERFORM public.rotina_conferencia_livro(c.contaid, p_agora);
      PERFORM public.rotina_limpeza(c.contaid, p_agora);
      PERFORM public.rotina_expurgo_fotos(c.contaid, p_agora);
      v_n := v_n + 1;
    EXCEPTION WHEN OTHERS THEN
      v_erros := v_erros + 1;
      PERFORM public.rotina_registrar(c.contaid, 'lista_do_dia', NULL, 'agendada', clock_timestamp(), 'erro', NULL, SQLERRM);
    END;
    -- As mensagens ficam num bloco próprio: um erro aqui não atrapalha a lista do dia.
    BEGIN
      PERFORM public.rotina_mensagens(c.contaid, p_agora);
    EXCEPTION WHEN OTHERS THEN
      v_erros := v_erros + 1;
      PERFORM public.rotina_registrar(c.contaid, 'mensagens', NULL, 'agendada', clock_timestamp(), 'erro', NULL, SQLERRM);
    END;
  END LOOP;

  RETURN jsonb_build_object('contas', v_n, 'erros', v_erros);
END;
$$;

-- ---------------------------------------------------------------------------
-- 7. Permissões: nada disso é do navegador
-- ---------------------------------------------------------------------------
REVOKE ALL ON FUNCTION public.rotina_expurgo_fotos(integer, timestamptz) FROM public, anon, authenticated;
REVOKE ALL ON FUNCTION public.fotos_expurgo_disparar()                   FROM public, anon, authenticated;
REVOKE ALL ON FUNCTION public.dias_guardar_foto(integer)                 FROM public, anon, authenticated;
REVOKE ALL ON FUNCTION public.rotinas_despachar(timestamptz)             FROM public, anon, authenticated;
REVOKE ALL ON FUNCTION public.expurgo_pegar(integer)                     FROM public, anon, authenticated;
REVOKE ALL ON FUNCTION public.expurgo_resultado(integer[], text)         FROM public, anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.expurgo_pegar(integer)             TO service_role;
GRANT  EXECUTE ON FUNCTION public.expurgo_resultado(integer[], text) TO service_role;
