-- Etapa 1.11, parte 2: fechamento mensal do ranking.
--
-- Regras (decisões do Wisley, 22/09/2026):
--   * Roda no dia 1, no HORARIO_FECHAMENTO_MENSAL da conta, para o mês anterior.
--   * Dias 1 a 7: provisório, refeito todo dia. Dia 8: definitivo.
--   * "Refazer fechamento" só pelo master, com motivo; a versão anterior fica
--     guardada (situação "substituido").
--   * Grava, por loja ativa e geral da conta: posição, pontos ganhos, pontos
--     regulares, possíveis, confiabilidade, esforço e nota (mesma conta do
--     ranking ao vivo). Cada ponto conta na loja em que a tarefa foi feita.
--   * Sem pontos automáticos para os vencedores.

-- ---------------------------------------------------------------------------
-- 1. Fechamentos (uma versão vale por mês; as anteriores ficam guardadas)
-- ---------------------------------------------------------------------------
CREATE TABLE public.fechamentosmensais (
  fechamentoid  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contaid       integer NOT NULL DEFAULT public.minha_conta() REFERENCES public.contas (contaid) ON DELETE RESTRICT,
  ano           integer NOT NULL,
  mes           integer NOT NULL CHECK (mes BETWEEN 1 AND 12),
  versao        integer NOT NULL DEFAULT 1,
  situacao      varchar(12) NOT NULL CHECK (situacao IN ('provisorio', 'definitivo', 'substituido')),
  origem        varchar(10) NOT NULL CHECK (origem IN ('rotina', 'master')),
  motivo        text,
  fechadopor    uuid,
  fechadoem     timestamptz NOT NULL DEFAULT now(),
  atualizadoem  timestamptz,
  definitivoem  timestamptz,
  substituidoem timestamptz,
  CONSTRAINT fechamentosmensais_conta_unico UNIQUE (contaid, fechamentoid),
  CONSTRAINT fechamentosmensais_versao_unica UNIQUE (contaid, ano, mes, versao),
  CONSTRAINT fechamentosmensais_master_com_motivo CHECK (origem <> 'master' OR length(btrim(coalesce(motivo, ''))) > 0)
);
CREATE UNIQUE INDEX fechamentosmensais_um_valendo
  ON public.fechamentosmensais (contaid, ano, mes) WHERE situacao <> 'substituido';

ALTER TABLE public.fechamentosmensais ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.fechamentosmensais TO authenticated;
GRANT ALL ON public.fechamentosmensais TO service_role;
CREATE POLICY fechamentosmensais_sel ON public.fechamentosmensais FOR SELECT TO authenticated
  USING (contaid = (select public.minha_conta()));

-- ---------------------------------------------------------------------------
-- 2. historicoranking: uma linha por pessoa, por loja (ou geral), por versão
--    (a tabela está vazia: nada a migrar)
-- ---------------------------------------------------------------------------
DROP POLICY IF EXISTS historicoranking_ins ON public.historicoranking;
DROP POLICY IF EXISTS historicoranking_upd ON public.historicoranking;
DROP POLICY IF EXISTS historicoranking_del ON public.historicoranking;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON public.historicoranking FROM anon, authenticated;

DROP INDEX IF EXISTS public.historicoranking_um_por_mes;
ALTER TABLE public.historicoranking ALTER COLUMN lojaid DROP NOT NULL;   -- vazio = geral da conta
ALTER TABLE public.historicoranking ADD COLUMN fechamentoid    integer NOT NULL;
ALTER TABLE public.historicoranking ADD COLUMN pontosregulares integer NOT NULL DEFAULT 0;
ALTER TABLE public.historicoranking ADD COLUMN confiabilidade  numeric(6,2) NOT NULL DEFAULT 0;
ALTER TABLE public.historicoranking ADD COLUMN esforco         numeric(6,2) NOT NULL DEFAULT 0;
ALTER TABLE public.historicoranking ADD COLUMN nota            numeric(6,2) NOT NULL DEFAULT 0;
ALTER TABLE public.historicoranking ADD CONSTRAINT historicoranking_fechamento_fk
  FOREIGN KEY (contaid, fechamentoid) REFERENCES public.fechamentosmensais (contaid, fechamentoid) ON DELETE RESTRICT;
CREATE UNIQUE INDEX historicoranking_uma_linha
  ON public.historicoranking (fechamentoid, coalesce(lojaid, 0), funcionarioid);
CREATE INDEX historicoranking_fechamento_idx ON public.historicoranking (fechamentoid);

-- Linhas de fechamento definitivo ou substituído não mudam nem se apagam.
CREATE OR REPLACE FUNCTION public.protege_historico_ranking()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
DECLARE
  v_situacao text;
BEGIN
  SELECT situacao INTO v_situacao FROM public.fechamentosmensais
   WHERE fechamentoid = CASE WHEN TG_OP = 'INSERT' THEN NEW.fechamentoid ELSE OLD.fechamentoid END;
  IF v_situacao IS DISTINCT FROM 'provisorio' AND TG_OP <> 'INSERT' THEN
    RAISE EXCEPTION 'Fechamento definitivo não muda. Use "Refazer fechamento".' USING ERRCODE = 'restrict_violation';
  END IF;
  IF v_situacao = 'substituido' THEN
    RAISE EXCEPTION 'Fechamento substituído não recebe linhas.' USING ERRCODE = 'restrict_violation';
  END IF;
  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$;
CREATE TRIGGER historicoranking_protege BEFORE INSERT OR UPDATE OR DELETE ON public.historicoranking
  FOR EACH ROW EXECUTE FUNCTION public.protege_historico_ranking();

-- Versão substituída não volta; definitivo só vira substituído.
CREATE OR REPLACE FUNCTION public.protege_fechamento()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'Fechamento não se apaga.' USING ERRCODE = 'restrict_violation';
  END IF;
  IF NEW.contaid <> OLD.contaid OR NEW.ano <> OLD.ano OR NEW.mes <> OLD.mes OR NEW.versao <> OLD.versao THEN
    RAISE EXCEPTION 'Fechamento não muda de mês nem de versão.' USING ERRCODE = 'restrict_violation';
  END IF;
  IF OLD.situacao = 'substituido'
     OR (OLD.situacao = 'definitivo' AND NEW.situacao NOT IN ('definitivo', 'substituido')) THEN
    RAISE EXCEPTION 'Fechamento definitivo não volta a provisório.' USING ERRCODE = 'restrict_violation';
  END IF;
  NEW.atualizadoem := now();
  RETURN NEW;
END;
$$;
CREATE TRIGGER fechamentosmensais_protege BEFORE UPDATE OR DELETE ON public.fechamentosmensais
  FOR EACH ROW EXECUTE FUNCTION public.protege_fechamento();

-- ---------------------------------------------------------------------------
-- 3. Cálculo (interno)
-- ---------------------------------------------------------------------------

-- Grava as linhas de um fechamento: uma por pessoa em cada loja ativa e no geral.
CREATE OR REPLACE FUNCTION public.fechamento_calcular(p_contaid integer, p_fechamentoid integer)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  f      public.fechamentosmensais%ROWTYPE;
  v_fim  date;
  v_n    integer;
BEGIN
  SELECT * INTO f FROM public.fechamentosmensais WHERE fechamentoid = p_fechamentoid AND contaid = p_contaid;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Fechamento não encontrado.' USING ERRCODE = 'no_data_found';
  END IF;
  v_fim := (make_date(f.ano, f.mes, 1) + interval '1 month - 1 day')::date;

  DELETE FROM public.historicoranking WHERE fechamentoid = p_fechamentoid AND contaid = p_contaid;

  INSERT INTO public.historicoranking (contaid, lojaid, fechamentoid, ano, mes, posicao, funcionarioid, nomefuncionario,
                                       pontosganhos, pontosregulares, pontospossiveis, percentualdesempenho,
                                       confiabilidade, esforco, nota)
  SELECT p_contaid, esc.lojaid, p_fechamentoid, f.ano, f.mes,
         row_number() OVER (PARTITION BY esc.lojaid ORDER BY r.nota DESC, r.pontosganhos DESC, r.nomecompleto),
         r.funcionarioid, r.nomecompleto, r.pontosganhos, r.pontosregulares, r.pontospossiveis, r.confiabilidade,
         r.confiabilidade, r.esforco, r.nota
    FROM (SELECT NULL::integer AS lojaid
          UNION ALL
          SELECT l.lojaid FROM public.lojas l WHERE l.contaid = p_contaid AND l.ativa) esc
   CROSS JOIN LATERAL public.ranking_mensal_da_conta(p_contaid, f.ano, f.mes, esc.lojaid, v_fim) r;
  GET DIAGNOSTICS v_n = ROW_COUNT;
  RETURN v_n;
END;
$$;

-- A rotina do fechamento para uma conta (uma vez por dia, após o horário).
CREATE OR REPLACE FUNCTION public.rotina_fechamento_mensal(p_contaid integer, p_agora timestamptz)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_hoje   date;
  v_hora   time;
  v_ref    date;
  v_ano    integer;
  v_mes    integer;
  v_inicio timestamptz := clock_timestamp();
  f        public.fechamentosmensais%ROWTYPE;
  v_linhas integer;
  v_acao   text;
BEGIN
  SELECT x.dia, x.hora INTO v_hoje, v_hora FROM public.rotina_hora_local(p_agora) x;
  v_ref := (date_trunc('month', v_hoje) - interval '1 day')::date;   -- último dia do mês anterior
  v_ano := extract(year FROM v_ref)::integer;
  v_mes := extract(month FROM v_ref)::integer;

  BEGIN
    IF v_hora < public.rotina_horario(p_contaid, 'HORARIO_FECHAMENTO_MENSAL', '08:00') THEN
      RETURN jsonb_build_object('acao', 'antes do horario');
    END IF;
    -- Já rodou hoje?
    IF EXISTS (SELECT 1 FROM public.rotinasexecucoes
                WHERE contaid = p_contaid AND rotina = 'fechamento_mensal' AND referencia = v_hoje AND resultado = 'ok') THEN
      RETURN jsonb_build_object('acao', 'ja rodou hoje');
    END IF;

    PERFORM pg_advisory_xact_lock(7312, p_contaid);
    SELECT * INTO f FROM public.fechamentosmensais
     WHERE contaid = p_contaid AND ano = v_ano AND mes = v_mes AND situacao <> 'substituido'
     FOR UPDATE;

    IF NOT FOUND THEN
      INSERT INTO public.fechamentosmensais (contaid, ano, mes, versao, situacao, origem, definitivoem)
      VALUES (p_contaid, v_ano, v_mes, 1,
              CASE WHEN extract(day FROM v_hoje) <= 7 THEN 'provisorio' ELSE 'definitivo' END, 'rotina',
              CASE WHEN extract(day FROM v_hoje) > 7 THEN now() END)
      RETURNING * INTO f;
      -- Criado já definitivo quando a rotina ficou parada do dia 1 ao 7:
      -- as linhas novas entram uma vez (o gatilho só impede mudar ou apagar).
      v_acao := CASE WHEN f.situacao = 'provisorio' THEN 'criado provisorio' ELSE 'criado definitivo' END;
    ELSIF f.situacao = 'provisorio' THEN
      v_acao := CASE WHEN extract(day FROM v_hoje) <= 7 THEN 'refeito provisorio' ELSE 'refeito e definitivo' END;
    ELSE
      -- Mês já definitivo: nada a fazer (e nada a registrar).
      RETURN jsonb_build_object('acao', 'ja definitivo');
    END IF;

    v_linhas := public.fechamento_calcular(p_contaid, f.fechamentoid);
    IF extract(day FROM v_hoje) > 7 AND f.situacao = 'provisorio' THEN
      UPDATE public.fechamentosmensais SET situacao = 'definitivo', definitivoem = now()
       WHERE fechamentoid = f.fechamentoid;
    END IF;

    PERFORM public.rotina_registrar(p_contaid, 'fechamento_mensal', v_hoje, 'agendada', v_inicio, 'ok',
      jsonb_build_object('mes', to_char(v_ref, 'MM/YYYY'), 'acao', v_acao, 'linhas', v_linhas,
                         'fechamentoid', f.fechamentoid), NULL);
    RETURN jsonb_build_object('acao', v_acao, 'linhas', v_linhas);
  EXCEPTION WHEN OTHERS THEN
    PERFORM public.rotina_registrar(p_contaid, 'fechamento_mensal', v_hoje, 'agendada', v_inicio, 'erro', NULL, SQLERRM);
    RETURN jsonb_build_object('erro', SQLERRM);
  END;
END;
$$;

-- ---------------------------------------------------------------------------
-- 4. "Refazer fechamento" (master, com motivo)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.refazer_fechamento(p_ano integer, p_mes integer, p_motivo text)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_conta integer := public.minha_conta_editavel();
  f       public.fechamentosmensais%ROWTYPE;
  v_novo  integer;
BEGIN
  IF v_conta IS NULL THEN
    RAISE EXCEPTION 'Sua conta não pode alterar dados no momento.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF NOT public.sou_master() THEN
    RAISE EXCEPTION 'Só o responsável pela conta refaz o fechamento.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF length(btrim(coalesce(p_motivo, ''))) = 0 THEN
    RAISE EXCEPTION 'Informe o motivo.' USING ERRCODE = 'check_violation';
  END IF;

  PERFORM pg_advisory_xact_lock(7312, v_conta);
  SELECT * INTO f FROM public.fechamentosmensais
   WHERE contaid = v_conta AND ano = p_ano AND mes = p_mes AND situacao <> 'substituido'
   FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Esse mês ainda não foi fechado.' USING ERRCODE = 'no_data_found';
  END IF;

  UPDATE public.fechamentosmensais SET situacao = 'substituido', substituidoem = now()
   WHERE fechamentoid = f.fechamentoid;

  -- A versão nova fica na mesma situação da anterior (provisória ou definitiva).
  INSERT INTO public.fechamentosmensais (contaid, ano, mes, versao, situacao, origem, motivo, fechadopor, definitivoem)
  VALUES (v_conta, p_ano, p_mes, f.versao + 1, f.situacao, 'master', btrim(p_motivo), auth.uid(),
          CASE WHEN f.situacao = 'definitivo' THEN now() END)
  RETURNING fechamentoid INTO v_novo;
  PERFORM public.fechamento_calcular(v_conta, v_novo);

  PERFORM public.rotina_registrar(v_conta, 'fechamento_mensal', public.dia_em_sao_paulo(now()), 'manual',
    clock_timestamp(), 'ok',
    jsonb_build_object('mes', lpad(p_mes::text, 2, '0') || '/' || p_ano, 'acao', 'refeito pelo master',
                       'versao', f.versao + 1, 'fechamentoid', v_novo), NULL);
  RETURN v_novo;
END;
$$;

-- ---------------------------------------------------------------------------
-- 5. Permissões
-- ---------------------------------------------------------------------------
REVOKE ALL ON FUNCTION public.protege_historico_ranking()                     FROM public, anon, authenticated;
REVOKE ALL ON FUNCTION public.protege_fechamento()                            FROM public, anon, authenticated;
REVOKE ALL ON FUNCTION public.fechamento_calcular(integer, integer)           FROM public, anon, authenticated;
REVOKE ALL ON FUNCTION public.rotina_fechamento_mensal(integer, timestamptz)  FROM public, anon, authenticated;
REVOKE ALL ON FUNCTION public.refazer_fechamento(integer, integer, text)      FROM public, anon;
GRANT EXECUTE ON FUNCTION public.refazer_fechamento(integer, integer, text)   TO authenticated;
