-- Etapa 1.12 — a TV entra por CÓDIGO CURTO, sem ninguém digitar link comprido.
--
-- Como funciona (o mesmo desenho que a TV da sala usa para entrar em serviço
-- de vídeo): a TV abre stgame.com.br/tv e mostra um código de 6 caracteres.
-- O gestor, do celular, digita esse código, escolhe a loja e dá um nome. A TV
-- estava perguntando de tempos em tempos "já me pareou?" e, quando a resposta
-- vem, recebe o link de sempre e o guarda no próprio aparelho.
--
-- ONDE ISSO É DIFERENTE DO RESTO DO BANCO, e por quê:
-- a linha do código NASCE SEM CONTA — quando a TV pede o código, ninguém
-- ainda sabe de que empresa ela é. É o mesmo caso de `tentativasacesso`, que
-- também guarda tentativas antes de existir conta. A proteção é a mesma das
-- duas: RLS ligada e NENHUMA policy, então ninguém lê esta tabela pelo
-- navegador; tudo passa por funções que só o servidor chama. A conta só entra
-- na linha no instante em que o gestor pareia, e aí ela é a conta DELE.
--
-- O link comprido de hoje continua valendo: o pareamento cria exatamente um
-- registro de `linkstv`, igual ao que "Criar link" sempre criou.

-- ---------------------------------------------------------------------------
-- 1. A tabela dos códigos
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.codigostv (
  codigotvid  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- O que aparece na tela da TV. Sem O/0, I/1 e S/5: de longe ninguém
  -- distingue, e quem digita erra.
  codigo      char(6) NOT NULL UNIQUE,
  -- O segredo do APARELHO. É com ele que a TV pergunta "já me pareou?", e é
  -- o que impede outro aparelho de pegar o link no lugar dela só por estar
  -- vendo o código na parede. Guardado embaralhado, nunca em claro.
  segredohash char(64) NOT NULL,
  criadoem    timestamptz NOT NULL DEFAULT now(),
  expiraem    timestamptz NOT NULL,
  -- Preenchidos no instante do pareamento. Vazios até lá — ver o comentário
  -- do topo.
  contaid     integer REFERENCES public.contas (contaid) ON DELETE CASCADE,
  linktvid    integer REFERENCES public.linkstv (linktvid) ON DELETE CASCADE,
  -- O link da TV, guardado por poucos minutos até ela vir buscar, e apagado
  -- na hora em que ela busca. Nunca fica parado aqui.
  token       text,
  pareadoem   timestamptz,
  entregueem  timestamptz
);

COMMENT ON TABLE public.codigostv IS
  'Códigos de pareamento da TV. Nasce sem conta (ninguém sabe de quem é a TV ainda) e ganha a conta do gestor que parear. Tabela interna: RLS ligada e nenhuma policy, ninguém a lê pelo navegador.';

CREATE INDEX IF NOT EXISTS codigostv_expiraem_idx ON public.codigostv (expiraem);
CREATE INDEX IF NOT EXISTS codigostv_segredo_idx  ON public.codigostv (segredohash);

ALTER TABLE public.codigostv ENABLE ROW LEVEL SECURITY;
-- Sem policy nenhuma, de propósito: nem o dono da conta lê esta tabela
-- direto. Só as funções abaixo, e só o servidor as chama.
REVOKE ALL ON public.codigostv FROM public, anon, authenticated;
GRANT  ALL ON public.codigostv TO service_role;

-- A trava de tentativas passa a conhecer o pareamento da TV.
ALTER TABLE public.tentativasacesso DROP CONSTRAINT IF EXISTS tentativasacesso_tipo_check;
ALTER TABLE public.tentativasacesso ADD  CONSTRAINT tentativasacesso_tipo_check
  CHECK (tipo IN ('senha', 'pin', 'tablet', 'pintablet', 'lojamanual', 'tvcodigo'));

-- ---------------------------------------------------------------------------
-- 2. A TV pede um código
-- ---------------------------------------------------------------------------
-- Sorteia um código do alfabeto seguro, guarda o segredo do aparelho e
-- devolve o código. De quebra, limpa os vencidos: a tabela não cresce.
CREATE OR REPLACE FUNCTION public.tv_novo_codigo(p_segredohash text, p_minutos integer DEFAULT 10)
RETURNS text
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  -- Sem O, 0, I, 1, S e 5: os que se confundem de longe.
  v_letras text := 'ABCDEFGHJKLMNPQRTUVWXYZ2346789';
  v_codigo text;
  v_tenta  integer := 0;
BEGIN
  IF NOT public.bot_contexto_confiavel() THEN
    RAISE EXCEPTION 'Só o servidor pede código de TV.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF p_segredohash IS NULL OR length(p_segredohash) <> 64 THEN
    RAISE EXCEPTION 'Aparelho não identificado.' USING ERRCODE = 'check_violation';
  END IF;

  -- Vencido não serve para nada e não pode atrapalhar o sorteio.
  DELETE FROM public.codigostv WHERE expiraem < now();

  LOOP
    v_codigo := '';
    FOR i IN 1..6 LOOP
      v_codigo := v_codigo || substr(v_letras, 1 + floor(random() * length(v_letras))::integer, 1);
    END LOOP;
    EXIT WHEN NOT EXISTS (SELECT 1 FROM public.codigostv WHERE codigo = v_codigo);
    v_tenta := v_tenta + 1;
    IF v_tenta > 50 THEN
      RAISE EXCEPTION 'Não foi possível gerar um código agora. Tente de novo.';
    END IF;
  END LOOP;

  INSERT INTO public.codigostv (codigo, segredohash, expiraem)
  VALUES (v_codigo, p_segredohash,
          now() + make_interval(mins => greatest(1, least(coalesce(p_minutos, 10), 60))));

  RETURN v_codigo;
END;
$$;

REVOKE ALL ON FUNCTION public.tv_novo_codigo(text, integer) FROM public, anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.tv_novo_codigo(text, integer) TO service_role;

-- ---------------------------------------------------------------------------
-- 3. O gestor pareia: digita o código, escolhe a loja e dá um nome
-- ---------------------------------------------------------------------------
-- Chamada por quem ESTÁ LOGADO: a conta sai de minha_conta_editavel(), nunca
-- do navegador. A loja é conferida contra essa conta, igual a criar_link_tv.
CREATE OR REPLACE FUNCTION public.parear_tv(p_codigo text, p_lojaid integer, p_nome text)
RETURNS void
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_conta  integer := public.minha_conta_editavel();
  v_codigo text    := upper(btrim(coalesce(p_codigo, '')));
  v_id     bigint;
  v_token  text;
  v_link   integer;
BEGIN
  IF v_conta IS NULL THEN
    RAISE EXCEPTION 'Sua conta não pode alterar dados no momento.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF length(btrim(coalesce(p_nome, ''))) = 0 THEN
    RAISE EXCEPTION 'Dê um nome à TV (ex.: TV do balcão).' USING ERRCODE = 'check_violation';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.lojas WHERE lojaid = p_lojaid AND contaid = v_conta AND ativa) THEN
    RAISE EXCEPTION 'Loja não encontrada ou desativada.' USING ERRCODE = 'no_data_found';
  END IF;

  -- O código tem de existir, estar no prazo e ainda não ter sido usado.
  -- FOR UPDATE: dois gestores digitando o mesmo código ao mesmo tempo, só um
  -- pareia.
  SELECT codigotvid INTO v_id
    FROM public.codigostv
   WHERE codigo = v_codigo AND expiraem > now() AND pareadoem IS NULL
   FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Código inválido ou vencido. Veja o código que está na TV agora.'
      USING ERRCODE = 'no_data_found';
  END IF;

  -- Daqui para baixo é exatamente o que "Criar link" sempre fez.
  v_token := replace(gen_random_uuid()::text, '-', '') || replace(gen_random_uuid()::text, '-', '');
  INSERT INTO public.linkstv (contaid, lojaid, nome, tokenhash, criadopor)
  VALUES (v_conta, p_lojaid, btrim(p_nome),
          encode(sha256(convert_to(v_token, 'UTF8')), 'hex'), auth.uid())
  RETURNING linktvid INTO v_link;

  UPDATE public.codigostv
     SET contaid = v_conta, linktvid = v_link, token = v_token, pareadoem = now()
   WHERE codigotvid = v_id;
END;
$$;

REVOKE ALL ON FUNCTION public.parear_tv(text, integer, text) FROM public, anon;
GRANT  EXECUTE ON FUNCTION public.parear_tv(text, integer, text) TO authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 4. A TV pergunta: "já me parearam?"
-- ---------------------------------------------------------------------------
-- Responde pelo SEGREDO do aparelho, não pelo código: quem só viu o código na
-- parede não leva o link. O link sai UMA vez e é apagado da linha na mesma
-- operação — não fica parado aqui.
CREATE OR REPLACE FUNCTION public.tv_buscar_link(p_segredohash text)
RETURNS jsonb
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE r record;
BEGIN
  IF NOT public.bot_contexto_confiavel() THEN
    RAISE EXCEPTION 'Só o servidor busca o link da TV.' USING ERRCODE = 'insufficient_privilege';
  END IF;

  SELECT codigotvid, token, pareadoem, expiraem INTO r
    FROM public.codigostv
   WHERE segredohash = p_segredohash
   ORDER BY criadoem DESC
   LIMIT 1
   FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('situacao', 'sem_codigo');
  END IF;
  IF r.pareadoem IS NULL THEN
    -- Ainda não parearam. Se o código venceu, a TV pede outro.
    RETURN jsonb_build_object('situacao', CASE WHEN r.expiraem < now() THEN 'vencido' ELSE 'esperando' END);
  END IF;
  IF r.token IS NULL THEN
    -- Já foi entregue uma vez. O código é de uso único.
    RETURN jsonb_build_object('situacao', 'ja_entregue');
  END IF;

  UPDATE public.codigostv SET token = NULL, entregueem = now() WHERE codigotvid = r.codigotvid;
  RETURN jsonb_build_object('situacao', 'pareada', 'token', r.token);
END;
$$;

REVOKE ALL ON FUNCTION public.tv_buscar_link(text) FROM public, anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.tv_buscar_link(text) TO service_role;

-- ---------------------------------------------------------------------------
-- 5. A trava de tentativas conhece o pareamento da TV
-- ---------------------------------------------------------------------------
-- Partiu da versao mais recente (20260928100500), com o diff conferido: a
-- unica mudanca e o tipo 'tvcodigo' na lista.
CREATE OR REPLACE FUNCTION public.tentativa_abrir_ex(p_contaid integer, p_tipo text,
                                                     p_chave text, p_origem text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_janela  interval := CASE WHEN p_tipo = 'pin' THEN interval '1 minute' ELSE interval '15 minutes' END;
  v_chave   text     := left(coalesce(p_chave, ''), 64);
  v_origem  text     := left(coalesce(p_origem, 'sem-ip'), 40);
  v_erros   integer;
  v_outros  integer;
  v_esperar integer  := 0;
  v_id      bigint;
BEGIN
  IF NOT public.bot_contexto_confiavel() THEN
    RAISE EXCEPTION 'Só o servidor abre tentativa de acesso.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF p_tipo NOT IN ('senha', 'pin', 'tablet', 'pintablet', 'lojamanual', 'tvcodigo') THEN
    RAISE EXCEPTION 'Tipo de tentativa inválido.' USING ERRCODE = 'check_violation';
  END IF;

  PERFORM pg_advisory_xact_lock(hashtextextended('stgame.chave:' || p_tipo || ':' || v_chave, 0));
  IF v_origem <> 'sem-ip' THEN
    PERFORM pg_advisory_xact_lock(hashtextextended('stgame.origem:' || p_tipo || ':' || v_origem, 0));
  END IF;

  -- ---- Login da loja com senha DIGITADA: atraso, nunca bloqueio ----------
  -- Bloquear devolveria o problema que fez a trava ser desligada na parte A:
  -- o engraçadinho erra de propósito e a loja fica sem sistema. O atraso
  -- castiga quem adivinha e não tira a loja do ar.
  IF p_tipo = 'lojamanual' THEN
    SELECT count(*) INTO v_erros FROM public.tentativasacesso t
     WHERE t.contaid IS NOT DISTINCT FROM p_contaid AND t.tipo = 'lojamanual' AND t.chave = v_chave
       AND NOT t.sucesso AND t.em > now() - interval '15 minutes'
       AND t.em > coalesce((SELECT max(s.em) FROM public.tentativasacesso s
                             WHERE s.contaid IS NOT DISTINCT FROM p_contaid AND s.tipo = 'lojamanual'
                               AND s.chave = v_chave AND s.sucesso), '-infinity'::timestamptz);
    v_outros := 0;
    IF v_origem <> 'sem-ip' THEN
      SELECT count(*) INTO v_outros FROM public.tentativasacesso t
       WHERE t.contaid IS NOT DISTINCT FROM p_contaid AND t.tipo = 'lojamanual' AND t.origem = v_origem
         AND NOT t.sucesso AND t.em > now() - interval '15 minutes'
         AND t.em > coalesce((SELECT max(s.em) FROM public.tentativasacesso s
                               WHERE s.contaid IS NOT DISTINCT FROM p_contaid AND s.tipo = 'lojamanual'
                                 AND s.origem = v_origem AND s.sucesso), '-infinity'::timestamptz);
    END IF;
    v_erros := greatest(v_erros, v_outros);
    IF v_erros > 0 THEN
      v_esperar := least(500 * (2 ^ least(v_erros - 1, 10))::integer, 10000);
    END IF;

    INSERT INTO public.tentativasacesso (contaid, tipo, chave, origem, sucesso)
    VALUES (p_contaid, p_tipo, v_chave, v_origem, false)
    RETURNING tentativaid INTO v_id;
    DELETE FROM public.tentativasacesso WHERE em < now() - interval '7 days';
    RETURN jsonb_build_object('tentativaid', v_id, 'esperar', v_esperar);
  END IF;

  -- ---- Os outros tipos, como já eram --------------------------------------
  IF p_tipo = 'pin' THEN
    SELECT count(*) INTO v_erros FROM public.tentativasacesso t
     WHERE t.contaid IS NOT DISTINCT FROM p_contaid AND t.tipo = 'pin' AND t.chave = v_chave
       AND t.em > now() - interval '1 day';
    IF v_erros >= 30 THEN
      RETURN jsonb_build_object('tentativaid', NULL, 'esperar', 0);
    END IF;
  END IF;

  IF p_tipo = 'pintablet' THEN
    SELECT count(*) INTO v_erros FROM public.tentativasacesso t
     WHERE t.contaid IS NOT DISTINCT FROM p_contaid AND t.tipo = 'pintablet' AND t.chave = v_chave
       AND NOT t.sucesso AND t.em > now() - interval '1 day';
    IF v_erros >= 20 THEN
      RETURN jsonb_build_object('tentativaid', NULL, 'esperar', 0);
    END IF;
  END IF;

  IF p_tipo <> 'tablet' THEN
    SELECT count(*) INTO v_erros FROM public.tentativasacesso t
     WHERE t.contaid IS NOT DISTINCT FROM p_contaid AND t.tipo = p_tipo AND t.chave = v_chave
       AND NOT t.sucesso AND t.em > now() - v_janela
       AND t.em > coalesce((SELECT max(s.em) FROM public.tentativasacesso s
                             WHERE s.contaid IS NOT DISTINCT FROM p_contaid AND s.tipo = p_tipo
                               AND s.chave = v_chave AND s.sucesso), '-infinity'::timestamptz);
    IF v_erros >= 5 THEN
      RETURN jsonb_build_object('tentativaid', NULL, 'esperar', 0);
    END IF;
  END IF;

  IF v_origem <> 'sem-ip' THEN
    SELECT count(*) INTO v_erros FROM public.tentativasacesso t
     WHERE t.contaid IS NOT DISTINCT FROM p_contaid AND t.tipo = p_tipo AND t.origem = v_origem
       AND NOT t.sucesso AND t.em > now() - v_janela
       AND t.em > coalesce((SELECT max(s.em) FROM public.tentativasacesso s
                             WHERE s.contaid IS NOT DISTINCT FROM p_contaid AND s.tipo = p_tipo
                               AND s.origem = v_origem AND s.sucesso), '-infinity'::timestamptz);
    IF v_erros >= 5 THEN
      RETURN jsonb_build_object('tentativaid', NULL, 'esperar', 0);
    END IF;
  END IF;

  INSERT INTO public.tentativasacesso (contaid, tipo, chave, origem, sucesso)
  VALUES (p_contaid, p_tipo, v_chave, v_origem, false)
  RETURNING tentativaid INTO v_id;

  DELETE FROM public.tentativasacesso WHERE em < now() - interval '7 days';
  RETURN jsonb_build_object('tentativaid', v_id, 'esperar', 0);
END;
$$;

-- Quem já chamava tentativa_abrir continua chamando: ela vira um atalho.
CREATE OR REPLACE FUNCTION public.tentativa_abrir(p_contaid integer, p_tipo text,
                                                  p_chave text, p_origem text)
RETURNS bigint
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT (public.tentativa_abrir_ex(p_contaid, p_tipo, p_chave, p_origem) ->> 'tentativaid')::bigint
$$;


REVOKE ALL ON FUNCTION public.tentativa_abrir_ex(integer, text, text, text) FROM public, anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.tentativa_abrir_ex(integer, text, text, text) TO service_role;
