-- Etapa 1.12, parte B1 — a ficha do tablet da loja (24/09/2026).
--
-- Problema prático: quando o gestor perde os dados de acesso do tablet, ele
-- não tem como recuperar. O usuário só aparecia no instante da criação, e a
-- senha nunca mais (ela é guardada só como resumo — PBKDF2 com sal —, e isso
-- fica como está: guardar senha recuperável seria um retrocesso).
--
-- Solução: o usuário passa a ficar sempre à vista, e existe "Gerar nova
-- senha". Toda geração fica registrada.

-- ---------------------------------------------------------------------------
-- 1. Histórico do acesso da loja
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.acessoslojaeventos (
  eventoid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contaid  integer NOT NULL DEFAULT public.minha_conta() REFERENCES public.contas (contaid) ON DELETE RESTRICT,
  lojaid   integer NOT NULL,
  evento   varchar(12) NOT NULL CHECK (evento IN ('criado', 'senha_nova')),
  userid   uuid REFERENCES auth.users (id) ON DELETE SET NULL,
  em       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT acessoslojaeventos_loja_fk FOREIGN KEY (contaid, lojaid)
    REFERENCES public.lojas (contaid, lojaid) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS acessoslojaeventos_loja_idx
  ON public.acessoslojaeventos (contaid, lojaid, em DESC);
ALTER TABLE public.acessoslojaeventos ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.acessoslojaeventos TO authenticated;
GRANT ALL    ON public.acessoslojaeventos TO service_role;

-- Só o master lê. Nem o gerente, nem o tablet, nem o administrador geral.
DROP POLICY IF EXISTS acessoslojaeventos_sel ON public.acessoslojaeventos;
CREATE POLICY acessoslojaeventos_sel ON public.acessoslojaeventos FOR SELECT TO authenticated
  USING (contaid = (select public.minha_conta()) AND (select public.sou_master()));

COMMENT ON TABLE public.acessoslojaeventos IS
  'Histórico do acesso do tablet de cada loja: quando foi criado e cada vez que uma senha nova foi gerada, e por quem.';

-- Recebe a conta: é interna, só o servidor chama (regra da Etapa 1.6). Quem
-- confere se é o master é a função de servidor, com o token de quem pediu.
CREATE OR REPLACE FUNCTION public.registrar_evento_acesso_loja(p_contaid integer, p_lojaid integer,
                                                               p_evento text, p_quem uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF NOT public.bot_contexto_confiavel() THEN
    RAISE EXCEPTION 'Só o servidor registra o acesso da loja.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.lojas WHERE contaid = p_contaid AND lojaid = p_lojaid) THEN
    RAISE EXCEPTION 'Loja não encontrada.' USING ERRCODE = 'no_data_found';
  END IF;
  INSERT INTO public.acessoslojaeventos (contaid, lojaid, evento, userid)
  VALUES (p_contaid, p_lojaid, p_evento, p_quem);
END;
$$;

-- ---------------------------------------------------------------------------
-- 2. A ficha: usuário, último uso e quantos aparelhos estão abertos
-- ---------------------------------------------------------------------------
-- O usuário do tablet mora em auth.users, que ninguém logado lê. Esta função
-- é a única porta, e só o servidor a chama, com a conta que ele já conferiu
-- pelo token.
CREATE OR REPLACE FUNCTION public.ficha_dos_tablets(p_contaid integer)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_sessoes jsonb := '{}'::jsonb;
BEGIN
  IF NOT public.bot_contexto_confiavel() THEN
    RAISE EXCEPTION 'Só o servidor lê a ficha do tablet.' USING ERRCODE = 'insufficient_privilege';
  END IF;

  -- Quantos aparelhos estão abertos. auth.sessions é interno do Supabase: se
  -- um dia ele mudar de nome, a ficha continua funcionando sem esse número.
  IF to_regclass('auth.sessions') IS NOT NULL THEN
    EXECUTE $q$
      SELECT coalesce(jsonb_object_agg(user_id::text, n), '{}'::jsonb)
        FROM (SELECT user_id, count(*) AS n FROM auth.sessions
               WHERE not_after IS NULL OR not_after > now()
               GROUP BY user_id) s
    $q$ INTO v_sessoes;
  END IF;

  RETURN (
    SELECT coalesce(jsonb_agg(jsonb_build_object(
             'lojaid',       l.lojaid,
             'loja',         l.nome,
             'usuario',      u.email,
             'ultimoacesso', u.last_sign_in_at,
             'aparelhos',    coalesce((v_sessoes ->> cu.userid::text)::integer, 0),
             'historico',    coalesce((
               -- Desempate por eventoid: dois eventos na mesma transacao
               -- carregam o mesmo now(), e a ordem ficaria ao acaso.
               SELECT jsonb_agg(jsonb_build_object('evento', e.evento, 'em', e.em, 'quem', q.email)
                                ORDER BY e.em DESC, e.eventoid DESC)
                 FROM public.acessoslojaeventos e
                 LEFT JOIN auth.users q ON q.id = e.userid
                WHERE e.contaid = p_contaid AND e.lojaid = l.lojaid), '[]'::jsonb))
           ORDER BY l.nome), '[]'::jsonb)
      FROM public.contasusuarios cu
      JOIN public.lojas l    ON l.contaid = cu.contaid AND l.lojaid = cu.lojaid
      LEFT JOIN auth.users u ON u.id = cu.userid
     WHERE cu.contaid = p_contaid AND cu.papel = 'loja' AND cu.lojaid IS NOT NULL);
END;
$$;

-- ---------------------------------------------------------------------------
-- 3. Permissões: as duas recebem a conta, então só o servidor as chama.
-- ---------------------------------------------------------------------------
REVOKE ALL ON FUNCTION public.registrar_evento_acesso_loja(integer, integer, text, uuid)
  FROM public, anon, authenticated;
REVOKE ALL ON FUNCTION public.ficha_dos_tablets(integer) FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.registrar_evento_acesso_loja(integer, integer, text, uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.ficha_dos_tablets(integer)                                 TO service_role;

-- ---------------------------------------------------------------------------
-- 4. O diagnóstico (/saude) conhece as funções desta parte
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.diagnostico_do_sistema()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_esperadas text[] := ARRAY[
    'tentativa_abrir', 'tentativa_fechar', 'acesso_por_email', 'definir_senha_gestor',
    'senha_app_de', 'senha_app_do_funcionario', 'definir_senha_app', 'definir_pin',
    'criar_codigo_acesso', 'usar_codigo_acesso', 'conta_do_codigo',
    'criar_acesso_loja', 'criar_acesso_colaborador', 'redefinir_acesso', 'trocar_cpf',
    'meu_acesso', 'situacao_dos_acessos', 'minha_politica_de_uso', 'politica_dar_ciencia',
    'limpar_senha_gestor', 'rotina_expurgo_fotos', 'expurgo_pegar', 'expurgo_resultado',
    -- Etapa 1.12, partes B1a e B1b
    'pegar_tarefa', 'revogar_aceite', 'atribuir_tarefa', 'fila_da_loja',
    'tarefas_nao_pegas', 'tarefas_pegas_da_pessoa', 'tarefa_unica_ja_cumprida',
    'visao_fila', 'visao_pessoa_do_pin', 'visao_pegar', 'visao_entregar',
    'fechamento_valendo', 'ficha_dos_tablets', 'registrar_evento_acesso_loja'
  ];
  v_faltando text[];
  v_tabelas  text[];
BEGIN
  IF NOT public.bot_contexto_confiavel() THEN
    RAISE EXCEPTION 'Só o servidor pede o diagnóstico.' USING ERRCODE = 'insufficient_privilege';
  END IF;

  SELECT coalesce(array_agg(f ORDER BY f), ARRAY[]::text[]) INTO v_faltando
    FROM unnest(v_esperadas) f
   WHERE NOT EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
                      WHERE n.nspname = 'public' AND p.proname = f);

  SELECT coalesce(array_agg(t ORDER BY t), ARRAY[]::text[]) INTO v_tabelas
    FROM unnest(ARRAY['codigosacesso', 'tentativasacesso', 'senhasgestor', 'fotosexpurgo',
                      'tarefascandidatos', 'acessoslojaeventos']) t
   WHERE to_regclass('public.' || t) IS NULL;

  RETURN jsonb_build_object(
    'funcoesfaltando', to_jsonb(v_faltando),
    'tabelasfaltando', to_jsonb(v_tabelas),
    'acessos', (SELECT count(*) FROM public.contasusuarios),
    'senhasgestor', (SELECT count(*) FROM public.senhasgestor));
END;
$$;

REVOKE ALL ON FUNCTION public.diagnostico_do_sistema() FROM public, anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.diagnostico_do_sistema() TO service_role;
