-- Etapa 1.8 (antiga Fase 8): metas de faturamento por loja.
-- Decisoes do Wisley em 22/09/2026, registradas em docs/PLANO_MIGRACAO.md.
--
-- - Meta do dia: valor fixo por dia da semana, por loja; "meta especial"
--   para uma data substitui o modelo daquele dia. A meta fica guardada no
--   lancamento (mudar o modelo depois nao muda dias passados).
-- - Lancamento: total vendido no dia (substitui); correcao exige motivo;
--   so o mes atual e o anterior; tudo no historico (quem, quando, antigo,
--   novo, motivo).
-- - Pontos pelo livro; no maximo um premio valendo por dia por loja (e um
--   por mes), garantido pelo banco. Ganha quem esta ligado a loja, ativo,
--   e no DIA DA VENDA (nao no dia do lancamento) nao esta de folga nem
--   afastado. Meta do mes: ligado e ativo quando bateu.
-- - Correcao: deixou de bater -> estorno automatico de quem recebeu;
--   voltou a bater -> paga de novo. Bonus de meta fora do ranking e da nota.
-- - TV: so porcentagem, a menos que a loja ligue "mostrar valores".

-- ===========================================================================
-- 1. Lojas: opcao de mostrar valores em R$ na TV (desligada por padrao)
-- ===========================================================================

ALTER TABLE public.lojas ADD COLUMN mostrarvalorestv boolean NOT NULL DEFAULT false;

-- ===========================================================================
-- 2. Meta do dia por dia da semana (modelos) e metas especiais por data
-- ===========================================================================

-- A trava antiga era "um por dia da semana POR CONTA": so uma loja do
-- cliente teria meta de segunda. Passa a ser por loja (a chave primaria ja
-- e lojaid + diasemanaid).
ALTER TABLE public.metasdiariasmodelos DROP CONSTRAINT metasdiariasmodelos_conta_unico;
ALTER TABLE public.metasdiariasmodelos ADD CONSTRAINT metasdiariasmodelos_conta_unico UNIQUE (contaid, lojaid, diasemanaid);
ALTER TABLE public.metasdiariasmodelos ADD CONSTRAINT metasdiariasmodelos_dia_valido CHECK (diasemanaid BETWEEN 1 AND 7);
ALTER TABLE public.metasdiariasmodelos ADD CONSTRAINT metasdiariasmodelos_valores_validos
  CHECK (valormeta >= 0 AND pontospremio >= 0 AND pontospremio <= 10000);

CREATE TABLE public.metasespeciais (
  metaespecialid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contaid        integer NOT NULL DEFAULT public.minha_conta() REFERENCES public.contas(contaid) ON DELETE RESTRICT,
  lojaid         integer NOT NULL,
  data           date    NOT NULL,
  descricao      varchar(100) NOT NULL CHECK (length(btrim(descricao)) > 0),
  valormeta      numeric(18,2) NOT NULL CHECK (valormeta >= 0),
  pontospremio   integer NOT NULL DEFAULT 0 CHECK (pontospremio BETWEEN 0 AND 10000),
  criadoem       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT metasespeciais_conta_unico UNIQUE (contaid, metaespecialid),
  CONSTRAINT metasespeciais_uma_por_data UNIQUE (lojaid, data),
  CONSTRAINT metasespeciais_loja_fk FOREIGN KEY (contaid, lojaid)
    REFERENCES public.lojas (contaid, lojaid) ON DELETE RESTRICT
);
CREATE INDEX metasespeciais_contaid_idx ON public.metasespeciais (contaid);

ALTER TABLE public.metasespeciais ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.metasespeciais FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.metasespeciais TO authenticated;
GRANT ALL ON public.metasespeciais TO service_role;
CREATE POLICY metasespeciais_sel ON public.metasespeciais FOR SELECT TO authenticated
  USING (contaid = (select public.minha_conta()));
CREATE POLICY metasespeciais_ins ON public.metasespeciais FOR INSERT TO authenticated
  WITH CHECK (contaid = (select public.minha_conta_editavel()));
CREATE POLICY metasespeciais_upd ON public.metasespeciais FOR UPDATE TO authenticated
  USING (contaid = (select public.minha_conta_editavel())) WITH CHECK (contaid = (select public.minha_conta_editavel()));
CREATE POLICY metasespeciais_del ON public.metasespeciais FOR DELETE TO authenticated
  USING (contaid = (select public.minha_conta_editavel()));

-- A meta de um dia: a especial daquela data, se houver; senao, o modelo do
-- dia da semana (1 = domingo ... 7 = sabado). Roda com a RLS de quem chama.
CREATE OR REPLACE FUNCTION public.meta_do_dia(p_lojaid integer, p_dia date)
RETURNS TABLE (valormeta numeric, pontospremio integer, origem text, descricao text)
LANGUAGE sql
STABLE
SET search_path = public, pg_temp
AS $$
  SELECT x.valormeta, x.pontospremio, x.origem, x.descricao
    FROM (
      SELECT me.valormeta, me.pontospremio, 'especial'::text AS origem, me.descricao::text AS descricao, 1 AS ordem
        FROM public.metasespeciais me
       WHERE me.lojaid = p_lojaid AND me.data = p_dia
      UNION ALL
      SELECT mm.valormeta, mm.pontospremio, 'semana', mm.nomedia::text, 2
        FROM public.metasdiariasmodelos mm
       WHERE mm.lojaid = p_lojaid AND mm.diasemanaid = extract(dow FROM p_dia)::integer + 1
    ) x
   ORDER BY x.ordem
   LIMIT 1
$$;

-- ===========================================================================
-- 3. Meta do mes (metasprincipais): uma por loja por mes do calendario
-- ===========================================================================

UPDATE public.metasprincipais SET status = 'Ativa' WHERE status IS NULL;
ALTER TABLE public.metasprincipais
  ADD COLUMN criadopor     uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  ADD COLUMN atualizadoem  timestamptz NOT NULL DEFAULT now();
ALTER TABLE public.metasprincipais ADD CONSTRAINT metasprincipais_mes_do_calendario CHECK (
  datainicio = date_trunc('month', datainicio)::date
  AND datafim = (date_trunc('month', datainicio) + interval '1 month - 1 day')::date);
ALTER TABLE public.metasprincipais ADD CONSTRAINT metasprincipais_valores_validos
  CHECK (valormetatotal > 0 AND pontospremio BETWEEN 0 AND 100000);
ALTER TABLE public.metasprincipais ADD CONSTRAINT metasprincipais_uma_por_mes UNIQUE (lojaid, datainicio);
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON public.metasprincipais FROM anon, authenticated;

-- ===========================================================================
-- 4. Lancamentos (metasdiariasapuracoes): um por loja por dia; a meta do
--    dia fica guardada no lancamento.
-- ===========================================================================

DROP INDEX IF EXISTS public.metasdiariasapuracoes_um_por_dia;
ALTER TABLE public.metasdiariasapuracoes ALTER COLUMN metaprincipalid DROP NOT NULL;
ALTER TABLE public.metasdiariasapuracoes
  ADD COLUMN valormetadia  numeric(18,2),
  ADD COLUMN pontosmetadia integer NOT NULL DEFAULT 0,
  ADD COLUMN origemmeta    varchar(10),
  ADD COLUMN descricaometa text,
  ADD COLUMN lancadopor    uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  ADD COLUMN lancadoem     timestamptz NOT NULL DEFAULT now(),
  ADD COLUMN atualizadopor uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  ADD COLUMN atualizadoem  timestamptz NOT NULL DEFAULT now();
ALTER TABLE public.metasdiariasapuracoes ADD CONSTRAINT metasdiariasapuracoes_um_por_dia UNIQUE (lojaid, dataapuracao);
ALTER TABLE public.metasdiariasapuracoes ADD CONSTRAINT metasdiariasapuracoes_valor_valido
  CHECK (valordia >= 0 AND valordia < 1000000000);
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON public.metasdiariasapuracoes FROM anon, authenticated;

-- Historico de lancamentos e correcoes. Nunca muda nem se apaga.
CREATE TABLE public.metashistorico (
  historicoid    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contaid        integer NOT NULL DEFAULT public.minha_conta() REFERENCES public.contas(contaid) ON DELETE RESTRICT,
  lojaid         integer NOT NULL,
  apuracaoid     integer NOT NULL,
  dataapuracao   date    NOT NULL,
  valoranterior  numeric(18,2),
  valornovo      numeric(18,2) NOT NULL,
  motivo         text,
  alteradopor    uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  alteradoem     timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT metashistorico_loja_fk FOREIGN KEY (contaid, lojaid)
    REFERENCES public.lojas (contaid, lojaid) ON DELETE RESTRICT,
  CONSTRAINT metashistorico_apuracao_fk FOREIGN KEY (contaid, apuracaoid)
    REFERENCES public.metasdiariasapuracoes (contaid, apuracaoid) ON DELETE RESTRICT
);
CREATE INDEX metashistorico_loja_idx ON public.metashistorico (lojaid, alteradoem DESC);

ALTER TABLE public.metashistorico ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.metashistorico FROM anon, authenticated;
GRANT SELECT ON public.metashistorico TO authenticated;
GRANT ALL ON public.metashistorico TO service_role;
CREATE POLICY metashistorico_sel ON public.metashistorico FOR SELECT TO authenticated
  USING (contaid = (select public.minha_conta()));
CREATE TRIGGER metashistorico_imutavel
  BEFORE UPDATE OR DELETE ON public.metashistorico
  FOR EACH ROW EXECUTE FUNCTION public.historico_imutavel();

-- ===========================================================================
-- 5. Premios de meta. No maximo um VALENDO por dia por loja (tipo 'dia') e
--    um por mes (tipo 'mes'), garantido por indice unico. Quem recebeu fica
--    no livro de pontos, ligado ao premio.
-- ===========================================================================

CREATE TABLE public.metaspremiacoes (
  premiacaoid     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contaid         integer NOT NULL DEFAULT public.minha_conta() REFERENCES public.contas(contaid) ON DELETE RESTRICT,
  lojaid          integer NOT NULL,
  tipo            varchar(3) NOT NULL CHECK (tipo IN ('dia', 'mes')),
  apuracaoid      integer,
  metaprincipalid integer,
  pontos          integer NOT NULL CHECK (pontos > 0),
  pagoem          timestamptz NOT NULL DEFAULT now(),
  estornadoem     timestamptz,
  CONSTRAINT metaspremiacoes_conta_unico UNIQUE (contaid, premiacaoid),
  CONSTRAINT metaspremiacoes_loja_fk FOREIGN KEY (contaid, lojaid)
    REFERENCES public.lojas (contaid, lojaid) ON DELETE RESTRICT,
  CONSTRAINT metaspremiacoes_apuracao_fk FOREIGN KEY (contaid, apuracaoid)
    REFERENCES public.metasdiariasapuracoes (contaid, apuracaoid) ON DELETE RESTRICT,
  CONSTRAINT metaspremiacoes_meta_fk FOREIGN KEY (contaid, metaprincipalid)
    REFERENCES public.metasprincipais (contaid, metaprincipalid) ON DELETE RESTRICT,
  CONSTRAINT metaspremiacoes_alvo CHECK (
    (tipo = 'dia' AND apuracaoid IS NOT NULL AND metaprincipalid IS NULL)
    OR (tipo = 'mes' AND metaprincipalid IS NOT NULL AND apuracaoid IS NULL))
);
CREATE UNIQUE INDEX metaspremiacoes_um_por_dia ON public.metaspremiacoes (apuracaoid)
  WHERE tipo = 'dia' AND estornadoem IS NULL;
CREATE UNIQUE INDEX metaspremiacoes_um_por_mes ON public.metaspremiacoes (metaprincipalid)
  WHERE tipo = 'mes' AND estornadoem IS NULL;
CREATE INDEX metaspremiacoes_loja_idx ON public.metaspremiacoes (lojaid, pagoem DESC);

ALTER TABLE public.metaspremiacoes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.metaspremiacoes FROM anon, authenticated;
GRANT SELECT ON public.metaspremiacoes TO authenticated;
GRANT ALL ON public.metaspremiacoes TO service_role;
CREATE POLICY metaspremiacoes_sel ON public.metaspremiacoes FOR SELECT TO authenticated
  USING (contaid = (select public.minha_conta()));

ALTER TABLE public.movimentospontos ADD COLUMN premiacaoid integer;
ALTER TABLE public.movimentospontos ADD CONSTRAINT movimentospontos_premiacao_fk
  FOREIGN KEY (contaid, premiacaoid) REFERENCES public.metaspremiacoes (contaid, premiacaoid) ON DELETE RESTRICT;

-- Quem ganha a meta do dia: ligado a loja, ativo e, NO DIA DA VENDA, sem
-- folga semanal, domingo de folga nem afastamento. Interna.
CREATE OR REPLACE FUNCTION public.equipe_da_meta(p_contaid integer, p_lojaid integer, p_dia date)
RETURNS SETOF integer
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT f.funcionarioid
    FROM public.funcionarioslojas fl
    JOIN public.funcionarios f ON f.funcionarioid = fl.funcionarioid AND f.contaid = fl.contaid
   WHERE fl.contaid = p_contaid AND fl.lojaid = p_lojaid
     AND fl.ativo AND f.ativo
     AND (p_dia IS NULL OR public.dia_de_trabalho(f.diadefolga, f.domingofolgamensal,
                                                  f.datainicioafastamento, f.datafimafastamento, p_dia))
   ORDER BY f.funcionarioid
$$;

-- Paga um premio (uma linha no livro por pessoa). Interna.
CREATE OR REPLACE FUNCTION public.pagar_premio_meta(
  p_contaid integer, p_lojaid integer, p_tipo text, p_apuracaoid integer, p_metaprincipalid integer,
  p_pontos integer, p_dia date, p_descricao text
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE v_id integer; v_func integer;
BEGIN
  INSERT INTO public.metaspremiacoes (contaid, lojaid, tipo, apuracaoid, metaprincipalid, pontos)
  VALUES (p_contaid, p_lojaid, p_tipo, p_apuracaoid, p_metaprincipalid, p_pontos)
  ON CONFLICT DO NOTHING
  RETURNING premiacaoid INTO v_id;
  IF v_id IS NULL THEN
    RETURN NULL;   -- ja ha um premio valendo: nao paga de novo
  END IF;

  FOR v_func IN SELECT * FROM public.equipe_da_meta(p_contaid, p_lojaid, p_dia) LOOP
    INSERT INTO public.movimentospontos (contaid, funcionarioid, lojaid, tipo, pontos, descricao, premiacaoid, criadopor)
    VALUES (p_contaid, v_func, p_lojaid, 'bonus', p_pontos, p_descricao, v_id, auth.uid());
  END LOOP;
  RETURN v_id;
END;
$$;

-- Estorna um premio: devolve, pelo livro, exatamente de quem recebeu. Interna.
CREATE OR REPLACE FUNCTION public.estornar_premio_meta(p_premiacaoid integer, p_motivo text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE m record;
BEGIN
  UPDATE public.metaspremiacoes SET estornadoem = now()
   WHERE premiacaoid = p_premiacaoid AND estornadoem IS NULL;
  IF NOT FOUND THEN
    RETURN;
  END IF;
  FOR m IN SELECT contaid, funcionarioid, lojaid, pontos, descricao
             FROM public.movimentospontos
            WHERE premiacaoid = p_premiacaoid AND tipo = 'bonus'
            ORDER BY funcionarioid
  LOOP
    INSERT INTO public.movimentospontos (contaid, funcionarioid, lojaid, tipo, pontos, descricao, premiacaoid, criadopor)
    VALUES (m.contaid, m.funcionarioid, m.lojaid, 'estorno_bonus', -m.pontos,
            m.descricao || ' — estornado: ' || p_motivo, p_premiacaoid, auth.uid());
  END LOOP;
END;
$$;

-- Confere a meta do dia de um lancamento e paga ou estorna. Interna.
CREATE OR REPLACE FUNCTION public.reavaliar_meta_do_dia(p_apuracaoid integer)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  a       public.metasdiariasapuracoes%ROWTYPE;
  v_ativo integer;
  v_loja  text;
  v_bateu boolean;
BEGIN
  SELECT * INTO a FROM public.metasdiariasapuracoes WHERE apuracaoid = p_apuracaoid;
  SELECT nome INTO v_loja FROM public.lojas WHERE lojaid = a.lojaid;
  v_bateu := coalesce(a.valormetadia, 0) > 0 AND a.pontosmetadia > 0 AND a.valordia >= a.valormetadia;
  SELECT premiacaoid INTO v_ativo FROM public.metaspremiacoes
   WHERE apuracaoid = p_apuracaoid AND tipo = 'dia' AND estornadoem IS NULL;

  IF v_bateu AND v_ativo IS NULL THEN
    PERFORM public.pagar_premio_meta(a.contaid, a.lojaid, 'dia', a.apuracaoid, NULL, a.pontosmetadia,
                                     a.dataapuracao,
                                     'Meta do dia ' || to_char(a.dataapuracao, 'DD/MM/YYYY') || ' — ' || v_loja);
  ELSIF NOT v_bateu AND v_ativo IS NOT NULL THEN
    PERFORM public.estornar_premio_meta(v_ativo, 'o valor corrigido não bate mais a meta');
  END IF;
END;
$$;

-- Confere a meta do mes de uma loja e paga ou estorna. Ganha quem esta
-- ligado e ativo quando bateu. Interna.
CREATE OR REPLACE FUNCTION public.reavaliar_meta_do_mes(p_contaid integer, p_lojaid integer, p_mes date)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  m       public.metasprincipais%ROWTYPE;
  v_total numeric;
  v_ativo integer;
  v_loja  text;
  v_bateu boolean;
BEGIN
  SELECT * INTO m FROM public.metasprincipais
   WHERE contaid = p_contaid AND lojaid = p_lojaid AND datainicio = date_trunc('month', p_mes)::date;
  IF NOT FOUND THEN
    RETURN;
  END IF;
  SELECT nome INTO v_loja FROM public.lojas WHERE lojaid = p_lojaid;
  SELECT coalesce(sum(valordia), 0) INTO v_total FROM public.metasdiariasapuracoes
   WHERE lojaid = p_lojaid AND dataapuracao BETWEEN m.datainicio AND m.datafim;
  v_bateu := m.pontospremio > 0 AND v_total >= m.valormetatotal;
  SELECT premiacaoid INTO v_ativo FROM public.metaspremiacoes
   WHERE metaprincipalid = m.metaprincipalid AND tipo = 'mes' AND estornadoem IS NULL;

  IF v_bateu AND v_ativo IS NULL THEN
    PERFORM public.pagar_premio_meta(p_contaid, p_lojaid, 'mes', NULL, m.metaprincipalid, m.pontospremio,
                                     NULL, 'Meta do mês ' || to_char(m.datainicio, 'MM/YYYY') || ' — ' || v_loja);
  ELSIF NOT v_bateu AND v_ativo IS NOT NULL THEN
    PERFORM public.estornar_premio_meta(v_ativo, 'o total do mês não bate mais a meta');
  END IF;
END;
$$;

-- Primeiro dia que ainda aceita lancamento ou correcao: o 1o do mes
-- anterior. Mais antigo, o banco recusa (estorno de meses atras derrubaria
-- o saldo de quem ja gastou os pontos).
CREATE OR REPLACE FUNCTION public.primeiro_dia_editavel_meta()
RETURNS date
LANGUAGE sql
STABLE
SET search_path = public, pg_temp
AS $$
  SELECT (date_trunc('month', public.dia_em_sao_paulo(now())) - interval '1 month')::date
$$;

-- Lanca (ou corrige) o total vendido num dia. Devolve o lancamento.
CREATE OR REPLACE FUNCTION public.lancar_venda_do_dia(p_lojaid integer, p_dia date, p_valor numeric, p_motivo text DEFAULT NULL)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_conta  integer := public.minha_conta_editavel();
  v_hoje   date    := public.dia_em_sao_paulo(now());
  v_ap     public.metasdiariasapuracoes%ROWTYPE;
  v_meta   record;
  v_mp     integer;
  v_motivo text := nullif(btrim(coalesce(p_motivo, '')), '');
  v_id     integer;
BEGIN
  IF v_conta IS NULL THEN
    RAISE EXCEPTION 'Sua conta não pode alterar dados no momento.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.lojas WHERE lojaid = p_lojaid AND contaid = v_conta AND ativa) THEN
    RAISE EXCEPTION 'Loja não encontrada.' USING ERRCODE = 'no_data_found';
  END IF;
  IF p_dia IS NULL OR p_dia > v_hoje THEN
    RAISE EXCEPTION 'Não dá para lançar venda de um dia que ainda não chegou.' USING ERRCODE = 'check_violation';
  END IF;
  IF p_dia < public.primeiro_dia_editavel_meta() THEN
    RAISE EXCEPTION 'Só dá para lançar ou corrigir vendas do mês atual e do mês anterior.' USING ERRCODE = 'check_violation';
  END IF;
  IF p_valor IS NULL OR p_valor < 0 THEN
    RAISE EXCEPTION 'O valor vendido precisa ser zero ou mais.' USING ERRCODE = 'check_violation';
  END IF;

  -- Um lancamento por vez para a mesma loja e dia, e para o mesmo mes.
  PERFORM pg_advisory_xact_lock(p_lojaid, p_dia - date '2000-01-01');
  PERFORM pg_advisory_xact_lock(p_lojaid, -(extract(year FROM p_dia)::integer * 12 + extract(month FROM p_dia)::integer));

  SELECT * INTO v_ap FROM public.metasdiariasapuracoes WHERE lojaid = p_lojaid AND dataapuracao = p_dia;

  IF NOT FOUND THEN
    SELECT * INTO v_meta FROM public.meta_do_dia(p_lojaid, p_dia);
    SELECT metaprincipalid INTO v_mp FROM public.metasprincipais
     WHERE lojaid = p_lojaid AND datainicio = date_trunc('month', p_dia)::date;
    INSERT INTO public.metasdiariasapuracoes (contaid, lojaid, metaprincipalid, dataapuracao, valordia,
                                              valormetadia, pontosmetadia, origemmeta, descricaometa,
                                              lancadopor, atualizadopor)
    VALUES (v_conta, p_lojaid, v_mp, p_dia, round(p_valor, 2),
            v_meta.valormeta, coalesce(v_meta.pontospremio, 0), v_meta.origem, v_meta.descricao,
            auth.uid(), auth.uid())
    RETURNING apuracaoid INTO v_id;
    INSERT INTO public.metashistorico (contaid, lojaid, apuracaoid, dataapuracao, valoranterior, valornovo, motivo, alteradopor)
    VALUES (v_conta, p_lojaid, v_id, p_dia, NULL, round(p_valor, 2), v_motivo, auth.uid());
  ELSE
    v_id := v_ap.apuracaoid;
    IF v_ap.valordia = round(p_valor, 2) THEN
      RETURN v_id;   -- nada mudou
    END IF;
    IF v_motivo IS NULL THEN
      RAISE EXCEPTION 'Este dia já tem lançamento. Para corrigir, informe o motivo.' USING ERRCODE = 'check_violation';
    END IF;
    UPDATE public.metasdiariasapuracoes
       SET valordia = round(p_valor, 2), atualizadopor = auth.uid(), atualizadoem = now()
     WHERE apuracaoid = v_id;
    INSERT INTO public.metashistorico (contaid, lojaid, apuracaoid, dataapuracao, valoranterior, valornovo, motivo, alteradopor)
    VALUES (v_conta, p_lojaid, v_id, p_dia, v_ap.valordia, round(p_valor, 2), v_motivo, auth.uid());
  END IF;

  PERFORM public.reavaliar_meta_do_dia(v_id);
  PERFORM public.reavaliar_meta_do_mes(v_conta, p_lojaid, p_dia);
  RETURN v_id;
END;
$$;

-- Cria ou altera a meta do mes de uma loja. So do mes anterior em diante.
CREATE OR REPLACE FUNCTION public.salvar_meta_do_mes(
  p_lojaid integer, p_mes date, p_nome text, p_valor numeric, p_pontos integer, p_descricao text DEFAULT NULL
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_conta integer := public.minha_conta_editavel();
  v_ini   date := date_trunc('month', p_mes)::date;
  v_id    integer;
BEGIN
  IF v_conta IS NULL THEN
    RAISE EXCEPTION 'Sua conta não pode alterar dados no momento.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.lojas WHERE lojaid = p_lojaid AND contaid = v_conta AND ativa) THEN
    RAISE EXCEPTION 'Loja não encontrada.' USING ERRCODE = 'no_data_found';
  END IF;
  IF v_ini < public.primeiro_dia_editavel_meta() THEN
    RAISE EXCEPTION 'Só dá para mexer na meta do mês atual, do anterior e dos próximos.' USING ERRCODE = 'check_violation';
  END IF;
  IF p_valor IS NULL OR p_valor <= 0 THEN
    RAISE EXCEPTION 'A meta do mês precisa ser maior que zero.' USING ERRCODE = 'check_violation';
  END IF;
  IF p_pontos IS NULL OR p_pontos < 0 THEN
    RAISE EXCEPTION 'Os pontos do prêmio precisam ser zero ou mais.' USING ERRCODE = 'check_violation';
  END IF;

  PERFORM pg_advisory_xact_lock(p_lojaid, -(extract(year FROM v_ini)::integer * 12 + extract(month FROM v_ini)::integer));

  INSERT INTO public.metasprincipais (contaid, lojaid, nomemeta, descricao, valormetatotal, datainicio, datafim,
                                      pontospremio, criadopor)
  VALUES (v_conta, p_lojaid, coalesce(nullif(btrim(coalesce(p_nome, '')), ''), 'Meta de ' || to_char(v_ini, 'MM/YYYY')),
          nullif(btrim(coalesce(p_descricao, '')), ''), round(p_valor, 2), v_ini,
          (v_ini + interval '1 month - 1 day')::date, p_pontos, auth.uid())
  ON CONFLICT (lojaid, datainicio) DO UPDATE
     SET nomemeta = EXCLUDED.nomemeta, descricao = EXCLUDED.descricao,
         valormetatotal = EXCLUDED.valormetatotal, pontospremio = EXCLUDED.pontospremio, atualizadoem = now()
  RETURNING metaprincipalid INTO v_id;

  -- Lancamentos do mes que ainda nao estavam ligados a meta.
  UPDATE public.metasdiariasapuracoes SET metaprincipalid = v_id
   WHERE lojaid = p_lojaid AND dataapuracao BETWEEN v_ini AND (v_ini + interval '1 month - 1 day')::date
     AND metaprincipalid IS DISTINCT FROM v_id;

  PERFORM public.reavaliar_meta_do_mes(v_conta, p_lojaid, v_ini);
  RETURN v_id;
END;
$$;

-- Resumo das metas de uma loja para um mes (tela Metas). RLS de quem chama.
CREATE OR REPLACE FUNCTION public.metas_do_mes(p_lojaid integer, p_mes date)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
  WITH lim AS (
    SELECT date_trunc('month', p_mes)::date AS ini,
           (date_trunc('month', p_mes) + interval '1 month - 1 day')::date AS fim
  ),
  dias AS (
    SELECT g::date AS d FROM lim, generate_series(lim.ini, lim.fim, interval '1 day') g
  ),
  linhas AS (
    SELECT d.d AS dia,
           a.apuracaoid, a.valordia,
           coalesce(a.valormetadia, md.valormeta) AS valormeta,
           CASE WHEN a.apuracaoid IS NOT NULL THEN a.pontosmetadia ELSE md.pontospremio END AS pontos,
           coalesce(a.origemmeta, md.origem) AS origem,
           coalesce(a.descricaometa, md.descricao) AS descricao,
           (SELECT count(*) FROM public.movimentospontos mv
              JOIN public.metaspremiacoes p ON p.premiacaoid = mv.premiacaoid
             WHERE p.apuracaoid = a.apuracaoid AND p.tipo = 'dia' AND p.estornadoem IS NULL
               AND mv.tipo = 'bonus') AS premiados
      FROM dias d
      LEFT JOIN public.metasdiariasapuracoes a ON a.lojaid = p_lojaid AND a.dataapuracao = d.d
      LEFT JOIN LATERAL public.meta_do_dia(p_lojaid, d.d) md ON true
  ),
  mes AS (
    SELECT m.metaprincipalid, m.nomemeta, m.valormetatotal, m.pontospremio,
           EXISTS (SELECT 1 FROM public.metaspremiacoes p
                    WHERE p.metaprincipalid = m.metaprincipalid AND p.tipo = 'mes' AND p.estornadoem IS NULL) AS premiado
      FROM public.metasprincipais m, lim
     WHERE m.lojaid = p_lojaid AND m.datainicio = lim.ini
  )
  SELECT jsonb_build_object(
    'mes',       (SELECT to_jsonb(mes) FROM mes),
    'vendido',   (SELECT coalesce(sum(valordia), 0) FROM linhas),
    'somametas', (SELECT coalesce(sum(valormeta), 0) FROM linhas),
    'diaslancados', (SELECT count(*) FROM linhas WHERE apuracaoid IS NOT NULL),
    'dias',      (SELECT coalesce(jsonb_agg(jsonb_build_object(
                    'dia', dia, 'apuracaoid', apuracaoid, 'vendido', valordia, 'meta', valormeta,
                    'pontos', pontos, 'origem', origem, 'descricao', descricao,
                    'bateu', valordia IS NOT NULL AND coalesce(valormeta, 0) > 0 AND valordia >= valormeta,
                    'premiados', premiados) ORDER BY dia), '[]'::jsonb) FROM linhas),
    'primeirodiaeditavel', public.primeiro_dia_editavel_meta()
  )
$$;

-- Bloco da meta para o painel e a TV. Na TV, sem a opcao da loja, nenhum
-- valor em reais sai do banco: so porcentagens. Interna (chamada pelo
-- montar_painel).
CREATE OR REPLACE FUNCTION public.meta_para_painel(p_contaid integer, p_lojaid integer, p_tv boolean)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_hoje    date := public.dia_em_sao_paulo(now());
  v_valores boolean;
  v_ap      public.metasdiariasapuracoes%ROWTYPE;
  v_md      record;
  v_meta    numeric;
  v_vendido numeric;
  v_dia     jsonb;
  v_mes     jsonb;
  m         public.metasprincipais%ROWTYPE;
  v_total   numeric;
  v_dias    integer;
BEGIN
  SELECT NOT p_tv OR mostrarvalorestv INTO v_valores
    FROM public.lojas WHERE lojaid = p_lojaid AND contaid = p_contaid;

  -- Meta de hoje: a guardada no lancamento, ou a do modelo/especial.
  SELECT * INTO v_ap FROM public.metasdiariasapuracoes WHERE lojaid = p_lojaid AND dataapuracao = v_hoje;
  SELECT * INTO v_md FROM public.meta_do_dia(p_lojaid, v_hoje);
  v_meta := coalesce(v_ap.valormetadia, v_md.valormeta);
  v_vendido := coalesce(v_ap.valordia, 0);
  IF coalesce(v_meta, 0) > 0 THEN
    v_dia := jsonb_build_object(
      'percentual', round(v_vendido * 100 / v_meta, 1),
      'bateu',      v_vendido >= v_meta,
      'lancado',    v_ap.apuracaoid IS NOT NULL,
      'especial',   CASE WHEN coalesce(v_ap.origemmeta, v_md.origem) = 'especial'
                         THEN coalesce(v_ap.descricaometa, v_md.descricao) END);
    IF v_valores THEN
      v_dia := v_dia || jsonb_build_object('vendido', v_vendido, 'meta', v_meta);
    END IF;
  END IF;

  SELECT * INTO m FROM public.metasprincipais
   WHERE lojaid = p_lojaid AND contaid = p_contaid AND v_hoje BETWEEN datainicio AND datafim;
  IF FOUND THEN
    SELECT coalesce(sum(valordia), 0), count(*) INTO v_total, v_dias
      FROM public.metasdiariasapuracoes WHERE lojaid = p_lojaid AND dataapuracao BETWEEN m.datainicio AND m.datafim;
    v_mes := jsonb_build_object(
      'nome',       m.nomemeta,
      'percentual', round(v_total * 100 / m.valormetatotal, 1),
      'bateu',      v_total >= m.valormetatotal);
    IF v_valores THEN
      v_mes := v_mes || jsonb_build_object(
        'vendido', v_total, 'meta', m.valormetatotal,
        'projecao', CASE WHEN v_dias > 0
                         THEN round(v_total / v_dias * (m.datafim - m.datainicio + 1), 2) END);
    END IF;
  END IF;

  IF v_dia IS NULL AND v_mes IS NULL THEN
    RETURN NULL;
  END IF;
  RETURN jsonb_build_object('dia', v_dia, 'mes', v_mes, 'valores', v_valores);
END;
$$;

-- ===========================================================================
-- 6. Painel da loja e TV ganham o bloco da meta (copia da versao anterior
--    do montar_painel com uma chave a mais).
-- ===========================================================================

CREATE OR REPLACE FUNCTION public.montar_painel(p_contaid integer, p_lojaid integer, p_tv boolean)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_hoje       date := public.dia_em_sao_paulo(now());
  v_loja       text;
  v_dia        jsonb;
  v_validacao  jsonb;
  v_pendentes  integer;
  v_podio      jsonb;
  v_atividade  jsonb;
BEGIN
  SELECT nome INTO v_loja FROM public.lojas WHERE lojaid = p_lojaid AND contaid = p_contaid;
  IF NOT FOUND THEN
    RETURN NULL;
  END IF;

  -- Tarefas do dia e a situacao de cada uma hoje.
  WITH dia AS (
    SELECT t.titulo,
           t.pontos,
           CASE WHEN p_tv THEN public.nome_curto(f.nomecompleto) ELSE f.nomecompleto END AS pessoa,
           (ta.tipofrequencia = 'Unica' AND ta.dataagendamento IS NOT NULL
            AND public.dia_em_sao_paulo(ta.dataagendamento) < v_hoje) AS atrasada,
           (SELECT e.statusvalidacao
              FROM public.entregas e
             WHERE e.atribuicaoid = ta.atribuicaoid
               AND e.statusvalidacao IN ('Pendente', 'Aprovada')
               AND public.dia_em_sao_paulo(e.dataenvio) = v_hoje
             ORDER BY e.entregaid DESC
             LIMIT 1) AS situacao
      FROM public.tarefasatribuidas ta
      JOIN public.tarefas t            ON t.tarefaid = ta.tarefaid
      JOIN public.funcionarios f       ON f.funcionarioid = ta.funcionarioid
      JOIN public.funcionarioslojas fl ON fl.funcionarioid = ta.funcionarioid AND fl.lojaid = ta.lojaid
     WHERE ta.contaid = p_contaid
       AND ta.lojaid = p_lojaid
       AND ta.datafimvigencia IS NULL
       AND f.ativo AND fl.ativo AND coalesce(t.ativa, true)
       AND public.tarefa_cai_no_dia(ta.tipofrequencia, ta.valorfrequencia, ta.dataagendamento, v_hoje)
       -- Justificada como "nao se aplica" (pendente ou aceita) nao e tarefa de hoje.
       AND NOT public.tem_justificativa(ta.atribuicaoid, ta.tipofrequencia, v_hoje, false)
       -- Unica entregue num dia anterior ja nao e tarefa de hoje.
       AND NOT (ta.tipofrequencia = 'Unica' AND EXISTS (
             SELECT 1 FROM public.entregas e2
              WHERE e2.atribuicaoid = ta.atribuicaoid
                AND e2.statusvalidacao IN ('Pendente', 'Aprovada')
                AND public.dia_em_sao_paulo(e2.dataenvio) < v_hoje))
  )
  SELECT jsonb_build_object(
           'total',       count(*),
           'aprovadas',   count(*) FILTER (WHERE situacao = 'Aprovada'),
           'emvalidacao', count(*) FILTER (WHERE situacao = 'Pendente'),
           'parafazer',   coalesce(
                            jsonb_agg(
                              jsonb_build_object('titulo', titulo, 'pessoa', pessoa,
                                                 'pontos', pontos, 'atrasada', atrasada)
                              ORDER BY atrasada DESC, pessoa, titulo
                            ) FILTER (WHERE situacao IS NULL),
                            '[]'::jsonb))
    INTO v_dia
    FROM dia;

  -- Em validacao: todas as pendentes da loja, de qualquer dia.
  SELECT count(*) INTO v_pendentes
    FROM public.entregas
   WHERE contaid = p_contaid AND lojaid = p_lojaid AND statusvalidacao = 'Pendente';

  SELECT coalesce(jsonb_agg(
           jsonb_build_object('titulo', titulo, 'pessoa', pessoa, 'pontos', pontos,
                              'enviadaem', dataenvio, 'dehoje', dehoje)
           ORDER BY dataenvio), '[]'::jsonb)
    INTO v_validacao
    FROM (
      SELECT t.titulo, t.pontos, e.dataenvio,
             CASE WHEN p_tv THEN public.nome_curto(f.nomecompleto) ELSE f.nomecompleto END AS pessoa,
             public.dia_em_sao_paulo(e.dataenvio) = v_hoje AS dehoje
        FROM public.entregas e
        JOIN public.tarefas t      ON t.tarefaid = e.tarefaid
        JOIN public.funcionarios f ON f.funcionarioid = e.funcionarioid
       WHERE e.contaid = p_contaid AND e.lojaid = p_lojaid AND e.statusvalidacao = 'Pendente'
       ORDER BY e.dataenvio
       LIMIT 50
    ) s;

  -- Podio do dia: pontos aprovados hoje na loja.
  SELECT coalesce(jsonb_agg(jsonb_build_object('pessoa', pessoa, 'pontos', pontos)
                            ORDER BY pontos DESC, pessoa), '[]'::jsonb)
    INTO v_podio
    FROM (
      SELECT CASE WHEN p_tv THEN public.nome_curto(f.nomecompleto) ELSE f.nomecompleto END AS pessoa,
             sum(e.pontosganhos)::integer AS pontos
        FROM public.entregas e
        JOIN public.funcionarios f ON f.funcionarioid = e.funcionarioid
       WHERE e.contaid = p_contaid AND e.lojaid = p_lojaid
         AND e.statusvalidacao = 'Aprovada'
         AND public.dia_em_sao_paulo(e.dataaprovacao) = v_hoje
       GROUP BY f.funcionarioid, f.nomecompleto
       ORDER BY sum(e.pontosganhos) DESC, f.nomecompleto
       LIMIT 3
    ) s;

  -- Atividade recente: as ultimas aprovacoes do dia.
  SELECT coalesce(jsonb_agg(jsonb_build_object('titulo', titulo, 'pessoa', pessoa,
                                               'pontos', pontos, 'aprovadaem', dataaprovacao)
                            ORDER BY dataaprovacao DESC), '[]'::jsonb)
    INTO v_atividade
    FROM (
      SELECT t.titulo, e.pontosganhos AS pontos, e.dataaprovacao,
             CASE WHEN p_tv THEN public.nome_curto(f.nomecompleto) ELSE f.nomecompleto END AS pessoa
        FROM public.entregas e
        JOIN public.tarefas t      ON t.tarefaid = e.tarefaid
        JOIN public.funcionarios f ON f.funcionarioid = e.funcionarioid
       WHERE e.contaid = p_contaid AND e.lojaid = p_lojaid
         AND e.statusvalidacao = 'Aprovada'
         AND public.dia_em_sao_paulo(e.dataaprovacao) = v_hoje
       ORDER BY e.dataaprovacao DESC
       LIMIT 10
    ) s;

  RETURN jsonb_build_object(
    'loja',         v_loja,
    'hoje',         v_hoje,
    'atualizadoem', now(),
    'progresso',    jsonb_build_object('total',       v_dia->'total',
                                       'aprovadas',   v_dia->'aprovadas',
                                       'emvalidacao', v_dia->'emvalidacao'),
    'parafazer',    v_dia->'parafazer',
    'emvalidacao',  v_validacao,
    'pendentes',    v_pendentes,
    'podio',        v_podio,
    'atividade',    v_atividade,
    'meta',         public.meta_para_painel(p_contaid, p_lojaid, p_tv)
  );
END;
$$;

-- ===========================================================================
-- 7. Permissoes (negadas por padrao).
-- ===========================================================================

REVOKE EXECUTE ON FUNCTION
  public.equipe_da_meta(integer, integer, date),
  public.pagar_premio_meta(integer, integer, text, integer, integer, integer, date, text),
  public.estornar_premio_meta(integer, text),
  public.reavaliar_meta_do_dia(integer),
  public.reavaliar_meta_do_mes(integer, integer, date),
  public.meta_para_painel(integer, integer, boolean),
  public.montar_painel(integer, integer, boolean)
FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION
  public.meta_do_dia(integer, date),
  public.primeiro_dia_editavel_meta(),
  public.lancar_venda_do_dia(integer, date, numeric, text),
  public.salvar_meta_do_mes(integer, date, text, numeric, integer, text),
  public.metas_do_mes(integer, date)
TO authenticated;

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO service_role;
