// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asgdynxdcdnjglgyyaek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzZ2R5bnhkY2RuamdsZ3l5YWVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk3NjgwMzMsImV4cCI6MjEwNTM0NDAzM30.YWricZ_ftYTMmPvA6ES-m5rJ4jV4iYo_BXtlW3WpN60";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});