// O CONTRATO do aplicativo com o banco: para cada função que o app chama,
// os parâmetros que ele espera encontrar.
//
// GERADO a partir de src/integrations/supabase/types.ts, que por sua vez vem
// do banco. Não edite à mão: rode `bun run contrato` depois de regenerar os
// tipos. O teste em contrato.test.ts reprova se este arquivo ficar para trás.
//
// Para que serve: a tela /saude manda esta lista para o banco e mostra o que
// não bate. Sem isso, uma função que mudou de parâmetros só aparecia quando
// alguém testava na loja — foi o que aconteceu em 25/09/2026.
export const CONTRATO: Record<string, string[]> = {
  abrir_solicitacao: ["p_categoria", "p_descricao", "p_funcionarioid", "p_lojaid", "p_quantidade", "p_tipo", "p_unidade"],
  acesso_por_email: ["p_email"],
  alterar_configuracao: ["p_chave", "p_valor"],
  alterar_hora_da_atribuicao: ["p_atribuicaoid", "p_hora"],
  alterar_pagamento_agendamento: ["p_agendamentoid", "p_status", "p_valor"],
  analise_de_tarefas: ["p_ate", "p_de", "p_lojaid"],
  anular_feedback: ["p_feedbackid", "p_motivo"],
  aprovar_entrega: ["p_entregaid"],
  arquivar_documento_pessoal: ["p_documentoid"],
  atribuicoes_para_entregar: ["p_lojaid"],
  atribuir_tarefa: ["p_dataagendamento", "p_disponivelapartir", "p_funcionarios", "p_horariodisparo", "p_lojaid", "p_tarefaid", "p_tipofrequencia", "p_valorfrequencia"],
  cancelar_agendamento: ["p_agendamentoid", "p_motivo"],
  cancelar_troca: ["p_motivo", "p_resgateid"],
  concluir_troca: ["p_resgateid"],
  conflitos_agendamento: ["p_dataevento", "p_ignorar", "p_lojaid"],
  conta_do_codigo: ["p_codigo"],
  cria_configuracoes_padrao: ["p_contaid"],
  cria_etapas_onboarding_padrao: ["p_contaid"],
  cria_produtos_do_sistema: ["p_contaid"],
  cria_tarefas_do_sistema: ["p_contaid"],
  cria_tipos_evento_padrao: ["p_contaid"],
  criar_acesso_colaborador: ["p_contaid", "p_funcionarioid", "p_pinhash", "p_quem", "p_userid"],
  criar_acesso_loja: ["p_contaid", "p_lojaid", "p_quem", "p_userid"],
  criar_agendamento: ["p_aceitawhatsapp", "p_cpf", "p_dataevento", "p_lojaid", "p_nomecliente", "p_observacoes", "p_pagamento", "p_responsavelid", "p_telefone", "p_tipoeventoid", "p_valor"],
  criar_codigo_acesso: ["p_codigohash", "p_contaid", "p_dias", "p_funcionarioid", "p_quem"],
  criar_conquista: ["p_bonus", "p_descricao", "p_dias", "p_icone", "p_nome", "p_retroativa", "p_tipo", "p_valor"],
  criar_convite_grupo: ["p_lojaid", "p_papel"],
  criar_convite_meu_telegram: [],
  criar_convite_telegram: ["p_funcionarioid"],
  criar_link_tv: ["p_lojaid", "p_nome"],
  decidir_justificativa: ["p_aceitar", "p_justificativaid", "p_motivo"],
  definir_horario_equipe: ["p_entrada", "p_funcionarios", "p_saida"],
  definir_pin: ["p_contaid", "p_funcionarioid", "p_pinhash", "p_provisorio"],
  definir_rotina_mensagem: ["p_ativo", "p_lojaid", "p_rotina"],
  definir_senha_app: ["p_contaid", "p_funcionarioid", "p_hash"],
  definir_senha_gestor: ["p_contaid", "p_hash", "p_userid"],
  desligar_telegram: ["p_vinculoid"],
  diagnostico_do_sistema: ["p_esperado"],
  editar_agendamento: ["p_aceitawhatsapp", "p_agendamentoid", "p_cpf", "p_nomecliente", "p_observacoes", "p_telefone", "p_tipoeventoid"],
  eh_admin_geral: [],
  erros_de_login: ["p_chaves"],
  estornar_entrega: ["p_entregaid", "p_motivo"],
  estornar_troca: ["p_motivo", "p_resgateid"],
  eu_cancelar_resgate: ["p_contaid", "p_funcionarioid", "p_resgateid"],
  eu_entregar: ["p_atribuicaoid", "p_caminho", "p_contaid", "p_fotoidunico", "p_funcionarioid", "p_observacao", "p_semhorafoto"],
  eu_extrato: ["p_ate", "p_contaid", "p_de", "p_funcionarioid"],
  eu_inicio: ["p_contaid", "p_funcionarioid"],
  eu_pedir_resgate: ["p_contaid", "p_funcionarioid", "p_lojaid", "p_produtoid", "p_valorreais"],
  eu_premios: ["p_contaid", "p_funcionarioid"],
  eu_resgates: ["p_contaid", "p_funcionarioid"],
  eu_tarefas: ["p_contaid", "p_funcionarioid"],
  excluir_documento_por_engano: ["p_documentoid", "p_motivo"],
  extrato_pontos: ["p_ate", "p_de", "p_funcionarioid"],
  fechamento_valendo: ["p_ano", "p_mes"],
  ficha_dos_tablets: ["p_contaid"],
  fila_da_loja: ["p_lojaid"],
  fora_do_comunicado: ["p_documentoid"],
  historico_da_pessoa: ["p_funcionarioid", "p_limite"],
  justificaveis: ["p_dia", "p_funcionarioid"],
  lancar_venda_do_dia: ["p_dia", "p_lojaid", "p_motivo", "p_valor"],
  liberar_documento_pessoal: ["p_documentoid"],
  limpar_senha_gestor: ["p_userid"],
  listar_trocas: ["p_limite"],
  marcar_agendamento_realizado: ["p_agendamentoid"],
  marcar_aviso_lido: ["p_avisoid"],
  marcar_senha_amao: ["p_amao", "p_contaid", "p_userid"],
  metas_do_mes: ["p_lojaid", "p_mes"],
  meu_acesso: [],
  minha_conta: [],
  minha_politica_de_uso: [],
  minha_taxa: [],
  mudar_situacao_solicitacao: ["p_observacao", "p_solicitacaoid", "p_status"],
  painel_da_loja: ["p_lojaid"],
  painel_da_tv: ["p_codigo"],
  painel_inicio: ["p_lojaid"],
  parear_tv: ["p_codigo", "p_lojaid", "p_nome"],
  passar_tarefa_de_folga: ["p_atribuicaoid", "p_funcionarioid"],
  pendencias_da_pessoa: ["p_ate", "p_de", "p_funcionarioid"],
  politica_dar_ciencia: ["p_assinaturaid", "p_contaid", "p_funcionarioid"],
  preparar_envio_documento: ["p_funcionarioid", "p_nomearquivo"],
  publicar_comunicado: ["p_alvo", "p_conteudo", "p_funcionarios", "p_lojas", "p_pontos", "p_titulo"],
  publicar_politica_de_uso: ["p_conteudo"],
  quem_trabalha_hoje: ["p_lojaid"],
  ranking_mensal: ["p_ano", "p_lojaid", "p_mes"],
  ranking_pontos: ["p_ate", "p_de", "p_lojaid"],
  reabrir_agendamento: ["p_agendamentoid", "p_motivo"],
  recibo_ciencia: ["p_assinaturaid"],
  recibo_resgate: ["p_resgateid"],
  recusar_entrega: ["p_entregaid", "p_motivo"],
  redefinir_acesso: ["p_contaid", "p_funcionarioid", "p_pinhash", "p_quem"],
  refazer_fechamento: ["p_ano", "p_mes", "p_motivo"],
  registrar_anexo_agendamento: ["p_agendamentoid", "p_caminho", "p_nomearquivo", "p_tamanho", "p_tipo"],
  registrar_ciencia_documento: ["p_documentoid"],
  registrar_documento_pessoal: ["p_caminho", "p_descricao", "p_funcionarioid", "p_nomearquivo", "p_referencia", "p_substitui", "p_tamanho", "p_tipo", "p_tipoarquivo"],
  registrar_entrega: ["p_aprovar", "p_atribuicaoid", "p_fotoidunico", "p_observacao", "p_pathfoto", "p_semhorafoto"],
  registrar_evento_acesso_loja: ["p_contaid", "p_evento", "p_lojaid", "p_quem"],
  registrar_feedback: ["p_comentario", "p_dia", "p_funcionarioid", "p_nota"],
  registrar_justificativa: ["p_aceitar", "p_atribuicaoid", "p_dia", "p_motivo"],
  registrar_troca: ["p_entregar", "p_funcionarioid", "p_lojaid", "p_produtoid"],
  registrar_troca_por_valor: ["p_entregar", "p_funcionarioid", "p_lojaid", "p_valorreais"],
  remarcar_agendamento: ["p_agendamentoid", "p_motivo", "p_novadata"],
  remover_anexo_agendamento: ["p_anexoid"],
  resumo_das_lojas: [],
  revogar_aceite: ["p_atribuicaoid", "p_dia", "p_motivo"],
  revogar_link_tv: ["p_linktvid"],
  rodar_geracao_hoje: [],
  rotinas_resumo_admin: [],
  salvar_meta_do_mes: ["p_descricao", "p_lojaid", "p_mes", "p_nome", "p_pontos", "p_valor"],
  salvar_tv_da_loja: ["p_blocos", "p_lojaid", "p_segundos", "p_valores"],
  senha_app_de: ["p_contaid", "p_cpf"],
  senha_app_do_funcionario: ["p_contaid", "p_funcionarioid"],
  situacao_dos_acessos: [],
  sou_master: [],
  tarefas_de_folga_hoje: ["p_lojaid"],
  tarefas_nao_pegas: ["p_lojaid"],
  tarefas_pegas_da_pessoa: ["p_ate", "p_de", "p_funcionarioid"],
  tentativa_abrir_ex: ["p_chave", "p_contaid", "p_origem", "p_tipo"],
  tentativa_fechar: ["p_sucesso", "p_tentativaid"],
  tratar_relato: ["p_denunciaid", "p_resposta", "p_status"],
  trocar_cpf: ["p_contaid", "p_cpf", "p_funcionarioid"],
  trocar_responsavel_agendamento: ["p_agendamentoid", "p_funcionarioid"],
  tv_buscar_link: ["p_segredohash"],
  tv_novo_codigo: ["p_minutos", "p_segredohash"],
  usar_codigo_acesso: ["p_codigohash", "p_contaid", "p_cpf"],
  visao_abrir_pedido: ["p_contaid", "p_descricao", "p_funcionarioid", "p_lojaid", "p_observacao", "p_quantidade", "p_tipo", "p_unidade"],
  visao_entregar: ["p_atribuicaoid", "p_caminho", "p_contaid", "p_fotoidunico", "p_funcionarioid", "p_lojaid", "p_observacao", "p_semhorafoto"],
  visao_fila: ["p_contaid", "p_lojaid"],
  visao_pegar: ["p_atribuicaoid", "p_contaid", "p_funcionarioid", "p_lojaid"],
  visao_pessoa_do_pin: ["p_contaid", "p_lojaid", "p_pinhash"],
};
